### PR TITLE
🌱 github: add labels to release-tracking issue template

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Add the labels which should always get set to exit triage.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area documentation

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by killianmuldoon** [comment]
Some funniness going on with `ok-to-test` - doesn't look like it's happening on other PRs though

**Comment by sbueringer** [comment]
@killianmuldoon it does: https://kubernetes.slack.com/archives/C8TSNPY4T/p1713805783629439

**Pull request merged**
