### PR TITLE
✨ Add ibmcloud provider support

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-ibmcloud/issues/320

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Should we include documentation updates within this PR to add details of the new provider and setup to the existing docs?

**Comment by mkumatag** [comment]
> Should we include documentation updates within this PR to add details of the new provider and setup to the existing docs?

well, I don't have the docs ready, seems like need more time for that.

one more question I have, atm ibmcloud provider code doesn't support betav1 code, so wondering whether still need to merge code the main or to the 0.4 and merge to main later.?!

**Comment by sbueringer** [comment]
@mkumatag You can add the provider to the provider contract and providers list if you want (see: https://github.com/kubernetes-sigs/cluster-api/pull/5593/files).

> one more question I have, atm ibmcloud provider code doesn't support betav1 code, so wondering whether still need to merge code the main or to the 0.4 and merge to main later.?!

For me it would be fine to merge this PR on main and then cherry-pick into release-1.0 and release-0.4. But I'm not sure how we usually handle cases like this, so let's wait  a bit for feedback from others. (@fabriziopandini )

**Comment by mkumatag** [comment]
> @mkumatag You can add the provider to the provider contract and ~providers list~ (EDIT: it is already in the providers list) if you want (see: https://github.com/kubernetes-sigs/cluster-api/pull/5593/files).

done

**Comment by fabriziopandini** [comment]
/lgtm

technically this is not something we consider as eligible for back porting, but given it makes users life easier, I'm ok with an exception.

**Comment by fabriziopandini** [comment]
/cherry-pick release-1.0
Let's go one step at time

**Review by vincepri — APPROVED** [review]
/approve

**Comment by mkumatag** [comment]
> @fabriziopandini: #5640 failed to apply on top of branch "release-1.0":
> ```
> Applying: Add ibmcloud provider support
> Using index info to reconstruct a base tree...
> M	cmd/clusterctl/client/config/providers_client.go
> M	cmd/clusterctl/client/config_test.go
> M	cmd/clusterctl/cmd/config_repositories_test.go
> Falling back to patching base and 3-way merge...
> Auto-merging cmd/clusterctl/cmd/config_repositories_test.go
> Auto-merging cmd/clusterctl/client/config_test.go
> Auto-merging cmd/clusterctl/client/config/providers_client.go
> CONFLICT (content): Merge conflict in cmd/clusterctl/client/config/providers_client.go
> error: Failed to merge in the changes.
> hint: Use 'git am --show-current-patch=diff' to see the failed patch
> Patch failed at 0001 Add ibmcloud provider support
> When you have resolved this problem, run "git am --continue".
> If you prefer to skip this patch, run "git am --skip" instead.
> To restore the original branch and stop patching, run "git am --abort".
> 
> ```
> 
> <details>
> 
> In response to [this](https://github.com/kubernetes-sigs/cluster-api/pull/5640#issuecomment-966422401):
> 
> >/cherry-pick release-1.0
> >Let's go one step at time
> 
> 
> Instructions for interacting with me using PR comments are available [here](https://git.k8s.io/community/contributors/guide/pull-requests.md).  If you have questions or suggestions related to my behavior, please file an issue against the [kubernetes/test-infra](https://github.com/kubernetes/test-infra/issues/new?title=Prow%20issue:) repository.
> </details>

Seems like need a manual back port, will submit for both 1.0 and 0.4 branches

**Pull request merged**
