### PR TITLE
:bug: Requeue health check during the creation of a new cluster accessor

### LINKED ISSUE #7989: Nodes get stuck in provisioned state because of failing refresh of credentials
**What steps did you take and what happened:**

## Short description:

When upgrading the cluster-api-controller to a version > 1.2.5 nodes get stuck in provisioned state and never reach the running state.

## Detailed description:

Our current setup consists of one management cluster responsible for itself and two workload clusters where all resources are located in different namespaces. We use AWS and the CAPA controller in version 2.0.2. We recognized the problem first, when we did an upgrade from 1.2.5 to 1.2.6 (it could be related to https://github.com/kubernetes-sigs/cluster-api/pull/7544). After the upgrade we saw that, after some time, nodes get stuck in the provisioned state and can't join the cluster properly.

image

When this state is reached, it seems that there is something wrong with the client credentials for the workload cluster because the log contains many entries like this one:

```
I0124 15:52:49.930948       1 reflector.go:257] Listing and watching *v1.Node from k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169
W0124 15:52:49.934248       1 reflector.go:424] k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: failed to list *v1.Node: Unauthorized
E0124 15:52:49.934533       1 reflector.go:140] k8s.io/client-go@v0.25.0/tools/cache/reflector.go:169: Failed to watch *v1.Node: failed to list *v1.Node: Unauthorized
```
So it seems that something with the refresh of the client credentials is not working anymore. What we can see is that the controller tries to create a new cluster accessor repeatedly for the different clusters but also that it runs into some sort of lock (which seems to be introduced by https://github.com/kubernetes-sigs/cluster-api/pull/7544):

```
0124 13:48:34.701004       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="cluster-*****/*********" Machine="******/workers-worker-0-58fb9c499d-hvnxh" node=""
E0124 13:48:34.704719       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-z4d6g" node=""
E0124 13:48:34.704762       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-4ltkt" node=""
E0124 13:48:34.704811       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-qcq99" node=""
E0124 13:48:34.704849       1 machineset_controller.go:754] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="******/workers-worker-0-58fb9c499d" namespace="******" name="workers-worker-0-58fb9c499d" reconcileID=e8476f23-ab51-4b2d-8352-1866806f02dd MachineDeployment="******/workers-worker-0" Cluster="******/******" Machine="******/workers-worker-0-58fb9c499d-m7t2r" node=""
```

At this point only a restart of the controller solves the problem for us. If we downgrade the controller to 1.2.5 everything is working again.

**What did you expect to happen:**
I would expect that the nodes can join the cluster even if the client credentials need to be refreshed.

**Anything else you would like to add:**

I can update the issue with some information from gops if that could be helpful for you :-)

**Environment:**

- cluster-api-provider-aws version: 2.0.2
- Cluster-api version: 1.3.2
- minikube/kind version:
- Kubernetes version: (use `kubectl version`): 1.23
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by AljoschaP**
**What this PR does / why we need it**:
When a cluster accessor is created, the health check is started before the accessor is stored. If the health check hits the `loadAccessor` before the accessor is stored, it returns `true`, leaves the health check and never retries it. Together with expiring kubeconfigs (e.g. EKS), this will lead to a situation where a kubeconfig will never be refreshed and the cluster is basically dead until we restart the controller. This PR uses the `TryLock` to check if the cluster is currently locked which means that we're probably in the middle of the creation of a new cluster accessor and requeues the health check until the creation is done.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7989

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Comment by sbueringer** [comment]
Thx, very nice catch!!

/lgtm

**Review by chrischdi — COMMENTED** [review]
Awesome finding 👍 

/lgtm

**Comment by sbueringer** [comment]
/hold cancel
e2e green

**Comment by fabriziopandini** [comment]
@AljoschaP that's a great first PR!
/lgtm
/approve

**Comment by sbueringer** [comment]
@AljoschaP if you have some time, can you please open a follow-up issue to add a unit test to cover this case?
(or a PR if you want to of course :))

Thank you!

**Comment by AljoschaP** [comment]
> @AljoschaP if you have some time, can you please open a follow-up issue to add a unit test to cover this case?
> 
> (or a PR if you want to of course :))
> 
> 
> 
> Thank you!

Of course 🙂 I will create an issue and start working on it beginning of next week 🙂 Thank you all!

**Comment by sbueringer** [comment]
Perfect, thank you very much!!

**Pull request merged**
