### PR TITLE
🌱 add deletion integration test for clusterclass

### PR DESCRIPTION
**Pull request by killianmuldoon**
Adds a deletion integration test to ensure the behaviour is being properly enforced by the clusterClass webhook (and possibly the reconciler in future). 

This test was added to prevent a regression of behaviour like #5737 and tests for the behaviour outlined in #5196

### CODE REVIEW

**Comment by sbueringer** [comment]
@killianmuldoon Test itself looks good. I wonder if it should be part of the controller integration tests or rather of our upcoming webhook integration tests.

**Comment by killianmuldoon** [comment]
> @killianmuldoon Test itself looks good. I wonder if it should be part of the controller integration tests or rather of our upcoming webhook integration tests.

I think maybe we should put the webhook integration tests in the same directory but namespace them as such maybe? so change the name of this test to TestClusterWebhook_deleteClusterClass. I am conscious that if we're doing validation in the reconciler as well there may be some crossover in these tests.

**Comment by sbueringer** [comment]
> > @killianmuldoon Test itself looks good. I wonder if it should be part of the controller integration tests or rather of our upcoming webhook integration tests.
> 
> I think maybe we should put the webhook integration tests in the same directory but namespace them as such maybe? so change the name of this test to TestClusterWebhook_deleteClusterClass. I am conscious that if we're doing validation in the reconciler as well there may be some crossover in these tests.

I would personally prefer having the webhook integration tests in a sub package of the webhooks implementation (aka 
 ~ `internal/webhook/integrationtests`) to keep them close to the corresponding code. But let's see what others think.

**Comment by fabriziopandini** [comment]
I'm happy to merge the test where it is now (where we can benefit from a set of util func shared with other integration tests), and eventually consider moving them somewhere else at a later stage if required.

**Comment by sbueringer** [comment]
> > I'm happy to merge the test where it is now (where we can benefit from a set of util func shared with other integration tests), and eventually consider moving them somewhere else at a later stage if required.
> 
> This would be my preferred option for now. I think we might need a delete reconcile test here anyway, but It's better not to add additional webhook tests here as they get done.

Sounds good to me!

/lgtm

**Comment by killianmuldoon** [comment]
@fabriziopandini Is this okay to be merged as is or should I add it to integration tests in a separate package?

**Pull request merged**
