### PR TITLE
🌱 Add timeout to check if KCP object exists

### PR DESCRIPTION
**Pull request by namnx228**
This is a manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/5889
/assign @fabriziopandini

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold
before landing in v0.4 branch, the PR should be cherry-picked into the v1.0 branch; also, could you provide a rationale about why this cherry-pick is required?

**Comment by namnx228** [comment]
> /hold before landing in v0.4 branch, the PR should be cherry-picked into the v1.0 branch; also, could you provide a rationale about why this cherry-pick is required?

This cherry pick is needed because the issue described in https://github.com/kubernetes-sigs/cluster-api/pull/5889 also happens in v0.4. 
I will open another PR to cherry pick this commit to v1.0

**Comment by sbueringer** [comment]
/ok-to-test

> Cherry-pick is fine for me, given that it's otherwise hard for providers who use 1.0 (same for 0.4) to get a stable CI without this fix.
> https://github.com/kubernetes-sigs/cluster-api/pull/5909#issuecomment-1005791041

/lgtm
pending the hold & that the 1.0 cherry-pick is merged first

**Comment by sbueringer** [comment]
/retitle 🌱 Add timeout to check if KCP object exists

**Comment by sbueringer** [comment]
/hold cancel
/lgtm
/approve

given that the 1.0 cherry-pick has been merged too

**Pull request merged**
