### PR TITLE
📖 book: fix link to GitHub doc

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
tried to use the URL where the doc is actually hosted, but has the same issue

**Comment by sbueringer** [comment]
Found a workaround for https://github.com/gaurav-nelson/github-action-markdown-link-check/issues/136 suggested here https://github.com/tcort/markdown-link-check/issues/201

**Comment by CecileRobertMichon** [comment]
Thanks for the heads up, just checked CAPZ doesn't reference https://help.github.com

**Comment by sbueringer** [comment]
> Thanks for the heads up, just checked CAPZ doesn't reference https://help.github.com

The issue is with docs.github. In that case help just redirects to docs. I think you might have it too: https://github.com/kubernetes-sigs/cluster-api-provider-azure/runs/6185196802?check_suite_focus=true

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
