### PR TITLE
✨ Expand fuzzing framework to allow custom functions

### PR DESCRIPTION
**Pull request by maelk**
**What this PR does / why we need it**:
Adds a parameter in FuzzTestFunc allowing to pass custom fuzzing functions if needed. This allows providers to define specific fuzzing behaviours when fuzzing their conversions.

### CODE REVIEW

**Comment by chuckha** [comment]
Cool! Do you have an issue open for this or can you expand a little upon the use case? I'm not sure when we'd want to replace the metafuzzer.Funcs. An example would really help me out

**Comment by detiber** [comment]
@chuckha If there are certain restrictions on some of the fields used (exclusive fields, enums, etc), there can be cases where custom fuzzing functions are required to properly generate data for those fields, otherwise the default fuzzer funcs will generate invalid content.

Overall, this lgtm, but will defer to @vincepri since he introduced the fuzz testing.

/ok-to-test

**Comment by chuckha** [comment]
@detiber thanks for explaining! I'm still trying to understand what is driving this change. As there is no linked issue I can only guess. Do we need this now or is this a hypothetical for the future? My guess is we need it for clusterctl, but I'm not sure.

**Comment by maelk** [comment]
@chuckha Our use-case is that in v1alpha2, we defined the APIEndpoint as a string that should be parseable by the url parse function. Here is how I am planning to use this PR : https://github.com/Nordix/cluster-api-provider-baremetal/blob/v1alpha3-mael/api/v1alpha2/conversion_test.go#L55.

**Comment by chuckha** [comment]
Ahhh that makes sense 👍 thanks for following up

**Pull request merged**
