### PR TITLE
🌱 Use .Index func when building field.Paths

### LINKED ISSUE #5216: Use .Index func consistently when building field.Paths
In our webhooks we often use `field.NewPath` to build paths to describe the location of validation errors. I recently found out that there's an `Index` func which we can use to add the array index. Currently, we often use string concatenation to produce something similar.

Example:

Current implementation:
```golang
field.NewPath("spec", "workers", fmt.Sprintf("machineDeployments[%v]", i), "template", "infrastructure")
```

Implementation with `Index`:
```golang
field.NewPath("spec", "workers", "machineDeployments").Index(i).Child("template", "infrastructure")
```

It's a minor problem, but I think it would be great if we can use `Index` consistently in all our webhooks.

**Environment:**

- Cluster-api version: latest

/kind cleanup
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by anusha94**
Using `.Index` func instead of `fmt` package to subscript array indexes

Fixes #5216

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/lgtm
/ok-to-test

@anusha94 Thanks for working on this! Just wondering if you've verified through the code that these are the only uses of the `NewPath` with this `fmt.Sprint`style that need updating? If there are other occurrences that could be updated to use the field index it may be preferable to include those here as well

**Comment by anusha94** [comment]
> these are the only uses of the NewPath with this fmt.Sprintstyle that need updating?


@JoelSpeed 
Did a blind search on the repo and only these made sense. Will check again though to be sure.

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

@anusha94 thanks for this cleanup!

**Pull request merged**
