### PR TITLE
🌱 Upgrade cert-manager to 1.5.3

### PR DESCRIPTION
**Pull request by ggpaue**
**What this PR does / why we need it**:
This PR upgrades cert-manager to 1.5.3

### CODE REVIEW

**Comment by sbueringer** [comment]
/ok-to-test
@ggpaue can we directly upgrade to 1.5.3?

**Comment by vincepri** [comment]
@ggpaue Can you sign the CLA?

**Comment by ggpaue** [comment]
> @ggpaue Can you sign the CLA?

Hi @vincepri I would love to sign it, can you tell me how to do it? many thanks!

**Comment by fabriziopandini** [comment]
Instruction for singing CLA can be found in https://github.com/kubernetes-sigs/cluster-api/pull/5299#issuecomment-925273398

**Comment by fabriziopandini** [comment]
changes lgmt, pending discussion about v1.5.1 vs v1.5.3

**Comment by ggpaue** [comment]
> Instruction for singing CLA can be found in [#5299 (comment)](https://github.com/kubernetes-sigs/cluster-api/pull/5299#issuecomment-925273398)

thanks @fabriziopandini I have signed the CLA through my company link (vmware)

**Comment by vincepri** [comment]
Let's update to 1.5.3? Seems worthwhile to jump

**Comment by ggpaue** [comment]
sure let me update this PR to 1.5.3

**Comment by sbueringer** [comment]
/lgtm
Not sure about the CLA, might need a bit to "sync" (I don't know details :)).

apidiff is okay (it's not required for merge)

**Comment by ggpaue** [comment]
I signed it

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
