### PR TITLE
🌱 ClusterCacheTracker: fix accessor deletion on health check failure

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #8948 (should fix the issue for main and release-1.5)

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @fabriziopandini @chrischdi @killianmuldoon 

I think we should have a follow-up to ensure we improve the test coverage of this critical component for cases like that workload clusters become unreachable

**Comment by sbueringer** [comment]
/cherry-pick release-1.5

This issue was introduced in the 1.5 cycle during the CR bump. So we shouldn't need it in v1.4.
I'll verify if this behavior works in v1.4

**Review by chrischdi — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
nice find!

**Comment by sbueringer** [comment]
Just more context for future us. We don't need this on release-1.4 or older because there we stil could precisely check for the error returned by the wait func. This changed and with >= release-1.5 we can't diferentiate between wait func timeout and client-go timeout.

1.4 code:
```go
	err := wait.PollImmediateUntil(in.interval, runHealthCheckWithThreshold, ctx.Done())
	// An error returned implies the health check has failed a sufficient number of
	// times for the cluster to be considered unhealthy
	// NB. we are ignoring ErrWaitTimeout because this error happens when the channel is close, that in this case
	// happens when the cache is explicitly stopped.
	if err != nil && err != wait.ErrWaitTimeout {
		t.log.Error(err, "Error health checking cluster", "Cluster", klog.KRef(in.cluster.Namespace, in.cluster.Name))
		t.deleteAccessor(ctx, in.cluster)
	}
```

**Pull request merged**
