### PR TITLE
📖  Fix quick-start link err

### PR DESCRIPTION
**Pull request by chymy**
**What this PR does / why we need it**:
Fix quick-start.md link err

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!
/lgtm
/ok-to-test

**Comment by fabriziopandini** [comment]
/cc @yastij @gab-satchi 
for the vSphere link change

**Review by gab-satchi — COMMENTED** [review]
thanks. 

/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
