### PR TITLE
🌱 Bump dependencies to fix CVEs

### PR DESCRIPTION
**Pull request by kashifest**
Fixes # https://github.com/advisories/GHSA-r48q-9g5r-8q2h , https://github.com/advisories/GHSA-69cg-p879-7622 and https://github.com/advisories/GHSA-hp87-p4gw-j4gq

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
Thanks for this! Just wondering why there weren't any advisories on the project https://github.com/kubernetes-sigs/cluster-api/security/advisories :thinking: 

This should be a candidate for release-1.2 as well, given they're CVEs.

/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Comment by fabriziopandini** [comment]
From a quick look, we are bumping golang.org/x/net, which we are using for context.
I would rather check if we can use the context from the go lib.
wdyt?

**Comment by sbueringer** [comment]
> Thanks for this! Just wondering why there weren't any advisories on the project https://github.com/kubernetes-sigs/cluster-api/security/advisories thinking Maybe I don't have access to them - @sbueringer can you see automated alerts? We should see if we can set them up if not.
> 
> ~This should be a candidate for release-1.2 as well, given they're CVEs.~
> 
> /lgtm

Got nothing because of:

> This PR is pointing to release-1.2 branch. Main branch has bumped these as a bi-product of other dependency uplifts.

(I usually get that stuff on my fork as well IIRC because I enabled it there)

**Review by vincepri — APPROVED** [review]
/approve

**Comment by furkatgofurov7** [comment]
> Got nothing because of:
> 
> > This PR is pointing to release-1.2 branch. Main branch has bumped these as a bi-product of other dependency uplifts.

This is interesting, we have never seen security advisories reporting any CVE for the repo in the past, but dependabot did couple of times. Also, we have the same package version in the provider's main branch and yet GH advisory has not suggested anything.

**Comment by sbueringer** [comment]
I think you have to enable it and I did on my fork.

I think it's the depandabot alerts

image

**Comment by furkatgofurov7** [comment]
Folks when can we expect the next patch release from release-1.2 branch (considering recent release was dropped a day ago)?

**Comment by sbueringer** [comment]
Current idea is ~ 8th November (~ a month after the last regular monthly non-bugfix patch release)

Are any of those CVE's an actually security issue for Cluster API or are they just making scanners un-happy?

**Comment by furkatgofurov7** [comment]
> Are any of those CVE's an actually security issue for Cluster API or are they just making scanners un-happy?

We got to know about them internally (security team) and were asked to uplift since one of them was critically high and we as a provider consuming CAPI. We have bumped them on the provider side as well (we were using exact same versions), and planning to drop a patch release in the provider after uplifting to the next CAPI patch release (IMO v1.2.5). 
 

> Current idea is ~ 8th November (~ a month after the last regular monthly non-bugfix patch release)

Should be fine I believe, was just planning things on provider side.

**Comment by sbueringer** [comment]
It also has been a while since I got one. So who knows how that actually works

**Pull request merged**
