### PR TITLE
:bug: [etcd] Bump go package to v3.5.3

### PR DESCRIPTION
**Pull request by dntosas**
**What this PR does / why we need it**:
Upgrading etcd golang libraries to the version that mitigates a critical
issue which leds to data corruption --> https://github.com/ahrtr/etcd-issues/tree/master/issues/13766

Signed-off-by: dntosas <ntosas@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Looks good overall - but could you remove the irrelevant changes to the clusterclass doc?

**Review by killianmuldoon — COMMENTED** [review]
I think the CI issues should be cleaned up if you run `make generate-modules` 

That pretty much just runs `go mod tidy` for each of the modules in the repo (hack and test each having their own go.mod)

**Comment by dntosas** [comment]
thnx for the tip @killianmuldoon :) i think we are good now

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
Just to note: this PR is fine but I think we don't have to upgrade the libraries to resolve the issue as the issue is in the etcd server.

I couldn't find the place where I read it so the best reference that I could find was:
> There are no breaking changes in API, meaning it’s safe to let v3.5 clients (e.g. the latest Kubernetes releases) talk to v3.4 servers.
> https://groups.google.com/a/kubernetes.io/g/dev/c/B7gJs88XtQc

**Pull request merged**
