### PR TITLE
🌱 Fix some nits in Cluster topology engine tests

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Some minor fixes as follow-up to #9373

I would have pushed a commit to #9373 directly, but I didn't have the permissions

(Johannes is on PTO and we decided that I take over his PR's while he's away)

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

until #9373 is merged and this PR rebased

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Merging given the changes are super trivial + the lgtm above

/approve

**Pull request merged**
