### PR TITLE
🐛update docker and containerd deps

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

There are few medium to low vulnerabilities were detected whoever using this module, hence these deps needs to be updated to the latest available version.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/lgtm

Seems reasonable given the vulnerabilities, thanks

**Review by fabriziopandini — COMMENTED** [review]
/approve

**Pull request merged**
