### PR TITLE
🌱 Replace reflect.DeepEqual in tests

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #8186

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by g-gaston — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
(fyi, next PR coming soon to replace it in a few places in our regular code)

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
