### PR TITLE
✨ add node predicate to machinehealthcheck controller

### PR DESCRIPTION
**Pull request by goushicui**
✨ (:sparkles:, feature additions)

**What this PR does / why we need it**:
I think we  only need to care about the node condition has changed for machine health check controller?

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by enxebre** [comment]
/ok-to-test
It's been a while since looking at MHC but yeah this use to be true. cc @JoelSpeed

**Comment by JoelSpeed** [comment]
What happens when a node is deleted? I think currently this triggers an MHC reconcile and that causes it to say that the Machine is unhealthy because the node is gone right? This PR would break that as it currently stands IIUC

**Comment by srm09** [comment]
/retitle ✨ add node predicate to machinehealthcheck controller

**Comment by vincepri** [comment]
Why do we need this and what's trying to solve?

**Comment by vincepri** [comment]
Closing this for now given the lack of updates, feel free to reopen once ready to be discussed or merged.

/close

**Pull request closed without merging**
