### PR TITLE
🌱 test/framework: don't fix kubeconfig for remote CAPD clusters

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This PR changes the fix kubeconfig logic so that we only adjust the kubeconfig when necessary.

Specifically it only makes sense to fix the kubeconfig when the CAPD cluster is running locally in Docker Desktop.

It is not necessary if the CAPD cluster is running on a remote host. Actually for remote clusters fixing the kubeconfig breaks the kubeconfig as the remote cluster is not available under 127.0.0.1

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
/retest
(unrelated flake)

/test pull-cluster-api-e2e-full-main

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
@sbueringer, with no rush, let's demo during office hours how to use a remote docker-engine, that's a nice one

**Comment by sbueringer** [comment]
> @sbueringer, with no rush, let's demo during office hours how to use a remote docker-engine, that's a nice feature to have

Yup will do. Probably after easter in April

**Pull request merged**
