### PR TITLE
:seedling: Update controller tools to v0.11.4

### LINKED ISSUE #8546: Bump controller-tools to v0.11.4
### What steps did you take and what happened?

controller-tools v0.11.4 contains a fix to get rid of creationTimestamp: null in generated YAMLs.

I think we should bump ASAP and probably also cherry-pick it back.

Related:
* https://github.com/kubernetes-sigs/cluster-api/issues/8457
* https://github.com/kubernetes-sigs/controller-tools/pull/800

### What did you expect to happen?

-

### Cluster API version

main

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by killianmuldoon**
Bump controller tools and regenerate based on the new version.

Release notes: https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.11.4
Fixes #8546

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
~~/cherry-pick release-1.3~~

Probably safer and easier to cherry-pick this manually

**Review by furkatgofurov7 — COMMENTED** [review]
lgtm

How about release-1.4 (I saw only the command for cherry-picking it to release-1.3)

**Comment by killianmuldoon** [comment]
>How about release-1.4 (I saw only the command for cherry-picking it to release-1.3)

I think we should cherry pick this but do so manually so we get the correct generation for each branch.

**Comment by killianmuldoon** [comment]
> pending green tests

Do you want to do a full run on this PR?

**Comment by sbueringer** [comment]
Reular ones are fine

/hold cancel

Not sure what the problem with the cla label is

**Comment by sbueringer** [comment]
We had some problems with tests before. I assume the hook component of Prow was down before.

**Pull request merged**
