### PR TITLE
:bug: Use k8s.io/utils/ptr instead of k8s.io/utils/pointer

### PR DESCRIPTION
**Pull request by sivchari**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Comment by killianmuldoon** [comment]
Not sure what our policy is with making changes to v1alpha3 now - but hold in case we have some issue with this.  IMO v1alpha3 as we have it is `current` code so it's fine to update dependencies like this

**Comment by sbueringer** [comment]
It's okay. We intentionally only restored it under internal and it is only used for conversion. For conversion this change doesn't matter at all. It also doesn't have any impact on the CRDs (which is the only thing from v1alpha3 surfaced to our users)

/hold cancel

**Pull request merged**
