### PR TITLE
🌱  update tests with builders

### PR DESCRIPTION
**Pull request by killianmuldoon**
**What this PR does / why we need it**:
This PR updates testing across the controllers/topology package to use a common set of object builders which follow a common set of semantics for creating objects to use in testing. 

This PR follows on from  #5055 which creates top level object builders for use in testing across different packages. This branch incorporates the commit from that PR and so can't be merged until the object builders file is merged.

These changes include a new option in the get_blueprint and get_current_state tests that avoid comparing the resource version. There's also a few pieces of refactoring done to the overall structure of the tests.

### CODE REVIEW

**Comment by killianmuldoon** [comment]
Tests now updated to ignore the resource version added by fake client. This reflects changes in the way resourceVersion is being handled in #5055

**Comment by fabriziopandini** [comment]
/lgtm
@vincepri PTAL; this should unblock work on integration steps and further cleanups on tests

**Pull request merged**
