### PR TITLE
📖 Add version table

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
Document the Kubernetes version supported by each Cluster API version

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2476

### CODE REVIEW

**Comment by vincepri** [comment]
Let's move the table to the book, in a compatibility section or something similar

**Comment by fabriziopandini** [comment]
/close
it turns out there is already this table in the book https://cluster-api.sigs.k8s.io/reference/versions.html#cluster-api-version-support-and-kubernetes-version-skew-policy

**Comment by luxas** [comment]
@fabriziopandini do you think documenting what I said above makes sense anyways?

**Comment by luxas** [comment]
We could also link to https://cluster-api.sigs.k8s.io/reference/versions.html#cluster-api-version-support-and-kubernetes-version-skew-policy from the main README IMO

**Comment by fabriziopandini** [comment]
hi @luxas 
IMO what we have in the [book](https://cluster-api.sigs.k8s.io/reference/versions.html#core-provider-cluster-api-controller) is enough to close the issue.

It would be nice to link your document in the same page (not in the readme, so all the version related info are in a single point); however if it should make clear that the link is about version skew of components inside a cluster, while the page talks about version compatibility matrix between CAPI/Kubernetes in the workload & management clusters

**Pull request closed without merging**
