### PR TITLE
:warning: Fix object logging in predicates

### LINKED ISSUE #10818: Improve logging of predicates
The predicates we have today only contain an absolute minimum amount of k/v pairs, e.g.
image

Some notes:
* it's impossible to figure out in which controller this predicate is sued
* kind (the 6th value) is just an empty string

I think we have to improve our predicate logs, otherwise they are not really useful.

(I noticed this when trying to debug predicates of a controller, which is very very had if there is no way to determine which log belongs to which controller)

In general we should compare the logs of our predicates with the logs of a regular controller and figure out which additional k/v pairs we need + we should make sure kind is logged correctly

### PR DESCRIPTION
**Pull request by Karthik-K-N**
**What this PR does / why we need it**:

This PR logs objects kind predicates for easier debugging.

Related PR with same changes for few predicates: https://github.com/kubernetes-sigs/cluster-api/pull/11188

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #10818

/area utils

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @chrischdi 
(for a first round of review when you have some time)

**Comment by Karthik-K-N** [comment]
> /lgtm
> 
> Question, should we also add it inside the `All` and `Any` predicates?
> 
> We also have some logging in them where we could populate the object k/v pair 🤔

Not sure, Why I didn't update them, But now I have updated it in separate commit, Please take a look.

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
