### PR TITLE
:seedling: Add runtime extension components to release

### PR DESCRIPTION
**Pull request by killianmuldoon**
Add a target to generate manifests for the test runtime extension to the release target. 

/area release

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
@killianmuldoon Can you provide some context as to why we did this? Was it just to allow users to install the test extension or did we have to do it for tests?

**Comment by killianmuldoon** [comment]
The context was this mostly: https://github.com/kubernetes-sigs/cluster-api/pull/8430#pullrequestreview-1366610058

But it wasn't causing a failing test at the time. I decided to add it to the release artifacts anyway as it makes sense IMO. Will also be useful in future if / when clusterctl upgrade tests include and rely on external patches.

**Pull request merged**
