### PR TITLE
🌱 Update version matrix for github workflows for release-1.7

### PR DESCRIPTION
**Pull request by Sunnatillo**
Update versions in the github actions matrices for the new release.

/area testings

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/area ci

(I think)

**Comment by chrischdi** [comment]
Let's link the tracking issue too:

Part of:

- #9800

**Review by adilGhaffarDev — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
/approve

/hold

We can merge already that's fine

**Pull request merged**
