### PR TITLE
🌱 Add category to DockerClusterTemplate

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
Looks good - I assume this is the only one that was missing the category?

**Comment by sbueringer** [comment]
> Looks good - I assume this is the only one that was missing the category?

That's correct. Did a few searches to double-check. We have one other YAML file with a "CRD" missing it but that is Metadata somewhere in clusterctl and we don't actually use it as a CRD and its missing a lot of other markers to actually be a full CRD. (we only use it as format for metadata.yaml but somehow generate a CRD YAML for it)

**Pull request merged**
