### PR TITLE
📖 Add embed util for mdbook / fixup prerequisites for CAPA

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by detiber** [comment]
Overall, lgtm. Am I correct in believing that this is only adding the embedding functionality, but not actually using it anywhere yet?

**Comment by vincepri** [comment]
@detiber That's correct, we need to add the correct examples / figure out some conventions in CAPA first

**Pull request merged**
