### PR TITLE
🌱 Make TestInfrastructureMachineTemplateBuilder deepcopy-able

### PR DESCRIPTION
**Pull request by sayantani11**
Made the TestInfrastructureMachineTemplateBuilder deepcopy-able

Fixes A part of #6016

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Looking good from a high level. Can you rebase on to main so we get a test signal?

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Pull request merged**
