### PR TITLE
🌱 remove redundant license

### PR DESCRIPTION
**Pull request by mkarroqe**
**What this PR does / why we need it**:

There is a redundant LICENSE file ([here](https://github.com/kubernetes-sigs/cluster-api/blob/main/LICENSE)) in [CAPD](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/LICENSE) from when it used to live in its own repo. Now that its been moved into the [cluster-api repo](https://github.com/kubernetes-sigs/cluster-api), which has its own LICENSE file ([here](https://github.com/kubernetes-sigs/cluster-api/tree/main/test/infrastructure/docker)), the CAPD one becomes redundant. They are the same file, and the CAPD one has been removed.

### CODE REVIEW

**Comment by stmcginnis** [comment]
/ok-to-test
/lgtm

Looks like we just need a signed CLA - thanks for cleaning things up!

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
lgtm approve pending CLA signing

**Comment by mkarroqe** [comment]
EasyCLA check passed- thanks for your patience!

**Comment by sbueringer** [comment]
Thx!

No worries 🙂

/approve

**Pull request merged**
