### PR TITLE
Add CAPO into contract list

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:
add openstack into provider contact list
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/approve

**Comment by randomvariable** [comment]
looks like linkchecker hit API limits. we might need to feed it a github token in the authorisation header @vincepri ?

/test pull-cluster-api-verify-external-links

**Pull request merged**
