### PR TITLE
🌱 Bump Go to v1.22.8 version

### PR DESCRIPTION
**Pull request by Sunnatillo**
Uplifts Go to v1.22.8 version

/area dependency

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Comment by sbueringer** [comment]
@Sunnatillo If you have some time, can you please open a PR for release-1.7?

**Comment by Sunnatillo** [comment]
> @Sunnatillo If you have some time, can you please open a PR for release-1.7?

sure.

**Pull request merged**
