### PR TITLE
Revert changes to generated files

### PR DESCRIPTION
**Pull request by k4leung4**
**What this PR does / why we need it**:
This will revert modifications to the generated files, and we work
around the initial reasons why we needed to modify them.

WaitForCacheSync can be called with a new channel, as it isn't really
used any more.

We store the shared informers for access to the queue instead of
storing the queue in Init.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by roberthbailey** [comment]
lgtm

**Comment by medinatiger** [comment]
we don't need to save machineListerSynced. Otherwise, lgtm to me. I will lgtm and add /hold. Please remove hold once you fix this tinny thing.

**Pull request merged**
