### PR TITLE
Copy terraform code to vsphere code

### LINKED ISSUE #233: [vSphere] rename terraform provider to vSphere provider
It seems like optimizing for a generic terraform controller is more overhead than we need right now. So we will scope the terraform work to just vsphere. This will improve refactoring all cloud/terraform to cloud/vsphere and tf-deployer to vsphere-deployer.

### PR DESCRIPTION
**Pull request by karan**
**What this PR does / why we need it**: Copy of terraform provider and deployer to a vsphere specific one.

This is literally a copy-paste of the directories, and renaming of packages, variables etc. I have tested that the new deployer works for creating a cluster.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #233

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by spew** [comment]
Please use "git mv" to rename the terraform/tf code to vsphere. That will make it obvious that there are no edits.

We have git history if someone wants to see the state of the previous TF code.

**Comment by roberthbailey** [comment]
Doesn't `git mv` remove the old code? The plan discussed on the call was to leave the existing code in place, fork a copy for vsphere, and then add vsphere specifics into the new code. That way folks can still use the old code to build terraform support for other environments (e.g. openstack).

**Comment by karan** [comment]
Yup `git mv` docs say that it will `Move or rename a file, a directory, or a symlink.`

**Comment by karan** [comment]
@spew The owners for now would be us, until a more formal OWNERS file exists after moving the providers to separate repos.

**Comment by roberthbailey** [comment]
@dims expressed interest today in building an openstack implementation on top of the existing terraform code.

**Comment by spew** [comment]
OK, sounds, good

lgtm

**Comment by roberthbailey** [comment]
`git cp` would have been nice (to preserve history) but since it doesn't exist....

/lgtm

**Comment by dims** [comment]
@roberthbailey @karan Thanks for copying over. I'll kick the tires of the old stuff with openstack and let you all know early next week.

**Comment by karan** [comment]
Rebased #240 (breaking API change). Need lgtm again. @roberthbailey

**Pull request merged**
