### PR TITLE
[WIP] 🌱 Clusterctl move Cluster Principal

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR extends `clusterctl move` so it will manage to move the cluster principal objects introduced for addressing CAPA multitenancy (https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1753/).
NB. the implementation is generic, so it will work for any infrastructure provider implementing a similar solution.

NB.
this PR will remain WIP until https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1753/ merges

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3081

### CODE REVIEW

**Comment by vincepri** [comment]
/milestone v0.3.x

Going to hold this until after v0.3.7 is cut

**Comment by CecileRobertMichon** [comment]
> NB. the implementation is generic, so it will work for any infrastructure provider implementing a similar solution.

Can we document this in https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html ?

**Comment by fabriziopandini** [comment]
> Can we document this in https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html 

Sure. I have a PR ready with the documentation for the three clusterctl PRs I have in flight

**Comment by fabriziopandini** [comment]
@randomvariable is there any ETA about the proposal for Cluster Principal in CAPA, so I can properly prioritize this work?

**Comment by randomvariable** [comment]
@fabriziopandini Proposal is in, implementation is in some part of the 0.5.x series, not the 0.5.5 that is currently in the process of being released.

**Comment by vincepri** [comment]
@fabriziopandini Can this be closed?

**Comment by fabriziopandini** [comment]
/close
We can reopen once the changes lands on CAPA
@randomvariable ^^

**Pull request closed without merging**
