### PR TITLE
🌱 Upgrade to controller-runtime v0.10.3

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Let's pick up latest bugfixes from controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.10.3

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by enxebre** [comment]
just url realised this is against release-1.0 :+1:

**Review by vincepri — APPROVED** [review]
/approve

**Comment by sbueringer** [comment]
> just url realised this is against release-1.0 👍

I thought CAPI main was using a newer version from CR main, that's why I wasn't opening this PR against CAPI main. 

But apparently CAPI main is using an older version from the CR release-0.10 branch. So we can do the some change on CAPI main

I'll open a PR for that.

**Pull request merged**
