### PR TITLE
🌱 bump crypto dep version

### PR DESCRIPTION
**Pull request by cahillsf**
**What this PR does / why we need it**:

Fixes failing security scan: https://github.com/kubernetes-sigs/cluster-api/actions/runs/7321592425/job/19942156373

/area dependency

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thx!

/approve

**Comment by sbueringer** [comment]
Maybe we'll get lucky with the cherry-picks

/cherry-pick release-1.6

**Pull request merged**
