### PR TITLE
🌱 Bump cluster-autoscaler to v1.29.0

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/cherry-pick release-1.6

(tests on release-1.6 where also bumped to test Kubernetes 1.29)

**Review by vincepri — APPROVED** [review]
/area e2e-testing
/lgtm

**Pull request merged**
