### PR TITLE
🌱 Bump default kind image to v1.32.0

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Kind added a new image for v1.32.0: https://github.com/kubernetes-sigs/kind/releases/tag/v0.25.0

Part of:

- #11064

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area e2e-testing

### CODE REVIEW

**Comment by chrischdi** [comment]
Manually verified quickstart.

/hold cancel

**Review by fabriziopandini — COMMENTED** [review]
Thanks for the quick turnout!
/lgtm
/approve

**Pull request merged**
