### PR TITLE
 🌱 Swap in new 1.9 RT members in OWNERS

### PR DESCRIPTION
**Pull request by Sunnatillo**
**What this PR does / why we need it**:
This PR updates new v1.9 release team members in OWNERS files

/area release

### CODE REVIEW

**Comment by sbueringer** [comment]
Please review release-team internally and then let me know when you need an approve to merge

/ok-to-test

**Review by chandankumar4 — APPROVED** [review]
lgtm

**Comment by Sunnatillo** [comment]
> Thanks for this PR! Happy to approve after #11097 is merged

#11097 got merged

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
