### PR TITLE
🌱 Extend Node drain e2e test to cover MachineDrainRules

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #11240

### CODE REVIEW

**Comment by sbueringer** [comment]
Rebased onto main

/assign @fabriziopandini @enxebre @vincepri

**Comment by fabriziopandini** [comment]
Nice job! great to have this test already implemented at this stage of the development cycle
/lgtm
/approve

**Pull request merged**
