### PR TITLE
⚠️ E2E test support definition of test files for each version

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR make it possible to define test file for each version of providers involved in a test, so it will be possible to test clusterctl upgrades from v1alpha3 to v1alpha4

In order to do so, existing ComponentSource types were removed from the current location `test/framework/config.go` and a new alternative was created into `test/framework/clusterctl/e2e_config.go`

(spin-off of #3708)

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/test pull-cluster-api-test-main

These test failures are flakes not related to changes in this PR

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
