### PR TITLE
🏃 Adds chuckha to maintainers list

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
Adds @chuckha to the maintainers list

lazy consensus! Probably keep this open for a week

/hold

### CODE REVIEW

**Comment by vincepri** [comment]
(Waiting to give a heads up to tomorrow's meeting)

Side note: should we do this as part of a the promotion process we discussed last week?

**Comment by ncdc** [comment]
Do you all want to merge this as-is, and then do a PR for promotions, or do a single PR for all promotions? (I'm fine either way.)

**Comment by vincepri** [comment]
I'll leave it up to @chuckha. I'd prefer to do promotions/removals in one batch if possible like we did in the early days of cluster api. 

We're also going to bring in other repositories with new reviewers/maintainers, which should be taken into account as well

**Comment by chuckha** [comment]
Those owner files are separate and will likely each have their own pr anyway. Let's merge and we can do an overall project OWNERS files update later

**Pull request merged**
