### PR TITLE
📖  Update site home page

### PR DESCRIPTION
**Pull request by a-mccarthy**
**What this PR does / why we need it**: 
This PR updates content on the home page of the cluster api docs site. The goal is to add more context around what cluster api is and why it was built to help new users understand the project better. Additionally, this PR includes some minor adjustments to the home page layout.

**Questions**:
* I have some other suggestions for the Community section on this page, which its included from thee README.md:Community file. Should I add those to this PR?

### CODE REVIEW

**Comment by vincepri** [comment]
🎉 

/ok-to-test

**Comment by vincepri** [comment]
```
docs/book/src/introduction.md
	ERROR	./developer/guide.html
		Stat docs/book/src/developer/guide.html: no such file or directory
	ERROR	/contributing.md
		Document root directory is not specified
	ERROR	/reference/providers.html
		Document root directory is not specified
```

Seems we might have to fix these links

**Comment by a-mccarthy** [comment]
@vincepri looks like the tests are all passing now. yay!

**Comment by vincepri** [comment]
/assign @detiber 
/approve

@a-mccarthy Are you able to squash commits?

**Comment by detiber** [comment]
lgtm pending squash

**Comment by a-mccarthy** [comment]
@vincepri and @detiber thanks for the reviews. I actually had another change i wanted to make to the Community section on this page. However, that content site's is pulled from the README, should i put that change into this PR? or open a new one?

I also am not sure how to squash commits :)

**Comment by detiber** [comment]
/lgtm
let's handle the other changes as a separate PR

**Pull request merged**
