### PR TITLE
⚠️ Remove util/restmapper package

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

### CODE REVIEW

**Comment by ncdc** [comment]
LGTM.

@akutz @andrewsykim @rudoi @juan-lee @rsmitty @michaelgugino @dlipovetsky FYI, this is breaking change to `master` potentially for downstream consumers, albeit a small one. Wanted to make sure you were aware. LMK if you have any concerns. Thanks!

**Comment by andrewsykim** [comment]
Thanks for the heads up!

**Comment by vincepri** [comment]
@ncdc Good to merge?

**Comment by dlipovetsky** [comment]
Noting in the commit message that it's replaced by the new mapper in controller-runtime would have been helpful. I see that it's documented in the v1a2-to-v1a3 doc, though, so thanks for that!

**Pull request merged**
