### PR TITLE
🌱 Add ClusterClass variables metadata

### LINKED ISSUE #10023: Provide metadata to ClusterClass variables
### What would you like to be added (User Story)?

As a developer/operator of cluster classes I would like to have additional metadata to the ClusterClass template variables. This would make possible automated selection of variable groups for UI purposes, and improve overall UX.

### Detailed Description

```go
type ClusterClassVariable struct {
	// Name of the variable.
	Name string `json:"name"`

        // Arbitrary metadata related to the variable
        Metadata map[string]string `json:"metadata"`

        … // All other fields
}
```

Cluster class will get an ability to assign common groups where the variable belongs, or pass any kind of information wich will not be visible in documentation, as would happen while using `Example` field.

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind feature

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
See issue for details. Would be nice to get this merged this week so it can be easily included in v1.7.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10023

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @fabriziopandini @chrischdi 

/cc @richardcase @Danil-Grigorev @JoelSpeed 
(@Danil-Grigorev I hope it's okay that I've opened this PR, I would like to get this into v1.7.0)

**Review by Danil-Grigorev — APPROVED** [review]
/lgtm

**Comment by Danil-Grigorev** [comment]
/lgtm
Thanks for jumping on this!

**Review by chrischdi — COMMENTED** [review]
/approve

/hold

in case you want others to review too.

**Comment by sbueringer** [comment]
/cherry-pick release-1.6

(based on the experimental feature clause, for quicker adoption)

**Pull request merged**
