### PR TITLE
🌱 Move internal test packages into internal/test

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
I think now that we've moved a few more packages into internal/ it makes sense to group the test packages together in `internal/test`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Found in the context of #5455

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
@fabriziopandini rebased

**Pull request merged**
