### PR TITLE
✨ gcp: add capg to clusterctl providers list

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
 add CAPG to clusterctl providers list which was not included

@devigned this is why you were not able to use clusterctl to get the provider

/assign @fabriziopandini @detiber 

If I forgot anything please let me know, thanks!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by cpanato** [comment]
hum, some flaky, will see if can we improve

**Review by wfernandes — COMMENTED** [review]
Hey @cpanato! Mostly lgtm. I know that GCP releases has a metadata.yaml as part of the release assets but if you'd like you can optionally include embedded metadata here as well.
https://github.com/kubernetes-sigs/cluster-api/blob/8437691189ad8de58168f6de1312e8ee56813a5b/cmd/clusterctl/client/repository/metadata_client.go#L234

**Comment by vincepri** [comment]
@wfernandes Do we want to keep adding metadata embedded in code or move away from it in the future?

**Comment by wfernandes** [comment]
I did want to move away from the embedded metadata TBH, but I thought we can cross that bridge when we get there and remove everything all at once as part of this https://github.com/kubernetes-sigs/cluster-api/issues/3515

I'm fine with not adding gcp metadata in this PR. 🙂

**Comment by fabriziopandini** [comment]
/milestone v0.4.0
IMO, this is also a good candidate for backporting...

**Comment by cpanato** [comment]
@wfernandes added PTAL

@fabriziopandini I will open a backport PR as soon this gets merged

**Comment by detiber** [comment]
/approve

Thanks for all your hard work getting this ready @cpanato

**Pull request merged**
