### PR TITLE
🌱 Use 10 ginkgo nodes for e2e tests

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #9579

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @killianmuldoon 

/hold 
for next 1.4 patch release

**Review by killianmuldoon — COMMENTED** [review]
/area ci

/lgtm

/hold

Until 1.4.8 is released.

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-release-1-4 

(never actually ran it on this branch to see how long it takes)

**Comment by sbueringer** [comment]
Hm doesn't look very stable, let's defer this :)

**Comment by sbueringer** [comment]
I'll revive this after we moved everything to EKS which I guess happens the next 1-2 months

**Comment by sbueringer** [comment]
/close

for now

**Pull request closed without merging**
