### PR TITLE
🌱 Migrate gcr.io/kubernetes-ci-images to gcr.io/k8s-staging-ci-images

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Migrate gcr.io/kubernetes-ci-images to gcr.io/k8s-ci-images. Backport of https://github.com/kubernetes-sigs/cluster-api/pull/4107 to release-0.3 branch.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold 
for #4107 to merge

**Comment by vincepri** [comment]
@furkatgofurov7 Run `make generate` on this PR, seems it's out of date

**Comment by fmuyassarov** [comment]
> @furkatgofurov7 Run `make generate` on this PR, seems it's out of date

lol, it should have been @fmuyassarov

**Comment by fmuyassarov** [comment]
@vincepri this one is also ready to go I think.

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
