### PR TITLE
📖 Retire Managed Kubernetes Feature Group

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**:

This CAEP and subsequent work that follows from it is sufficient to move Managed Kubernetes forward in Cluster API:

- https://github.com/kubernetes-sigs/cluster-api/pull/8500

Thanks, everyone!

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx everyone for working on this!

/lgtm

**Review by killianmuldoon — COMMENTED** [review]
Job well done!

/lgtm

@jackfrancis let me know if you think this is fine to be approved or if you'd like more eyes on it.

**Comment by fabriziopandini** [comment]
Thanks everyone for working on this!
/lgtm
/approve

**Pull request merged**
