### PR TITLE
Added more spec for machinedeployment.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by detiber** [comment]
looks good to me, but defer offical lgtm to @davidewatson
/assign @vincepri
/milestone v1alpha1

**Comment by gyliu513** [comment]
FYI @davidewatson can you help review?

**Pull request merged**
