### PR TITLE
:seedling: Update cert-manager to v1.12.0

### PR DESCRIPTION
**Pull request by killianmuldoon**
Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.12.0

/area dependency

### CODE REVIEW

**Comment by killianmuldoon** [comment]
Not sure if we should backport this one  - there's no CVEs in this release, so maybe let's leave it for the time being.

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

I think we can cherry-pick given:
> - Cert-manager version bumps (to avoid having releases with cert-manager versions that are out of support, when possible)

1.11 should be out of support in ~ 4 months. So maybe it's just easier to cherry-pick through vs. letting them diverge and trying to only bump when they are actually out of support.

**Pull request merged**
