### PR TITLE
🌱 Use manager in test extension

### LINKED ISSUE #7258: Consider adding liveness/readiness probes and metrics endpoint to test extension
To make our test extenson / the reference implementation more production ready it would be great if we have readiness/liveness and metrics endpoints.

**Details**

I think we have at least two options:
* start a manager which gives us the additional endpoints always for free
  * we have to figure out how that can work with our custom extension server (which uses a webhook server underneath)
* implement similar endpoints as CR in our webhook server library

It would be great if we could also use the webhookServer.StartedChecker for our liveness/readiness endpoints like we do in our controllers here: https://github.com/kubernetes-sigs/cluster-api/blob/73f436e4778d31758f50b295a65a8a70b33ca354/main.go#L284-L292

/area topology
/kind feature

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7258

### CODE REVIEW

**Comment by fabriziopandini** [comment]
Nice! awesome to to see the runtime extensions catching up with the rest of capi, getting liveness/readiness probes, settings for TLS, client-go QPS and burst etc.
A lot of great things!
/lgtm
cc @chrischdi

**Comment by sbueringer** [comment]
Looks like I broke RBAC. Another try...

/test pull-cluster-api-e2e-main

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Going to cherry-pick this as an improvement of our test code.

The changes in exp/runtime/server/server.go are compatible (and it's also an experimental feature/package)


/cherry-pick release-1.6

**Pull request merged**
