### PR TITLE
:seedling: Update cert-manager to v1.10.1

### LINKED ISSUE #7702: Bump cert manager to v1.10.1
This fixes some CVEs; ideally, we should backport to 1.2

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Update cert-manger to v1.10.1. 

Fixes #7702

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/cherry-pick release-1.3

**Review by ykakarap — CHANGES_REQUESTED** [review]

**Review by ykakarap — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by killianmuldoon** [comment]
Will do a manual cherry pick.

**Pull request merged**
