### PR TITLE
🌱 Make generate clusterctl config changes

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Somehow a PR got through without running make generate (probably #4113 ?). For now this pushes the latest make generate changes. As a follow up we should find out why PR tests didn't catch this. Unless this is being generated incorrectly?

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/hold

verify is saying generated files are out of date, not sure what's going on... I double checked my branch is rebased with latest upstream main branch. Will investigate tomorrow PT time.

**Comment by fabriziopandini** [comment]
I stumbled into the same problem and solved by doing `make clean generate-biodata`
`make clean` force the rebuild of the bin data util, and this fixed everything for me

**Pull request closed without merging**
