### PR TITLE
:seedling: Add Status.NodeInfo to Machine objects

### PR DESCRIPTION
**Pull request by vincepri**
This change syncs up NodeInfo from the Node object upon reconciliation.

Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by ykakarap** [comment]
LGTM overall but might have to run `make generate` also may be adjust for the custom conversion function.

**Comment by fabriziopandini** [comment]
lgtm pending fix to generate func

**Pull request merged**
