### PR TITLE
🌱 add custom reference types

### PR DESCRIPTION
**Pull request by schrej**
**What this PR does / why we need it**:
This PR adds new reference types to gradually replace `v1.ObjectReference` over time. It also contains some utility and conversion methods.

It was argued in #2318 that it's too big of a breaking change with no real benefit, and that `v1.ObjectReference` is used everywhere.
I'd still like to replace it because of several reasons:

- Use of [`v1.ObjectReference`](https://pkg.go.dev/k8s.io/api/core/v1#ObjectReference) is discouraged. It's recommended to create custom types instead. The reasons listed are similar to the ones I see with cluster-api.
- A lot of fields within references are there, but not respected by CAPI. It's technically a breaking change to remove them. But any fields that would get removed (with the exception of `APIVersion`) aren't used at all by CAPI, or have a predictable value (Namespace). Using those fields anyway is possible, but they have no effect on CAPI, and it can be very unclear which fields are actually used where.
- Pinning the version in the reference is useless, and even generates [extra work](https://github.com/kubernetes-sigs/cluster-api/blob/992a83c2ac8e02ac0ab3fed5ed2c88ebd82cebf6/util/conversion/conversion.go#L64). The clients should be able to decide on their own which version they want to query. That's why versioning and conversion exists.
- Validation is used frequently to ensure references don't reach across namespaces. It would be much simpler if the namespace field just didn't exist on those references.

I propose to add these new reference types (collected from my previous work on this issue, e.g. #5001) to move the hurdle of discussing the types when trying to avoid `v1.ObjectReference`.
They should be used by any new types added to CAPI. And the rest should follow with v1beta2. 

**Which issue(s) this PR fixes**:
#2318

### CODE REVIEW

**Comment by enxebre** [comment]
thanks @schrej, is the proposed API solving anything we couldn't get by switching to https://github.com/kubernetes/api/blob/v0.23.3/core/v1/types.go#L5617 if we choose to?

**Comment by schrej** [comment]
Oh, good find. Those should be sufficient for local references, yes. We can certainly get rid of the `LocalObjectReference` then. We'll have to decide whether we want to have a "pinned" reference, containing a UID and therefore referencing a specific object, for status or not.
I didn't find any namespaced references there though, so we would need to keep those in CAPI if we need them. And, if we have a few custom reference types, it might make sense to keep all of them within CAPI, for both consistence and the convenience of having conversion methods imo.

**Comment by sbueringer** [comment]
@schrej WDYT about opening an issue for this? Just so we can discuss how/if we can make this change and then track it accordingly so we can make the change when it's appropriate based on our deprecation policies (probably before v1beta2 (?))

We recently found out that the Namespace field in MD/MS/Machine refs is not actually used. I would have added that to a "Let's get rid of ObjectReference" issue, but it doesn't seem we have one.

**Comment by schrej** [comment]
#2318 used to be about replacing v1.ObjectReference, but was renamed at some point as it was decided to keep it for now.

**Comment by sbueringer** [comment]
> #2318 used to be about replacing v1.ObjectReference, but was renamed at some point as it was decided to keep it for now.
> 
> But we can of course create another one to start the discussion again.

I wasn't aware of the rename. I think if that issue is now scoped to only documentation it would be good to have an issue for the change itself **if** we plan on implementing it at some point.

**Comment by vincepri** [comment]
Closing this in favor of discussing it first in #6539

**Pull request closed without merging**
