### PR TITLE
🌱 Add k3s providers to cluster-api book

### PR DESCRIPTION
**Pull request by zawachte**
**What this PR does / why we need it**:
Adds https://github.com/cluster-api-provider-k3s/cluster-api-k3s to the cluster-api book.
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
No existing issue ... can create one if needed.

### CODE REVIEW

**Comment by zawachte** [comment]
> * Do you also want to add this provider to `clusterctl`?
If that is allowed ... would love to.

> * Do you know what the differences are between this provider and the kubekey k3s provider? - https://github.com/kubernetes-sigs/cluster-api/pull/7528 @24sama who added that last year.

I don't. I agree with the concern. It would be good to understand the overlap.

**Comment by 24sama** [comment]
Hi @zawachte @killianmuldoon 
The kubekey k3s provider basically forks the cluster api k3s provider and optimizes some logic to accommodate kubekey use.

**Comment by killianmuldoon** [comment]
> The kubekey k3s provider basically forks the cluster-api-k3s-provider and optimizes some logic to accommodate kubekey use.

Would there be any way to upstream those changes and deduplicate the effort? Seems like it would be good for everyone.

Either way I think it's fine to add the k3s providers to the book. @fabriziopandini WDYT about adding this provider to clusterctl given the duplication?

**Comment by CecileRobertMichon** [comment]
+1 to adding k3s to both the book and clusterctl 

Agree with @killianmuldoon that it would be best to make the changes to the k3s provider instead of maintaining a separate provider, if the kubekey changes are generic enough that they can benefit all

**Comment by 24sama** [comment]
Agree with @killianmuldoon,  kubekey changes are not very generic. We may spend some time contributing these changes upstream.

And for this PR, +1 to adding k3s provider to the book.

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

The duplication definitely shouldn't prevent this provider from being in the CAPI book - but it would be great if there could be some joint effort to merge the two providers.

Thanks @zawachte and @24sama for helping me understand the current state.

**Comment by zawachte** [comment]
Thanks @killianmuldoon. I will raise a follow up for the clusterctl support.

**Pull request merged**
