### PR TITLE
:sparkles: Docker: Add support to specify network name

### PR DESCRIPTION
**Pull request by PedroRibeiro95**
**What this PR does / why we need it**:

By default, the CAPD provisioner forces the use of the `kind` network in Docker. This breaks other use cases when deploying in Docker, but not using Kind (like K3D), as the controller will fail to create resources as it cannot find the network to bind to. 

This change allows the user to optionally specify a different network name to use for provisioning, which allows deploying under different platforms.

**Which issue(s) this PR fixes**:

/area provider/infrastructure-docker

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

The specific use case of specifying the network seems okay to me - but CAPD doesn't support k3s, and I don't think there's any plans to do so. 

If that's the overall goal it would be good to create an issue outlining the approach and the changes that could be required in CAPD.

**Comment by PedroRibeiro95** [comment]
Good catch @killianmuldoon, I actually meant to say k3d. I sucessfully managed to launch a CAPD-managed cluster using the ClusterAPI by mounting the `docker.sock` to the k3d nodes, by manually patching the CAPD controller to use an image built with this change and by adding the name of the k3d network to the Docker CAPI resources. I think this change gives flexibility for cases where people want to test under a Docker environment, but not necessarily through kind.

**Comment by fabriziopandini** [comment]
> it would be good to create an issue outlining the approach and the changes that could be required in CAPD.

I agree with that
/hold

>  I think this change gives flexibility for cases where people want to test under a Docker environment, but not necessarily through kind.

CAPD does not require kind.
But it makes assumptions about using a docker network named kind, that's all we need.
The reason for that is that using kind as a network name is that it makes things easier for folks using kind to setup the management clusters, as well as E2E tests were we are using kind.

If k3d provides a docker environment, what you have to do is to create a network named kind for CAPD to work

**Comment by fabriziopandini** [comment]
/close
due to lack of updates

**Pull request closed without merging**
