### PR TITLE
🐛 KubeadmControlPlane should adopt v1alpha2 kubeconfig secrets

### LINKED ISSUE #4047: Backport KubeadmControlPlane should adopt v1alpha2 kubeconfig secrets to release 0.3
**User Story**

https://github.com/kubernetes-sigs/cluster-api/pull/4034 introduced a fix for ensuring kubeconfig secrets created by v1alpha2 controllers are adopted by KCP, thus allowing periodic kubeconfig secret re-generation preventing the expiration of the embedded client certificate.

This fix should be backported in the release 0.3 branch; Nb. small changes are required due to differences in controller-runtime (e.g. logger is not available in the context, so it should be passed as a parameter from the reconcile method down the chain)

/kind bug

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
Backports the fix made to the `main` branch as part of #4034 

**Which issue(s) this PR fixes**:
Fixes #4047

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/lgtm
/assign @CecileRobertMichon @detiber 
for approval

**Review by CecileRobertMichon — APPROVED** [review]
/approve

**Pull request merged**
