### PR TITLE
Remove lint comments and fix issues

### LINKED ISSUE #1553: Avoid using //nolint in the codebase
Unless absolutely necessary, we should try and remove the `//nolint` comments in the codebase by fixing the linting issues.

/kind feature
/help
/priority backlog
/milestone v0.3.0

### PR DESCRIPTION
**Pull request by avorima**
**What this PR does / why we need it**:

Removes some `nolint` comments and fixes issues. Leftover `nolint` comments are due to

- Receiver name mismatch in `api/v1alpha2`
- Gosec issue in `test/helpers/kind/setup.go`

The auto-generated deep copy files use `in` as receiver name, whereas the conversion code uses either `src` or `dest` for the `ConvertTo*` and `ConvertFrom*` methods.

Gosec complains because the arguments to `exec.Command` are not constants or initialized in the function that calls `exec.Command`. This will always be the cases, since the name is a public property of the Cluster struct and the path to the kind binary is a command line flag.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1553

### CODE REVIEW

**Comment by fabriziopandini** [comment]
lgtm for the clusterctl part

**Comment by vincepri** [comment]
@avorima PR needs rebase

**Pull request merged**
