### PR TITLE
🌱 Fix comment issue in method `MachineSetToDeployments`

### PR DESCRIPTION
**Pull request by chymy**
**What this PR does / why we need it**:
Fix comment issue of  `MachineSetToDeployments`  method in `controllers/machinedeployment_controller.go`
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by alexander-demichev — COMMENTED** [review]
thanks!

**Review by fabriziopandini — COMMENTED** [review]
/approve

**Pull request merged**
