### PR TITLE
📖 Update CAPI support and guarantees for v1.8

### PR DESCRIPTION
**Pull request by chandankumar4**
**What this PR does / why we need it**:

This PR updates the supported versions for the next release cycle (1.8).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes Task: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#update-supported-versions

@kubernetes-sigs/cluster-api-release-team

/area documentation

### CODE REVIEW

**Comment by sbueringer** [comment]
This has overlap with @fabriziopandini's PR

**Comment by sbueringer** [comment]
Okay I think it's easier to rebase if we merge this one first

/ok-to-test
/lgtm
/approve

**Comment by fabriziopandini** [comment]
@sbueringer ok to rebase my PR, but we should find a way to set EOL for 1.5 in the current version of the book without cherry-picking the new 1.8 columns that should exist only on main

**Comment by fabriziopandini** [comment]
The two PR are orthogonal now
@chandankumar4 could you cherry-pick your PR to 1.7 (without the 1.8 column)?

**Comment by fabriziopandini** [comment]
Yes, I think it makes sense to backport everything in this PR except for the 1.8 column

**Pull request merged**
