### PR TITLE
🌱 fixed grammatically incorrect plurals in release tools

### LINKED ISSUE #9009: Fix grammatically incorrect plurals in the release notes tool
### What steps did you take and what happened?

[Release notes tool](https://github.com/kubernetes-sigs/cluster-api/blob/main/hack/tools/release/notes.go) logs incorrectly framed plurals in the release notes. Example: `1 new commits merged`

### What did you expect to happen?

It would be nice if the release notes tool outputs singular nouns when there is just one change and plural nouns when there are many. 

### Cluster API version

Unrelated to CAPI version. 

### Kubernetes version

Unrelate to K8s version

### Anything else you would like to add?

This issue should be part of https://github.com/kubernetes-sigs/cluster-api/issues/9008

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by Dhairya-Arora01**
**What this PR does / why we need it**: fixed grammatically incorrect plurals in release tools as stated in #9009 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9009

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

/assign @g-gaston @nawazkh

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

/hold
Feel free to merge. Let's merge and cherry-pick it before the release

**Comment by nawazkh** [comment]
/lgtm
Thanks for the changes!

**Pull request merged**
