### PR TITLE
[release-1.2] 🐛 bugfix function aggregateFromMachinesToKCP

### PR DESCRIPTION
**Pull request by jackfrancis**
This is a manual cherry-pick of #8132 into release-1.2.

Credit to @wm775825 for the fix!

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx for cherry-picking!

/lgtm
/approve

**Comment by jackfrancis** [comment]
@sbueringer what's funny is that the linter appears to be wrong, as those vars are indeed referenced outside the modified if statement (in the case switch above).

**Comment by sbueringer** [comment]
Yeah that's roughly the reason why we dropped the linter :D

**Comment by sbueringer** [comment]
> Yeah that's roughly the reason why we dropped the linter :D

@jackfrancis Was no fun to try to debug this: https://github.com/esimonov/ifshort/issues/23
(+ linter is apparently archived now)

**Pull request merged**
