### PR TITLE
Fix links in Architecture documentation.

### PR DESCRIPTION
**Pull request by ArmandGrillet**
The links now point to the legacy documentation of Kubebuilder.

**What this PR does / why we need it**: The links in the documentation were broken, after checking the Kubebuilder documentation it appears that they have been moved to the legacy documentation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
@ArmandGrillet thank you for the contribution. Once you have sorted out the CLA bot instructions linked above, we can get this merged :)

**Comment by ArmandGrillet** [comment]
@detiber CNCF CLA signed ✅

**Pull request merged**
