### PR TITLE
🐛 Etcd should talk to leader when moving leadership

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
/assign @chuckha

### CODE REVIEW

**Comment by chuckha** [comment]
/lgtm

this will unblock the current failure, i'll clean up this function tho as the logic is a little bit confusing to follow

**Comment by vincepri** [comment]
Tested on a running AWS cluster, it immediately unblocked upgrades

**Pull request merged**
