### PR TITLE
🌱 Update Controller Runtime v0.9.6 / envtest Kubernetes 1.22.0

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@vincepri Just out of curiosity. Imho it's not a big issue as CI runs not on Mac.

Does this mean when running with `KUBEBUILDER_ENVTEST_KUBERNETES_VERSION` below v1.22 on MacOS I'll get the race condition mentioned here https://github.com/kubernetes-sigs/controller-runtime/pull/1630/files?

**Comment by sbueringer** [comment]
/lgtm
/retest
(the usual flake)

**Comment by vincepri** [comment]
@sbueringer No, that only applied to controller runtime (which spins up ~20 or more envtest environments)

**Comment by sbueringer** [comment]
> @sbueringer No, that only applied to controller runtime (which spins up ~20 or more envtest environments)

Oh of course. Thought - based on your Slack message - we also profit :)

**Pull request merged**
