### PR TITLE
:book: Documentation improvements: public release session

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Part of #9216 

**What this PR does / why we need it**:
- Add documentaion for public release session

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
/approve

/hold
feel free to unhold when the release team is happy with it

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks!

/lgtm

**Pull request merged**
