### PR TITLE
🌱 Give permissions for release notes tool to release team

### LINKED ISSUE #9524: Release tool review permissions for release team
### What would you like to be added (User Story)?

As the release team, we would like to able to review and merge change to the release tool by ourselves without depending on maintainers, speeding up the development cycle.

### Detailed Description

We propose to add `lgtm` permissions for the release team and `approve` permissions for the release team leader, only for the [`release`](https://github.com/kubernetes-sigs/cluster-api/tree/main/hack/tools/release) folder.

Follow up from https://github.com/kubernetes-sigs/cluster-api/pull/9500#pullrequestreview-1644587693

@kubernetes-sigs/cluster-api-release-team

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind proposal
/area release

### PR DESCRIPTION
**Pull request by g-gaston**
**What this PR does / why we need it**:
Give the release team more autonomy to iterate on the release tool.

**Which issue(s) this PR fixes**:
Fixes #9524

/area release

### CODE REVIEW

**Comment by g-gaston** [comment]
> Could we document in the release docs that this folder, and the `docs/release` folder have these permissions? Could be a good pointer for future release teams.

I don't have a strong opinion
@furkatgofurov7 opinions?

**Comment by furkatgofurov7** [comment]
> > Could we document in the release docs that this folder, and the `docs/release` folder have these permissions? Could be a good pointer for future release teams.
> 
> I don't have a strong opinion @furkatgofurov7 opinions?

No strong opinion either, but might be useful to document it since future teams know in advance what is possible / not when it comes to reviewing the PRs in specific folders without waiting for maintainers. Probably, it fits better somewhere in https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-team.md document

**Review by furkatgofurov7 — COMMENTED** [review]
Thank you!

/lgtm

**Comment by killianmuldoon** [comment]
/lgtm

Would like to get a another maintainer to approve given this is an Owner file change.

**Review by neolit123 — COMMENTED** [review]
+1

**Pull request merged**
