### PR TITLE
🌱 clusterctl: Add labels to OWNERS file

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:
Testing automatic area labels (discussed in #8263) on a limited area to try it out.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Partof #8263

### CODE REVIEW

**Comment by oscr** [comment]
Question: why is the ci bot adding random emojis?

**Review by ykakarap — APPROVED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by oscr** [comment]
It worked! Created a pr and the area was auto assigned: #8344 8344

**Comment by sbueringer** [comment]
> > Question: why is the ci bot adding random emojis?
> 
> I think it does this for the Owners file - not sure `why` though

It has a plugin for it, not sure why 😃

**Comment by sbueringer** [comment]
Related

/joke

**Pull request merged**
