### PR TITLE
Enable integration tests and verbose logging on the continuous test run

### PR DESCRIPTION
**Pull request by spew**
**What this PR does / why we need it**:
This PR enables tests with the "integration" tag and verbose logging in the continuous integration test run. The reason why verbose logging should be turned on is it will make it much easier for developers to debug broken tests in the CI environment. 

**Release note**:

```release-note
NONE
```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by k4leung4** [comment]
lgtm

**Comment by jessicaochen** [comment]
Uh. We want to run unit tests in the presubmit, right? This seems to *only* run integration tests.

**Comment by spew** [comment]
I know it doesn't appear that way, but this will run both unit and integration tests. Also, there is no way to "only" run just the integration tests :(

See the below output for proof that this runs the unit tests: 

```
$ go test -tags=integration ./...
ok  	sigs.k8s.io/cluster-api/cloud/google	(cached)
ok  	sigs.k8s.io/cluster-api/cloud/google/clients	(cached)
?   	sigs.k8s.io/cluster-api/cloud/google/cmd/gce-machine-controller	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/google/cmd/gce-machine-controller/app	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/google/cmd/gce-machine-controller/app/options	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/google/cmd/generate-image	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/google/config	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/google/gceproviderconfig	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/google/gceproviderconfig/v1alpha1	[no test files]
ok  	sigs.k8s.io/cluster-api/cloud/google/machinesetup	(cached)
?   	sigs.k8s.io/cluster-api/cloud/terraform	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/terraform/cmd/terraform-machine-controller	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/terraform/config	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/terraform/namedmachines	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/terraform/terraformproviderconfig	[no test files]
?   	sigs.k8s.io/cluster-api/cloud/terraform/terraformproviderconfig/v1alpha1	[no test files]
ok  	sigs.k8s.io/cluster-api/clusterctl	6.523s
ok  	sigs.k8s.io/cluster-api/clusterctl/clusterdeployer	(cached)
ok  	sigs.k8s.io/cluster-api/clusterctl/clusterdeployer/minikube	(cached)
ok  	sigs.k8s.io/cluster-api/clusterctl/cmd	0.167s
?   	sigs.k8s.io/cluster-api/cmd/apiserver	[no test files]
?   	sigs.k8s.io/cluster-api/cmd/controller-manager	[no test files]
?   	sigs.k8s.io/cluster-api/errors	[no test files]
?   	sigs.k8s.io/cluster-api/gcp-deployer	[no test files]
?   	sigs.k8s.io/cluster-api/gcp-deployer/cmd	[no test files]
?   	sigs.k8s.io/cluster-api/gcp-deployer/deploy	[no test files]
?   	sigs.k8s.io/cluster-api/pkg	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/apis	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/apis/cluster	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/apis/cluster/common	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/apis/cluster/install	[no test files]
ok  	sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1	(cached)
?   	sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1/testutil	[no test files]
ok  	sigs.k8s.io/cluster-api/pkg/cert	(cached)
?   	sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/fake	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/scheme	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/clientset_generated/clientset/typed/cluster/v1alpha1/fake	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions/cluster	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions/cluster/v1alpha1	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/informers_generated/externalversions/internalinterfaces	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/client/listers_generated/cluster/v1alpha1	[no test files]
?   	sigs.k8s.io/cluster-api/pkg/controller	[no test files]
ok  	sigs.k8s.io/cluster-api/pkg/controller/cluster	(cached)
?   	sigs.k8s.io/cluster-api/pkg/controller/config	[no test files]
ok  	sigs.k8s.io/cluster-api/pkg/controller/machine	(cached)
?   	sigs.k8s.io/cluster-api/pkg/controller/machinedeployment	[no test files]
ok  	sigs.k8s.io/cluster-api/pkg/controller/machineset	(cached)
?   	sigs.k8s.io/cluster-api/pkg/controller/sharedinformers	[no test files]
ok  	sigs.k8s.io/cluster-api/pkg/node/util	(cached)
?   	sigs.k8s.io/cluster-api/pkg/openapi	[no test files]
?   	sigs.k8s.io/cluster-api/tf-deployer	[no test files]
?   	sigs.k8s.io/cluster-api/tf-deployer/cmd	[no test files]
?   	sigs.k8s.io/cluster-api/tf-deployer/deploy	[no test files]
?   	sigs.k8s.io/cluster-api/tools/repair	[no test files]
?   	sigs.k8s.io/cluster-api/tools/repair/cmd	[no test files]
?   	sigs.k8s.io/cluster-api/tools/repair/util	[no test files]
?   	sigs.k8s.io/cluster-api/tools/upgrader	[no test files]
?   	sigs.k8s.io/cluster-api/tools/upgrader/cmd	[no test files]
?   	sigs.k8s.io/cluster-api/tools/upgrader/util	[no test files]
?   	sigs.k8s.io/cluster-api/util	[no test files]
```

**Pull request merged**
