### PR TITLE
:book: Ensure correct make targets in order to build book

### PR DESCRIPTION
**Pull request by randomvariable**
Fixes https://master.cluster-api.sigs.k8s.io/

### CODE REVIEW

**Comment by randomvariable** [comment]
/hold

still don't have all the plugins working.

**Comment by detiber** [comment]
Added some additional details in the following slack thread: https://kubernetes.slack.com/archives/C8TSNPY4T/p1601395372085700?thread_ts=1601393918.082900&cid=C8TSNPY4T

I think the issue is the linkchecker plugin and the build image not supporting rust: https://kubernetes.slack.com/archives/C8TSNPY4T/p1601395372085700?thread_ts=1601393918.082900&cid=C8TSNPY4T

**Review by vincepri — APPROVED** [review]
/approve
/milestone v0.3.10

**Pull request merged**
