### PR TITLE
⚠️ Generate v1alpha4 types

### LINKED ISSUE #3428: Generate v1alpha4 types
Tracking issue to generate Cluster API types for:

- Core types
- CABPK
- KCP
- CAPD

/kind feature
/area api
/milestone v0.4.0

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
Generates types for v1alpha4
- [ ] Core types
- [ ] Core/experimental types
- [ ] Bootstrap types
- [ ] Control plane types
- [ ] Docker infra types

Remove v1alpha2 types

**Which issue(s) this PR fixes**:
Fixes #3428

### CODE REVIEW

**Comment by srm09** [comment]
@vincepri Does it make sense to overload this single PR with all the types, or should we create multiple PRs with each of the tasks.

**Comment by vincepri** [comment]
We also need to remove the v1alpha2 types

**Comment by vincepri** [comment]
@srm09 Single PR sounds good, but let's split the commits. If that sounds too much, we can do multiple PRs

**Comment by srm09** [comment]
Closing this, will open another one in its place.

**Pull request closed without merging**
