### PR TITLE
🌱 Promote CecileRobertMichon as maintainer

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
@CecileRobertMichon has been very active in both Cluster API repository, and running meetings.

### CODE REVIEW

**Comment by vincepri** [comment]
/milestone v0.3.x
/hold
for lazy consensus until next week

**Comment by detiber** [comment]
Huge +1 from me

**Comment by fabriziopandini** [comment]
Strong +1 from me, thanks @CecileRobertMichon  for all your help!

**Comment by justaugustus** [comment]
Huge +1 from me! Cecile has been extremely dedicated to this project since she start contributing to capz, and I'm looking forward to her continued maintainership.
/pony party

**Comment by ncdc** [comment]
+1 yay!

**Comment by fabriziopandini** [comment]
Lazy consensus deadline is passed and there is consensus
/hold cancel
/lgtm

@CecileRobertMichon, congrats! Now you should get the superpowers to apply the milestone label!

**Pull request merged**
