### PR TITLE
🌱 release notes: also detect alpha releases as pre releases

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
* While we don't do it / plan for it today. It's entirely possible that we want to cut alpha releases in CAPI at some point
* This tool is also used in (at least) CAPV / controller-runtime. Also relatively realistic that we have alpha releases there

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by willie-yao — APPROVED** [review]
/lgtm

**Review by chrischdi — COMMENTED** [review]
/approve

**Pull request merged**
