### PR TITLE
📖 Add envsubst as prerequisite in developer guide

### LINKED ISSUE #4012: Cannot start capi-controller-manager
I followed the instruction in https://cluster-api.sigs.k8s.io/developer/guide.html
the developer guide, with the option 2, the old-fashioned way. Everything is fine until I check the status of cluster:

NAMESPACE             NAME                                         READY   STATUS             RESTARTS   AGE
capi-system           capi-controller-manager-d56f68c59-xmk6x      1/2     CrashLoopBackOff   1          13s
capi-webhook-system   capi-controller-manager-76ddbdd9dd-z6b85     1/2     CrashLoopBackOff   1          13s

I checked the logs:
kubectl logs capi-controller-manager-d56f68c59-xmk6x -n capi-system -c manager
invalid argument "MachinePool=${EXP_MACHINE_POOL:=false},ClusterResourceSet=${EXP_CLUSTER_RESOURCE_SET:=false}" for "--feature-gates" flag: invalid value of MachinePool=${EXP_MACHINE_POOL:=false}, err: strconv.ParseBool: parsing "${EXP_MACHINE_POOL:=false}": invalid syntax

**What did you expect to happen:**
The status of pods should be running.

**Environment:**

- Cluster-api version:
$ clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.11", GitCommit:"e9cf6846b6d93dedadfcf44c00357d15f5ccba64", GitTreeState:"clean", BuildDate:"2020-11-19T18:49:17Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Minikube/KIND version: 
$ kind version
kind v0.9.0 go1.15.2 linux/amd64

- Kubernetes version: (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"clean", BuildDate:"2020-11-11T13:17:17Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-14T07:30:52Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from `/etc/os-release`):
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"

/kind bug
/area clusterctl

### PR DESCRIPTION
**Pull request by Insullone**
What this PR does / why we need it:
Add envsubst as prerequisite in Chapter 'Developer Guide' of the book and update corresponding instructions using envsubst.

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #4012

### CODE REVIEW

**Comment by Insullone** [comment]
Should be done with signing the CLA, please verify

**Review by vincepri — APPROVED** [review]
/lgtm
/milestone v0.4.0

**Comment by vincepri** [comment]
/approve

@Insullone This requirement applies to v0.3.x as well, could you cherry-pick this commit to release-0.3 branch?

**Comment by Insullone** [comment]
@vincepri Sure, no problem.

**Comment by Insullone** [comment]
@vincepri PR was made #4025 in release-0.3

**Pull request merged**
