### PR TITLE
Update bootstrap proposal: document Status.Ready

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR updates the bootstrap proposal to match v1alpha2 controller expectations around `Status.Ready` for bootstrap and infrastructure providers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
It also removes outdated links in comments to the previously used sequence diagram tool.

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by vincepri** [comment]
Unfortunately that was a Google doc one, I can try to update it or remove it

**Comment by chuckha** [comment]
either way, i kinda like it, but i also wouldn't miss it terribly if it were gone

thanks for getting this done!!

**Comment by vincepri** [comment]
@chuckha Converted Figure 1 in #1163

**Comment by vincepri** [comment]
@chuckha Is this good to go?

**Pull request merged**
