### PR TITLE
🌱 Retire the Alternative communication pattern feature group

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
After chatting with the organizers of the feature group, we agreed that we should put this work on hold due to lack of contributors/lack of interest. 

A great thanks to @richardcase and @fgutmann for the work so far, and let's hope this discussion gets back some interest soon.

/area community-meeting

### CODE REVIEW

**Comment by richardcase** [comment]
I can't make the office hours. I think given that the feature group started strong and then faded away that it's good to retire it.

I think the discussion will come up again in the future and we can resurrect it again at that point.

So +1 for retiring it.

**Comment by chrischdi** [comment]
Thanks for the effort.

/approve

**Comment by fabriziopandini** [comment]
/hold cancel
As per office hours discussion

**Comment by fgutmann** [comment]
Thank you @richardcase and all others who contributed to the group! I truly enjoyed all our meetings and discussions. Unfortunately, I also do not have the capacity at this time anymore to contribute to this group.

Thanks for giving the group a graceful retirement :-)

**Pull request merged**
