### PR TITLE
📖 add release 1.8 book link

### PR DESCRIPTION
**Pull request by chandankumar4**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

Part of: https://github.com/kubernetes-sigs/cluster-api/issues/11092

/area release

### CODE REVIEW

**Comment by chandankumar4** [comment]
> @chandankumar4 are we planning to backport this change?

@fabriziopandini 
No, we don't need to backport this change, as the 3rd point mentioned [here](https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/communications#ensure-the-book-for-the-new-release-is-available) it's only for main branch.

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Comment by chandankumar4** [comment]
One [this](https://github.com/kubernetes/k8s.io/pull/7570) PR is merged, the broken link should be fixed!!

**Comment by fabriziopandini** [comment]
> Once https://github.com/kubernetes/k8s.io/pull/7570 PR is merged, the broken link should be fixed!!

It is merged now

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Pull request merged**
