### PR TITLE
Cannot retrieve machine name

### PR DESCRIPTION
**Pull request by clyang82**
Cannot get the machine name there. so just replace with `machine` string.

Signed-off-by: clyang82 <clyang@cn.ibm.com>

### CODE REVIEW

**Comment by vincepri** [comment]
I'm confused on why this change is needed. Isn't the machine name a required field that should always be populated?

**Comment by clyang82** [comment]
> I'm confused on why this change is needed. Isn't the machine name a required field that should always be populated?

machine name is generated based on `generateName` from `machines.yaml`. during this step, we cannot get the machine name so that it is always empty. it is better to use general name `machine` to complete this sentence.

**Comment by vincepri** [comment]
I see, this is a problem specific to clusterctl. 

/approve
/assign @davidewatson @chuckha @ncdc

**Comment by clyang82** [comment]
@vincepri Could you leave a `/lgtm` label here? Thanks.

**Pull request merged**
