### PR TITLE
🌱 ClusterClass: clarify that enum works with all types

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
Need to run make-generate I think - otherwise
/lgtm

**Comment by sbueringer** [comment]
> Need to run make-generate I think - otherwise /lgtm

Thx, yup. Should be fixed now

**Comment by sbueringer** [comment]
Next try this time with regenerated deep copy funcs

**Pull request merged**
