### PR TITLE
:seedling: update github.com/go-logr/logr and k8s.io packages

### PR DESCRIPTION
**Pull request by bhcleek**
Update github.com/go-logr/logr to the latest release, v1.2.2, and k8s.io
packages to the versions required to work with the v1.x versions of
github.com/go-logr/logr. The changes to accommodate
github.com/go-logr/logr were cherry picked from commit
3b4953a9021de8abf184b5fba59ff43e36738667.

In addition to the changes from commit
3b4953a9021de8abf184b5fba59ff43e36738667, this also required two small
changes to do a deep copy of a machine before calling
reconcileInterruptibleNodeLabel and changes to use the expected types
for webhook configurations required to work with the updated
controller-runtime.

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@bhcleek We are only doing those kind of version changes on new CAPI minor releases, as they are considered breaking changes.

> https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#codebase-and-go-modules
> A (patch) release SHOULD only include backwards compatible set of bugfixes.

**Comment by bhcleek** [comment]
@sbueringer thank you for taking a look.

I think this may qualify for 
> We only accept backports of critical bugs, security issues, or bugs without easy workarounds, any backport MUST not > be breaking for either API or behavioral changes. We generally do not accept PRs against older release branches.

The changes here are all required to be able to use a github.com/go-logr/logr. In the case where a Go module uses sigs.k8s.io/cluster-api and either k8s.io package >= v0.23.0 _or_ anything else that uses the >=v1 release of github.com/go-logr/logr, it's not possible to use the sigs.k8s.io/cluster-api in the v0.4 line at the moment, because of breaking changes introduced in github.com/go-logr/logr between v04.0 and v1.2.2.

**Comment by sbueringer** [comment]
I think in those cases we can only recommend to use a newer version of CAPI.

Different consumers of CAPI v0.4.x might want to use different versions of our dependencies. But our policy up until now was to pick one minor controller-runtime / Kubernetes version and stick without during for the entire release series (in this case v0.4.x).

If we upgrade to newer versions of those dependencies in the next v0.4.x release, this will be a breaking change for all consumers which are relying on the current versions.

**Comment by bhcleek** [comment]
Understood. Should I close this then?

**Comment by sbueringer** [comment]
I think, yes. Unfortunately we can't merge it.

**Pull request closed without merging**
