### PR TITLE
Add make genclientset to generate the clientset just with one command

### PR DESCRIPTION
**Pull request by ingvagabund**
**What this PR does / why we need it**: Adding `make genclientset` to generate the clientset

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

More about the `client-gen`: https://github.com/kubernetes/community/blob/master/contributors/devel/generating-clientset.md

**Release note**:

```release-note
None
```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by ingvagabund** [comment]
https://github.com/kubernetes/client-go/commit/af8ed43b018ae37b7ac79a162c28fb7921049224 missing in release-6.0 branch.

**Comment by ingvagabund** [comment]
@justinsb @kris-nova @roberthbailey PTAL

**Comment by roberthbailey** [comment]
lgtm

**Pull request merged**
