### PR TITLE
🐛  Add list conversions

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Bueringer <buringerst@vmware.com>

**What this PR does / why we need it**:
We missed a few conversion funcs for List types in the past, this PR adds them.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/retest
flake

**Comment by fabriziopandini** [comment]
Thanks for cross checking this!
/lgtm

**Comment by fabriziopandini** [comment]
@sbueringer should we do the same for extensions types (MachinePools, CRS etc)

**Pull request merged**
