### PR TITLE
🌱 Added test for state_test.go

### PR DESCRIPTION
**Pull request by razashahid107**
**What this PR does / why we need it**:
This PR adds tests for the new ClusterClass MachinePool implementation for the internal/controllers/topology/cluster/scope/state_test.go
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes part of #5991

/area testing

### CODE REVIEW

**Comment by razashahid107** [comment]
@willie-yao I'd really appreciate if you review the PR

**Comment by willie-yao** [comment]
@razashahid107 Will take a look asap. Thanks for your PR!

**Review by willie-yao — APPROVED** [review]
Wow awesome work @razashahid107! This looks great to me 🚀 
/lgtm

**Comment by willie-yao** [comment]
@razashahid107 Make sure to add the 🌱 emoji in the PR title

**Comment by willie-yao** [comment]
Hmm looks like the unit test job didn't run before, will remove the lgtm until those are fixed
/lgtm cancel

**Comment by sbueringer** [comment]
/close

See above

**Pull request closed without merging**
