### PR TITLE
🌱 [WIP] [DNR] Reproduce clusterctl upgrade e2e test flake

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Currently contains:
* Improve KCP logging
* Improve e2e test assertion
* Increase timeout for which Machines have to remain stable

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @furkatgofurov7

I looked into the test artifacts of a failed test. It looks like KCP rolls out a new Machine for some reason after the upgrade to main. I improved the logging in KCP and in the e2e test. That should give us more data as soon as we hit the flake again.

**Comment by furkatgofurov7** [comment]
> cc @furkatgofurov7
> 
> I looked into the test artifacts of a failed test. It looks like KCP rolls out a new Machine for some reason after the upgrade to main. I improved the logging in KCP and in the e2e test. That should give us more data as soon as we hit the flake again

Hey @sbueringer thanks a lot, I was testing just the timeout increase in https://github.com/kubernetes-sigs/cluster-api/pull/8119 and it seems to be passing in a row. But I do agree with the ^, it is most likely a rollout issue rather than a timeout.

**Comment by sbueringer** [comment]
Wrong test case failed
/test pull-cluster-api-e2e-full-main

**Comment by furkatgofurov7** [comment]
okay, so we detected a rollout as per logs:
```
 INFO: Rollout detected
  INFO: Detected new machines
  INFO: New machine clusterctl-upgrade/clusterctl-upgrade-61xx5y-control-plane-4kvpv:
  Object:
    apiVersion: cluster.x-k8s.io/v1beta1
    kind: Machine
    metadata:
      annotations:
        controlplane.cluster.x-k8s.io/kubeadm-cluster-configuration: '{"etcd":{},"networking":{},"apiServer":{"certSANs":["localhost","127.0.0.1","0.0.0.0","host.docker.internal"]},"controllerManager":{"extraArgs":{"enable-hostpath-provisioner":"true"}},"scheduler":{},"dns":{}}'
      creationTimestamp: "2023-02-16T11:12:10Z"
      finalizers:
      - machine.cluster.x-k8s.io
      generation: 2
      labels:
        cluster.x-k8s.io/cluster-name: clusterctl-upgrade-61xx5y
        cluster.x-k8s.io/control-plane: ""
        cluster.x-k8s.io/control-plane-name: clusterctl-upgrade-61xx5y-control-plane
      managedFields:
      - apiVersion: cluster.x-k8s.io/v1beta1
        fieldsType: FieldsV1
        fieldsV1:
          f:metadata:
            f:annotations:
              .: {}
              f:controlplane.cluster.x-k8s.io/kubeadm-cluster-configuration: {}
            f:finalizers:
              .: {}
              v:"machine.cluster.x-k8s.io": {}
            f:labels:
              .: {}
              f:cluster.x-k8s.io/cluster-name: {}
              f:cluster.x-k8s.io/control-plane: {}
              f:cluster.x-k8s.io/control-plane-name: {}
            f:ownerReferences:
              .: {}
              k:{"uid":"91a4ee37-bdcb-4455-9350-2058b1728ed3"}:
                .: {}
                f:apiVersion: {}
                f:blockOwnerDeletion: {}
                f:controller: {}
                f:kind: {}
                f:name: {}
                f:uid: {}
          f:spec:
            .: {}
            f:bootstrap:
              .: {}
              f:configRef: {}
              f:dataSecretName: {}
            f:clusterName: {}
            f:infrastructureRef: {}
            f:version: {}
          f:status:
            .: {}
            f:bootstrapReady: {}
            f:conditions: {}
            f:lastUpdated: {}
            f:observedGeneration: {}
            f:phase: {}
        manager: manager
        operation: Update
        time: "2023-02-16T11:12:10Z"
      name: clusterctl-upgrade-61xx5y-control-plane-4kvpv
      namespace: clusterctl-upgrade
      ownerReferences:
      - apiVersion: controlplane.cluster.x-k8s.io/v1beta1
        blockOwnerDeletion: true
        controller: true
        kind: KubeadmControlPlane
        name: clusterctl-upgrade-61xx5y-control-plane
        uid: 91a4ee37-bdcb-4455-9350-2058b1728ed3
      resourceVersion: "3392"
      uid: b4c3d76d-fd74-4306-a470-99c3cee7938b
    spec:
      bootstrap:
        configRef:
          apiVersion: bootstrap.cluster.x-k8s.io/v1beta1
          kind: KubeadmConfig
          name: clusterctl-upgrade-61xx5y-control-plane-bkrkw
          namespace: clusterctl-upgrade
          uid: 34323a9d-c8f4-428a-b76c-c0440f0f5603
        dataSecretName: clusterctl-upgrade-61xx5y-control-plane-bkrkw
      clusterName: clusterctl-upgrade-61xx5y
      infrastructureRef:
        apiVersion: infrastructure.cluster.x-k8s.io/v1beta1
        kind: DockerMachine
        name: clusterctl-upgrade-61xx5y-control-plane-jxw2w
        namespace: clusterctl-upgrade
        uid: 393302d9-af38-4005-9612-3d721c1f0671
      nodeDeletionTimeout: 10s
      version: v1.26.0
    status:
      bootstrapReady: true
      conditions:
      - lastTransitionTime: "2023-02-16T11:12:16Z"
        message: 1 of 2 completed
        reason: Bootstrapping
        severity: Info
        status: "False"
        type: Ready
      - lastTransitionTime: "2023-02-16T11:12:10Z"
        status: "True"
        type: BootstrapReady
      - lastTransitionTime: "2023-02-16T11:12:16Z"
        message: 1 of 2 completed
        reason: Bootstrapping
        severity: Info
        status: "False"
        type: InfrastructureReady
      - lastTransitionTime: "2023-02-16T11:12:10Z"
        reason: WaitingForNodeRef
        severity: Info
        status: "False"
        type: NodeHealthy
      lastUpdated: "2023-02-16T11:12:10Z"
      observedGeneration: 2
      phase: Provisioning
```

**Comment by sbueringer** [comment]
The diff which leads to a rollout is detected here: https://github.com/kubernetes-sigs/cluster-api/blob/eca3d1706910494992a8c1bcb652632a38c7357f/controlplane/kubeadm/internal/filters.go#L241

Just impossible to tell from the YAML why reflect.DeepEqual detects a difference

**Comment by sbueringer** [comment]
@furkatgofurov7 I found the issue, it's a fun one...

Context:
* We introduced a new ImagePullPolicy field in KubeadmConfigSpec.InitConfiguration.NodeRegistration and KubeadmConfigSpec.JoinConfiguration.NodeRegistration
* The ImagePullPolicy field has a default value which is applied via OpenAPI
* This happens as soon as there is any kind of update on KCP the existing KubeadmConfig
* When KCP checks for rollouts it compares the KubeadmConfigSpec in KCP with the existing KubeadmConfig

Example error case:
* We install Cluster API v0.3
* We create the cluster including KCP
* Cluster API is upgraded to main
* ImagePullPolicy is defaulted in the KubeadmConfig of the Machine. It is not defaulted in KCP 
* KCP controller reconcile detects a diff (`InitConfiguration.NodeRegistration.ImagePullPolicy: IfNotPresent != `) and triggers a rollout

The solution is essentially to set the default value in a way that it doesn't make a difference when we calculate if we need a rollout or not

**Comment by sbueringer** [comment]
@killianmuldoon ^^ that's a interesting reason why we can't do all defaulting via the OpenAPI schema :joy:

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-main
/test pull-cluster-api-e2e-full-main

Found another issue, this time ImagePullPolicy defaulting triggers a rollout by the Cluster topology reconciler (ImagePullPolicy is not defaulted for the existing KubeadmConfigTemplate, but for the new/desired one => diff => rollout)

**Comment by sbueringer** [comment]
Other flake
/test pull-cluster-api-e2e-full-main

**Comment by sbueringer** [comment]
Other flake
/test pull-cluster-api-e2e-full-main

**Comment by sbueringer** [comment]
/close

CI should be stable again

**Pull request closed without merging**
