### PR TITLE
Always pull distroless/static:latest before building

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR makes sure to always pull the latest version of distroless/static before building a new image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Related to #999

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ncdc** [comment]
Or do `docker build --pull ...`?

**Comment by detiber** [comment]
lgtm

/assign @justinsb 

@justinsb It looks like we might need a replacement build for 0.1.2, the current build seems to have used an older version of `gcr.io/distroless/static` that was missing the `nobody` user.

**Comment by vincepri** [comment]
@detiber Needs another lgtm, used @ncdc's wise suggestion

**Comment by detiber** [comment]
/lgtm

@vincepri this will actually need to be backported to the `release-0.1` branch with some changes, since the `release-0.1` branch does not have the multi-arch support.

**Pull request merged**
