### PR TITLE
🌱Changelog entry to include cert-manager to v1.14.2

### PR DESCRIPTION
**Pull request by troy0820**
**What this PR does / why we need it**:
- [x] Updates the changelog to include cert-manager to v1.14.2 for v1.6.2 and v1.5.6

/area release

### CODE REVIEW

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by chrischdi** [comment]
/approve

I'll also edit the GH release notes.

**Review by chrischdi — COMMENTED** [review]
/hold

**Comment by chrischdi** [comment]
One nit.

Already updated the release notes.

**Pull request merged**
