### PR TITLE
🐛 Fix Canonical import paths err

### PR DESCRIPTION
**Pull request by chymy**
**What this PR does / why we need it**:
Canonical import paths err in  `bootstrap/kubeadm/types/v1beta2/doc.go`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
