### PR TITLE
[release-1.2] 🌱 CAPD: set privileged PSA policy

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Manual cherry-pick of the CAPD change in #7446

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @killianmuldoon

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
