### PR TITLE
🌱renamed machinehealthcheck_status_matcher to test file

### LINKED ISSUE #3843: MachineHealthCheck Status Matcher should be in a test file
**What steps did you take and what happened:**
This is not a bug TBH but rather a code inconsistency.

The file https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machinehealthcheck_status_matcher.go
**should be a test file** `https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/machinehealthcheck_status_matcher_test.go`

**What did you expect to happen:**
All the tests should still pass.

**Environment:**

- Cluster-api version: 28c941aeb7912411bcb195af47c99bc936f8fe0a

/kind bug
/area testing
/kind cleanup

### PR DESCRIPTION
**Pull request by arghya88**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3843

### CODE REVIEW

**Comment by arghya88** [comment]
Tracker for API diff

```
Activated service account credentials for: [pr-kubekins@kubernetes-jenkins-pull.iam.gserviceaccount.com]
+ ./scripts/ci-apidiff.sh
cd hack/tools && go build -tags=tools -o bin/go-apidiff github.com/joelanford/go-apidiff
go: downloading github.com/joelanford/go-apidiff v0.0.0-20191206194835-106bcff5f060
go: downloading github.com/spf13/cobra v1.0.0
go: downloading golang.org/x/exp v0.0.0-20191002040644-a1355ae1e2c3
go: downloading golang.org/x/tools v0.0.0-20200616195046-dc31b401abb5
go: downloading gopkg.in/src-d/go-git.v4 v4.13.1
go: downloading github.com/spf13/pflag v1.0.5
go: downloading golang.org/x/crypto v0.0.0-20200622213623-75b288015ac9
go: downloading gopkg.in/src-d/go-billy.v4 v4.3.2
go: downloading github.com/sergi/go-diff v1.1.0
go: downloading github.com/kevinburke/ssh_config v0.0.0-20190725054713-01f96b0aa0cd
go: downloading github.com/xanzy/ssh-agent v0.2.1
go: downloading github.com/mitchellh/go-homedir v1.1.0
go: downloading golang.org/x/net v0.0.0-20200707034311-ab3426394381
go: downloading github.com/emirpasic/gods v1.12.0
go: downloading github.com/jbenet/go-context v0.0.0-20150711004518-d14ea06fba99
go: downloading golang.org/x/sys v0.0.0-20200323222414-85ca7c5b95cd
go: downloading github.com/src-d/gcfg v1.4.0
go: downloading gopkg.in/warnings.v0 v0.1.2
go: downloading golang.org/x/xerrors v0.0.0-20191204190536-9bdfabe68543
go: downloading golang.org/x/mod v0.3.0
*** Running go-apidiff ***

sigs.k8s.io/cluster-api/controllers
  Incompatible changes:
  - MatchMachineHealthCheckStatus: removed
+ EXIT_VALUE=1
+ set +o xtrace
```

**Review by vincepri — APPROVED** [review]
/approve

**Comment by arghya88** [comment]
@fabriziopandini rebased cause of conflict. PTAL again.

**Pull request merged**
