### PR TITLE
:seedling: Move experimental addon controllers to internal

### PR DESCRIPTION
**Pull request by vibhorrawat**
**What this PR does / why we need it**:
Move experimental addon controllers to internal and added a shim (alias.go) for exposing Reconcilers

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*: 
Ref #5455

### CODE REVIEW

**Comment by vibhorrawat** [comment]
Two failures- 
1- `pull-cluster-api-apidiff-main` Failed (Required = False)
Looking at the build logs and error suggests Incompatible changes-
```
*** Running go-apidiff ***
sigs.k8s.io/cluster-api/exp/addons/controllers/predicates
  Incompatible changes:
  - ResourceCreate: removed
sigs.k8s.io/cluster-api/exp/addons/controllers
  Incompatible changes:
  - (*ClusterResourceSetBindingReconciler).Reconcile: removed
  - (*ClusterResourceSetReconciler).ApplyClusterResourceSet: removed
  - (*ClusterResourceSetReconciler).Reconcile: removed
  - ErrSecretTypeNotSupported: removed
```
2- `pull-cluster-api-verify-main` Failed (Required = True)
Build logs suggest issue during `make` execution
```
 - apiGroups:
   - apiextensions.k8s.io
   resources:
@@ -229,15 +208,6 @@ rules:
   - patch
   - update
   - watch
-- apiGroups:
-  - ""
-  resources:
-  - configmaps
-  verbs:
-  - get
-  - list
-  - patch
-  - watch
 - apiGroups:
   - ""
   resources:
generated files are out of date, run make generate
make[1]: *** [Makefile:691: verify-gen] Error 1
make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api'
make: *** [Makefile:674: verify] Error 2
```
Any pointers to fix these?

**Comment by fabriziopandini** [comment]
1. don't worry about this, it is a non blocking check that reports changes in CAPI public APIs, and in case of this PR, they are expected given that we are moving stuff to internal
2. this should not happen. I suggest to rebase on top of main to get the latest changes

**Review by fabriziopandini — COMMENTED** [review]
@vibhorrawat thanks for you fist contribution to Cluster API! Welcome to the team 🥳 
changes lgtm pending green CI signal (verify only)

**Comment by sbueringer** [comment]
Same from my side. Thank you very much!

You have to add the following line:
```bash
		paths=./$(EXP_DIR)/addons/internal/... \
```
Below ~l.371
```bash
		paths=./$(EXP_DIR)/addons/controllers/... \
```

You can directly squash the change into your current commit.

**Comment by vibhorrawat** [comment]
@fabriziopandini @sbueringer Thank you so much for the specific details that helped to fix the test failures. As of now, all the _Required_ checks are passing. Kindly review and do the needful.

Looking forward for more of these to learn and familiarize myself with `cluster-api` 🎉

**Comment by fabriziopandini** [comment]
@vibhorrawat could you kindly fix one things I forgot in the previous pass 😅 

You should add this PR into [API change](https://cluster-api.sigs.k8s.io/developer/providers/v1.0-to-v1.1.html#api-change) documentation for provider implementers

**Comment by vibhorrawat** [comment]
> You should add this PR into [API change](https://cluster-api.sigs.k8s.io/developer/providers/v1.0-to-v1.1.html#api-change) documentation for provider implementers

Done. Added the PR to API Change.
Kindly review. 

@sbueringer your `lgtm` has been removed. Please re-review. 😄

**Comment by fabriziopandini** [comment]
/lgtm
/approve
yay!

**Comment by fabriziopandini** [comment]
:-( rebase first

**Comment by vibhorrawat** [comment]
@fabriziopandini The conflicts are resolved now. Could you please re-review this one. @sbueringer Sorry for being such a pain, had to resolve the branch conflict. Kindly re-review.

**Comment by sbueringer** [comment]
> @fabriziopandini The conflicts are resolved now. Could you please re-review this one. @sbueringer Sorry for being such a pain, had to resolve the branch conflict. Kindly re-review.

No worries :)

/lgtm

**Pull request merged**
