### PR TITLE
Pretty diffs in clusterctl testing

### LINKED ISSUE #255: Enable diffing of large strings in unit tests with reasonable output
Right now, when diffing two large strings that don't match, most unit tests will just output both strings. We should bring in a diff library that intelligently displays what is different.

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
Clusterctl integration tests now print a human readable output. This change uses [go-diff](https://github.com/sergi/go-diff) which is based on Google's [diff-match-patch](https://github.com/google/diff-match-patch)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #255

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by roberthbailey** [comment]
@spew - this one is for you! ;)

**Comment by roberthbailey** [comment]
It looks like a bunch of this PR is a duplicate of https://github.com/kubernetes-sigs/cluster-api/pull/672. Can you rebase now that that one merged to make this diff smaller?

**Comment by vincepri** [comment]
@roberthbailey All done!

**Pull request merged**
