### PR TITLE
🐛 Fix a bug that completion suggestions for --namespace are not updated

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**:

If `--kubeconfig-context` is specified, completion suggestions for`--namespace` needs to provide namespaces of the cluster specified with`--kubeconfig-context`.

However, it currently uses the current context even if`--kubeconfig-context` is specified.

**Before**

```shell
$ kind create cluster --name test
$ kubectl create ns kind-test --context kind-test
namespace/kind-test created
$ kind create cluster

# complete namespaces of the cluster of current context
$ clusterctl get kubeconfig --namespace <tab>
default             kube-node-lease     kube-public         kube-system         local-path-storage

# complete namespaces of the cluster of current context even if --kubeconfig-context is specified
$ clusterctl get kubeconfig --kubeconfig-context kind-test --namespace <tab>
default             kube-node-lease     kube-public         kube-system         local-path-storage
```

**After**

```shell
# complete namespaces of the cluster of current context
$ clusterctl get kubeconfig --namespace <tab>
default             kube-node-lease     kube-public         kube-system         local-path-storage

# complete namespaces of the cluster of context specified with --kubeconfig-context
$ clusterctl get kubeconfig --kubeconfig-context kind-test --namespace <tab>
default             kind-test           kube-node-lease     kube-public         kube-system         local-path-storage
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

ref/ https://github.com/kubernetes-sigs/cluster-api/pull/5094

### CODE REVIEW

**Comment by superbrothers** [comment]
I found a problem shortly after merging #5094. sorry.

**Comment by sbueringer** [comment]
Q: Should we cherry-pick this onto v1alpha4?

**Comment by vincepri** [comment]
@sbueringer Until we merge the first breaking change, we can fast forward the branch

**Pull request merged**
