### PR TITLE
[release-1.3] 🐛 test/e2e: use topology cluster-template for clusterctl upgrade mgmt cluster

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Cherry-pick of #8311

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
Thanks for the work on getting CI stable
/lgtm
/approve

**Comment by sbueringer** [comment]
@furkatgofurov7 @killianmuldoon @ykakarap @fabriziopandini 

This broke e2e-mink8s on release-1.3 as it has ClusterTopology disabled.

I would propose to use Kubernetes 1.22 for the e2e-mink8s test so we can enable ClusterTopology: https://github.com/kubernetes/test-infra/pull/29094/files

I think this is simpler then trying to do bigger changes on the release-1.3 branch to use the right cgroupDriver without ClusterClass.

I think as we already have a few 1.3 patch releases out we can remain confident regardless that 1.3 works with Kubernetes 1.20 management clusters

**Comment by sbueringer** [comment]
Btw for this case https://github.com/kubernetes-sigs/cluster-api/issues/8224 would have helped. But as of today it's not possible to run e2e-mink8s on PRs.

**Pull request merged**
