### PR TITLE
Enable setting profile for minikube bootstrap cluster.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/844

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Enable setting profile for minikube bootstrap cluster.
```

### CODE REVIEW

**Comment by detiber** [comment]
/lgtm

Does this also solve the issue with deleting a pre-existing minikube cluster?

**Comment by gyliu513** [comment]
> Does this also solve the issue with deleting a pre-existing minikube cluster?

@detiber Yes :-)

**Pull request merged**
