### PR TITLE
🌱 test: Dump resources before deleting extensionconfig

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

This PR ensures that resources are dumped before deleting the extensionconfig.

Deleting the extensionconfig pollutes the state of e.g. the ClusterClass and would make the dump lead to wrong conclusions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area e2e-testing

### CODE REVIEW

**Comment by chrischdi** [comment]
/retest

machinepool flake

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
