### PR TITLE
Add Dockerfile for plantuml image used to generate proposal diagrams

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What this PR does / why we need it**:
Provides Dockerfile for plantuml image

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
#1070 

This is just the Dockerfile. I can work on the publishing in a separate PR.

### CODE REVIEW

**Comment by vincepri** [comment]
Should we add some documentation on how to use this tool?

**Comment by dlipovetsky** [comment]
@vincepri Sure. I can add that. I can add README.md here for now. Also, I want someone to bikeshed on where the Dockerfile should go :smile:

**Comment by dlipovetsky** [comment]
@vincepri Added a README.

**Pull request merged**
