### PR TITLE
🌱 Change default log level to 2

### LINKED ISSUE #9092: Use --v=2 as default log-level
I would propose to use log level 2 as a default in core CAPI.

This helps to align to our own and upstream conventions:

Upstream:
> klog.V(2).InfoS - Useful steady state information about the service and important log messages that may correlate to significant changes in the system. **This is the recommended default log level for most systems**
> https://github.com/kubernetes/community/blob/master/contributors/devel/sig-instrumentation/logging.md

Cluster API:
> Ideally, in a future release of Cluster API we will switch to use 2 as a default verbosity (currently it is 0) for all the Cluster API controllers as recommended by the Kubernetes guidelines.
>  https://cluster-api.sigs.k8s.io/developer/logging.html#log-levels

I think it would be very helpful so we don't have a tendency to add logs at log level 0 just to make them visible per default just because our default log level is 0 (instead of 2)

One example: In our e2e test jobs we are using the default log level (as we should). But to be able to debug any failures there the logs have to be on log level 0 otherwise we don't see them.

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9092

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/area logging

**Pull request merged**
