### PR TITLE
📖 Toleration of v1.24 control plane taints

### LINKED ISSUE #6172: migration-guide: document toleration of control plane taints in manager.yaml
Let's document in our migration guide (https://cluster-api.sigs.k8s.io/developer/providers/v1.1-to-v1.2.html) that CAPI providers should tolerate both control plane taints (in manager.yaml). This makes sure they can be also run on v1.24 control plane nodes.

Let's also add a note that if the label is used in the manager.yaml that should be adjusted as well. (e.g. like here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/main/config/manager/manager.yaml#L52)

In core CAPI this has been added in: https://github.com/kubernetes-sigs/cluster-api/pull/5919/files

/kind feature
/area documentation
/good-first-issue

### PR DESCRIPTION
**Pull request by ditsuke**
**What this PR does / why we need it**:
Documents toleration of control plane taints for compatibility with Kubernetes 1.24 control plane nodes. Also documents the need to adjust manager.yaml so providers can work with the new control-plane label introduced by v1.24.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6172

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!

/lgtm

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
@ditsuke thanks for this PR!
/lgtm
/approve

**Pull request merged**
