### PR TITLE
:seedling: Update cert-manager to v1.11.0

### PR DESCRIPTION
**Pull request by bryan-cox**
Signed-off-by: brcox <brcox@redhat.com>

**What this PR does / why we need it**:
Resolves https://github.com/kubernetes-sigs/cluster-api/issues/7892

**Which issue(s) this PR fixes**:
Resolves https://github.com/kubernetes-sigs/cluster-api/issues/7892

### CODE REVIEW

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/approve

@fabriziopandini Should we pro-actively backport this into release-1.3 and release-1.2 like we did in the past to keep using a supported cert-manager version in those branches?

**Comment by fabriziopandini** [comment]
> @fabriziopandini Should we pro-actively backport this into release-1.3 and release-1.2 like we did in the past to keep using a supported cert-manager version in those branches?

yes, cert manager bump is one of the types of backports we try to have on all branches

/cherry-pick release-1.3

**Pull request merged**
