### PR TITLE
🌱 use golangci lint v1.38.0

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR sets the version used by `make lint` to be consistent with the version we are running in CI https://github.com/kubernetes-sigs/cluster-api/blob/cc1298536490f67b8a48dc8876dea22dbb0eb736/.github/workflows/golangci-lint.yml#L23

/assign @sbueringer 
/assign @vincepri

### CODE REVIEW

**Comment by JoelSpeed** [comment]
Tests are failing (in verify) due to what I believe is an updated version of the CRD generator, have we updated deps somewhere recently and missed regenerating all of the CRD manifests?

Otherwise, changes in this PR seem fine

**Comment by sbueringer** [comment]
Also lgtm for the change. Not sure what's going on with the CRD gen.

**Comment by vincepri** [comment]
@fabriziopandini Can you rebase and regen the files?

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
