### PR TITLE
:seedling: Update cert-manager to v1.11.2

### PR DESCRIPTION
**Pull request by killianmuldoon**
Update cert manager version to v1.11.2

Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.11.2
/area dependency

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
There's some CVEs reported in the release notes - though they don't impact cert manager directly.

Maybe we can cherry-pick out of caution? We already cherry-picked v1.11.1 back to the 1.4 and 1.3 branches.

**Comment by sbueringer** [comment]
/lgtm
/approve

Yup why not

**Pull request merged**
