### PR TITLE
🚀 Release v1.6.8

### PR DESCRIPTION
**Pull request by rajankumary2k**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
LGTM

**Comment by sbueringer** [comment]
/hold

Please rebase this PR to only contain one clean commit

**Comment by sbueringer** [comment]
v1.6.8.md itself looks fine to me

**Review by chandankumar4 — APPROVED** [review]
lgtm

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
