### PR TITLE
📖 Rename Metal3.io provider from Baremetal to Metal3

### LINKED ISSUE #2447: Discussion: Should we rename references to metal3.io from BareMetal Provider to metal3.io instead?
**User Story**

All references in documentation (and clusterctl) reference the metal3.io provider as the Baremetal Provider, which is a bit misleading. There could be multiple baremetal providers in the future, such as one that could leverage Packet's [tinkerbell project](https://tinkerbell.org/).

### PR DESCRIPTION
**Pull request by maelk**
**What this PR does / why we need it**:
This PR renames the Metal3.io provider from Baremetal to Metal3 in clusterctl and the documentation

**Which issue(s) this PR fixes** :
Fixes #2447

### CODE REVIEW

**Comment by maelk** [comment]
/hold
to give some time for the discussion
/assign @detiber 
/cc @vincepri

**Comment by vincepri** [comment]
is it ok to unhold or do we want to wait until next week?

**Comment by maelk** [comment]
I would rather put a lazy consensu deadline, to give the metal3.io community time to discuss the extent of the renaming internally. What about next wednesday ?

**Comment by ncdc** [comment]
This is async from the 0.3 work, so moving to Next & we can merge after/assuming lazy consensus.

/milestone Next

**Comment by Arvinderpal** [comment]
Just a general comment: `cluster-api-provider-baremetal` by itself is insufficient for creating metal3/baremetal clusters/machines.  This is in contrast (I believe) to the other providers which for the most part involve defining env variables and are good to go. 
Since additional providers can be easily added in the clusterctl config file, would it make more sense to leave this out of the defaults?

**Comment by maelk** [comment]
@detiber  I had to rebase, could you please lgtm again ?

**Pull request merged**
