### PR TITLE
Rename controllers test files

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR is a follow-up to #958 where these files weren't renamed to avoid confusion during the review process.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by gyliu513** [comment]
@vincepri  Just a question here: Do we really need to rename? As the file was already under the folder of `machineset`, so seems no need to add `machineset` again for file names?

**Comment by vincepri** [comment]
The renaming mostly to keep things in sync between the file that's being tested and the tests. The file has been renamed mostly because the logs were showing `controller.go` everywhere across machine/cluster/machineset/machinedeployment which made things a little confusing. Does that help clarify?

**Comment by ncdc** [comment]
Disambiguating the `controller.go` log lines is a huge win.

**Comment by gyliu513** [comment]
> The renaming mostly to keep things in sync between the file that's being tested and the tests. The file has been renamed mostly because the logs were showing controller.go everywhere across machine/cluster/machineset/machinedeployment which made things a little confusing. Does that help clarify?

I see, thanks @vincepri .

**Pull request merged**
