### PR TITLE
🌱 bump clusterctl upgrade test to CAPI v0.3.23

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Let's use the latest CAPI v0.3 release (released yesterday)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
/hold cancel

e2e-full-main (including clusterctl upgrade) was green

**Comment by sbueringer** [comment]
Unrelated flake
/retest

**Pull request merged**
