### PR TITLE
📖 Add page for the bootstrap kubeadm provider

### LINKED ISSUE #4151: Import CABPK documentation from the legacy repo
Today I stumbled into https://github.com/kubernetes-sigs/cluster-api-bootstrap-provider-kubeadm#bootstrap-orchestration, which IMO contains valuable insights on how CABPK works.

If there is consensus I would like to import such informations in the CAPI repo, TBD if as a readme in the bootstrap/kubeadm folder of if somewhere into the book (or both using include in the book)

/kind documentation
/milestone v0.4.0

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

Add a REDME to the bootstrap/kubeadm folder. The readme covers topics likes how CABPK works, bootstrap orchestration, certificate management, etc.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4151

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
@ykakarap thanks for this PR!
In order make this more visible I suggest to add a Kubeadm bootstrap page under tasks

**Comment by ykakarap** [comment]
> In order make this more visible I suggest to add a Kubeadm bootstrap page under tasks

Looks like there [is a page](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/tasks/kubeadm-bootstrap.md) with similar content (some of the information seems outdated) and some [additional information](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/tasks/kubeadm-bootstrap.md#additional-features). 
Shall I add the additional content into this yaml and make this readme an import in the book?

**Comment by fabriziopandini** [comment]
> Looks like there is a page with similar content (some of the information seems outdated) and some additional information.
Shall I add the additional content into this yaml and make this readme an import in the book?

good catch!
Let's improve `docs/book/src/tasks/kubeadm-bootstrap.md` with the comment discussed above and make sure the page shows up in the book index

**Comment by ykakarap** [comment]
we do not need the readme in `bootstrap/kubeadm/` anymore, correct?

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
