### PR TITLE
Remove control plane version master set label on node in template

### PR DESCRIPTION
**Pull request by k4leung4**
**What this PR does / why we need it**:
Remove control plane version master set label on node in template

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by jessicaochen** [comment]
Seems reasonable, have you validated e2e (ie. create cluster, mess with a machine, delete cluster) with vsphere-deployer?

**Comment by k4leung4** [comment]
i was able to create a new cluster and delete machine with this change.

**Pull request merged**
