### PR TITLE
🌱 in-memory provider: add apiserver & etcd metrics

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
Lgtm, but let's wait for https://github.com/kubernetes-sigs/cluster-api/pull/8938 to merge so we can add metrics for MoveLeader and MemberRemove

/hold

**Comment by sbueringer** [comment]
@fabriziopandini done, ptal :)

**Pull request merged**
