### PR TITLE
🌱 Add conformance e2e tests

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10062

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

for corresponding test-infra PR

**Comment by fabriziopandini** [comment]
@sbueringer should we also update https://cluster-api.sigs.k8s.io/reference/jobs as part of this PR?

**Comment by fabriziopandini** [comment]
/lgtm
/approve

/hold 
for https://github.com/kubernetes-sigs/cluster-api/pull/10060#issuecomment-1912252309

**Comment by sbueringer** [comment]
I'll do a follow-up on that.

WDYT would it make sense to just link to our templates and prowjob gen instead?

It's a lot of toil to keep the jobs.md up-to-date and I have no idea who is even reading it

**Pull request merged**
