### PR TITLE
:warning: Clusterctlv2 add interfaces for the low-level Repository library

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR adds a clusterctl interfaces low-level api for managing Repository config objects, and more specifically the interfaces for managing two types of YAML files:
- YAML files defining the provider components (CRD, Controller, RBAC etc.)
- YAML files defining the cluster templates (Cluster, Machines)

By adding those interfaces, with this PR, then it will be possible to parallelize the work of adding the concrete implementation of each interface.

**Which issue(s) this PR fixes**
Rif #1729

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@ncdc @vincepri @detiber this is ready for review now

**Comment by fabriziopandini** [comment]
@chuckha many thanks for the detailed feedback. the articles you linked are really interesting.

I see both pros and cons approach you are proposing and in the current approach, that mimics what is implemented in the Kubernetes API package; nevertheless, I will be happy to address if your concerns - including also re-working of the code already merged -  if the consensus goes in that direction.

Said that my major concern is to keep the clusterctl work going, so, I this will be ok for you/for the team, I would prefer to experiment on an alternative approach for the API surface in a separated PR, and use the current approach for unblocking works on the clusterctl federated repository

@ncdc @vincepri @detiber opinions?

**Comment by chuckha** [comment]
that's fine. all of kubernetes does this anyway and it's not a huge deal, it's just annoying to work with from time to time.

**Comment by vincepri** [comment]
@chuckha Are you ok to approve this PR as-is given the comments above?

We merged some other PRs that follow this pattern (or anti-pattern as you mentioned 😄). Given that the tight timeline, and that the code can always be improved in future iterations, I'd like to get these merged asap

**Comment by chuckha** [comment]
yep, it's fine to merge

**Pull request merged**
