### PR TITLE
🐛 Bump cloud init build to 45m

### LINKED ISSUE #1998: Push job is broken
**What steps did you take and what happened:**
https://prow.k8s.io/?repo=kubernetes-sigs%2Fcluster-api

This is blocking me moving forward with e2es since the additional managers are not getting images pushed.

/kind bug
/assign

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:

30m was not enough

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1998 

/assign @ncdc

### CODE REVIEW

**Comment by vincepri** [comment]
Any reason it takes so long to build these images?

**Comment by ncdc** [comment]
We're building all go packages for 3 binaries * amd64, arm, arm64, ppc, s390x. That takes a while. We may be able to add lines to the Dockerfile to do a `go build -i` or `go install` before we build the actual binary, which would presumably cut down the time by approximately 1/3 (but probably a bit less).

**Comment by vincepri** [comment]
Let's bump the machineType in the options https://cloud.google.com/cloud-build/docs/build-config and see how it goes?

**Comment by ncdc** [comment]
We can look into that but I do think that trying to cache the bulk of the packages in a separate `RUN` command before we build the actual binary would really help too.

**Pull request merged**
