### PR TITLE
✨  Adds moby client

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
This PR is the start of removing "docker exec" and associated work arounds that CAPD has had to do and makes working with docker a little obtuse. This will simultaneously clean up the exec calls throughout CAPD as well as allow for better separation of concerns.

The types in `container_client.go` are the types this application will use, applications such as podman or moby will have to convert their types into our types. This allows the caller (something in CAPD) to define their own interface. You can see a sample commented out interface in `container_client.go`. This is not where the interface will live, but this is what different runtimes will need to implement.

The client is almost entirely tested, but requires docker to be running on the host.

Related to #1751 

/cc @kfox1111 

A lot of the types are copied out of the docker library. I figure if we want to port capd over to other runtimes we'll have to figure out how to reconcile the differences, but this is a good place to start. As we use this it will become clear which fields CAPD cares and does not care about.

### CODE REVIEW

**Comment by vincepri** [comment]
What's the status of this PR? Going to move it out of the milestone for now until we have a clear idea.

/milestone Next

**Comment by chuckha** [comment]
/close

I don't have time for this anymore. If anyone would like to pick it up and has a reason to, please feel free!

**Pull request closed without merging**
