### PR TITLE
✨ Update docs/Makefile

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

I noticed that the docs/Makefile diagrams target uses an old PlantUML container from `k8s.gcr.io`. I took some inspiration from [OpenStack provider](https://github.com/kubernetes-sigs/cluster-api-provider-openstack/blob/main/docs/Makefile) and updated the Makefile in the following way. 
 
* Add a help target.
* Add diagram build container target.
* Update diagram build target to use local image.
* Update Dockerfile usage instructions.

Finally I also regenerated the proposal diagrams since they where generated with an older version of PlantUML.

Makefile help output:
```shell
make 

Usage:
  make <target>

build
  diagrams         Make PlantUML diagrams
  plantuml-builder  Make diagram build container

general
  help             Display this help
```

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
I think we should be careful with the differences between the new and old images - some of them appear to be incorrectly formatted so we might need to update the plantuml files so that the resulting images are closer to the originals.

Would it be possible to do this incrementally? I understand there might be a large amount of work to update the images so the newer version of plantuml produces something close to the original versions. If it's possible we could create an umbrella task to update these images one-by-one (or batch by batch)

**Comment by oscr** [comment]
What would you say about removing the updates to proposals and change the "make diagrams" just builds the CAPI book? The proposals don't need to be updated so we can just let them be. Then in a separate pr we can either update the diagrams target or add a separate target for proposals diagrams together with fixes for them. Sounds ok @killianmuldoon?

**Comment by killianmuldoon** [comment]
Could we maybe add two targets - `make diagrams-book` and `make diagrams-proposals`? We could then aggregate them under `make-diagrams`. I don't think we run this command as part of any wider workflow so it would be fine to exclude the proposals for now.

We would need a solution to the broken proposal images sooner rather than later though as it would impact anyone trying to create new images for a proposal.

**Comment by killianmuldoon** [comment]
I must have missed the updates on https://github.com/kubernetes-sigs/cluster-api/pull/7017 - it looks like there's a few issues there as well. Have you made any progress on figuring out why the layering / opacity is changing? I think that's the fundamental problem, everybody else seemed happy with the colors on that PR 😆

**Comment by killianmuldoon** [comment]
Thanks for making the updates! 

/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
