### PR TITLE
:seedling: Included githubactions in the dependabot config

### PR DESCRIPTION
**Pull request by naveensrinivasan**
**What this PR does / why we need it**:

This should help with keeping the GitHub actions updated on new releases. This will also help with keeping it secure.

Dependabot helps in keeping the supply chain secure https://docs.github.com/en/code-security/dependabot

GitHub actions up to date https://docs.github.com/en/code-security/dependabot/working-with-dependabot/keeping-your-actions-up-to-date-with-dependabot

https://github.com/ossf/scorecard/blob/main/docs/checks.md#dependency-update-tool

Signed-off-by: naveensrinivasan <172697+naveensrinivasan@users.noreply.github.com>

Similar to https://github.com/kubernetes/minikube/pull/13770

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
I know there's some history behind enabling/disabling CAPI in the past as we had some issues with it.
I'll wait for comments from folks familiar with that.

**Comment by naveensrinivasan** [comment]
Thanks, I have enabled dependabot only for GitHub actions.

**Comment by vincepri** [comment]
If this is only for github actions, it should be fine to try it out

**Comment by sbueringer** [comment]
Okay sounds good to me.

/ok-to-test
/lgtm

@killianmuldoon Slightly related. I think we can follow-up with additional config for gomod where we only allow upgrades to the coredns migration lib with `allow` (https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#allow)

**Comment by naveensrinivasan** [comment]
@sbueringer  Is there anything else required to merge this? Thanks

**Review by killianmuldoon — APPROVED** [review]
/lgtm

I think this would be good to implement to see how it works and what config might suit.

**Comment by sbueringer** [comment]
> @sbueringer Is there anything else required to merge this? Thanks

Should be fine from your side. Let's see if @fabriziopandini or @vincepri have further comments and I think otherwise we can merge.

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
