### PR TITLE
🌱 Move ykakarap to emeritus approvers

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

First of all, @ykakarap thank you very much for all the work you did on Cluster API. It was always great working with you!!

This PR moves Yuvaraj to emeritus approver, given that he wasn't actively contributing for a while now and considering that we want to keep our OWNERS files reasonably up-to-date.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
Thanks @ykakarap for the great work in CAPI, I hope we can see you around again sometime in the future!
/lgtm
/approve

**Comment by fabriziopandini** [comment]
Let give folks some time to chime in, otherwise I will approve this PR after office hours

**Comment by sbueringer** [comment]
^^
/hold

**Pull request merged**
