### PR TITLE
🌱 Improve clusterctl client config logic & error message

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Looking at this PR (https://github.com/Homebrew/homebrew-core/pull/180957/files), the new error message is not good:
image

The problem is that on the original PR that changed this in CAPI (https://github.com/kubernetes-sigs/cluster-api/pull/11006/files) the strings.Replace doesn't work because the err from rest.InClusterConfig doesn't contain "invalid configuration".

Let's try to get this into v1.8.1 later this week

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @adilGhaffarDev

**Review by chrischdi — COMMENTED** [review]
/approve

**Comment by chrischdi** [comment]
/area clusterctl

/lgtm

/hold

for your convenience

**Comment by adilGhaffarDev** [comment]
We will have to open PR manually in `Homebrew` for 1.8.1 and change the assert_match string again. I will keep it in mind for next patch release.

**Pull request merged**
