### PR TITLE
📖 add step for indexing the CRDs of the latest release

### LINKED ISSUE #9290: Ensure doc.crds.dev is updated on new release
Part of Improvement tasks for v1.6 release cycle https://github.com/kubernetes-sigs/cluster-api/issues/9104
>  automate updates to specific versions of https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api after release is cut
the link: https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api@latest needs to be called at least once before it's cached as the base page for the repo. The idea is to automate that update - we could initially document checking that page as a task during the release process manually. Automation can also be considered, i.e the same way how it is done in https://github.com/oracle/cluster-api-provider-oci/blob/main/.github/workflows/release.yaml#L28-L31

There is discussion in the umbrella issue regarding whether automation is worth the maintenance effort.  As a first step we will document that this link needs to be called after the release has been cut, and continue discussing tradeoffs for pursuing automation if needed.

- [x] document that the new release tag link needs to be accessed in order to index the updated tag
- [ ] attempt to address the `latest` tag behavior when no tag is provided in the URL params
  - [x] [FR opened](https://github.com/crdsdev/doc/issues/175) here 
  - [ ] open a PR - [WIP](https://github.com/crdsdev/doc/pull/176)

/kind documentation
/area release

### PR DESCRIPTION
**Pull request by cahillsf**
**What this PR does / why we need it**:
Adds a step in the release cycle for ensuring the most recent release version is indexed for cluster API repo in [docs.crds.dev](https://doc.crds.dev/github.com/kubernetes-sigs/cluster-api) 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #9290

/area release
/kind documentation

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

Thanks!

**Review by furkatgofurov7 — COMMENTED** [review]
Thank you very much!

/lgtm

**Comment by furkatgofurov7** [comment]
@cahillsf can you link the issue this PR fixes in the description, unless you want to keep it open?

**Comment by sbueringer** [comment]
> @cahillsf can you link the issue this PR fixes in the description, unless you want to keep it open?

We should always link it, either via "fixes" or "part of" (the latter if we don't want to close the issue)

**Pull request merged**
