### PR TITLE
🌱  modify providerid struct string method to receive value

### LINKED ISSUE #5755: Implement `fmt.Stringer` interface with value receiver
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/5751#discussion_r758661985 

It seems like the String func should always be implemented with a value receiver. That way it works independent of if the type (in this example `TemplateRef`) is a pointer or not. I tested it with ~ `fmt.Sprintf("%s %s", &api.TemplateRef{..}, api.TemplateRef{..}`.

`TemplateRef` has already been fixed in #5751. This issue is about fixing other occurrences of that problem:

* [x] func (p *ProviderID) String() string {
    *  exported type in controllers/noderefutil
* [ ] func (n *Node) String() string {
    *  exported type in test/infrastructure/docker/docker/types
* [ ] func (n *NetworkRanges) String() string {
    *  exported type in api/v1beta1

Can we just change those funcs? I don't see an alternative with deprecations etc..

/kind cleanup
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by DiptoChakrabarty**
🌱 

**What this PR does / why we need it**:
This modifies the String method which implements the Stringer interface to receive value instead of pointers  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5755 (working on)

If this seems correct would like to modify the other ones as well

### CODE REVIEW

**Comment by sbueringer** [comment]
/ok-to-test

Change itself looks good to me. I just can't say if we have a problem with our API stability guarantees (as stated in the issue).

/cc @CecileRobertMichon @enxebre @fabriziopandini  @vincepri

**Comment by enxebre** [comment]
Thanks, TIL. I don't think this is breaking given https://go.dev/doc/effective_go#pointers_vs_values
>The rule about pointers vs. values for receivers is that value methods can be invoked on pointers and values, but pointer methods can only be invoked on pointers.

/lgtm

**Comment by sbueringer** [comment]
There's a parallel discussion in https://github.com/kubernetes-sigs/cluster-api/issues/5755#issuecomment-988962715
Let's see what the outcome of this is before we merge this PR

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
