### PR TITLE
📖 Update versions doc with k8s v1.27 notes

### PR DESCRIPTION
**Pull request by furkatgofurov7**
Signed-off by: Furkat Gofurov (furkat.gofurov@suse.com)

**What this PR does / why we need it**:
Updates versions.md with new k8s version v1.27.0 notes

Part of: https://github.com/kubernetes-sigs/cluster-api/issues/8459

cc @kubernetes-sigs/cluster-api-release-team

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Comment by furkatgofurov7** [comment]
> I am fine either way, probably let's merge it after jobs are 🟢
> 
> >

Okay, so first set of runs seems to be 100% 🟢:

- https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-1.4#capi-e2e-release-1-4-1-26-1-27
- https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api-1.4#capi-e2e-release-1-4-1-27-latest
- https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-26-1-27
- https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-27-latest

**Comment by sbueringer** [comment]
Great!

I think the think I'm mostly looking for is green tests on #8518

**Comment by furkatgofurov7** [comment]
> Great!
> 
> What I'm mostly looking for is green tests on #8518 (as this runs our full e2e test suite against 1.27)

Absolutely, we had already successful run on #8518 but that is a separate topic, and new tests looks very stable (100% green) after 3 runs. @sbueringer I think we are safe to take this PR in?

**Comment by sbueringer** [comment]
Yup feel free to merge

**Comment by furkatgofurov7** [comment]
> We need to put some notes (maybe in umbrella issue) so that we don't forget about back-porting it to next v1.4.x release (probably the one on Tuesday 2nd May 2023) that actually supports v1.27.

Created a [PR](https://github.com/kubernetes-sigs/cluster-api/pull/8539) (on hold) assuming v1.4.2 will support 1.27, we can see later when new 1.4.x is out and assumption made in #8539 makes sense or not.

**Pull request merged**
