### PR TITLE
🌱 go.mod reformat to have only two require blocks

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Follow-up after discussion at https://github.com/kubernetes-sigs/cluster-api/pull/9189#discussion_r1294677973

Note: this does not add, remove or change any dependency. It only reformats the `go.mod` file.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
I guess we'd need to do this periodically if go itself doesn't keep the format consistent. Have we any way to do this or should this change be just a one off?

**Comment by chrischdi** [comment]
> I guess we'd need to do this periodically if go itself doesn't keep the format consistent. Have we any way to do this or should this change be just a one off?

I think it is a one-off for now. As this is only a cosmetic optimisation I think we should not worry about it. 

Except there is a proper linter so we can enforce it. But I don't think its worth investing that time.

**Comment by sbueringer** [comment]
I think it's fine as a one-off for now. Just wanted to have some order given current attention on dependencies

**Pull request merged**
