### PR TITLE
🌱 Build golangci-lint locally

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR switch to building golangci-lint locally, so we can leverage the same mechanism used by other tools and drop the script for downloading the right version.

Note. We are picking the version from .github/workflows/golangci-lint.yml, so we ensure the version used by CI and the version used by make are always in sync.

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
/lgtm

Not sure if we previously had problems with local building. Based on https://github.com/kubernetes-sigs/cluster-api/pull/4700 it sounds like it was mostly about dependencies which is not an issue anymore with the way we build today

**Comment by fabriziopandini** [comment]
We don't have anymore hack/tools/go.mod issues that existed before, it is simpler and it stays in sync we what we use in CI
We should be good

**Pull request merged**
