### PR TITLE
⚠️ Update klog dependency to v2

### LINKED ISSUE #3763: Invalid ProviderID error is malformed
**What steps did you take and what happened:**
Have a provider write a ProviderID that doesn't match the form we describe in https://github.com/kubernetes-sigs/cluster-api/blob/master/controllers/noderefutil/providerid.go

See a confusing error in the logs:
> controller.go:257] controller-runtime/controller "msg"="Reconciler error" "error"="providerID must be of the form \u003ccloudProvider\u003e://\u003coptional\u003e/\u003csegments\u003e/\u003cprovider id\u003e" "controller"="machine" "name"="bmo-md-1-6bf4fd585d-jfwbx" "namespace"="default"

**What did you expect to happen:**
I think we just want it to print out the error string verbatim, I don't know where the formatting strings are coming from.

**Anything else you would like to add:**
I remember fixing this in klog ages ago. Maybe we just need to bump that? https://github.com/kubernetes/klog/issues/139

/kind bug

### PR DESCRIPTION
**Pull request by stmcginnis**
**What this PR does / why we need it**:
This switches klog usage over to klog v2.5.0 to match the current
version being used in k/k.

This should also address some issues we're seeing that have since been
fixed in klog between the quite old v1.0.0 and v2.5.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3763

### CODE REVIEW

**Comment by neolit123** [comment]
cc @enyinna1234

**Comment by neolit123** [comment]
i didn't check the CI errors here, but you are probably going to have to update the go.mod/sum files too.

**Comment by vincepri** [comment]
We should move controller runtime first to klog v2, if we haven't already.

**Comment by detiber** [comment]
> We should move controller runtime first to klog v2, if we haven't already.

I don't think controller-runtime uses klog directly, only `github.com/go-logr/logr` and `zap`.  I'd expect anything using klog would be through transitive dependencies.

**Comment by stmcginnis** [comment]
Thanks @vincepri and @detiber. From my understanding, this should be fine. But I'm still pretty new to the code, so if there is anywhere else I should look to verify things or get other parts updated, just let me know. Happy to take a look!

**Comment by stmcginnis** [comment]
Indeed, it would appear controller-runtime had already switch to klog v2:

https://github.com/kubernetes-sigs/controller-runtime/blob/85527dfb53483d218ce87733abd3093b1c05c618/go.sum#L795

**Comment by stmcginnis** [comment]
/test pull-cluster-api-test-main

Appears to have hit #4184

**Comment by detiber** [comment]
Running `make modules` should clean up the error in the `pull-cluster-api-verify` job

**Comment by stmcginnis** [comment]
Thanks! Looks like that didn't do it though - pretty much had run those manually. Glad to know about it though.

Looks like I may need to run `make generate`? Will see once it finally finishes running.

**Comment by stmcginnis** [comment]
Hah, I take that back. Running `make modules` initially didn't show any local changes for me. But after reverting this apparently very bad `make generate` changes, I ran it again and now it does actually show a change in test/infrastructure/docker/go.sum. :shrug:

**Comment by vincepri** [comment]
/milestone v0.4.0
/retitle ⚠️ Update klog dependency to v2

**Comment by CecileRobertMichon** [comment]
Does this require providers to bump klog version too? If so can we please document it in v1alpha3 --> v1alpha4 [docs](https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md)

**Comment by stmcginnis** [comment]
It's my understanding that it should not have an impact on providers. klog and klogv2 should be able to be used together, it's just the path through the code that consuming code will take to ultimately get to the logging.

**Comment by CecileRobertMichon** [comment]
@vincepri why did you mark the change as breaking?

**Comment by vincepri** [comment]
It'd be great actually if we document that we've switched to v2 (hence my marking this PR as ⚠️). When mixed, klog's flags are not going to work across packages. For example, logtostderr or log to file, and any other flag (even verbosity) would only be respected for the flags that are being registered in the `main.go`, while the rest of the codebase is going to use what's the default.

Hope the above example makes sense, happy to provide more details.

**Comment by stmcginnis** [comment]
Oh, great point @vincepri, I hadn't thought of that.

Where should this be documented? Happy to add some notification about the v2 requirement. I see `docs/developer`, but that currently only has release information.

I will also look at proposing updates to any of the other upstream `cluster-api-*` repos.

**Comment by CecileRobertMichon** [comment]
@stmcginnis https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
