### PR TITLE
📖 fix file name of clusterclass proposal

### PR DESCRIPTION
**Pull request by schrej**
The date at the beginning contains an extra digit, which breaks sorting when adding newer proposals.

Since the PR validation complains that this description is a little short, I'll add this line to hopefully satisfy it :smile:

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
Q: Do we have any links to the proposal that we should fix? (I'm aware we can't fix them all, but maybe let's check with grep.app if there are some best-effort fixes we should make)

**Comment by schrej** [comment]
GitHub Code Search found two more that aren't just forks.

**Comment by killianmuldoon** [comment]
Out of curiosity - how did you find those other links?

**Comment by killianmuldoon** [comment]
Broken links look fine to me -they're just a result of updating the links here.

/lgtm

**Comment by fabriziopandini** [comment]
I think we are referencing this from the Kubernetes blog...

**Comment by schrej** [comment]
The [Introducing ClusterClass and Managed Topologies in Cluster API
](https://v1-22.docs.kubernetes.io/blog/2021/10/08/capi-clusterclass-and-managed-topologies/) blog post doesn't mention it.

**Comment by killianmuldoon** [comment]
But it does link https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-classes.html (which is dead)

**Comment by sbueringer** [comment]
> But it does link https://cluster-api.sigs.k8s.io/tasks/experimental-features/cluster-classes.html (which is dead). I'll add a cluster-class reference page with links to that address in main. I guess we might have to backport to 1.1 to get it in the latest version of the book though, right @sbueringer?

Yes `https://cluster-api.sigs.k8s.io/` is current release-1.1.

**Comment by killianmuldoon** [comment]
I was thinking of moving that index page to the location of the old cluster-classes.md which would minimally fix the issue and only slightly disturb the structure.

**Comment by sbueringer** [comment]
> I was thinking of moving that index page to the location of the old cluster-classes.md which would minimally fix the issue and only slightly disturb the structure.

Sounds good!

**Review by fabriziopandini — COMMENTED** [review]
Given the work for searching for broken links
/lgtm
/approve

**Comment by sbueringer** [comment]
I merged it manually, given that it would have been impossible because of the linkchecker otherwise.

**Pull request merged**
