### PR TITLE
[release-1.6] :seedling: test: add dynamic finalizer assertions for e2e framework

### PR DESCRIPTION
**Pull request by adityabhatia**
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9970

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # https://github.com/kubernetes-sigs/cluster-api/issues/9969

/area testing

### CODE REVIEW

**Comment by adityabhatia** [comment]
**Note**: This PR doesn't contain the Kind conflict addressed [here](https://github.com/kubernetes-sigs/cluster-api/pull/9891/files). IMO it also makes sense to cherry-pick that change, to avoid any namespaced name collisions?
cc: @sbueringer

**Comment by sbueringer** [comment]
/ok-to-test

@adityabhatia Sorry. Just noticed that I also want to cherry-pick https://github.com/kubernetes-sigs/cluster-api/pull/10004.
Can you rebase this PR once #10004 merges please?

**Comment by sbueringer** [comment]
> **Note**: This PR doesn't contain the Kind conflict addressed [here](https://github.com/kubernetes-sigs/cluster-api/pull/9891/files). IMO it also makes sense to cherry-pick that change, to avoid any namespaced name collisions? I can create a 1.6 cherry-pick once this PR is merged, to avoid conflicts. cc: @sbueringer

Agree, thx! I'll cherry-pick the other one with the bot then a quick rebase on this PR should be fine

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
