### PR TITLE
🌱Fix linting issues for operator

### PR DESCRIPTION
**Pull request by alexander-demichev**
**What this PR does / why we need it**:
Run `make lint-fix` and `make generate` in the operator.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]

**Comment by enxebre** [comment]
Is this not running in CI?

**Comment by MarcelMue** [comment]
> Is this not running in CI?

I believe it is running but the problem was introduced before we added it in CI IIRC

**Pull request merged**
