### PR TITLE
 🌱 Make in memory runtime and server accessible from outside

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR makes public the in-memory runtime package and the in-memory server package so they can be used by other providers as well (we plan to use them in CAPV).

On top of moving those packages out of "internal", the package import alias has been aligned across all the codebase.

/area provider/infrastructure-in-memory

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/test pull-cluster-api-e2e-main-full

To run the test using the in-memory provider

**Comment by fabriziopandini** [comment]
/hold
It seems there is ongoing work in vcsim that could help us here, I'm gathering info

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
/hold cancel
the ongoing work in vcsim will make it easier some parts of the CAPV testing effort, but we still need to use this package if we want to keep the simulated environment as lightweight as possible (e.g. don't use a container for each VM)

cc @sbueringer

**Pull request merged**
