### PR TITLE
reset cluster.status.ControlPlaneInitialized when all control planes are removed

### PR DESCRIPTION
**Pull request by accepting**
Signed-off-by: JunLi <lijun.git@gmail.com>

**What this PR does / why we need it**:
Reset cluster.status.ControlPlaneInitialized to false when all control plane machines are removed

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/1746

### CODE REVIEW

**Comment by ncdc** [comment]
@detiber I think I'm ok with this change for standalone control plane machines. But for `KubeadmControlPlane`-based clusters, we wouldn't do this (since we won't support scale to 0). Right?

**Comment by detiber** [comment]
> @detiber I think I'm ok with this change for standalone control plane machines. But for KubeadmControlPlane-based clusters, we wouldn't do this (since we won't support scale to 0). Right?

I'm a bit torn on this...  What is the expectation of behavior after recovering from this situation?

- If users expect that there cluster will continue to function as it was before removing the control plane Machines, then they will be confused as to why it doesn't, or why existing worker Machines may fail to re-associate with the newly provisioned control plane.
- If the expectation is only that it's a way to troubleshoot and repair a control plane that failed to come up correctly due to misconfiguration, then it's likely okay.

I suspect we would likely trying to be catering to the second expectation here, but I wonder how non-developers of Cluster API would expect this to behave? I have a feeling it would be leaning towards the first expectation.

**Comment by ncdc** [comment]
Good points. I don't think we should be encouraging creating a control plane, scaling it down to 0 (by removing all the machines), and then trying to scale up again.

Do you think we should reject (webhook) deleting the last control plane machine if there are any other machines still around?

@accepting do you have a specific need to be able to scale a control plane down to 0 and then back up again?

**Comment by detiber** [comment]
> Do you think we should reject (webhook) deleting the last control plane machine if there are any other machines still around?

I'm not sure we should go that far, considering that control plane management is a loose concept right now (at least until we implement the proposal). By the time we get to the last control plane machine, the etcd cluster may have already lost quorum and things are going to be in a bad state.

**Comment by ncdc** [comment]
Oh, just remembered we have cluster deletion logic that deletes the control plane machines last. So that wouldn't work.

**Comment by accepting** [comment]
@ncdc @detiber I just encount this situtation when I test the process of initializing masters. In my case, I need to repeatedly create and delete master machiens by changing the replica of a machineset. I don't want to delete the whole cluster when trying to delete the last control plane machine. If I delete the cluster, I need to recreate all related CRDs again which includes Cluster, ClusterInfra, MachineSet and maybe BoostrapTemplates and MachineInfraTemplates.

In my opinion, if all control plane machines are removed but the filed `Status.ControlPlaneInitialized` of the Cluster Object is still true, that is very confusing for everyone. That state does not match the semantics of the filed `Status.ControlPlaneInitialized`. Everyone may encount this situation someday, unless the cluster-api can ensure that a control plane cannot be scaled down to 0 once it's scaled up.

**Comment by vincepri** [comment]
During v1alpha2, we adopted`*Initialized` values to avoid using `Ready` fields that could flip-flop. IIRC this field was only to be written to once in a Cluster's lifetime.

Few notes:

- We should update the description of the field to communicate our expectations https://github.com/kubernetes-sigs/cluster-api/blob/6ae7aac4149c2f34f7bfadcc291309115a623c67/api/v1alpha3/cluster_types.go#L106
- The kubeadm bootstrapper uses this field to create the first control plane machine https://github.com/kubernetes-sigs/cluster-api/blob/f1f6030607a939b2e833f97cba84f8bca3882271/bootstrap/kubeadm/controllers/kubeadmconfig_controller.go#L202

**Comment by vincepri** [comment]
If this change is to be merged, we need to also add it to this list https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/providers/v1alpha2-to-v1alpha3.md

**Comment by ncdc** [comment]
@accepting we discussed this issue/PR in the community meeting today. Would you be able to wait and use the new `KubeadmControlPlane` that we'll be developing for v1alpha3? We are generally not in favor of proceeding with this change for control planes that are managed as individual machines.

**Comment by accepting** [comment]
> @accepting we discussed this issue/PR in the community meeting today. Would you be able to wait and use the new `KubeadmControlPlane` that we'll be developing for v1alpha3? We are generally not in favor of proceeding with this change for control planes that are managed as individual machines.

I am fine for this. I can think ways to workaround for the moment.

**Comment by ncdc** [comment]
Thanks!
/close

**Pull request closed without merging**
