### PR TITLE
:book: update quickstart kustomize commands to target correct subdir

### PR DESCRIPTION
**Pull request by cahillsf**
**What this PR does / why we need it**:
Currently the quickstart guide applies two of the `kustomize` commands to directories that do not contain the kustomization.yaml file, resulting in the following errors when you step through these commands:

```
 kustomize build bootstrap/kubeadm/config
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/stephen.cahill/cluster-api/bootstrap/kubeadm/config'
```

```
kustomize build controlplane/kubeadm/config
Error: unable to find one of 'kustomization.yaml', 'kustomization.yml' or 'Kustomization' in directory '/Users/stephen.cahill/cluster-api/controlplane/kubeadm/config'
```

This PR updates the two commands to target the correct subdirectories for the commands to succeed.

### CODE REVIEW

**Comment by elmiko** [comment]
/ok-to-test

this looks reasonable to me

**Comment by elmiko** [comment]
/retitle :book: update quickstart kustomize commands to target correct subdir

**Review by killianmuldoon — COMMENTED** [review]
Thanks for catching this!
/lgtm
/approve

**Pull request merged**
