### PR TITLE
🌱 Bump kubebuilder tools to v0.4.2

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @killianmuldoon @fabriziopandini @chrischdi 

cc @kubernetes-sigs/cluster-api-release-team

**Comment by furkatgofurov7** [comment]
I think we need to merge https://github.com/kubernetes-sigs/kubebuilder-release-tools/pull/58 before taking this in?

cc @mjlshen

**Review by killianmuldoon — COMMENTED** [review]
Release v0.4.2 is still using the outdated image in its action. The current plan was to bump the versions in the kubebuilder-tools repo and then use the sha of the commit for this action so we get the correct image version.

I'm not sure when we'll get a future release of kubebuilder-tools but we should be sure to track it so we can go back to a tagged version of this action.

**Comment by furkatgofurov7** [comment]
> I'm not sure when we'll get a future release of kubebuilder-tools but we should be sure to track it so we can go back to a tagged version of this action.

Yeah, probably not too soon based on the slack conversations @vincepri was also suggesting to you use sha  of the commit in the meantime

**Comment by killianmuldoon** [comment]
Fine IMO to merge this as is, but it won't unblock us. Let's merge this and wait for the updates in kubebuilder and do a follow up bump.

/cc @mjlshen 

/lgtm
/approve

**Comment by sbueringer** [comment]
Do we know if the action works after the last fix? If we don't know, let's bump to the sha of the right commit to test it.

We shouldn't trial-and-error going forward with kubebuilder-release-tools releases

**Pull request merged**
