### PR TITLE
Switch apiGroup to x-k8s.io

### LINKED ISSUE #1073: Come up with globally valid API groups
/kind bug

https://github.com/kubernetes-sigs/cluster-api/blob/814130408c655984e6b2b10d698243aa226fb43f/pkg/apis/cluster/v1alpha1/cluster_types.go#L26

The API group `.k8s.io` should not be used by anything other than core Kubernetes.

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1073 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
Does the CAEP also need to be updated for the correct API group?

**Comment by vincepri** [comment]
@detiber I haven't found any references to the API group in the proposals

**Pull request merged**
