### PR TITLE
:seedling: test: combine Finalizers tests to default quick start tests

### LINKED ISSUE #9636: Merge finalizer tests with default quick start tests
https://github.com/kubernetes-sigs/cluster-api/pull/9471 introduced new tests to check that finalizers were correctly re-reconciled in Cluster API.

After a week of runs there's been no failures in this test. We should consider merging these tests with the basic CAPI e2e tests in order to reduce the total number of tests we run and the length of the `e2e-full` test run. 

Let's gather another week of data before moving ahead with this, and consider merging after Nov. 6th.

Ref: https://github.com/kubernetes-sigs/cluster-api/pull/9471#pullrequestreview-1659797987

### PR DESCRIPTION
**Pull request by adityabhatia**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9636 

/area e2e-testing

### CODE REVIEW

**Comment by adityabhatia** [comment]
Rebased. 
/unhold

**Comment by sbueringer** [comment]
Thx!

/lgtm

Let's just wait 2-3 days to get more data on main to confirm the finalizers test are absolutely stable.

**Comment by adityabhatia** [comment]
> Thx!
> 
> 
> 
> /lgtm
> 
> 
> 
> Let's just wait 2-3 days to get more data on main to confirm the finalizer tests are absolutely stable.

Sounds good. 
/hold

**Comment by adityabhatia** [comment]
Since the quick start tests have been running quite stable for a while, should we merge this?
cc: @killianmuldoon

**Comment by chrischdi** [comment]
Let's finally get this in.

/lgtm
/approve

**Review by killianmuldoon — COMMENTED** [review]
Thanks for following up on this!

/approve

**Pull request merged**
