### PR TITLE
🌱 clusterctl upgrade cert-manager ignore provider CRDs

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
clusterctl upgrades reads a bunch of objects from the cluster while inspecting current installation of cert-manager.
This is getting kind of critical due to CAPA introducing global resources, that we can't filter out upfront, and in case for any reason CAPA webhooks are not working this makes the operation to fail.

With this PR we are making discovery of cert-manager objects smarter (and as a positive side effect also faster), by dropping all the CRDs that belong to a provider.
/cc @sbueringer @vincepri @ykakarap

### CODE REVIEW

**Comment by sbueringer** [comment]
/retest

/lgtm
(I assume manually verified, that it solves the issue?)

**Comment by fabriziopandini** [comment]
/hold
I have a better fix in https://github.com/kubernetes-sigs/cluster-api/pull/5684

**Comment by fabriziopandini** [comment]
/close
given that https://github.com/kubernetes-sigs/cluster-api/pull/5684 is merged

**Pull request closed without merging**
