### PR TITLE
🌱 Add maxItems to all condition fields

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Found a few more places

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

Note: should we also add this to the proposal?

**Review by JoelSpeed — COMMENTED** [review]
Adding limits to already shipped fields could be a breaking change, how are we arguing to mitigate that? (Or were these the ones that just merged?)

**Comment by chrischdi** [comment]
> Adding limits to already shipped fields could be a breaking change, how are we arguing to mitigate that? (Or were these the ones that just merged?)

AFAIK these are only on new fields which we introduced with the other PR and are only on main :-) So should be good.

**Comment by sbueringer** [comment]
All of these were just added with Fabrizio's PR

**Comment by sbueringer** [comment]
But I guess overall we'll have to figure out how pragmatic we are with things like this (I would say case-by-case decision).

Because stuff like "adding CEL rules later" (or literally every additional validation) could be considered a breaking change

**Comment by sbueringer** [comment]
Added to the proposal as well + regen

**Comment by vincepri** [comment]
This is going to be only in 1.9? If so I'm fine with it, and we should probably check other places where we're adding slices to bound them, given that's a good way to break things

**Review by chrischdi — COMMENTED** [review]
/approve

**Comment by sbueringer** [comment]
This PR only adds it to API fields that we added a few days ago. We simply forgot to add it in all places

/assign @fabriziopandini @chrischdi

**Pull request merged**
