### PR TITLE
🌱Update controller-runtime to v0.19.3

### PR DESCRIPTION
**Pull request by m-messiah**
**What this PR does / why we need it**:

The PR bumps controller-runtime dependency to https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.19.3 with timeouts in leaderelection and inotify-agnostic certwatcher

/area dependency

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/lgtm
/assign @fabriziopandini @chrischdi

**Comment by sbueringer** [comment]
Same here:

I'll bring this up elsewhere (we don't have to discuss here) but just for reference the change in CR (https://github.com/kubernetes-sigs/controller-runtime/pull/3035) leads to up to 10 seconds additional webhook downtime after certificate rotation
https://github.com/kubernetes-sigs/cluster-api/pull/11525#issuecomment-2563770139

**Pull request merged**
