### PR TITLE
[0.1] Update lodash gitbook dependency to address CVE

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Update lodash version to address CVE

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by ncdc** [comment]
@davidewatson you were the last to update this for a previous CVE. I ran `npm audit fix` and it edited the shrinkwrap file. I manually copied those changes to the package lock file. PTAL & make sure it all looks good - thanks!

**Comment by davidewatson** [comment]
Vince already gave this a /lgtm...
/approve

**Pull request merged**
