### PR TITLE
:seedling: OWNERS: Remove randomvariable (Naadir Jeewa)

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

Regret to inform that I'm stepping away from Cluster API so will not be able to review PRs. I wasn't in the owners file long enough to justify moving to emeritus either.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by randomvariable** [comment]
Prow looks broken?

**Comment by sbueringer** [comment]
> Prow looks broken?

Yup > https://kubernetes.slack.com/archives/C8TSNPY4T/p1641380084203900

/test pull-cluster-api-verify-main

/lgtm 
:(

**Comment by enxebre** [comment]
thanks @randomvariable 
/approve
:'(

**Pull request merged**
