### PR TITLE
✨ Setup controllers and roles for operator objects

### PR DESCRIPTION
**Pull request by alexander-demichev**
**What this PR does / why we need it**:
Setup controllers and generate roles for all operator objects.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/4270

/area operator

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Comment by vincepri** [comment]
@alexander-demichev Please run `make lint-fix`

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
