### PR TITLE
[release-1.2] 🌱 ClusterClass & test/framework: consider replicas for control plane readiness

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Manual cherry-pick of #7914

Doesn't contain all changes to the self-hosted test as the self-hosted test didn't contain an upgrade in release-1.2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Will fix up

**Comment by sbueringer** [comment]
Manual cherry-pick. so I want to see the test results before merging

/hold
/test pull-cluster-api-e2e-full-release-1-2
/test pull-cluster-api-e2e-workload-upgrade-1-26-latest-release-1-2

**Comment by fabriziopandini** [comment]
/lgtm
pending CI

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-release-1-2

Let's see if it's just a flake

**Pull request merged**
