### PR TITLE
📖 Add members of 1.8 release

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #10472

/area release

### CODE REVIEW

**Comment by sbueringer** [comment]
/approve

Just so you can merge it, I didn't review.

**Comment by chrischdi** [comment]
/ok-to-test

will leave up lgtm to someone else :-) Feel free to ping me if it is finalised

**Review by chandankumar4 — APPROVED** [review]
/lgtm
Communications team members looks good

**Pull request merged**
