### PR TITLE
🐛  Fix ObjectTracker to allow retry on error

### PR DESCRIPTION
**Pull request by vishnukarthikl**
**What this PR does / why we need it**:

When ObjectTracker.Watch is called, the object's GroupKind is stored in a cache, so that duplicate
registration is avoided. But if some reason the watch registration errored out, the
cache doesn't clear out the object as the wrong key was passed. This fix allows the
Watch to be retried correctly in the case of failures with the registration.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/ok-to-test
/milestone v0.4.0

This is probably a candidate for backporting as well

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
/milestone v0.4.0

Thank you!

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
