### PR TITLE
🌱 Update docker to v20.10.16

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

This PR will update the docker dependency to the latest available version

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
> +6 −765

Wow - I wonder why there's such a big diff for the small change?

**Comment by mkumatag** [comment]
> > +6 −765
> 
> Wow - I wonder why there's such a big diff for the small change?

seems like nobody ran `go mod tidy` before :P there were some unwanted deps!

**Comment by killianmuldoon** [comment]
On the docker side? We run it as part of `make generate-modules` and there's no diff when I run it on current main.

**Comment by killianmuldoon** [comment]
That project actually uses a vendor.mod instead of a go.mod, which means (I think) they have to do manual cleanups to get rid of dependencies. It looks like there's a few of those in the git history - https://github.com/moby/moby/commits/master?after=262f574f01e7e525af37e3bf278300045c076b71+34&branch=master&path%5B%5D=vendor.mod&qualified_name=refs%2Fheads%2Fmaster. 

Looks like we're reaping the benefits -thanks for removing so much unneeded dependencies from the repo! :smile:

/lgtm

**Comment by sbueringer** [comment]
Thx!

/retitle 🌱 Update docker to v20.10.16
/approve
/lgtm

**Pull request merged**
