### PR TITLE
✨ Use KubeadmControlPlane in the e2e test

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

/hold

I'm holding because this test requires Delete to be implemented before it can pass, but this is the direction the e2e framework is headed.

As KubeadmControlPlane is not strictly a required piece, I'm considering adding this as an additional test that folks don't have to use as they may not use the KubeadmControlPlane with their set up.

### CODE REVIEW

**Comment by akutz** [comment]
Hi @chuckha,

Want me to run CAPV with this PR and see what happens?

**Comment by chuckha** [comment]
@akutz Ah, I should have stated why I tagged you. I mostly wanted you to see where this test was going and to make sure that CAPV was going to be using the kubeadm control plane controller -- but I think I'll make this its own test and keep the existing control-plane set up test that you're already using. That way providers can choose to use this test or not.

**Comment by chuckha** [comment]
thanks to @akutz, should remove the logs and such.

**Pull request closed without merging**
