### PR TITLE
[release-1.2] 🌱 Update references following Flatcar GitHub org rename

### PR DESCRIPTION
**Pull request by johananl**
**What this PR does / why we need it**: Cherry-pick of #7200.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

cc @sbueringer

### CODE REVIEW

**Comment by sbueringer** [comment]
@johananl 
Changes look fine thx. Can you please run `make generate-modules` to fix the broken verify job?

**Comment by johananl** [comment]
> @johananl Changes look fine thx. Can you please run `make generate-modules` to fix the broken verify job?

Done.

**Comment by sbueringer** [comment]
Thank you very much!

/test pull-cluster-api-e2e-full-release-1-2

**Pull request merged**
