### PR TITLE
Include links to known implementations of Cluster API provisioners.

### PR DESCRIPTION
**Pull request by davidewatson**
**What this PR does / why we need it**:

As discussed during the weekly cluster-api-wg meeting, there are multiple Cluster API provisioners in various stages of development. In order to provide a common rallying point for shared development efforts, we are working on creating sig-lifecycle sponsored repositories. This README update is to document those efforts until we have shared and/or well-known repositories.

**Which issue(s) this PR fixes**:
Related to  https://github.com/kubernetes-sigs/cluster-api/issues/383

**Special notes for your reviewer**:
NONE

**Release note**:
NONE

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by davidewatson** [comment]
I've updated the pointer to the Openstack implementation. Since all of the other reference implementations may eventually be moved under the `kubernetes-sigs` organization, what do we want to do with this PR?

We could replace it with a summary of https://github.com/kubernetes-sigs/cluster-api/issues/383 This would have the advantage of potentially requiring less maintenance over time. Alternatively, we can merge it as is, close it, or?

I've heard from multiple people that this PR is where they first learned of impl x or y, so I think there is some value for new comers.

**Comment by dims** [comment]
@davidewatson thanks for updating the PR with the new repo for OpenStack impl

Yes, this list is definitely valuable. So +1 from me.

**Pull request merged**
