### PR TITLE
🏃 Remove WaitGroup for MachineSet controller deletion requests

### LINKED ISSUE #2989: MachineSet controller deletion requests don't need to run in a WaitGroup
The MachineSet controller currently uses a WaitGroup when it scales down: https://github.com/kubernetes-sigs/cluster-api/blob/59a696e07b5e4620ba66ce17cd35d2d0b0ae73d0/controllers/machineset_controller.go#L377-L393

This was added around v1alpha1 timeframe because Delete at that time was blocking. Today, these Delete calls can be done sequentially because they return right away and don't have to wait for the delete to finish.

/kind cleanup
/milestone v0.3.x
/priority backlog
/help

### PR DESCRIPTION
**Pull request by akhil-rane**
**What this PR does / why we need it**:
This PR removes the WaitGroup for MachineSet controller deletion requests.
It was added around v1alpha1 timeframe because Delete at that time was blocking.
Today, these Delete calls can be done sequentially because they return right
away and don't have to wait for the delete to finish.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2989

### CODE REVIEW

**Comment by fabriziopandini** [comment]
thanks @akhil-rane , good catch!
/ok-to-test
/approve

**Comment by fabriziopandini** [comment]
/hold
Oh, I just noticed that https://github.com/kubernetes-sigs/cluster-api/pull/3089 is tackling this problem as part of a broader cleanup 😓
@vincepri how do you want to proceed here?

**Comment by akhil-rane** [comment]
@fabriziopandini Oops! my bad. I did not notice that @vincepri had already created a PR.

**Comment by vincepri** [comment]
/retitle 🏃 Remove WaitGroup for MachineSet controller deletion requests

**Comment by vincepri** [comment]
@fabriziopandini We can merge this one first, then I'll rebase and we merge the other one in

**Pull request merged**
