### PR TITLE
📖 Update ClusterClass proposal

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This PR updates the proposal based on recent developments.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
I thought about needing to add examples and descriptions here, but I don't think they really need to be covered in the proposal at this stage.

**Comment by sbueringer** [comment]
> I thought about needing to add examples and descriptions here, but I don't think they really need to be covered in the proposal at this stage.

I would have added them, but they are part of the JSONSchemaProps which is not part of the proposal currently :) (which is probably a good thing)

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

Thank you!

**Pull request merged**
