### PR TITLE
:book: fixing clusterctl.exe installation directions for curl.exe

### PR DESCRIPTION
**Pull request by luthermonson**
**What this PR does / why we need it**:
Fixes clusterctl.exe installation on Windows, first it was missing the -L for the redirect and was returning empty content for the http request. but... curl is sometimes an alias in PowerShell for `Invoke-WebRequest` so the best and most cross compatible way for cmd and powershell I ever found was to just call `curl.exe` explicitly which always ends up being the curl everyone expects.

This is what happens using the docs as they exist today in powershell
```
~ > curl https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/clusterctl-windows-amd64.exe -o clusterctl.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
~ > get-content .\clusterctl.exe
~ > clusterctl
ResourceUnavailable: Program 'clusterctl.exe' failed to run: An error occurred trying to start process 'C:\Users\luthe\bin\clusterctl.exe' with working directory 'C:\Users\luthe'. The specified executable is not a valid application for this OS platform.At line:1 char:1
+ clusterctl
+ ~~~~~~~~~~.
```

This is what happens after this patch

```
~ > curl -L https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0/clusterctl-windows-amd64.exe -o clusterctl.exe
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100 61.6M  100 61.6M    0     0  26.6M      0  0:00:02  0:00:02 --:--:-- 33.8M
~ > .\clusterctl.exe version
clusterctl version: &version.Info{Major:"1", Minor:"2", GitVersion:"v1.2.0", GitCommit:"aebeed871c780cfc71bc292dd59eed381da0771f", GitTreeState:"clean", BuildDate:"2022-07-18T14:52:17Z", GoVersion:"go1.18.3", Compiler:"gc", Platform:"windows/amd64"}
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks for fixing this up! We definitely have a problem reviewing Windows workflows 🙂 Hopefully someone who can run this locally is able to confirm it's the right approach!

**Comment by luthermonson** [comment]
@killianmuldoon can this get merged?

**Comment by killianmuldoon** [comment]
> @killianmuldoon can this get merged?

I'd prefer to wait until other Windows-using folks chime in here to be sure this is the correct solution. I'll raise it in the slack channel and see if anyone can help.

**Comment by jackfrancis** [comment]
cc @marosset

**Comment by marosset** [comment]
> > @killianmuldoon can this get merged?
> 
> I'd prefer to wait until other Windows-using folks chime in here to be sure this is the correct solution. I'll raise it in the slack channel and see if anyone can help.

Using `curl.exe` for windows instead of the `curl` powershell alias is my recommended approach.
These will work in either powershell or cmd
I made recently made the same suggestions in k/website :)

/ok-to-test
/lgtm

**Comment by killianmuldoon** [comment]
Thanks for helping review this @marosset!

/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
