### PR TITLE
:seedling: Bump cert-manager to v1.13.2

### PR DESCRIPTION
**Pull request by killianmuldoon**
:seedling: Bump cert-manager to **v1.13.2**
Release notes: https://github.com/cert-manager/cert-manager/releases/tag/v1.13.2

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/area dependency

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks!

/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
