### PR TITLE
🐛 Use Kubernetes 1.24 in quickstart and CAPD, bump to kind v0.14

### PR DESCRIPTION
**Pull request by sbueringer**
What this PR does / why we need it:
Cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/6513
Also includes https://github.com/kubernetes-sigs/cluster-api/pull/6557

Which issue(s) this PR fixes (optional, in fixes #<issue number>(, fixes #<issue_number>, ...) format, will close the issue(s) when PR gets merged):
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Should be ready now, all tests green

/assign @fabriziopandini @killianmuldoon @chrischdi

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
