### PR TITLE
📖  Add new fix for Docker inotify troubleshooting

### LINKED ISSUE #5940: Docker Desktop >= 4.3.* for MacOS: unable to create workload cluster with CAPD
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

It looks like it's not possible to create workload clusters with CAPD on Docker Desktop for MacOS out of the box.

The creation of the management cluster still works, but usually the creation of the first worker machine of the workload cluster fails. 
CAPD / the worker machine report a lot of `too many open files` errors.

It seems to be an issue in Docker Desktop itself (https://github.com/docker/for-mac/issues/6071). So mostly opening the issue in CAPI for visibility.

It can be reproduced by running the regular CAPD quickstart with CAPD on MacOS.

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Adds information to point users to a Docker Desktop upgrade when they encounter the 'too many files' issue on Docker Desktop for Mac / CAPD.

Fixes #5940

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm

Fine to keep it now but at some point I would drop the workaround from the book (a few months - a year from now or so, if anyone remembers)

**Comment by killianmuldoon** [comment]
Who knows if this will have a regression 😄. But yeah, we can't keep building up small fixes for every point version in third party dev tools.

**Review by vincepri — APPROVED** [review]
/approve

**Comment by fabriziopandini** [comment]
Now I can finally upgrade docker 😜

**Pull request merged**
