### PR TITLE
🌱 Move the ClusterTopologyReconciler to a separated package

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR moves the ClusterTopologyReconciler to a separated package, separating it from the other controller that are stable.

NOTE: this PR is only re-shuffling things, no additional changes applied

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5038

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@killianmuldoon PTAL

**Comment by sbueringer** [comment]
/lgtm
(diffed all files to be sure, and it looks good)

**Review by killianmuldoon — COMMENTED** [review]
I think we should rethink the clusterclass.go file as it doesn't make it clear what that functionality the file actually has. Could the getClass function be joined with currentstate.go? It seems that the functions fit well together.

**Comment by sbueringer** [comment]
One option could be to name it `currentclusterclass` analog to `currentstate` which signals a bit that we retrieve the current clusterclass/state in those files

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
