### PR TITLE
🌱 Refactor controlplane health check in KCP

### LINKED ISSUE #3858: Forward-port refactor controlplane health check in KCP
https://github.com/kubernetes-sigs/cluster-api/pull/3806 introduced a refactor for reconcile-health in release 0.3; we should 
We should now forward port the same changes in release v0.4

/kind feature

### PR DESCRIPTION
**Pull request by arghya88**
**What this PR does / why we need it**:
Forward ports #3806 to master
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3858

### CODE REVIEW

**Comment by arghya88** [comment]
cc @fabriziopandini @sedefsavas

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
