### PR TITLE
🌱(option): Add OptionFunc

### PR DESCRIPTION
**Pull request by cndoit18**
Add an optionfunc that implements Option

Signed-off-by: cndoit18 <cndoit18@outlook.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

@cndoit18 Thanks for the contribution! Could you add a brief explanation for why you've made this change?

**Comment by cndoit18** [comment]
> /ok-to-test
> 
> @cndoit18 Thanks for the contribution! Could you add a brief explanation for why you've made this change?

Hi，when I want to add some options, I always have to create an empty structure, which confuses me, so I want to adapt it to a function that returns options

**Comment by killianmuldoon** [comment]
This is a breaking change for the API so we'd have to deprecate the older structs before implementing the new ones, but this is a big change to the way we currently do things so we'd need some consensus on the change before proceeding.

Currently we follow the pattern from [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/options.go)

We can discuss this here, but if this is a change you really want to make to the API it might be better to open an issue so we can a range of opinions on the change.

**Comment by cndoit18** [comment]
> This is a breaking change for the API so we'd have to deprecate the older structs before implementing the new ones, but this is a big change to the way we currently do things so we'd need some consensus on the change before proceeding.
> 
> Currently we follow the pattern from [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime/blob/master/pkg/client/options.go)
> 
> We can discuss this here, but if this is a change you really want to make to the API it might be better to open an issue so we can a range of opinions on the change.

OK, thanks

**Pull request closed without merging**
