### PR TITLE
[release-1.8] 🐛 KCP: remove etcd member in pre-terminate hook

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Manual cherry-pick of #11137

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
This PR is a squashed version of #11137 as of now

/hold

until #11137 is merged

**Comment by chrischdi** [comment]
/lgtm
/approve

Compared the diffs

```
git diff origin/main...sbueringer/pr-kcp-pre-terminate > diff-main.diff
git diff origin/release-1.8...sbueringer/pr-kcp-pre-terminate-1.8 > diff-1.8.diff
diff  diff-1.8.diff diff-main.diff
```

**Pull request merged**
