### PR TITLE
 📖 Clean up some typos and links in CAPI book

### PR DESCRIPTION
**Pull request by abhay-krishna**
Fixing some typos and incorrect links in the CAPI book.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
cc @oscr if you have some time

**Review by killianmuldoon — COMMENTED** [review]
Thanks for this - some really nice cleanups here!

/lgtm
/approve

**Comment by killianmuldoon** [comment]
This maybe isn't worth backporting manually as it could be a bunch of work and this is mostly just cleanups - fine with just keeping it on the main branch IMO

**Pull request merged**
