### PR TITLE
🌱 book: add API conversion code walkthrough video

### LINKED ISSUE #5289: Create step-by-step guide for implementing conversion webhooks in CAPI
**User Story**

As a developer I would like to understand the steps that go into creating a conversion webhook for a new type in Cluster API.

**Detailed Description**
This issue should result in some documentation on the specific tasks required to turn a new CAPI API type into a convertible type that is registered properly with a conversion webhook in the CAPI controller.

/kind feature

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5289

### CODE REVIEW

**Comment by sbueringer** [comment]
@killianmuldoon just fyi, there's another occurrence of the object mover flake: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/5958/pull-cluster-api-test-main/1484083624197230592

/retest

**Comment by killianmuldoon** [comment]
/lgtm

If we're going to be adding a number of these should we think about getting a core Youtube channel to host them on? Personal Youtube channels might become a problem to maintain over time.

**Review by killianmuldoon — APPROVED** [review]
/lgtm

If we're going to be adding a number of these should we think about getting a core Youtube channel to host them on? Personal Youtube channels might become a problem to maintain over time.

**Comment by sbueringer** [comment]
> /lgtm
> 
> If we're going to be adding a number of these should we think about getting a core Youtube channel to host them on? Personal Youtube channels might become a problem to maintain over time.

According to the meeting notes it's recommended to upload the videos with the personal YouTube account and then add it to the Sig Cluster Lifecycle playlist (https://docs.google.com/document/d/1ushaVqAKYnZ2VN_aa3GyKlS4kEd6bSug13xaXOakAQI/edit#heading=h.pxsq37pzkbdq). Which was done in this case.

I don't have any background information why it's done like this and if there are alternatives.

**Comment by sbueringer** [comment]
Fixes #5289

**Review by fabriziopandini — COMMENTED** [review]
🥳 
/lgtm
/approve

**Pull request merged**
