### PR TITLE
clusterctl/kind: return stdout and not combined output

### PR DESCRIPTION
**Pull request by neolit123**
**What this PR does / why we need it**:

Ideally only the stdout of kind commands should be captured
and returned, in case kind commands also contain stderr.

Fixes a recent bug where the kind command "get kubeconfig-path"
started printing a deprecation message to stderr.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

NONE?

/kind bug
/priority important-longterm

### CODE REVIEW

**Comment by neolit123** [comment]
https://prow.k8s.io/view/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/1792/pull-cluster-api-verify/1197602407840747523
```
make[2]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api'
make[1]: Leaving directory '/home/prow/go/src/sigs.k8s.io/cluster-api'
!!! Generated code is out of date:
 M go.mod

Please run make generate.
make: *** [Makefile:288: verify] Error 1
```

yet, `make generate` does not generate changes.

**Comment by vincepri** [comment]
@neolit123 Are you using Go 1.12 or 1.13?

**Comment by neolit123** [comment]
@vincepri go 1.13?

**Comment by vincepri** [comment]
We’re still on Go 1.12, the linter is failing because go.mod generates different results when using a version vs the other, if you can switch and regenerate the CI should go green

**Comment by neolit123** [comment]
@vincepri updated.
although something weird is going on with github.

this force-push
https://github.com/kubernetes-sigs/cluster-api/compare/c231b331ae02262b555b64438cd95bf4e8b11bcf..86182375777a2a68f1a343c8d60d87d7366c667c

made a change to gomod

but it's not reflected here:
https://github.com/kubernetes-sigs/cluster-api/pull/1792/files

**Pull request merged**
