### PR TITLE
adding correct make cmd

### PR DESCRIPTION
**Pull request by Emc1992**
**What this PR does / why we need it**: 
- Makefile doesn't have test-e2e, only test cmd

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
- N/A

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
@Emc1992 if you are confortable with this, this paragraph requires some more changes:

- the title should be testing (without E2E)
- `make -C test/infrastructure/docker test` is used to run unit tests (not E2E tests)
- `make test-e2e` runs the CAPI E2E tests that are based on CAPD (CAPD does not have a separated 2e2 suite anymore)
- we should add a warning on top of the page "The Docker provider is not designed for production use and is intended for development environments only."

**Comment by Emc1992** [comment]
> @Emc1992 if you are confortable with this, this paragraph requires some more changes:
> 
> - the title should be testing (without E2E)
> - `make -C test/infrastructure/docker test` is used to run unit tests (not E2E tests)
> - `make test-e2e` runs the CAPI E2E tests that are based on CAPD (CAPD does not have a separated 2e2 suite anymore)
> - we should add a warning on top of the page "The Docker provider is not designed for production use and is intended for development environments only."
> 

Sure, I'll check it out tonight

**Comment by vincepri** [comment]
@Emc1992 Are you still interested in getting this change merged? Also, please sign the CNCF CLA

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
Happy to approve when the CLA is signed. Also, please squash commits

**Comment by Emc1992** [comment]
> /lgtm

Sorry - I swore I already did this weeks ago. My bad!

**Comment by vincepri** [comment]
Seems one of your commit isn't properly signed / committed with a username, it should be fine after fixing that

**Comment by Emc1992** [comment]
> Seems one of your commit isn't properly signed / committed with a username, it should be fine after fixing that

> Seems one of your commit isn't properly signed / committed with a username, it should be fine after fixing that

Only on web client, I assume that's the issue. Will update on the other laptop once its rebuilt.

**Pull request closed without merging**
