### PR TITLE
📖  update autoscaling from zero proposal

### PR DESCRIPTION
**Pull request by elmiko**
**What this PR does / why we need it**:

include the latest changes to the annotation that are proposed in the cluster autoscaler

ref: https://github.com/kubernetes/autoscaler/pull/5382
ref: https://github.com/kubernetes/autoscaler/pull/5416

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm

I assume we don't have to update the book, as the book embeds the README in the autoscaler repo.

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by elmiko** [comment]
> I assume we don't have to update the book, as the book embeds the README in the autoscaler repo.

correct, i just wanted to make sure we kept all the info accurate

**Comment by sbueringer** [comment]
> > I assume we don't have to update the book, as the book embeds the README in the autoscaler repo.
> 
> correct, i just wanted to make sure we kept all the info accurate

Yup sure. Thanks for doing that! :)

**Comment by elmiko** [comment]
the autoscaler change has merged
/hold cancel

**Pull request merged**
