### PR TITLE
Bump controller manager rev to pick up machineset controller fix

### PR DESCRIPTION
**Pull request by k4leung4**
**What this PR does / why we need it**:
This is to pick up #316

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by karan** [comment]
lgtm

**Comment by k4leung4** [comment]
image pushed.

/hold cancel

**Pull request merged**
