### PR TITLE
:book: Update config paths in docs

### PR DESCRIPTION
**Pull request by Namanl2001**
Signed-off-by: Naman <namanlakhwani@gmail.com>

**What this PR does / why we need it**:
`manager_image_patch.yaml` files are moved to a new location, updating their paths in the docs.

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by Namanl2001** [comment]
failing check `Check Markdown links / Broken Links (pull_request)` seems flaky, since logged out link is accessible: https://github.com/kubernetes-sigs/cluster-api/runs/7197389000?check_suite_focus=true#step:4:658 

what needs to be done to make `verify / verify PR contents (pull_request_target)` green?

**Comment by killianmuldoon** [comment]
/retitle :book: Update config paths in docs

**Pull request merged**
