### PR TITLE
Update k8s/code-generator to latest release-1.13

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR updates the `k8s.io/code-generator` dependency to the latest commit in the releast-1.13 branch.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by vincepri** [comment]
@detiber IIRC I ran `dep ensure -update <repo>@<tag>`

**Comment by tariq1890** [comment]
Just to add. I am wary of version locking without a TOML pin especially when this repo is transitively depending on k8s libraries through `controller-runtime` and `controller-tools` . This will need to be addressed sooner or later in the interest of long term project health.

**Comment by vincepri** [comment]
In this case the Kubernetes version is usually dictated from controller-runtime. Maybe we can revisit dependencies later when we tackle #1025, wdyt?

**Comment by vincepri** [comment]
@detiber Added the constraint as well

**Pull request merged**
