### PR TITLE
🌱 WIP Tiltfile with load provider

### LINKED ISSUE #3793: Switch Tilt configuration to use upstream include/load rather than using the custom tilt-provider.json
**User Story**

As a developer I would like the Tilt configuration to more closely match upstream conventions

**Detailed Description**

Currently we have a custom multi-repository configuration mechanism for adding provider configuration to our common cluster-api Tilt configuration. Instead, we should likely switch to the new upstream conventions (that didn't exist when our custom solution was created) of using [include/load with a Tiltfile in the child repositories](https://docs.tilt.dev/multiple_repos.html).

This would also likely require reworking the way we are doing live updates. It should be possible to use the [restart_process](https://github.com/tilt-dev/tilt-extensions/tree/master/restart_process) extension to avoid duplicating the current live update process in place (which was built using the recommended way prior to tilt extensions being introduced).

/kind feature

### PR DESCRIPTION
**Pull request by davideimola**
Co-authored-by: Ludovico Russo <ludus.russo@gmail.com>

**What this PR does / why we need it**:
This PR handles the cluster-api providers' Tiltfile in a different way, by using `load`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3793

### CODE REVIEW

**Comment by davideimola** [comment]
@fabriziopandini @vincepri before go further on the implementation of this thing I would like to discuss it a bit.
As I can see the method requested can be implemented by loading only the required providers inserted in the config file.

I think to handle this thing we have to refactor all the Tiltfile in the providers to let it work.

WTDYT?

cc @ludusrusso

**Review by fabriziopandini — COMMENTED** [review]
@davideimola @ludusrusso I'm still investigating new tilt features, but my first take at this PR is the following.
- Whatever change we are introducing we should document impact for the developers into https://cluster-api.sigs.k8s.io/developer/tilt.html; this will help also in understanding the PR
- By reading the tilt doc, I see a potential advantage if we can use https://docs.tilt.dev/tiltfile_config.html, live reload if a config change, but I'm still trying to understand what advantages we could get from https://docs.tilt.dev/multiple_repos.html, apart from allowing a theoretical grater flexibility for the providers. At the same time I don't want to drop the simplicity of the current model where provider are not required to have tilt skills. What is your opinion after your exploration? 
- I'm wondering if we should move the adoption of the reload extension into a separated PR, because it is introducing a considerable number of new files; also I was expecting that by using such extension we could further simplify our Tiltfile by dropping the existing custom implementation of restart, e.g 
https://github.com/fabriziopandini/cluster-api/blob/404215420c883e8003fb9422cd81a46eb2b678a2/Tiltfile#L127-L142

**Comment by davideimola** [comment]
Hi @fabriziopandini as I can say I think it can be a good thing to use both tiltfile config and live reload. Probably you are right when you say to open different PRs.

I understand what you are saying about multiple repos Tiltfile, but I think it can be a good thing to standardize both CAPI and the providers to use Tilt.

I think it is interesting if the providers' devs can work on their Tiltfile if they requires particular configurations!

**Comment by vincepri** [comment]
Hi folks, what's the status of this PR?

**Comment by davideimola** [comment]
HI @vincepri 
This PR is blocked because I have done a part of the job to have an estimate of how it can works. But atm I do not understand how we would like to proceed with this issue. The problem I can see, this thing involves each module.

**Comment by vincepri** [comment]
@davideimola Is it ok to close it for now then?

**Comment by davideimola** [comment]
@vincepri hi, yes it is fine.

**Pull request closed without merging**
