### PR TITLE
🐛   cherry-pick: update CoreDNS ClusterRole (Kubernetes>=1.22,CoreDNS >= 1.8.1)

### LINKED ISSUE #4927: capi-e2e-main-1-21-latest fails because of CoreDNS RBAC issues
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]

After we changed our 1.21=>latest upgrade tests to CoreDNS 1.8.4 they are failing now ([testgrid](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-21-latest))

**What did you expect to happen:**
They should still work.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

CoreDNS 1.8.4 also uses EndpointSlices. Thus the ClusterRole `system:coredns` has been adapted in kubeadm (https://github.com/kubernetes/kubernetes/pull/102466/files). As we're installing the cluster with 1.21 and then just updating to 1.22 we still have the old ClusterRole. I assume we have to ensure that starting with CoreDNS 1.8.4 the ClusterRole also includes EndpointSlices. 

This problem affects all clusters installed with kubeadm < 1.22 when using CoreDNS >= 1.8.4.

Currently our jobs do not fail when the conformance test fails, but this should be fixed through #4907.

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4927

### CODE REVIEW

**Comment by sbueringer** [comment]
@randomvariable that's the one we were talking about recently. It's required to be able to upgrade to Kubernetes 1.22 and CoreDNS v1.8.4

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
