### PR TITLE
📖 book: fix broken link in Contributing

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/7110#discussion_r958366116

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @CecileRobertMichon

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
