### PR TITLE
Implement Scale Subresource for MachineSet and MachineDeployment (#580)

### PR DESCRIPTION
**Pull request by stpabhi**
Signed-off-by: Abhilash Pallerlamudi <stp.abhi@gmail.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
Implement Scale Subresource for MachineSet
```

### CODE REVIEW

**Comment by roberthbailey** [comment]
Should we also add the same scale resource on machine deployments?

/cc @pwittrock @droot to verify the changes adding the kubebuilder comments look sane.

**Comment by stpabhi** [comment]
> Should we also add the same scale resource on machine deployments?
Should i Include it in this PR?
> /cc @pwittrock @droot to verify the changes adding the kubebuilder comments look sane.

**Comment by droot** [comment]
annotations in the comments for scale subresource looks sane. We are yet to add `Scale` method to the client pkg in `controller-runtime` though.

**Comment by stpabhi** [comment]
@roberthbailey ok, will update the PR and also 
> kubectl scale —replicas=2 machinesets/machineset-example
does show the scaled replicas in the yaml.

**Comment by stpabhi** [comment]
@roberthbailey added scale subresource for MachineDeployment. Is it good?

**Comment by alvaroaleman** [comment]
@stpabhi Just for my understanding, does adding the scale subresource mean one now has to use a dedicated scale client or is it just another way of changing the replicas and simply adjusting `.spec.replicas` continues to work?

**Comment by stpabhi** [comment]
> @stpabhi Just for my understanding, does adding the scale subresource mean one now has to use a dedicated scale client or is it just another way of changing the replicas and simply adjusting `.spec.replicas` continues to work?

To use ```kubectl scale``` as per my understanding.

**Pull request merged**
