### PR TITLE
🐛 capd: fix MachinePool reconciler

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@fabriziopandini 
Test was green locally. I would recommend merging the PR ASAP after we have green e2e-full and upgrade tests

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
