### PR TITLE
📖 testing: add jq variant for inspecting json logs

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Documents a variant of using `jq` to inspect the json logs of tests.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
nice, thanks for documenting this!
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
Awesome - thanks for adding this!

/lgtm
/approve

**Pull request merged**
