### PR TITLE
 📖 add maas to infra provider list

### PR DESCRIPTION
**Pull request by jzhoucliqr**
**What this PR does / why we need it**:

Add MAAS to infra provider list. 

This is a baremetal provider build on top of Canonical MAAS. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/ok-to-test

Welcome to the MAAS provider! if you eat to show up at the CAPI meeting and demo the new provider this will be great!
/lgtm

**Comment by jzhoucliqr** [comment]
> /ok-to-test
> 
> Welcome to the MAAS provider! if you eat to show up at the CAPI meeting and demo the new provider this will be great!
> /lgtm

Thanks @fabriziopandini. Sure, will do!

**Pull request merged**
