### PR TITLE
Load auth plugins for client-go for clusterctl

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Currently `clusterctl` commands that use a pre-provided kubeconfig will not correctly authenticate if the kubeconfig uses auth plugins (such as oidc), this PR loads the client-go auth plugins.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by neolit123** [comment]
`+54,573 −3 `
:grimacing:

**Comment by detiber** [comment]
> `+54,573 −3 `
> :grimacing: 

@neolit123 The vast majority of the changes are vendored dependencies. I could potentially limit the loaded plugins to only allow oidc, which would solve my use case, but that would limit the use of other plugin-based auth methods for use by others when interacting with existing external management clusters.

**Pull request merged**
