### PR TITLE
🌱 Randomly generated namespace in exp pkg tests

### PR DESCRIPTION
**Pull request by GrigoriyMikhalkin**
Partly solves #4629.

Updates namespace generation in exp pkg tests.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/ok-to-test
please ensure namespace cleanup and whenever possible replace "default" with a random namespace

**Comment by fabriziopandini** [comment]
/lgtm
please squash commits before merge

**Comment by fabriziopandini** [comment]
/test pull-cluster-api-test-main
test failures seems unrelated to this PR

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
