### PR TITLE
✨ Uplift controller runtime to v0.11.1

### LINKED ISSUE #6138: Upgrade to controller-runtime v0.11.1
Let's upgrade to the latest controller-runtime release v0.11.1 (released today).

Tasks:
* [ ] Upgrade `sigs.k8s.io/controller-runtime v0.11.0` in go.mod files to `sigs.k8s.io/controller-runtime v0.11.1`
* [ ] Run `make modules`

/kind feature

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Uplifts controller runtime module in go.mod files located in:
- root of the repo;
- hack/tools;
- test folders

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6138

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!

/lgtm
/ok-to-test

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by enxebre** [comment]
for ref, it brings fix for https://github.com/kubernetes-sigs/controller-runtime/issues/1789
/approve

+1 to cherry-pick this

**Comment by sbueringer** [comment]
@furkatgofurov7 Thank you very much!

**Pull request merged**
