### PR TITLE
:seedling: Update mdbook to v0.4.10

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm


remind me, are we running the book verify target in CI ?

**Comment by vincepri** [comment]
No I don't think so, not sure if we should?

**Comment by CecileRobertMichon** [comment]
I guess it'd be good to check the book build doesn't break with changes like this

**Comment by vincepri** [comment]
Oh the book build yes, it's checked with `netlify` builds. I thought you were referring to the linkchecker

**Pull request merged**
