### PR TITLE
⚠️ Update Controller Runtime to v0.9.0

### LINKED ISSUE #4714: Update controller runtime to v0.9.0
Pending on v0.9.0 controller-runtime [release](https://github.com/kubernetes-sigs/controller-runtime/releases).

We are currently using a beta release of controller-runtime, we should switch to using the v0.9.0 stable release as soon as it is available, before releasing v0.4.0.

/kind release-blocking

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4714

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

/retest

**Pull request merged**
