### PR TITLE
🌱 Add v1.9 release team members to timeline doc

### PR DESCRIPTION
**Pull request by Sunnatillo**
**What this PR does / why we need it**:

This PR adds v1.9 release team members to release timeline doc 

/area release

### CODE REVIEW

**Comment by sbueringer** [comment]
Please review release-team internally and then let me know when you need an approve to merge

/ok-to-test

**Review by hackeramitkumar — APPROVED** [review]
lgtm

**Comment by fabriziopandini** [comment]
Thanks everyone for stepping up 🙇  🤟 
Happy to approve when we got +1 from all the appointed release team members

**Review by chandankumar4 — APPROVED** [review]
lgtm

**Comment by SD-13** [comment]
lgtm

**Comment by pravarag** [comment]
lgtm

**Comment by varshasuryawanshi** [comment]
lgtm..

**Comment by Sunnatillo** [comment]
> Please review release-team internally and then let me know when you need an approve to merge
> 
> /ok-to-test

we can merge this now

**Comment by chrischdi** [comment]
/approve

Thanks everyone!

**Pull request merged**
