### PR TITLE
Update boilerplate checks and generated files

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR fixes the year value in `hack/boilerplate.go.txt`, which is used by kubebuilder when generating new files.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by ncdc** [comment]
I know other kubernetes repos removed the YEAR from the boilerplate file used for code generation because of this issue. Let me dig up a link.

**Comment by vincepri** [comment]
@detiber ptal

**Comment by detiber** [comment]
I'll defer to @ncdc I'm not a huge fan of updating the copyright date for generated files, but I'm not caremad enough to block for this either :joy:

**Comment by ncdc** [comment]
Does this impact anything other than clientsets, listers, and shared informers?

**Comment by vincepri** [comment]
I'm not totally sure, I ran `make generate` and it re-generated the clientset files

**Comment by ncdc** [comment]
Oops! I didn't mean remove the copyright year entirely, from every file. Just the auto-generated ones!

**Pull request merged**
