### PR TITLE
🌱  Update Docker and containerd dependencies

### PR DESCRIPTION
**Pull request by mkumatag**
**What this PR does / why we need it**:

- Updating the docker go dep to the latest available version

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!
/lgtm

**Comment by sbueringer** [comment]
/retitle 🌱  Update Docker and containerd dependencies

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
