### PR TITLE
[release-1.2] ✨  Add 3DS outscale provider

### PR DESCRIPTION
**Pull request by outscale-vbr**
**What this PR does / why we need it**:
Add outscale also in  release-1.2 if you want to get the changes into the v1.2.4 release as well
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by outscale-vbr** [comment]
@sbueringer
i backport in release-1.2.

**Comment by sbueringer** [comment]
Thank you very much!

/lgt

**Comment by sbueringer** [comment]
@outscale-vbr Looks like unit tests have an issue

**Comment by sbueringer** [comment]
Please drop the first two commits

**Comment by outscale-vbr** [comment]
@sbueringer I drop two first commits and rebase

**Comment by sbueringer** [comment]
/ok-to-test

Looks good. I think we can merge after the tests

/lgtm

**Pull request merged**
