### PR TITLE
✨ Update cert-manager version (v1.9.1 -> v1.10.0)

### LINKED ISSUE #7416: Upgrade to cert-manager v1.10.0
Hey folks,

cert-manager v1.10 was released. So let's bump the version used in CAPI (https://github.com/cert-manager/cert-manager/releases/tag/v1.10.0)

/kind feature

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

Updates cert-manager from v1.9.1 -> v1.10.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7416

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
Thanks!
/lgtm
Pending the e2e tests

**Comment by fabriziopandini** [comment]
/lgtm
@sbueringer PTAL

**Comment by sbueringer** [comment]
Thx
/approve

**Pull request merged**
