### PR TITLE
[release-1.2] :book: Update docs/Makefile. Fix proposal diagrams transparency

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

Adds 3 pr's that updates the CAPI book and proposals diagrams and the Makefile. 

* [Update plantuml version (v1.2019.6 -> v1.2022.6)](https://github.com/kubernetes-sigs/cluster-api/pull/7050/commits/1a0b5a561d4aecb7ddec3c10d6a5ff0bea44ab35)
* [Update docs/Makefile. Fix proposal diagrams transparency issue with new](https://github.com/kubernetes-sigs/cluster-api/pull/7050/commits/a41ed8a4e34f8925b452bef43f3cda05c4bff1a2)
* [Add PlantUML diagram transparency for book and proposals](https://github.com/kubernetes-sigs/cluster-api/pull/7050/commits/7854dd9e6ae54cd686da02798b76a6285281487d)

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
I'm not sure if we can combine cherry-picks for PRs @vincepri @ykakarap  WDYT?

For this and other doc PRs it's not important - we're not cherry picking to get into a release we're just trying to get the latest docs into the version of the book that's available at the principle branch.

**Review by ykakarap — COMMENTED** [review]
I would be fine with adding the 2 cherry-picks to this PR given that they are related. 

Let's make sure to update the PR description to clearly call out that it is a manual cherry pick for the 2 PRs and also let's update the title of the PR to reflect the changes (important when generating the release catalog).

**Comment by oscr** [comment]
I also included #7017 to keep the build working. With it `make diagrams` doesn't produce a diff.

**Comment by oscr** [comment]
@ykakarap I updated the pr description to reflect the changes as you mentioned. Anything you would like to add?

**Comment by killianmuldoon** [comment]
One thing 🙂 
/retitle [release-1.2] Update docs/Makefile. Fix proposal diagrams transparency

**Comment by killianmuldoon** [comment]
That just brings the title into line with how we tend to do other cherry-picks

**Comment by killianmuldoon** [comment]
One thing 🙂
/retitle [release-1.2] :book: Update docs/Makefile. Fix proposal diagrams transparency

**Comment by sbueringer** [comment]
Is there a reason why we can't cherry-pick the individual PRs in the right order? It would safe us the work of re-reviewing all changes and would keep it a lot simpler tracking-wise

**Comment by oscr** [comment]
The reason was a merge conflict when cherry-picking #7046. I also added #7017 to ensure that if you run make diagrams and get the new diagrams.

**Comment by sbueringer** [comment]
Sounds good.

We should cherry-pick #7056 after #7050 is merged

**Comment by sbueringer** [comment]
Diffed against main. Everything identical apart from #7056

/lgtm
/approve

**Pull request merged**
