### PR TITLE
✨ Add healthprobe for bootstrap and controlplane

### PR DESCRIPTION
**Pull request by chymy**
**What this PR does / why we need it**:
Add healthprobe for bootstrap provider and controlplane provider.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@chymy I think we should also add probes to the manager.yamls

**Comment by chymy** [comment]
> @chymy I think we should also add probes to the manager.yamls

Thanks @sbueringer, done.
Local testing is ok. I don't know why pull-cluster-api-test-main always fails.

**Comment by sbueringer** [comment]
@chymy 
Thx,
/lgtm

Looks unrelated to me. Unfortunately we have a lot of flaky tests right now. Hope we'll get that fixed soon.

/retest

**Comment by JoelSpeed** [comment]
Gave this a pass, no additions from me

/lgtm
/retest

**Pull request merged**
