### PR TITLE
📖 book: remove old versions from versions.md

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/8134#discussion_r1116173172

### CODE REVIEW

**Comment by oscr** [comment]
Nice cleanup! Thank you for your hard work

/lgtm

**Review by fabriziopandini — COMMENTED** [review]
Thanks for following up on my comment after the previous PR merged, really appreciated.
/lgtm
/approve

**Pull request merged**
