### PR TITLE
🌱 Remove myself from reviewers

### PR DESCRIPTION
**Pull request by benmoss**
**What this PR does / why we need it**:
I'm not able to keep up with this project anymore and it's filling up my GitHub notifications 😸

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
thank you for all your help @benmoss!

**Comment by ncdc** [comment]
@vincepri what's up with the GH checks here?

**Comment by vincepri** [comment]
Probably just need to add a longer description?

**Comment by vincepri** [comment]
If we add back the PR template it should pass

**Comment by ncdc** [comment]
Updated description. Closing & reopening to see if that'll kick the job.

**Pull request merged**
