### PR TITLE
:seedling: Bump controller tools to v1.13.0

### PR DESCRIPTION
**Pull request by killianmuldoon**
Bump controller tools to v1.13.0

Release notes: [kubernetes-sigs/controller-tools@v0.13.0 (release)](https://github.com/kubernetes-sigs/controller-tools/releases/tag/v0.13.0)

part of https://github.com/kubernetes-sigs/cluster-api/issues/8708

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/area dependency

**Comment by sbueringer** [comment]
Please add "part of https://github.com/kubernetes-sigs/cluster-api/issues/8708" to the pr description

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
