### PR TITLE
🌱 Fixing kubetest warnings for deprecations

### LINKED ISSUE #10171: Check Kubetest parameters
### What steps did you take and what happened?

I was checking a test running conformance on https://github.com/kubernetes-sigs/cluster-api/pull/10166 and I noticed those logs entries

```
  You're using deprecated Ginkgo functionality:
  =============================================
    --ginkgo.flakeAttempts is deprecated, use --ginkgo.flake-attempts instead
    Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags
    --ginkgo.progress is deprecated .  The functionality provided by --progress was confusing and is no longer needed.  Use --show-node-events instead to see node entry and exit events included in the timeline of failed and verbose specs.  Or you can run with -vv to always see all node events.  Lastly, --poll-progress-after and the PollProgressAfter decorator now provide a better mechanism for debugging specs that tend to get stuck.
    --ginkgo.slowSpecThreshold is deprecated use --slow-spec-threshold instead and pass in a duration string (e.g. '5s', not '5.0')
    Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed--slowspecthreshold
```

It would be great to check if we have the same issue on the more recent branches (main, 1.6., 1.%) and eventually fix it

cc @kubernetes-sigs/cluster-api-release-team 

### What did you expect to happen?

Our tests to not use deprecated flags

### Cluster API version

1.4.x

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
/area ci

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10171

/area testing

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
by looking at the output of the conformance test it seems that also one of the new flags (slow-spec-threshold) is now deprecated

`[38;5;11m--ginkgo.slow-spec-threshold is deprecated --slow-spec-threshold has been deprecated and will be removed in a future version of Ginkgo.  This feature has proved to be more noisy than useful.  You can use --poll-progress-after, instead, to get more actionable feedback about potentially slow specs and understand where they might be getting stuck.[0m`

but we can take care care of this in a follow up

**Comment by chrischdi** [comment]
@adilGhaffarDev : this made the following periodics fail:

- [capi-e2e-main-1-24-1-25](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-24-1-25)
- [capi-e2e-main-1-25-1-26](https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main-1-25-1-26)
```

**Comment by adilGhaffarDev** [comment]
> @adilGhaffarDev : this made the following periodics fail:

I am checking

**Comment by chrischdi** [comment]
I think when running kubetest we just pass down the arguments. Older versions of kubetest might have a too old ginkgo version.

**Comment by adilGhaffarDev** [comment]
> I think when running kubetest we just pass down the arguments. Older versions of the kubetest images we use (depends on k8s version) might have a too old ginkgo version.

yes that is the issue, I don't see `--ginkgo.progress is deprecated ` in older tests. But I can see other deprecation warnings:
```
     --ginkgo.flakeAttempts is deprecated, use --ginkgo.flake-attempts instead
    Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed-command-line-flags
    --ginkgo.slowSpecThreshold is deprecated use --slow-spec-threshold instead and pass in a duration string (e.g. '5s', not '5.0')
    Learn more at: https://onsi.github.io/ginkgo/MIGRATING_TO_V2#changed--slowspecthreshold
```
I will revert `-ginkgo.show-node-events` to `-ginkgo.progress`

**Comment by adilGhaffarDev** [comment]
@chrischdi  I have created the PR: https://github.com/kubernetes-sigs/cluster-api/pull/10214 please check.

**Pull request merged**
