### PR TITLE
🐛 Use metadata.yaml in github repo to fetch latest release for older contracts

### LINKED ISSUE #4856: clusterctl does not honor contract metadata when looking up latest release for providers
**What steps did you take and what happened:**

Using `clusterctl` v0.3.x without explicitly specifying component versions breaks now that v0.4.0 is released.

```sh
> clusterctl init
Fetching providers
Error: current version of clusterctl could install only v1alpha3 providers, detected v1alpha4 for provider cluster-api
> clusterctl version
clusterctl version: &version.Info{Major:"0", Minor:"3", GitVersion:"v0.3.19", GitCommit:"665d56652a787180dc36ecbfdf183b1e436fba75", GitTreeState:"clean", BuildDate:"2021-06-09T18:20:15Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
```

**What did you expect to happen:**

`clusterctl` to install the latest version compatible with clusterctl

**Anything else you would like to add:**

This is following up from a Slack conversation: https://kubernetes.slack.com/archives/C8TSNPY4T/p1624629661483900

Users that were relying on things to work consistently found automation that they had built broken immediately after the v0.4.0 release was published.

**Environment:**

- Cluster-api version: v0.3.19
- Minikube/KIND version: v0.11.1
- Kubernetes version: (use `kubectl version`): v1.13.1

/kind bug

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: backport of #4866 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4856

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/retest

test is passing locally

**Comment by CecileRobertMichon** [comment]
I cannot repro this test failure locally, not sure what's going on...

**Comment by randomvariable** [comment]
i had hit these flakes before

/retest

**Pull request merged**
