### PR TITLE
🌱 ClusterClass: change PatchSelectorMatch fields to non-pointer

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This PR changes the fields of PatchSelectorMatch to non-pointer. I think it makes sense because there is no semantical  difference between nil and the zero value.

> Fields SHOULD be pointers if the nil and the zero values (by Go standards) have semantic differences
> quote from our API conventions

It's simply easier to handle the fields if they are no pointers and as they don't have to be ...

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Follow-up to  https://github.com/kubernetes-sigs/cluster-api/pull/5735#discussion_r759161216

### CODE REVIEW

**Comment by sbueringer** [comment]
Diff is fine because the struct has not been released (yet)

**Review by killianmuldoon — COMMENTED** [review]
/lgtm 

Thanks for changing this!

**Comment by fabriziopandini** [comment]
/lgtm 
given that those type are not part of a release yet

@vincepri PTAL

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
