### PR TITLE
Correct Type and Provider column information

### LINKED ISSUE #3440: kubectl get providers column mismatch
**What steps did you take and what happened:**
After running a `clusterctl init` command against a cluster, we can use `kubectl get providers -A` to see the list of installed providers. 
```bash
$ kubectl get providers -A
NAMESPACE   NAME                    TYPE   PROVIDER                 VERSION   WATCH NAMESPACE
foo         bootstrap-kubeadm              BootstrapProvider        v0.3.8    foo
foo         cluster-api                    CoreProvider             v0.3.7
foo         control-plane-kubeadm          ControlPlaneProvider     v0.3.8    foo
foo         infrastructure-aws             InfrastructureProvider   v0.5.2    foo
```
However, the `TYPE` column is empty and the `PROVIDER` column has the type value.

**What did you expect to happen:**
I expect to see the `TYPE` column to have the values such as `InfrastructureProvider` and `CoreProvider`. The `PROVIDER` column should have the name of the provider.

**Anything else you would like to add:**
The CRD spec needs to match `.type` and `.providerName`.

https://github.com/kubernetes-sigs/cluster-api/blob/3ae90857a5ab1b21bf35bcdab2daf3e259454b96/cmd/clusterctl/config/crd/bases/clusterctl.cluster.x-k8s.io_providers.yaml#L21-L27

https://github.com/kubernetes-sigs/cluster-api/blob/3ae90857a5ab1b21bf35bcdab2daf3e259454b96/cmd/clusterctl/api/v1alpha3/provider_type.go#L37-L44

**Environment:**
- Cluster-api version: 6311dc2c1f966edde41c842fb812596fc3ca0b25
- Kubernetes version: (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T23:34:25Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2020-01-14T00:09:19Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
```

/kind bug
/area clusterctl

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

Corrects the information shown in the `Type` and `Provider` columns of kubectl output

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3440 

/cc @wfernandes

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@ykakarap CAPI uses controller-tools for generating the CRD yaml, so you should not modify the YAML directly

You should modify the go code/annotations where the API types are defined [here](https://github.com/fabriziopandini/cluster-api/blob/1d8066c914165c6b0c5da09690bc3842030ce908/cmd/clusterctl/api/v1alpha3/provider_type.go#L27-L28) and then run make generate. Let me know if you need more clarification about how this works

**Comment by ykakarap** [comment]
@fabriziopandini thanks for the pointer. I made the fix and all the tests are now green.

/assign @fabriziopandini

**Comment by fabriziopandini** [comment]
/approve

@wfernandes PTAL

**Pull request merged**
