### PR TITLE
🌱 feat: make docker machine bootstrap timeout configurable

### LINKED ISSUE #9530: Increase timeout for bootstrapping docker machine
### What would you like to be added (User Story)?

As a user I would like to give more time to the Docker machine to bootstrap when not using CAPBK.

### Detailed Description

Currently, there is a 3 minute timeout for bootstrapping a Docker machine https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/internal/controllers/dockermachine_controller.go#L307. We are using CAPD to test RKE2 bootstrap provider and it might take more than 3 minutes for bootstrap to succeed. We would like this timeout to be increased or made configurable.

cc @richardcase 

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind feature
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by salasberryfin**
**What this PR does / why we need it**:

Currently, there is a 3 minute timeout for bootstrapping a Docker Machine. When not using CAPBK, it may take more than 3 minutes for bootstrap to succeed.

This PR adds a new optional field to `DockerMachineSpec`: `BootstrapTimeout`. When setting the timeout, it will default to 3 minutes if no value is set. 

**Which issue(s) this PR fixes**:
Fixes #9530 

/area provider/infrastructure-docker

### CODE REVIEW

**Comment by richardcase** [comment]
As **BootstrapTimeout** is a new field you'll need to restore its value when going from v1alpha4 back to v1beta1 for the fuzzy tests to pass.

What this means is that for **DockerMachine** you'll need to make the ConvertTo/ConvertFrom functions in [this](https://github.com/kubernetes-sigs/cluster-api/blob/main/test/infrastructure/docker/api/v1alpha4/conversion.go) similar to what is being done for **DockerCluster**....so store the marshalled version and then restore. I'll ping you on slack to chat.

**Comment by salasberryfin** [comment]
Thanks @richardcase. This is hopefully fixed now.

**Comment by salasberryfin** [comment]
@sbueringer thanks for the suggestions. Last push addresses both changes: setting type as `*metav1.Duration` and using a local variable.

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/approve

**Pull request merged**
