### PR TITLE
:seedling: drop pr approver workflow top-level permissions

### PR DESCRIPTION
**Pull request by tuminoid**
**What this PR does / why we need it**:

Set PR approver workflow top-level permissions to none. This is the best practice for GH actions, and for example OpenSSF Scorecards penalize CAPI for not having it.

/area ci

### CODE REVIEW

**Comment by sbueringer** [comment]
Does this workflow work without any permissions?

**Comment by tuminoid** [comment]
> Does this workflow work without any permissions?

Setting the job level permissions to `actions: write` already [drops all permissions from the job](https://docs.github.com/en/actions/using-jobs/assigning-permissions-to-jobs): `If you specify the access for any of these scopes, all of those that are not specified are set to none.` 

As described, this is merely a best practice improvement to explicitly drop them at top-level (ie. safe guards against adding another job without permissions = full access via top-level) and it makes security scanners happier. Foe example, [OpenSSF scorecard](https://securityscorecards.dev/viewer/?uri=github.com/kubernetes-sigs/cluster-api).

**Comment by sbueringer** [comment]
Ups, missed that we are adding the permission on the lower level

**Pull request merged**
