### PR TITLE
📖 Add IBM VPC environment variables

### PR DESCRIPTION
**Pull request by Amulyam24**
**What this PR does / why we need it**:
Adds VPC environment varibales for IBM Cloud provider in quick start.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Looks good for me, but would be good to get a review from someone who is familiar with the IBM provider as well.

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

But like @sbueringer I'm not familiar with the specifics of the IBM Cloud details.

**Comment by Amulyam24** [comment]
I have requested @Prajyot-Parab to review on behalf of IBM Cloud provider.

**Review by Prajyot-Parab — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve
/cherry-pick release-1.1

**Pull request merged**
