### PR TITLE
📖 Fix incorrect indents

### PR DESCRIPTION
**Pull request by zhangdb-git**
**What this PR does / why we need it**:
There is an incorrect indent in proposals.

**Which issue(s) this PR fixes** :
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@zhangdb-git I think our "verify PR contents" linter suggests you should use our regular PR template :)

**Comment by zhangdb-git** [comment]
@enxebre  @fabriziopandini  Could you review my PR ?

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
