### PR TITLE
Remove NodeConditions from Machine.Status

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR removes `Conditions` fields from `Machine.Status`. Only applies to v1alpha2 types.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
/lgtm
/hold

+1 from me considering the Node's Conditions and Addresses can be introspected by following the nodeRef.

holding to give time for additional feedback.

**Comment by ncdc** [comment]
+1. I know there was #950 (closed, unfixed) so we should probably discuss a solution for @jichenjc.

**Comment by detiber** [comment]
While #950 was closed/unresolved, The related PR stated that the getting the Addresses from the node was sufficient: https://github.com/kubernetes-sigs/cluster-api/pull/951#issuecomment-503371787

**Comment by rudoi** [comment]
+1 from me!

**Comment by akutz** [comment]
Is this because of the presence of NodeRef? And if so, will this be back ported to 1.5? CAPV does currently use the Machine's addresses as part of the workflow to indicate whether or not a machine is ready. In fact, this is critical since on-prem providers may not have a ControlPlaneEndpoint from an external load balancer, and thus the initial control plane machine's IP address(es) are used to determine the control plane endpoint.

**Comment by akutz** [comment]
Is this because of the presence of NodeRef? And if so, will this be back ported to 1.5? CAPV does currently use the Machine's addresses as part of the workflow to indicate whether or not a machine is ready. In fact, this is critical since on-prem providers may not have a ControlPlaneEndpoint from an external load balancer, and thus the initial control plane machine's IP address(es) are used to determine the control plane endpoint.

I'm adding a hold that anyone can cancel at any time. I just want to make sure that we understand the effects this may have on providers relying on those addresses. If we shouldn't be, then tell us why not, and what we should use instead. Thanks!

/hold

**Comment by ncdc** [comment]
This will not be backported.

If you need to know when a machine is "ready", we have machine.status.infrastructureReady in v1alpha2. This field flips to true only when the infrastructure provider decides this is appropriate.

If you need to know the apiserver's url... we'll need to continue to think about that.

**Comment by davidewatson** [comment]
I am not sure about this change and would like feedback from others who participated in the debate which introduced it (e.g. @hardikdr, @alvaroaleman, etc.).

0) Accessing `Node` heath is harder when there is indirection. Even with the `NodeRef` controller, https://github.com/kubernetes-sigs/cluster-api/pull/1052, this is non-trivial for a `kubectl` user.
1) Historically we have said that the `MachineSet` controller should not depend on `Nodes` directly. Instead, it should only depend on `Machines`. This PR would change that assumption.

# Notes

`Conditions` were added here: https://github.com/kubernetes-sigs/cluster-api/pull/483

At the time I remember there was a long discussion. Two reasons from the PR are https://github.com/kubernetes-sigs/cluster-api/issues/47 and https://github.com/kubernetes-sigs/cluster-api/issues/253 Looking at [last years meeting notes](https://docs.google.com/document/d/16ils69KImmE94RlmzjWDrkmFZysgB2J4lGnYMRN89WM/edit#heading=h.oc87g6fd6waj) on August 15th another reason was given: to avoid requiring the `MachineSet` controller to access remote `Node` resources. The general principle was that controllers should be able to be layered (i.e. `MachineDeployment` -> `MachineSet` -> `Machine` -> `Node`) and controllers at different layers should only depend on the layer immediately below.

**Comment by andrewsykim** [comment]
If the intent is to rely on Kubernetes Node addresses, there are some issues there worth considering:
* There can be multiple addresses of the same type and deciding which address to use for a given machine may not be trivial. Most consumers of node addresses will choose the first one, but the ordering of addresses is also subject to change. There are multiple bug reports of Kubernetes clusters on AWS breaking because the kubelet started to report addresses from ENIs that were not meant to be consumed by the kubelet. 
* The update mechanism for node addresses by the kubelet has some issues, the biggest one being that if it sees more than 1 address of the same type it can unintentionally merge the two, so the initial address chosen for the machine may not be the same over time and in some cases not exist at all. (see https://github.com/kubernetes/kubernetes/pull/79391 for more details)
* The machine address is now highly coupled to the cloud provider implementation.

**Comment by vincepri** [comment]
Let's add this item to next week's agenda and discuss on Zoom, if you all agree. 

One thing I'd like to point out is that both of these fields are unused in v1alpha1.

**Comment by ncdc** [comment]
Addresses may be used by providers (e.g. CAPV uses them).

**Comment by akutz** [comment]
> Addresses may be used by providers (e.g. CAPV uses them).

Currently refactoring that out, but it just opens up a broader issue related to how CAPI providers handle addressing versus the cloud providers for the same platform (as @andrewsykim noted).

**Comment by ncdc** [comment]
CAPI generally shouldn't need to communicate directly with a server, should it? Maybe if you're writing a provider that is trying to configure the server after it's been provisioned (post-boot bootstrapping instead of pre-boot)?

**Comment by akutz** [comment]
> CAPI generally shouldn't need to communicate directly with a server, should it? Maybe if you're writing a provider that is trying to configure the server after it's been provisioned (post-boot bootstrapping instead of pre-boot)?

It's less about CAPI and more about how there's not a good way, today in Kubernetes, to differentiate between addresses on a **host** that have nothing to do with Kubernetes. For example, an IPv4 address that is exclusively used for SSH. Should a cloud provider report that as a node address? Today there's no way to distinguish that address from any other address reported by the host.

And CAPI providers may also need to get IPs from a machine to do things like:
* Configure an LB's targets
* Determine the IP used by a guest as the API server endpoint (when there is no LB)

CAPV implements a field `PreferredAPIEndpointCIDR` to exclude reported addresses, such as the one in the above SSH example.

@andrewsykim and I have discussed how the address detection should be sync'd between CAPV and the vSphere CCM, because we're effectively faced with the same problem, and handling it in two different places.

It's an issue that extends beyond CAPI providers, and should likely be handled by CCMs. That way even CAPI providers can query the NodeRef for a node's addresses and be able to know which address is bound to which service on that node.

**Comment by alvaroaleman** [comment]
> At the time I remember there was a long discussion [...]

IIRC most of the discussion was around if we should have conditions on the machine itself as opposed to querying it directly from the Node object. The latter makes IMHO more sense, as we otherwise duplicate health check information.

>  It's an issue that extends beyond CAPI providers, and should likely be handled by CCMs

Yes. We currently use adresses to match instances to nodes on cloud providers that do not set the providerID, however this is an issue for cluster-autoscaler anyways so not really a solution going forward: https://github.com/kubermatic/machine-controller/issues/564

**Comment by dhellmann** [comment]
If we don't place addresses on the Machine, providers that need the addresses (bootstrapping, post-boot config, rebooting, etc.) will need to understand the CRDs for all providers in order to be able to take any action. So, I think we should keep the addresses where they are.

I also agree with @ncdc's comment from the meeting on 3 July that we should add compliance tests that ensure the infrastructure provider fills in the addresses when a Machine is created.

**Comment by vincepri** [comment]
@dhellmann For addresses, we can require Infrastructure providers to always specify address as part of their status and add a check in the Machine Controller. Other providers that need to use this field can use this repository's utilities to deal with unstructured objects. 

One thing I wanted to clarify about the `Conditions` field is that these are actually `NodeConditions` and shouldn't be confused with the conditions we discussed for handling phases later on.

**Comment by dlipovetsky** [comment]
The Machine resource has a complex lifecycle. Clients need to get insight into that lifecycle. For this, the [Kubernetes API conventions](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#typical-status-properties) recommend using Conditions.

From comments in #997, I understood that we _want_ to adopt Conditions, although we would wait for a follow-up proposal before adding support for them to the Machine controller. (I will add quotes from the PR to this comment)

If we want to adopt Conditions, I think it makes to keep the field around while we add support for them to the Machine controller.

**Comment by enxebre** [comment]
Conditions exists only post node creation and are merely a mirror of node conditions a so it seems reasonable to me to remove them and force everyone to consume the node as the source of truth. Addresses is a different case, they are legit pre-node existence and consumable by other pre-boot cluster api components or/and external tooling.

**Comment by ncdc** [comment]
Please note, this PR is suggesting we remove the `NodeConditions` (which happen to be called `Conditions`):

```go
// Conditions lists the conditions synced from the node conditions of the corresponding node-object.
	// Machine-controller is responsible for keeping conditions up-to-date.
	// MachineSet controller will be taking these conditions as a signal to decide if
	// machine is healthy or needs to be replaced.
	// Refer: https://kubernetes.io/docs/concepts/architecture/nodes/#condition
	// +optional
	Conditions []corev1.NodeCondition `json:"conditions,omitempty"`
```

**Comment by vincepri** [comment]
Also I would like to point out that the comment on `Conditions` is misleading given that the code doesn't actually ever use or update this field.

**Comment by akutz** [comment]
Hi @dhellmann,

> If we don't place addresses on the Machine, providers that need the addresses (bootstrapping, post-boot config, rebooting, etc.)

CAPV maintains the addresses in both locations for this reason. Placing them solely on the NodeRef fails to address the issue of IP addresses that may not be relevant to Kubernetes, but relevant to machine infrastructure. This is an issue that I've discussed with @andrewsykim quite a bit.

Today there are only five choices for a Kubernetes [`NodeAddressType`](https://godoc.org/k8s.io/api/core/v1#NodeAddressType):

```golang
type NodeAddressType string

const (
    NodeHostName    NodeAddressType = "Hostname"
    NodeExternalIP  NodeAddressType = "ExternalIP"
    NodeInternalIP  NodeAddressType = "InternalIP"
    NodeExternalDNS NodeAddressType = "ExternalDNS"
    NodeInternalDNS NodeAddressType = "InternalDNS"
)
```

I think the node address type should be a bit mask:

```golang
type NodeAddressType uint32

const (
	NodeAddrUnknown NodeAddressType = 0
	NodeAddrDNS NodeAddressType = 1 << iota
	NodeAddrIP4
	NodeAddrIP6
	NodeAddrInternal
	NodeAddrExternal
	NodeAddrAPIServer
	NodeAddrKubelet
	// and others
)
```

This way it will be possible to easily ascertain the purpose of an address associated with a node, whether it's meant for the API server, the Kubelet, some non Kubernetes service, the address family, etc.

**Comment by dlipovetsky** [comment]
> Please note, this PR is suggesting we remove the NodeConditions

Thanks for clarifying @ncdc. I overlooked that.

Since we would have to change the Conditions type from `corev1.NodeConditions` to something defined by CAPI itself, and that replacement type is not proposed yet, I am ok with removing Conditions in the interim, then adding Conditions back when needed.

**Comment by moshloop** [comment]
My concern would be around forcing a remote call for static or slow changing fields could introduce undefined or unwanted behavior when there are intermittent network issues, especially if these addresses are used for load balancers/endpoints.

**Comment by michaelgugino** [comment]
To chime in, we're using the addresses today in OpenShift.

Generally speaking, components external to cluster-api should be able to rely on machine-object as the source of truth.  We might need these addresses for any number of things (today we use internal hostname for CSR approval), and having to account for a proliferation of infra-providers seems unhelpful long term.

**Comment by detiber** [comment]
I'm +1 for removing the existing Conditions as documented (mirroring Node Conditions).

I'm now a -1 on Removing the Addresses. I think there has been sufficient cases made where the existing Node Addresses may not be sufficient.

**Comment by vincepri** [comment]
Would having `Addresses` in the Infrastructure Provider status field and some helper methods in CAPI to quickly parse unstructured objects be a possible alternative?

The upside is that we don't have to copy the status and deal with 2 source of truth.

**Comment by detiber** [comment]
> Would having Addresses in the Infrastructure Provider status field and some helper methods in CAPI to quickly parse unstructured objects be a possible alternative?

> The upside is that we don't have to copy the status and deal with 2 source of truth.

I would expect these addresses to only be set on create, especially since we have said that a failed instance should not be replaced by a Machine controller.

In general, if we expect an outside system to interact with it, then it should be a field on a known resource and not have to deal with unstructured.

**Comment by timothysc** [comment]
+0 on Addresses 

IMO I had thoughts of using conditions for the future states of the state machine.

**Comment by detiber** [comment]
> IMO I had thoughts of using conditions for the future states of the state machine.

No objections from me here, but the comment would need updating and we are still lacking a backing implementation to populate the field.

**Comment by vincepri** [comment]
Hey folks, given the received feedback, I went ahead and scoped down the PR to just remove NodeConditions and keep Addresses.

**Comment by hardikdr** [comment]
I am inclined towards keeping something-like Conditions in API. From UX PoV it helps in realizing the status of the machine `quickly` and probably could also be used for extension of machine-phases. 

Although we never really implemented the logic to populate this field so far, we might want to consider having it in the future. I think it does not have to be NodeConditions, it could be something generic, what we could also define. For now, I am happy with the current changes, thanks for the PR.

**Comment by detiber** [comment]
@hardikdr fully agree longer term that having Machine Conditions would be beneficial, but I'd also like to get away from having fields for unimplemented functionality.

**Comment by ncdc** [comment]
And again, to clarify, we do still have some "conditions" in the machine status: bootstrapReady and infrastructureReady. These are actively used in v1alpha2.

**Comment by vincepri** [comment]
Given that it has been 2 weeks and comments have slowed down on this PR, should we merge this change?

**Comment by ncdc** [comment]
I haven't seen any major disagreements in the comments for removing NodeConditions. Lazy consensus ftw.

/hold cancel
/lgtm

**Comment by ncdc** [comment]
Oh but you need to rebase 😄

**Comment by vincepri** [comment]
@ncdc Just rebased :)

**Pull request merged**
