### PR TITLE
🌱 ClusterClass: also consider MD unavailableReplicas for rollout

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@fabriziopandini @ykakarap WDYT would it make sense to also check unavailableReplicas for MD's like we're doing for control planes?

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
/hold
have to take a look if we should extend unit tests, once I know if we want to do this change

**Comment by fabriziopandini** [comment]
/lgtm
/approve

@sbueringer I think this is a nice improvement, let's get it merged if test grid is green

**Comment by sbueringer** [comment]
Sounds good

/test pull-cluster-api-e2e-full-main

I spent a few minutes later checking if we want to extend our unit tests a bit

**Comment by sbueringer** [comment]
@fabriziopandini Extended tests a bit. Should be ready now

/hold cancel

**Comment by fabriziopandini** [comment]
Thanks for the extensive work on testing, really appreciated!
/lgtm
/approve

**Pull request merged**
