### PR TITLE
:book: :seedling: Note macOS may need more memory.

### PR DESCRIPTION
**Pull request by davidewatson**
**What this PR does / why we need it**:
Otherwise CAPD quickstart failed on my Mac.

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
I had to do this too, so +1 from me, definitely a good addition

/lgtm

**Comment by randomvariable** [comment]
@fabriziopandini can you add an approve?

**Review by vincepri — APPROVED** [review]
/approve
/milestone v0.4

**Pull request merged**
