### PR TITLE
🌱 Add .PHONY for doctoc target

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Forgot to add this in my previous PR

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by killianmuldoon** [comment]
Looks like the other fix wasn't cherry-picked which is fine unless there's a reason to do so?

**Comment by sbueringer** [comment]
Sorry which other fix? This one? https://github.com/kubernetes-sigs/cluster-api/pull/9112

I think it's okay if we only ensure up-to-date TOC on main

**Pull request merged**
