### PR TITLE
🌱 Bump controller-gen to v0.15

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Bump to latest main for now (4th April)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of https://github.com/kubernetes-sigs/cluster-api/issues/10026

### CODE REVIEW

**Review by g-gaston — COMMENTED** [review]
lgtm

**Comment by sbueringer** [comment]
/hold

until CT v0.15 release (will take a bit :))

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
