### PR TITLE
🐛 test/e2e: Calculate correct worker count in clusterctl upgrade test

### LINKED ISSUE #9886: Timed out after 300.000s. Timed out waiting for all machines to be exist
### Which jobs are failing?

Failing:
- capi-e2e-dualstack-and-ipv6-main

Flaking:
- capi-e2e-main
- capi-e2e-mink8s-main

### Which tests are failing?

capi-e2e: [It] When testing clusterctl upgrades using ClusterClass (v1.6=>current) [ClusterClass] Should create a management cluster and then upgrade all the providers

### Since when has it been failing?

this fail started happening after the merge of this PR: https://github.com/kubernetes-sigs/cluster-api/pull/9799

### Testgrid link

https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-dualstack-and-ipv6-main
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-main
https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-mink8s-main

### Reason for failure (if possible)

need to investigate.

### Anything else we need to know?

_No response_

### Label(s) to be applied

/kind failing-test

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Since #9799 we are testing the upgrade from v1.6. In v1.6 we introduced support for MachinePools in ClusterClass.

Before this PR we assumed that the number of expected machines is controlPlaneMachineCount+workerMachineCount

With this PR we are now taking a closer look at Cluster / MachineDeployment / MachinePool objects to calculate the actual expected count.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9886

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Merging given lgtm above

/approve

**Pull request merged**
