### PR TITLE
:warning: Remove v1alpha4 API Version

### PR DESCRIPTION
**Pull request by killianmuldoon**
Remove the v1alpha4 version across the CAPI codebase.

/area api

Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8038

### CODE REVIEW

**Comment by vincepri** [comment]
@killianmuldoon are you rebasing this?

**Comment by killianmuldoon** [comment]
Thanks for the reminder @vincepri - I've rebased and this one is ready for review.

**Review by sbueringer — COMMENTED** [review]
A few more ideas:
* Let's drop cluster.x-k8s.io/v1alpha4: v1alpha4 in kustomization.yamls
* I guess it's time to get rid of `ExcludeNamespaces: []string{"capi-webhook-system"}, // this namespace has been dropped in v1alpha4; this ensures we are not waiting for deployments being deleted as part of the upgrade process`

I think otherwise we're good

**Comment by sbueringer** [comment]
Thank you very much!!

/lgtm
/approve

**Pull request merged**
