### PR TITLE
:book: Update cert manager version in migration doc

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Update cert manager version in the migration doc. Related to version bump in #7705

### CODE REVIEW

**Review by oscr — APPROVED** [review]
/lgtm

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
/hold 

For #7718 to merge.

**Review by ykakarap — APPROVED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
@ykakarap yeah I'll make sure it's reflected across the branches once we get the updates merged.

**Pull request merged**
