### PR TITLE
🏃‍♂️  Remove cmd/clusterctl/test folder

### LINKED ISSUE #2930: Remove cmd/clusterctl/test
With #2884 clusterctl is now tested by the CAPI e2e tests, so it is possible to remove e2e tests `under cmd/clusterctl/test`

/kind cleanup
/area clusterctl
/help
/good-first-issue

### PR DESCRIPTION
**Pull request by prankul88**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2930

### CODE REVIEW

**Comment by prankul88** [comment]
@fabriziopandini Deleting this folder would also delete the `go.mod` and `go.sum` files which are used by `make modules` command. Should I move these 2 files to `test/e2e` folder and add an option of `make modules` in  the Makefile there?

**Comment by prankul88** [comment]
@fabriziopandini `make modules` fail due to missing `CLUSTERCTL_E2E_DIR` https://github.com/kubernetes-sigs/cluster-api/blob/ba3bd5c095e0c7af6d39ff62a6bd77b8609722fe/Makefile#L326

**Comment by fabriziopandini** [comment]
@prankul88 you can drop this line and the declaration of the CLUSTERCTL_E2E_DIR variable

**Comment by prankul88** [comment]
@fabriziopandini PTAL

**Comment by fabriziopandini** [comment]
/approve

/assign @wfernandes @vincepri 
for final lgtm

**Comment by vincepri** [comment]
/retitle 🏃‍♂️  Remove cmd/clusterctl/test folder 
LGTM

**Comment by wfernandes** [comment]
Reviewing

**Comment by wfernandes** [comment]
@fabriziopandini I noticed that currently in `cmd/clusterctl/test` there is a `move_test.go` which we currently do not have in `test/e2e`. Is that currently being worked on?

**Comment by sedefsavas** [comment]
@wfernandes test/e2e/self_hosted_test.go is testing the move.

**Pull request merged**
