### PR TITLE
🌱 Update conversion-gen version (v0.23.1 -> v0.25.0)

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

Update conversion-gen version  (v0.23.1 -> v0.25.0).

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #6661

### CODE REVIEW

**Review by ykakarap — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
