### PR TITLE
[release-1.2] 🌱 Update kubebuilder envtest (1.25.2 -> 1.26.0)

### PR DESCRIPTION
**Pull request by aniruddha2000**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #7671

@kubernetes-sigs/cluster-api-release-team

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
Thanks for this @aniruddha2000!
For future reference you can use the cherry-pick bot to do this work automatically as here: https://github.com/kubernetes-sigs/cluster-api/pull/7717#issuecomment-1372078766

Some times it might not work and you'll have to open the PR manually, but it does save a good bit of the copy-past of cherry-picks :slightly_smiling_face:

**Comment by aniruddha2000** [comment]
@killianmuldoon thanks for the information. From future I will try to do it with bot first

**Comment by sbueringer** [comment]
@aniruddha2000 Just fyi. I changed "Fixes" to "Part of". Please only use "Part of" if a PR closes a sub-task of an issue. Otherwise GitHub closes the whole issue :)

**Pull request merged**
