### PR TITLE
Update minikube driver information

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

- Add link to minikube drivers page
- Recommend kvm2 instead of kvm as that is what the minikube folks recommend
- doc the "--vm-driver" parameter with an example

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note

```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by karan** [comment]
lgtm

(leaving slash for second reviewer)

**Comment by jessicaochen** [comment]
Looks great. Thanks!

/lgtm

**Pull request merged**
