### PR TITLE
🐛 capd: don't add host ports to exposed ports of containers

### PR DESCRIPTION
**Pull request by schrej**
This fixes an issue when running capd with podmans docker compatibility mode. And it's also incorrect in general.

**What this PR does / why we need it**:
CAPD currently adds the host ports that are part of a port mapping to the list of 'exposed ports' of the container. This is incorrect and leads to an error when using CAPD with podman, since capd sets the host port to 0 so an available port is automatically selected.

```
controller.go:324] "Reconciler error" err="failed to create load balancer: error creating container \"capi-quickstart-lb\": Error response from daemon: fill out specgen: port numbers must be between 1 and 65535 (inclusive), got 0" controller="dockercluster" controllerGroup="infrastructure.cluster.x-k8s.io" controllerKind="DockerCluster"

```

There is no specific documentation around this that I could find. The closest is this: https://github.com/moby/moby/issues/3039

This took way to long 😄 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by chrischdi** [comment]
Can you please add the error when using CAPD with podman in the description?

This helps to verify in future to verify if the same issue occurs again.

**Comment by schrej** [comment]
done

**Review by chrischdi — COMMENTED** [review]
/lgtm

I think this PR makes sense as is. Thanks @schrej !

Looks like podman is a bit more correct on its api / docker a bit more lazy :-)

**Comment by sbueringer** [comment]
Thx!

Looks good to me and tests are green so

/approve

**Pull request merged**
