### PR TITLE
🐛 fetch_ext_bins should cleanup the temp file after downloading it

### PR DESCRIPTION
**Pull request by MaXinjian**
$ make test
  $ ls -l /tmp/ | grep kubebuilder-tools
-rw-r--r--  1 root root 52352311 Nov 26 10:33 kubebuilder-tools-1.19.2-linux-amd64.tar.gz

Signed-off-by: Ma Xinjian <maxj.fnst@cn.fujitsu.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/lgtm
/approve

**Comment by vincepri** [comment]
/retitle 🐛 fetch_ext_bins should cleanup the temp file after downloading it

**Pull request merged**
