### PR TITLE
🌱 fix linting

### PR DESCRIPTION
**Pull request by apricote**
**What this PR does / why we need it**:

Fix linting issues that are currently causing test failures in unrelated PRs. Issues were introduced by #6395, but I don't understand why they did not fail the checks back then.

### CODE REVIEW

**Comment by stmcginnis** [comment]
/lgtm

Thanks!

**Comment by jackfrancis** [comment]
Thank you @apricote!

**Comment by sbueringer** [comment]
@apricote @CecileRobertMichon The issue wasn't caught in #6395 because the golangci-lint action was not run on the final PR. This was probably caused by the issue that we have to manually allow checks to run after each commit on PRs of new contributors.

**Comment by sbueringer** [comment]
I would suggest:
image

But I think the important ones are the linter actions if you prefer to not add the other ones

**Comment by CecileRobertMichon** [comment]
@sbueringer I made the first 4 required but PR Desc and PR Type don't seem to show up as their own status. Theoretically this should prevent tide from merging but looks like there might be a bug preventing this behavior from working as expected according to https://github.com/kubernetes/test-infra/issues/24921

**Comment by CecileRobertMichon** [comment]
I also found https://github.com/kubernetes/test-infra/pull/22630 which seems to be doing what we want but the follow-up PRs suggest it didn't fully work... @cpanato @dims any insight on how we can make our lint GH Action required for tide merge in the CAPI repo? We want to make sure tide doesn't merge the PR before the action even runs when the contributor is new and the action needs manual approval before it can run.

**Comment by cpanato** [comment]
> I also found [kubernetes/test-infra#22630](https://github.com/kubernetes/test-infra/pull/22630) which seems to be doing what we want but the follow-up PRs suggest it didn't fully work... @cpanato @dims any insight on how we can make our lint GH Action required for tide merge in the CAPI repo? We want to make sure tide doesn't merge the PR before the action even runs when the contributor is new and the action needs manual approval before it can run.

afaik you just need to make that check required in the repository and then prow will merge if all required checks are passing

**Pull request merged**
