### PR TITLE
[release-1.8] 🐛 Make KCP pre-terminate hook more robust

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Manual cherry-pick of #11161

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
No conflicts, just want to speed up the test process

/assign @neolit123 @chrischdi @fabriziopandini 

/hold
(so we just merge it after the PR against main merged)

**Review by neolit123 — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
Flake assessment:
* pull-cluster-api-e2e-mink8s-release-1-8 
  * Job: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/11164/pull-cluster-api-e2e-mink8s-release-1-8/1833464510954868736
  * One of our regular flakes: "tls: failed to verify certificate:"
* pull-cluster-api-e2e-release-1-8
  * Job: https://prow.k8s.io/view/gs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/11164/pull-cluster-api-e2e-release-1-8/1833464511009394688
  * Looks like a known flake: "No Control Plane machines came into existence."
  * I'm not sure what this is exactly, but I think it's very unlikely that it correlates with this PR as in this case the creation of the initial control plane fails.

Also going to retest here, but if we get the same results I would merge

/retest

**Comment by sbueringer** [comment]
/hold cancel

https://github.com/kubernetes-sigs/cluster-api/pull/11161 is merged

**Comment by sbueringer** [comment]
/override pull-cluster-api-e2e-release-1-8

Test failure is unrelated

**Pull request merged**
