### PR TITLE
 📖 Add intial Spot instances proposal

### PR DESCRIPTION
**Pull request by JoelSpeed**
**What this PR does / why we need it**:

Based off of the [google doc](https://docs.google.com/document/d/1naxBVVlI_O-u6TchvQyZFbIaKrwU9qAzYD4akyV68nQ) proposal that was shared at the end of February, I have created this proposal doc based off of the template explaining how Spot instances should be implemented across the three cloud providers; AWS, Azure, GCP.

Note, this proposal does not change anything within the cluster-api repository itself, but is hosted here so that the implementation of spot support across the cloud providers can be tracked centrally and implemented in a similar manner across each provider. The goal of this project is that support should feel the same in each of the providers.

I think I've included all the people who I discussed this with and gave feedback in the reviewers list, let me know if anyone else should be added

### CODE REVIEW

**Comment by fabriziopandini** [comment]
+1 from my side to get this work started.

**Comment by detiber** [comment]
/hold
holding for additional reviewers
/lgtm

**Comment by enxebre** [comment]
thanks @JoelSpeed 
/lgtm

**Pull request merged**
