### PR TITLE
🐛 Use nonroot user with id

### LINKED ISSUE #4046: Containers still run as root due to non-numeric user in Docker image
**What steps did you take and what happened:**

Deploying CAPI using `clusterctl init` on cluster with the following PSP:
```yaml
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: zz-minimal
  annotations:
    seccomp.security.alpha.kubernetes.io/allowedProfileNames: 'docker/default,runtime/default'
    seccomp.security.alpha.kubernetes.io/defaultProfileName:  'docker/default'
spec:
  privileged: false
  # Required to prevent escalations to root.
  allowPrivilegeEscalation: false
  # This is redundant with non-root + disallow privilege escalation,
  # but we can provide it for defense in depth.
  requiredDropCapabilities:
  - KILL
  - MKNOD
  - SETUID
  - SETGID
  # Allow core volume types.
  volumes:
  - 'configMap'
  - 'emptyDir'
  - 'projected'
  - 'secret'
  - 'downwardAPI'
  # Assume that persistentVolumes set up by the cluster admin are safe to use.
  - 'persistentVolumeClaim'
  hostNetwork: false
  hostIPC: false
  hostPID: false
  runAsUser:
    # Require the container to run without root privileges.
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  supplementalGroups:
    rule: 'MustRunAs'
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  fsGroup:
    rule: 'MustRunAs'
    ranges:
    # Forbid adding the root group.
    - min: 1
      max: 65535
  readOnlyRootFilesystem: false
```

Which enforces containers to run as non-root user still makes CAPI containers to not converge. This is despite having user defined in Dockerfile: https://github.com/kubernetes-sigs/cluster-api/blob/995597dc195324c5cd3ab95750f9eb9e8beda6c2/Dockerfile#L59

Events observed:
```
  Warning  Failed     10m (x5 over 11m)   kubelet            Error: container has runAsNonRoot and image has non-numeric user (nobody), cannot verify user is non-root
  Warning  Failed     10m (x6 over 11m)   kubelet            Error: container has runAsNonRoot and image will run as root
```

**What did you expect to happen:**
CAPI containers should not run as root and should converge.

**Anything else you would like to add:**
Downstream issue: https://github.com/kinvolk/lokomotive/issues/1265

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by shysank**
**What this PR does / why we need it**:

This pr updates the non root user from `nobody` to `nonroot` (with id). This is needed when pod security policies are enabled in the cluster to prevent containers from running as root.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4046

### CODE REVIEW

**Comment by shysank** [comment]
This is still in in WIP because, we'll need to update `gcr.io/kubebuilder/kube-rbac-proxy` to anything >= 0.7.0. The latest image available is `0.5.0`. There is some ongoing work [here](https://github.com/kubernetes-sigs/kubebuilder/issues/1785) to automatically build images base off of tags in https://github.com/brancz/kube-rbac-proxy. Will need to follow up on that.

**Comment by vincepri** [comment]
We should be able to use "nonroot" instead of nobody user id instead?

**Comment by shysank** [comment]
> We should be able to use "nonroot" instead of nobody user id instead?

It requires a numeric id. I tried with `nonroot`, and it still failed. It may work if we don't set user because it is already set in the base image. https://github.com/GoogleContainerTools/distroless/pull/375/files

**Comment by shysank** [comment]
Also verified `kube-rbac-proxy` where a similar thing is done https://github.com/brancz/kube-rbac-proxy/pull/86/files

**Comment by vincepri** [comment]
Got it, thanks for the explanation 👍 Let's maybe put that in a comment in the Dockerfile itself?

**Comment by vincepri** [comment]
@shysank Should we also change other Dockerfiles around?

**Comment by shysank** [comment]
Yeah, we'll need to do it for all the providers as well. But, only after we can get a new image of `kube-rbac-proxy`

**Comment by vincepri** [comment]
Got it, we should try to update at least the other Dockerfiles in this repository though?

**Comment by shysank** [comment]
There is only one for docker provider. But, it does not use the `distroless` image. I haven't checked it yet with psp enabled. I'll try it and see what happens.

**Comment by shysank** [comment]
Tired this locally, and found that we set `privileged:true` [here](https://github.com/kubernetes-sigs/cluster-api/blob/a5dee81b2b969732f8e2825d31a743ac8bfdfbe0/test/infrastructure/docker/config/manager/manager.yaml#L39) which fails when `psp` is enabled. I'm guessing it's probably to access the docker socket. Is it worth trying to make `capd` to use non root user since it's only going to be used for testing purposes? @vincepri

**Comment by fabriziopandini** [comment]
I'm ok with keeping CAPD as an exception (to be documented somewhere in the book)

**Comment by vincepri** [comment]
Yeah CAPD isn't meant to be used in production, and afaik there is no way around it because you need to volume mount the docker socket somehow

**Comment by vincepri** [comment]
@shysank Is this still a WIP?

**Comment by shysank** [comment]
> @shysank Is this still a WIP?

`kube-rbac-proxy` image was just recently published. I'll remove the wip once I update the image.

**Review by vincepri — APPROVED** [review]
/approve

@shysank Could you help opening issues or PRs in the providers repos?

**Pull request merged**
