### PR TITLE
🐛 clusterctl: support Windows paths in overridesFolder

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
We have ~ the same code in `newLocalRepository` apparently just never noticed that it's missing for `overridesFolder`

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @fabriziopandini 
No rush!

We don't necessarily need it for the KubeCon tutorial as we are not planning to use the overridesFolder. But who knows.

Might be good and straightforward to get into v1.2.3 anyway. I tested this change on Windows 11 and I think the risk is relatively low as its windows specific code

/cherry-pick release-1.2

**Comment by fabriziopandini** [comment]
Nice catch!
/lgtm
/approve

**Pull request merged**
