### PR TITLE
🌱  Change all references to master branch in docs to main branch

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: https://github.com/kubernetes-sigs/cluster-api/issues/3280

/hold

this should merge after the branch rename is done.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by neolit123 — COMMENTED** [review]
Btw, https://sigs.k8s.io/cluster-api/README.md is an example for a branchless URL to this repository. It does not work for raw links thought - e.g. a raw link to a text file.

For the kubernetes org, URLs are git.k8s.io.

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Pull request merged**
