### PR TITLE
⚠️ Adapt clusterctl to the new manifests format

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
Given that #3042 for v1alpha4 requires single controllers managing all namespaces, this PR removes from clusterctl all the code implemented for managing webhooks in a separated namespace.

NOTE: when we will implement v1alpha3 --> v1alpha4 upgrades, we should manage the proper cleanup of the webhook namespace as a special case (as well as other actions like converting the provider inventory according to the management cluster operator requirements).

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/milestone v0.4.0

/hold
for https://github.com/kubernetes-sigs/cluster-api/pull/3985 to merge

**Comment by fabriziopandini** [comment]
@vincepri @wfernandes 
I'm eager to cleanup clusterctl code before the management cluster operator work start, but also I'm starting to think that this specific cleanup could prevent us to use clusterctl v0.4.x to create a v1alpha3 cluster, and this could make more complex testing upgrades.
So I'm leaning toward to punt on this cleanup. opinions?
I will open an issue to discuss other cleanups (e.g. removing support for management groups).

**Comment by vincepri** [comment]
@fabriziopandini Shouldn't we download and use one of the latest releases of clusterctl on v0.3.x to generate v1alpha3 files?

**Comment by fabriziopandini** [comment]
@vincepri  in our E2E tests we are using clusterctl as a library for creating the management cluster, and if the library supports only v1alpha4 manifest it will be impossible to use our current machinery to test v1alpha3 --> v1alpha4

**Comment by wfernandes** [comment]
> to use clusterctl v0.4.x to create a v1alpha3 cluster

Hmm...I think i understand considering we have a non-goal in the caep to not support the installation of v1alpha3 providers using the operator and if clusterctl is going to be modified to rely on the operator, then the E2E cannot use clusterctl to deploy a v1a3 cluster.

Maybe instead we adapt the E2E framework to use a v1alpha3 manifest in `test/e2e/data/v1alpha3` to deploy the `cluster-api-components.yaml`
And if we decide to do something like this we should do the above first before cleaning up clusterctl.

**Comment by fabriziopandini** [comment]
/close
I'm going to open an issue to track this until we reach an agreement on how to make it possible to test v1alpha3 to v1alpha4

**Pull request closed without merging**
