### PR TITLE
[WIP] Do not merge - Test v1.19.1

### PR DESCRIPTION
**Pull request by fabriziopandini**
Hack for running E2E with a custom node image v1.19.1 (not yet available upstream)

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@vincepri E2E failures are now fixed (see https://github.com/kubernetes-sigs/cluster-api/pull/3600, now included in this PR as well), so

single version tests are passing with v1.19.1 
upgrade v1.18.2 --> v1.19.1 is passing

**Comment by vincepri** [comment]
Perfect thank you!

**Pull request closed without merging**
