### PR TITLE
feat(bootstrap): initialize variable out of for range

### PR DESCRIPTION
**Pull request by lsytj0413**
**What this PR does / why we need it**:

The variable **allowdGKs** should initialize out of for range, because it will never been modified in the loop, and doesn't have ref with special loop var.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by lsytj0413** [comment]
> /ok-to-test
> /lgtm
> 
> Was this causing a bug or is this just an optimisation?
> 
> Seems sensible to me

Just an optimisation。maybe i should remove the fix-prefix from the title？

**Comment by JoelSpeed** [comment]
> Just an optimisation。maybe i should remove the fix-prefix from the title？

SGTM

**Comment by lsytj0413** [comment]
> > Just an optimisation。maybe i should remove the fix-prefix from the title？
> 
> SGTM

done, PTAL

**Pull request merged**
