### PR TITLE
:seedling: [release-1.9] Update md link check for release-1.9

### PR DESCRIPTION
**Pull request by cahillsf**
**What this PR does / why we need it**:
following https://github.com/kubernetes-sigs/cluster-api/tree/main/docs/release/role-handbooks/ci-signal#setup-jobs-and-dashboards-for-a-new-release-branch

update the link check

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
/approve

**Review by Sunnatillo — COMMENTED** [review]
/lgtm

**Review by chandankumar4 — APPROVED** [review]
/lgtm

**Pull request merged**
