### PR TITLE
🐛 ClusterClass: fix reconciliation of MD delete

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Currently it is not possible to delete MachineDeployments via Cluster.spec.topology,
because the code in current state assumes that for an existing MachineDeployment there is still an entry in Cluster.spec.topology.workers.

This was introduced in https://github.com/kubernetes-sigs/cluster-api/pull/7231 and thus v1.2 and main is affected

Follow-up:
* [x] Open an issue to add integration or e2e test coverage: https://github.com/kubernetes-sigs/cluster-api/issues/7404

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by killianmuldoon** [comment]
Follow-up to have this covered in some e2e test, or maybe just an integration test would work.

**Comment by killianmuldoon** [comment]
Fix is working for me, it also fixes clusters in a bad state from an upgrade from v1.2.3. i.e. 
-> Delete machineDeploymentTopology in v1.2.3
-> See error in logs and failed deletion
-> Update CAPI controller to this PR
-> Topology properly reconciled
-> Adding and removing new MD topologies works as expected after this recovery.

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
I'll open an issue to extend the clusterclass changes e2e test to delete the MD we have at the end and verify that it's gone. Should be a straight-forward change and shouldn't even take longer, given that we have to delete the whole Cluster anyway.

**Comment by fabriziopandini** [comment]
Thanks for the quick fix, IMO this is worth an extra patch release sometime beginning next week
/lgtm
/approve

**Comment by sbueringer** [comment]
I'll open a cherry-pick PR

**Comment by sbueringer** [comment]
Thx @killianmuldoon for the additional testing!!

**Pull request merged**
