### PR TITLE
:seedling: Remove Kubeadm upstream v1beta1 types

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Remove Kubeadm v1beta1 types from the CAPI codebase. 

According to the [Kubeadm docs] "kubeadm v1.22.x and newer no longer support v1beta1 and older APIs, but can be used to migrate v1beta2 to v1beta3". CAPI no longer supportes v1.22 management clusters, and will not support v1.22 workload clusters with the release of CAPI v1.6.0.

Part of https://github.com/kubernetes-sigs/cluster-api/issues/8038

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/area provider/bootstrap-kubeadm

**Comment by killianmuldoon** [comment]
This PR contains https://github.com/kubernetes-sigs/cluster-api/pull/8997

I'll come back to it once that PR has been merged.

**Comment by sbueringer** [comment]
-2,5k would be nice

**Comment by killianmuldoon** [comment]
With this change CAPBK will fail hard if a Cluster of v1.15.0 or older is used - I wonder if we should reject this at the webhook level.

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
> With this change CAPBK will fail hard if a Cluster of v1.15.0 or older is used - I wonder if we should reject this at the webhook level.

I think this is something for the related issue around version validation across CAPI that is open since forever

**Comment by sbueringer** [comment]
nit: v1.15 itself would work

**Comment by killianmuldoon** [comment]
Agreed - I hope nobody's trying to use current CAPI with v1.14.0 and it would probably fail pretty hard in other cases anyway.

Cross-linking the other issue: https://github.com/kubernetes-sigs/cluster-api/issues/7010

**Comment by sbueringer** [comment]
> Agreed - I hope nobody's trying to use current CAPI with v1.14.0 and it would probably fail pretty hard in other cases anyway.
> 
> Cross-linking the other issue: #7010

Yup. We already have the same problem with 1.12 today :joy:

**Pull request merged**
