### PR TITLE
Fix json tags for API types

### PR DESCRIPTION
**Pull request by nikhita**
- Fix JSON tag format for `ValueFrom`
- Add `omitempty` json tag for `ProviderConfig`

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by xmudrii** [comment]
Looks good!

/assign @roberthbailey

**Comment by roberthbailey** [comment]
I believe that @pwittrock and I also fixed this in https://github.com/kubernetes-sigs/cluster-api/pull/494. 

@pwittrock - are you ok rebasing that PR on this change? If so, we could merge it so that it gets picked up in the last release that we cut before the kubebuilder switchover.

**Comment by roberthbailey** [comment]
(wrong button)

**Comment by nikhita** [comment]
Can someone add a lgtm again? :)

Looks like the closing + lgtm raced, prow only considers open PRs for adding the lgtm label.

**Pull request merged**
