### PR TITLE
🐛 Skipping cleanup unhealthy replicas when oldMSReplicas is lower than oldMSAvailableReplicas

### PR DESCRIPTION
**Pull request by Levi080513**
**What this PR does / why we need it**:

The cause of https://github.com/kubernetes-sigs/cluster-api/issues/8987 is that after MachineDeployment first scale down old MachineSets, `oldMSReplicas < oldMSAvailableReplicas`, and when MachineDeployment need to scale down old MachineSets in a further step, cleaning up unhealthy  replicas failed due to `oldMSReplicas < oldMSAvailableReplicas`=> `newReplicasCount > oldMSReplicas`, and the scaleDownOldMachineSetsForRollingUpdate method will not be executed.

https://github.com/kubernetes-sigs/cluster-api/blob/0cbde4a7d4189aaaac32580e335074467b6efc98/internal/controllers/machinedeployment/machinedeployment_rolling.go#L184-L236

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #
https://github.com/kubernetes-sigs/cluster-api/issues/8987

### CODE REVIEW

**Comment by enxebre** [comment]
thanks! it'd be nice to unit test `cleanupUnhealthyReplicas`, if that's not trivial we could extract the logic within the loop into its own function which receives the scale function as a parameter so  r.scaleMachineSet can be mocked in the unit.

**Comment by killianmuldoon** [comment]
I tried to recreate this with the same settings as above but couldn't. In my case all of the Machines were correctly scaled down. I wonder is there something else going on in this cluster that resulted in this issue.

I think the first thing that's needed is a test case to reproduce this.

**Comment by Levi080513** [comment]
`Before rolling update MachineDeployment, paused all old Machine by add annotation cluster.x-k8s.io/paused`
In this way, the scene where the problem occurred can be preserved.

There are two MachineSets in total
```
~ kc get machineset -n default
NAME                                                  CLUSTER                  REPLICAS   READY   AVAILABLE   AGE     VERSION
hw-sks-test-1.24.13-04-workergroup-556df7fff9xbkbgd   hw-sks-test-1.24.13-04   2          2       2           3d22h   v1.24.13
hw-sks-test-1.24.13-04-workergroup-79db8577bfxsfdd8   hw-sks-test-1.24.13-04   3          3       3           3d22h   v1.24.13
```

new MachineSet .spec.replicas=2 and .status.availableReplicas=2
```
~ kc get machineset -n default  hw-sks-test-1.24.13-04-workergroup-556df7fff9xbkbgd -ojson | jq .status.availableReplicas
2
~ kc get machineset -n default  hw-sks-test-1.24.13-04-workergroup-556df7fff9xbkbgd -ojson | jq .spec.replicas
2
```

old MachineSet  .spec.replicas=2 and .status.availableReplicas=3
```
~ kc get machineset -n default  hw-sks-test-1.24.13-04-workergroup-79db8577bfxsfdd8 -ojson | jq .spec.replicas
2
~ kc get machineset -n default  hw-sks-test-1.24.13-04-workergroup-79db8577bfxsfdd8 -ojson | jq .status.availableReplicas
3
```

the events for the MachineDeployment is this
```
Events:
  Type     Reason           Age                   From                          Message
  ----     ------           ----                  ----                          -------
  Normal   SuccessfulScale  51m                   machinedeployment-controller  Scaled MachineSet default/hw-sks-test-1.24.13-04-workergroup-556df7fff9xbkbgd: 0 -> 2
  Normal   SuccessfulScale  49m                   machinedeployment-controller  Scaled MachineSet default/hw-sks-test-1.24.13-04-workergroup-79db8577bfxsfdd8: 3 -> 2
  Warning  ReconcileError   2m56s (x62 over 49m)  machinedeployment-controller  when cleaning up unhealthy replicas, got invalid request to scale down default/hw-sks-test-1.24.13-04-workergroup-79db8577bfxsfdd8: 2 -> 3
```

In normal scenarios, old MachineSet replicas should be 1 at this time, but blocked by cleanupUnhealthyReplicas failure.
And this problem does not affect the final result, but it will slow down the speed of scaling down.

**Comment by Levi080513** [comment]
The occurrence of this problem is related to this PR https://github.com/kubernetes-sigs/cluster-api/pull/3434. When calculating the MachineSet status, we will calculate the deleting Machine together. This will result in oldMSReplicas < oldMSAvailableReplicas.

I tried adding ut, but found another problem. When oldMSReplicas < oldMSAvailableReplicas,
The result of `scaleDownOldMachineSetsForRollingUpdate` execution is also not accurate. Because we use availableMachineCount to calculate the number of replicas that need to be scaled down, this may cause the number of replicas to be scaled down to increase.
https://github.com/kubernetes-sigs/cluster-api/blob/ab50d0bc33ccaeb01bde978cd0d25e93efed95ba/internal/controllers/machinedeployment/machinedeployment_rolling.go#L264

**Pull request closed without merging**
