### PR TITLE
📖 Docs fix, duplicated ```yaml

### PR DESCRIPTION
**Pull request by mmahrouss**
Duplicated ```yaml at cert-manager-configuration

**What this PR does / why we need it**:

Fix yaml code section in docs

**Which issue(s) this PR fixes**:
None

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks for catching this! A couple of procedural issues:
Could you sign the CLA and add the "docs" symbol at the start of the title.

**Comment by mmahrouss** [comment]
@killianmuldoon Alright, done

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
