### PR TITLE
🐛 [release-1.5] docker: ignore kubeadm preflight check for FileContent--proc-sys-net-bridge-bridge-nf-call-ip6tables

### PR DESCRIPTION
**Pull request by chrischdi**
Manual cherry-pick of:
- #10938

/area provider/infrastructure-docker

### CODE REVIEW

**Comment by sbueringer** [comment]
Looks like we need the controller-gen fix

/lgtm
/approve

for this PR until then :)

**Comment by chrischdi** [comment]
Waiting for the following to merge for retest:

- #10945

**Comment by chrischdi** [comment]
Propably fails at conversion-verifier

**Pull request merged**
