### PR TITLE
🌱 ClusterClass: relax validation of MD variables overrides of opt variables

### LINKED ISSUE #7023: Relax validation for MachineDeployment's variables.overrides
**User Story**

As a user, I would like to use MachineDeployment's variable overrides with optional variables without being forced to define an empty value in top-level variables.

**Detailed Description**

Today MachineDeployment's variable overrides require a variable to value that exists in top-level variables.
However, this seems counter-intuitive when the variable is defined as optional/without a default value.

This issue is about relaxing validation rules to allow to set MachineDeployment's variable overrides without value in top-level variables if the variable is optional/without a default value.

**Anything else you would like to add:**

The only concern about this change is what happens if the variable definition change from optional to required? Does our validation detect this change and prevents it?

/kind feature
/triage accepted

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

I tested roughly:
* initially variable: required + Cluster: set on MD + set on top-level
* Cluster tried to unset top-level => validation error
* made variable optional > could set/remove it on MD and top-level arbitrarily
* tried to make variable required again > only worked after the top-level variable was set again

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7023

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @fabr

**Comment by sbueringer** [comment]
cc @fabriziopandini

**Comment by fabriziopandini** [comment]
/lgtm

@killianmuldoon PTAL when you have some time

**Review by killianmuldoon — COMMENTED** [review]
Looks good!

/lgtm

**Comment by sbueringer** [comment]
Thx!

/approve

**Pull request merged**
