### PR TITLE
:book: default GOPROXY if not set when building mdbook preprocessors

### LINKED ISSUE #3658: Book preview does not render tabs
**What steps did you take and what happened:**
If I open the preview of the Cluster API book at https://master.cluster-api.sigs.k8s.io/user/quick-start.html is does not see tabs:
Screenshot 2020-09-17 at 14 53 10

**What did you expect to happen:**
To see tabs, like I can see when I run `make serve-book`:
Screenshot 2020-09-17 at 14 50 19

**Anything else you would like to add:**
From a quick look at the HTML, the web site at master.cluster-api.sigs.k8s.io does not apply transformations to {{tabs}}{{tab}} directives at all, so most probably there is some problem in the site generation part, not in the page source. 

/kind bug
/area documentation

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Attempts to fix the book build

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3658

### CODE REVIEW

**Comment by sedefsavas** [comment]
Test failure is unrelated. Just need to add a quote  `GOPROXY="${GOPROXY:-"https://proxy.golang.org"}"`, then lgtm.

**Comment by detiber** [comment]
@sedefsavas thanks, fixed up the shellcheck complaints

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
