### PR TITLE
🏃dependencies: update controller-runtime to v0.5.2 and controller-tool to v0.2.8

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
- update dependencies: update controller-runtime to v0.5.2 and controller-tool to v0.2.8
- update manifests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
 - Fixes https://github.com/kubernetes-sigs/cluster-api/issues/2787

### CODE REVIEW

**Comment by JoelSpeed** [comment]
@cpanato How do you feel about squashing this into one commit? Otherwise happy to LGTM

**Comment by cpanato** [comment]
@JoelSpeed done :)

**Comment by JoelSpeed** [comment]
/lgtm

Thanks @cpanato

**Pull request merged**
