### PR TITLE
:bug: Allow KCP spec.version to be mutable

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
/assign @chuckha @ncdc @detiber 
/milestone v0.3.0

### CODE REVIEW

**Comment by ncdc** [comment]
2 things:
1. Let's make sure we have a test case for this?
1. We need to sort the expected & actual strings in the `TestPaths` to avoid flakes (since we're ranging on map keys)

**Comment by vincepri** [comment]
@ncdc Flake is being fixed in https://github.com/kubernetes-sigs/cluster-api/pull/2583

**Comment by chuckha** [comment]
+1 to adding a test case. We aren't explicitly checking that version is allowed to change in the update tests right now.

**Pull request merged**
