### PR TITLE
🌱 Bump kpromo to 3.4.4

### LINKED ISSUE #6454: Remove empty digests workaround from promote-images target
Once https://github.com/kubernetes-sigs/promo-tools/issues/546 is fixed, we should remove `--digests ""` from the `promote-images` Makefile target.

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6454

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

(But I'm not able to give it a test run)

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
