### PR TITLE
📖 Move release timeline docs

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

This doc is outdated since the timeline has passed, 1.3 is released and we're currently working on 1.4.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Should we really drop this doc? AFAIK Kubernetes keeps the old ones. 

I think it could be interesting to keep, while it doesn't really hurt to keep.

**Review by killianmuldoon — COMMENTED** [review]
> would prefer to keep it as it makes it easier to lookup what we did in previous releases

Agreed - but maybe we should add a note to the top that the doc is archived as the release cycle has been completed? Might be useful for someone looking at release details and picking the wrong doc.

**Comment by oscr** [comment]
My main goal was just to get old information out of the way. But if we use Kubernetes as a reference they have a `releases/release-version` folder structure. [Example](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.25) containing release notes-draft, release team, timeline etc. That would both maintain the information and make it clear it's not current.

**Comment by sbueringer** [comment]
Sounds good to me!

**Comment by elmiko** [comment]
i think it's nice to have the old release notes, but agree we should do something to make sure that users know they are for previous releases.

**Comment by oscr** [comment]
I've moved the release-docs into a `releases` folder, and if it's of interest I could add older releases such as `1.2` to get more historic coverage. Yes/No?

Looking at the [Kubernetes release repo](https://github.com/kubernetes/sig-release/tree/master/releases/release-1.25) they additionally have a folder structure and OWNERS files which I assume is to enable release notes work. I don't think it's needed now but worth considering. However this brings us to the question of [user and provider implementers release notes](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#add-docs-to-collect-release-notes-for-users-and-migration-notes-for-provider-implementers).

Today the changes docs are in `docs/book/src/developer/providers/`. However I suggest moving the following docs

* v0.3-to-v0.4.md
* v0.4-to-v1.0.md
* v1.0-to-v1.1.md
* v1.1-to-v1.2.md
* v1.2-to-v1.3.md
* v1.3-to-v1.4.md

To for example `docs/CHANGELOGS` and making a for the current release adding two sections: users and provider implementers. This makes it easy to keep track and edit both.

cc @joekr @VibhorChinda @sayantani11 Please feel free to jump in here.

**Comment by sbueringer** [comment]
> I could add older releases such as 1.2 to get more historic coverage. Yes/No?

I think 1.3 + 1.4 is fine. Creating the historic information is just a lot of work that we don't necessarily need.

> Today the changes docs are in docs/book/src/developer/providers/

In general no objection to move things around. But I would prefer that those docs are still part of the book (I think they don't have to be part of the book folder for that though, see CONTRIBUTING.md).

> To for example docs/CHANGELOGS and making a for the current release adding two sections: users and provider implementers. This makes it easy to keep track and edit both.

First of all. I wonder if we should discuss this on a separate issue and merge the current PR as is. Just feels more appropriate to discuss it on an issue where it's more visible to other folks who might want to chime in.

I think we're getting to an interesting point. Essentially we have two docs: one for provider authors one for users. And then we have the difference between those docs being in a draft state or final (or maybe we don't want to distinguish, but I definitely see a difference between the user doc where we would add notes over time and then the final release notes on the release).

So I think we might want a bigger discussions about:
* how do we collect information, e.g.
  * add them to docs as part of the PRs making the change
  * putting them in some way in the PR description so they can be automatically pulled from there
* where do we want to publish the final release notes:
  * on the GitHub release
  * in docs/CHANGELOG or CHANGELOG like Kubernetes (they then link from a release to the doc)
* how to we distinguish between draft and final state

**Comment by elmiko** [comment]
subdir seems like a nice easy solution, i'm ok with this.

**Review by ykakarap — COMMENTED** [review]
The subdirectory seems okay.

Regarding having changelogs (release notes specifically) in a folder, I would like to mention that this will happen as a result of the release automation process (the current proposal that we are working on). 
With the new release automation process we are going to propose that the release team open a PR that adds the release notes and this will be used as a trigger for the whole release automation pipelines. Therefore we will end up with release notes markdown files in these folders. (Exact folder structure is TBD.)

Lets move further discussion on this to a dedicated issue.

**Comment by oscr** [comment]
As recommended I have created a separate issue to capture the discussion about user and provider implementers release notes: #8051

**Comment by oscr** [comment]
@sbueringer Yes. Thank you! :+1:

**Pull request merged**
