### PR TITLE
🌱Add leases to leader election role in operator

### PR DESCRIPTION
**Pull request by alexander-demichev**
**What this PR does / why we need it**:

Add leases to leader election role in operator. Similar to what is done here https://github.com/kubernetes-sigs/cluster-api/blob/master/config/rbac/leader_election_role.yaml#L34

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
/lgtm

**Review by JoelSpeed — APPROVED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Comment by vincepri** [comment]
🎉 @k8s-ci-robot is setting milestones correctly now

**Pull request merged**
