### PR TITLE
Revert "Replace openssl with client-go/util libraries for cert generation"

### PR DESCRIPTION
**Pull request by rsdcastro**
Reverts kubernetes-sigs/cluster-api#144

### CODE REVIEW

**Comment by krousey** [comment]
/hold
Are you reverting 2 PRs here?

**Comment by rsdcastro** [comment]
This reverts 2 commits (but a single PR).

**Comment by krousey** [comment]
Yea, I'm curious about the second commit. "Revert "machinedeployment boilerplate and remove internalversion dir"

**Comment by rsdcastro** [comment]
I'll close this out as I got this fixed in a different PR.

/close

**Pull request closed without merging**
