### PR TITLE
:book: docs/tilt: fix duplicate key in tilt-provider.yaml

### PR DESCRIPTION
**Pull request by bengentil**
Signed-off-by: Benjamin Gentil <benjamin.gentil@infomaniak.com>

**What this PR does / why we need it**: this fixes a duplicate key in the `tilt-provider.yaml` example

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by stmcginnis** [comment]
/lgtm

Test failures don't appear to be related: `Error: failed: No matching PR type indicator found in title.`

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
