### PR TITLE
Test updating gitbook.

### PR DESCRIPTION
**Pull request by davidewatson**
**What this PR does / why we need it**:

Updates GitBook to match latest API changes.

**Release note**:
```release-note
Updated GitBook.
```

### CODE REVIEW

**Comment by davidewatson** [comment]
None of our CI checks will pass for the `gh-pages` branch...
/hold

**Comment by detiber** [comment]
@davidewatson I believe prow will still apply the old config for existing PRs, a new PR would need to be created to trigger the new config.

**Comment by vincepri** [comment]
That worked 😄

**Comment by vincepri** [comment]
Seems the gh-pages branch needs a OWNERS file, otherwise we can't approve.

**Comment by detiber** [comment]
@vincepri I just merged an OWNERS file into the gh-pages branch, it should work now.

**Comment by vincepri** [comment]
@davidewatson might need a rebase

**Comment by detiber** [comment]
oops, it also needs the OWNER_ALIASES file, I'll fix

**Comment by detiber** [comment]
@davidewatson It looks like this is all net-new, is this currently being reformatted for the docs subdirectory workflow?

**Comment by davidewatson** [comment]
After talking to @BenTheElder I learned that kind and kubebuilder recently switched to using netlify so I don't think there is any reason for us to use firebase anymore. Instead, I think the gh-pages branch should be deleted after we complete the following:

>- to get decent community owned domains the sites need to be under the main docs team on netlify which "owns" those as far as netlify is concerned (k8s.io and kubernetes.io), because of this a restricted netlify maintainers team should have access.
>- subprojects can request a site, for which the following will be done as one-time setup:
>-- create a netlify site, pointed at the source repo
>-- enable image asset optimization from the netlify UI, as without this you don't get reasonable caching headers for images, and this seems to not be configurable in `netlify.toml`
>-- configure the site domain to foo.sigs.k8s.io
>
>To do this one of the netlify maintainers needs to temporarily be made an owner of the repo under question.
>
>- the subproject from that point on can configure the rest in `netlify.toml` [1] without any access to the netlify site, it should be hands off rom this point
>
>[1]: https://www.netlify.com/docs/netlify-toml-reference/ (edited) 

https://kubernetes.slack.com/archives/C1J0BPD2M/p1550730915035500

**Comment by BenTheElder** [comment]
FWIW that roughly outlines my upcoming proposal for how to solve this based on our current experiments, I do not have the authority to say this is definitely what will be supported 😅

I'm pretty hopeful it will be however, expect follow up on that this coming week.

**Comment by davidewatson** [comment]
@vincepri: Yes. We can use https://github.com/kubernetes-sigs/cluster-api/issues/655 since netlify also provides continuous deployment.

/close

**Pull request closed without merging**
