### PR TITLE
🌱 Bump controller-runtime to v0.16.3

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Should these bumps be taken care of by dependabot now if we give it time?

/lgtm
/approve 

/hold

**Comment by killianmuldoon** [comment]
(Feel free to remove hold)

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks @sbueringer!

/lgtm

**Pull request merged**
