### PR TITLE
🌱 Separate schema and CEL errors in CC variable validation

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
The main goal of this PR is to minimize the diff to the upstream k/k implementation. This makes it less error-prone to keep up-to-date with changes in k/k.

Additionally this has the benefit that errors in CEL don't block additional CEL or schema validation.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lg

**Review by fabriziopandini — COMMENTED** [review]
Nice!
/lgtm
/approve

**Pull request merged**
