### PR TITLE
:running: Add Cecile to reviewer list

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
@CecileRobertMichon expressed interested in getting more involved in Cluster API PR reviews. Let's make that happen :)

### CODE REVIEW

**Comment by detiber** [comment]
+1 from me
/hold
hold added for lazy consensus

**Comment by randomvariable** [comment]
+1

**Comment by chuckha** [comment]
+1!

**Comment by nader-ziada** [comment]
+1

**Comment by vincepri** [comment]
/hold cancel

We're past the usual 7-day period, I think we can probably merge this after the community meeting today, and congrats to @CecileRobertMichon !

**Comment by ncdc** [comment]
/lgtm
🎉

**Pull request merged**
