### PR TITLE
🌱 condition: fix godoc for MachineNodeHealthyCondition

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

We do not check `NodeNetworkUnavailable`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Follow-up of https://github.com/kubernetes-sigs/cluster-api/pull/11145#discussion_r1756583001

### CODE REVIEW

**Comment by sbueringer** [comment]
@fabriziopandini 

I think this PR should be merged in any case. Our implementation simply doesn't check `NodeNetworkUnavailable`, so it makes sense that our documentation matches that.

I have absolutely no clue if we should check the `NodeNetworkUnavailable` condition going forward, probably would require some additional research. And I would see it orthogonal to all ongoing efforts.


/lgtm

**Comment by chrischdi** [comment]
> I have absolutely no clue if we should check the `NodeNetworkUnavailable` condition going forward, probably would require some additional research. And I would see it orthogonal to all ongoing efforts

Wild guess: maybe not necessary because its part of Ready

**Comment by chrischdi** [comment]
I tried to look it up, the comment was added in:

- #3890

But the condition is only mentioned on the comment.

**Comment by fabriziopandini** [comment]
/lgtm
/approve

Added a note about NodeNetworkUnavailable in https://github.com/kubernetes-sigs/cluster-api/issues/11105

**Pull request merged**
