### PR TITLE
🌱 [release-1.6] Promote chrischdi to Cluster API maintainer

### PR DESCRIPTION
**Pull request by chrischdi**
Manual cherry-pick of #9997

/area community-meeting

/assign sbueringer 

/cherry-pick release-1.5

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Q: Is the owners file branch specific? i.e do you not have approve rights on release-1.6 currently?

I wasn't aware we had to update older branches like this.

/lgtm
/approve
/hold

**Comment by chrischdi** [comment]
> Q: Is the owners file branch specific? i.e do you not have approve rights on release-1.6 currently?
> 
> I wasn't aware we had to update older branches like this.
> 
> /lgtm /approve /hold

Hmm good question 🤔 cc @sbueringer I thought this was required 😂

**Comment by killianmuldoon** [comment]
I hope it's not - otherwise we should really be doing this on all branches - even ones that are completely out of date IMO.

**Comment by sbueringer** [comment]
> I hope it's not - otherwise we should really be doing this on all branches - even ones that are completely out of date IMO.

Prow takes the OWNERS files from the branch you want to merge into. It has to, the folder structure could be entirely different.

In my opinion it's good enough to backport into active branches. There are still a lot of folks around who have approval rights on very old branches.

In any case. We have enough permissions on the repo, we can merge in every branch we want if necessary.

**Comment by sbueringer** [comment]
/lgtm
/approve
/hold cancel

@chrischdi Feel free to prove it by trying to approve the release-1.5 cherry-pick :D

**Pull request merged**
