### PR TITLE
⚠️ [cleanup] move version package from cmd to version/

### LINKED ISSUE #2823: Move `version` package from cmd
As we're starting to use `version` package in controllers too, we should move the package from `cmd/version` to somewhere more suitable.

ref: https://github.com/kubernetes-sigs/cluster-api/pull/2814#discussion_r400257654

/kind cleanup

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
- move version package to a more generic location

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2823

### CODE REVIEW

**Comment by vincepri** [comment]
Do we need this under `util`? What about just having it as a top level package?

**Comment by nader-ziada** [comment]
> Do we need this under `util`? What about just having it as a top level package?

util was just the only 'generic' kind of place, top level is also good I guess

**Comment by nader-ziada** [comment]
> Do we need this under `util`? What about just having it as a top level package?

what do you think about creating a `pkg` folder then putting version under?

**Comment by vincepri** [comment]
Just `cluster-api/version` should be ok

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
