### PR TITLE
🌱 Add ownerRefs to BootstrapConfig/InfraMachinePool in classy Clusters

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Thought about this for a bit. I think it makes sense to do the same as in the MD case.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #5991

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Definitely makes sense to me.

/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/area clusterclass

**Comment by sbueringer** [comment]
/assign @chrischdi 

@killianmuldoon Would it be fine to merge after Christian reviewed it as well? Or do you think we should get Fabrizio's review?

**Comment by killianmuldoon** [comment]
>Or do you think we should get Fabrizio's review?

I'm not fully read into the context here - was there some decision made about this in some of the other MachinePool ClusterClass PRs?

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
One nice addition - I see it's already a follow-up on https://github.com/kubernetes-sigs/cluster-api/issues/5991 would be to add ownerRef validation for MachinePools in e2e.

**Comment by sbueringer** [comment]
> I'm not fully read into the context here - was there some decision made about this in some of the other MachinePool ClusterClass PRs?

I intentionally didn't include it in the first PR because I wanted to think about it some more. Apart from that nobody has any MP-specific context :)

**Pull request merged**
