### PR TITLE
🐛 MHC sort mhc status targets to avoid status keep changing

### LINKED ISSUE #3997: MachineHealthCheck status targets keep changing
**What steps did you take and what happened:**
MachineHealthCheck Status targets machines names are not in order, cause continuous reconciliation of MHC

```
status:
  targets:
  - vs-static-cp-6kpcb
  - vs-static-workerpool1-vsan-cluster-6fc449df6f-qsld2
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-ztw88
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-phlrw
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-8znsm
```

then seconds later:
```
status:
  targets:
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-phlrw
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-8znsm
  - vs-static-cp-6kpcb
  - vs-static-workerpool1-vsan-cluster-6fc449df6f-qsld2
  - vs-static-workerpool1-vsan-cluster-cc7bffc69-ztw88

```

**What did you expect to happen:**

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: v0.3.11
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by jzhoucliqr**
**What this PR does / why we need it**:

cherry-pick #3998 to master

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3997

### CODE REVIEW

**Comment by vincepri** [comment]
Could we add a simple test?

**Comment by fabriziopandini** [comment]
lgtm pending test implementation as per @vincepri comment

**Comment by vincepri** [comment]
@jzhoucliqr Do you have some time to write up a simple unit test?

**Comment by jzhoucliqr** [comment]
@vincepri sorry for the delay. will add soon.

**Pull request merged**
