### PR TITLE
🏃Minor fix for MachinePool kubebuilder rbac tag

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
This PR removes `exp.infrastructure.cluster.x-k8s.io` from machine pool rbac. Should be `exp.cluster.x-k8s.io` instead.

### CODE REVIEW

**Comment by vincepri** [comment]
/hold 

I think it should be both, because MachinePool implementations might refer to experiments in infrastructure provider, like CAPZ

@CecileRobertMichon can you confirm?

**Comment by CecileRobertMichon** [comment]
> I think it should be both, because MachinePool implementations might refer to experiments in infrastructure provider, like CAPZ

Correct, see https://github.com/kubernetes-sigs/cluster-api/pull/2959. cc @devigned

**Comment by sedefsavas** [comment]
Makes sense, didn't think about providers. Thanks!

**Pull request closed without merging**
