### PR TITLE
📖 Add machine infra provider spec doc

### LINKED ISSUE #1725: Add specification document for machine infrastructure provider
We should add a specification document for what a machine infrastructure provider must do. For example, something like:

- A machine infrastructure provider must provide a CustomResourceDefinition to represent provider-specific details for machine infrastructure. For example, if your provider is Acme, a reasonable name for the CRD might be AcmeMachine.
- The CRD must have spec and status
- The CRD's status must have the following fields
    - Ready
    - ...
- A machine infrastructure provider must reconcile its custom resources
    - ... Define required behaviors ...

etc.

/kind documentation
/priority important-soon
/milestone v0.3.0

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Add a specification document containing the required data model and
behaviors for machine infrastructure providers.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1725 

/kind documentation
/milestone v0.3.0
/priority important-soon

### CODE REVIEW

**Comment by detiber** [comment]
/lgtm
/hold
hold to allow @vincepri to finish reviewing

**Comment by vincepri** [comment]
@ncdc needs rebase

**Comment by ncdc** [comment]
Rebased

**Pull request merged**
