### PR TITLE
🌱 Bump opentelemetry to fix CVEs

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
xref: https://github.com/kubernetes-sigs/cluster-api/actions/runs/6849669132/job/18622320776

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks for noticing and fixing it ahead of rc release

/lgtm

Edit: looks like we need additional changes in go code to comply with new version of otelgrpc

**Review by furkatgofurov7 — COMMENTED** [review]
/area dependency
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
