### PR TITLE
🌱 Release v1.5.3

### PR DESCRIPTION
**Pull request by g-gaston**
/area release

### CODE REVIEW

**Review by furkatgofurov7 — COMMENTED** [review]
@g-gaston looks good, we should re-generate notes once again to add missing commit(s) that went in after PR was up. As is now, 8a5085942969291b7fb4c6814fce68df4fc7fed0 is missing.

**Comment by g-gaston** [comment]
> @g-gaston looks good, we should re-generate notes once again to add missing commit(s) that went in after PR was up. As is now, [8a50859](https://github.com/kubernetes-sigs/cluster-api/commit/8a5085942969291b7fb4c6814fce68df4fc7fed0) is missing.

Done!

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by killianmuldoon** [comment]
@g-gaston can you retitle this to fit the older release PR style?

**Review by furkatgofurov7 — APPROVED** [review]
/approve
/hold

**Pull request merged**
