### PR TITLE
🌱 Bump autoscaler to v1.28.0

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Ups forgot to run e2e-full. Let me know if CI breaks :D

**Comment by sbueringer** [comment]
First run after merge: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1697533477378854912

**Comment by killianmuldoon** [comment]
Do we want this in release-1.5?

**Pull request merged**
