### PR TITLE
🐛Change CI bucket for conformance tests to the non-bazel build

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
This PR changes the conformance test CI bucket because bazel build is removed recently https://github.com/kubernetes/kubernetes/pull/99561

This was causing conformance tests to fail on the master branch: https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2280

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-aws/issues/2280

### CODE REVIEW

**Comment by sedefsavas** [comment]
cc @randomvariable @nader-ziada

**Comment by fabriziopandini** [comment]
@sedefsavas pull-cluster-api-verify is failing. please run `make generate-bindata`

**Review by vincepri — APPROVED** [review]
/approve
/lgtm
/milestone v0.4.0

**Pull request merged**
