### PR TITLE
✨ MHC external remediation

### LINKED ISSUE #3848: Forward-port MHC external remediation to main branch
**Detailed Description**

PR [3606](https://github.com/kubernetes-sigs/cluster-api/pull/3606) implemented External Remediation proposal [3190](https://github.com/kubernetes-sigs/cluster-api/pull/3190). Feature was added to release-0.3 branch. We need to forward-port this to main branch after v1alpha4 PR goes in.

/kind feature

### PR DESCRIPTION
**Pull request by arghya88**
**What this PR does / why we need it**:
This PR implements External Remediation proposal #3190
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3848

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@jan-est PTAL

**Comment by jan-est** [comment]
looks good to me

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
