### PR TITLE
:bug: test/framework isDockerCluster should check that infra ref is present

### PR DESCRIPTION
**Pull request by vincepri**
**What this PR does / why we need it**:

```
 sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).isDockerCluster(0x1400079a100?, {0x10232c318, 0x140007a8960}, {0x14000a28618, 0x17}, {0x14000764170, 0xc})
        /Users/vincepri/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.8.0-rc.0/framework/cluster_proxy.go:481 +0x200
    sigs.k8s.io/cluster-api/test/framework.(*clusterProxy).GetWorkloadCluster(0x14000399ea0, {0x10232c318, 0x140007a8960}, {0x14000a28618, 0x17}, {0x14000764170, 0xc}, {0x0, 0x0, 0x0})
        /Users/vincepri/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.8.0-rc.0/framework/cluster_proxy.go:358 +0x20c
    sigs.k8s.io/cluster-api/test/framework.DumpAllResourcesAndLogs({0x10232c318, 0x140007a8960}, {0x10233ce58, 0x14000399ea0}, {0x14000567540, 0x5a}, 0x140007a6160, 0x14000a3a820)
        /Users/vincepri/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.8.0-rc.0/framework/spec_helpers.go:77 +0x3a0
    sigs.k8s.io/cluster-api/test/framework.DumpSpecResourcesAndCleanup({0x10232c318, 0x140007a8960}, {0x101928048, 0xb}, {0x10233ce58, 0x14000399ea0}, {0x14000567540?, 0x10364f0e0?}, 0x140007a6160, 0x14000595c70, ...)
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thx!

/cherry-pick release-1.8

**Pull request merged**
