### PR TITLE
:seedling: kubernetesversions: Add option to inject CI artifacts into a KubeadmConfig for a MachinePool

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
/assign @fabriziopandini

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
It will be great to have a test using this code in CAPI soon, so we can validate these changes locally before they are picked up by providers.

**Comment by randomvariable** [comment]
@fabriziopandini 

Yup. I need to fix up what I had in https://github.com/kubernetes-sigs/cluster-api/pull/3593, should be ready early next week.

**Pull request merged**
