### PR TITLE
Verify boilerplate

### PR DESCRIPTION
**Pull request by ingvagabund**
**What this PR does / why we need it**: The PR adds hack/verify_boilerplate.py which verifies all relevant files has properly specified boilerplate.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**: `make verify` to run the boilerplate verification

**Release note**:

```release-note
None
```

### TODO

**have the generators generate the boilerplate as well**:
  * [x] - https://github.com/kubernetes-sigs/cluster-api/pull/367
  * [x] - https://github.com/kubernetes-sigs/cluster-api/pull/371

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by roberthbailey** [comment]
Is `verify_boilerplate.py` a copy of https://github.com/kubernetes/kubernetes/blob/master/hack/verify-boilerplate.sh? Are you concerned about keeping it in sync with the source version should that one change?

**Comment by roberthbailey** [comment]
lgtm

**Comment by ingvagabund** [comment]
> Is verify_boilerplate.py a copy of https://github.com/kubernetes/kubernetes/blob/master/hack/verify-boilerplate.sh? Are you concerned about keeping it in sync with the source version should that one change?

It's picked from the `test-infra` [1]. I don't think we need to be concerned about that as long as all the boilerplates are properly set. Don't think other repos see it differently.

[1] https://github.com/kubernetes/test-infra/blob/master/hack/verify_boilerplate.py

**Pull request merged**
