### PR TITLE
[release-1.5] 🐛Don't use v1alpha3 in clusterctl upgrade test

### LINKED ISSUE #9411: CAPI test cannot get correct number of machines when upgrading from v1.5.0  to v1.5.1
### What steps did you take and what happened?

We utilize CAPI test framework for upgrading providers. When running upgrade test from CAPI v1.5.0 to v1.5.1, following code cannot get correct number of ready machines. 

```
		By("Waiting for the machines to exist")
		Eventually(func() (int64, error) {
			var n int64
			machineList := &clusterv1alpha3.MachineList{}
			if err := managementClusterProxy.GetClient().List(ctx, machineList, client.InNamespace(testNamespace.Name), client.MatchingLabels{clusterv1.ClusterNameLabel: workLoadClusterName}); err == nil {
				for _, machine := range machineList.Items {
					if machine.Status.NodeRef != nil {
						n++
					}
				}
			}
			return n, nil
		}, input.E2EConfig.GetIntervals(specName, "wait-worker-nodes")...).Should(Equal(*controlPlaneMachineCount+*workerMachineCount), "Timed out waiting for all machines to be exist")

```
We checked the machines are ready. But the following error occured:

```
  [FAILED] Timed out after 1800.000s.
  Timed out waiting for all machines to be exist
  Expected
      <int64>: 0
  to equal
      <int64>: 2
  In [It] at: /home/****/go/pkg/mod/sigs.k8s.io/cluster-api/test@v1.5.1/e2e/clusterctl_upgrade.go:402 @ 09/13/23 02:59:32.879

```

### What did you expect to happen?

Provider upgrade tests to pass.

### Cluster API version

CAPI v1.5.0 

### Kubernetes version

v1.28.1

### Anything else you would like to add?

Link to the logs of the test:
https://jenkins.nordix.org/job/metal3_capm3_from-release-1-5_main_e2e_clusterctl_upgrade_test_ubuntu/2/consoleFull

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by mdbooth**
This is a partial backport of commit 5c4ce8b.

**What this PR does / why we need it**:
The clusterctl upgrade test explicitly uses api version v1alpha3 to check for machine readiness, but this version is no longer served by CAPI 1.5. This means that the test now requires the 'before' version to be <1.5. While this doesn't impact the use of the clusterctl upgrade tests in CAPI itself, which explicitly tests upgrades from 1.3 and 1.4, but not 1.5, it does impact use by providers who are also running this test.

**Which issue(s) this PR fixes**:
Fixes #9411

/area testing

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks - let's run the tests to be sure.

/test

**Comment by mdbooth** [comment]
/test pull-cluster-api-test-release-1-5

Looks like a flake.

**Review by furkatgofurov7 — COMMENTED** [review]
Thanks @mdbooth!

I will defer to what CI thinks, otherwise LGTM.

**Comment by sbueringer** [comment]
/lgtm

Fine to merge after green e2e-full for me

**Comment by mdbooth** [comment]
> /lgtm
> 
> Fine to merge for me after green e2e-full

e2e-full is green.

**Comment by sbueringer** [comment]
Thx!

/approve

**Pull request merged**
