### PR TITLE
🌱 Update k8s API to v1.25

### PR DESCRIPTION
**Pull request by Fedosin**
This PR bumps required k8s libraries and fixes breaking changes introduced there.

Signed-off-by: Mikhail Fedosin <mfedosin@redhat.com>

Part of #6661

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks for the contribution @Fedosin! We should wait for an update to the versions used by controller runtime before we bump Kubernetes in Cluster API.

Part of #6661

**Comment by sbueringer** [comment]
> Thanks for the contribution @Fedosin! We should wait for an update to the versions used by controller runtime before we bump Kubernetes in Cluster API.
> 
> Part of #6661

+1
There doesn't seem to be a PR yet to bump CR to the final v1.25.0 rc release so if someone wants to open that PR there... :)

cc @oscr (just that you're aware this PR exists)

**Comment by sbueringer** [comment]
Thx for the bump in CR!

I would suggest to bump to the latest commit on CR main. I know it's not a release but we still have a lot of time until the CAPI release. So this should give us enough time to pick up a CR release once it exists (and I would add a sub-task to #6661)

@vincepri WDYT?

**Comment by vincepri** [comment]
Agree with @sbueringer, we follow and bundle what Controller Runtime offers, the version should be updated there first and picked up in the next release

**Comment by sbueringer** [comment]
@Fedosin To clarify. We want to wait for the next CR release v0.13.0 to have a released version of CR with the right dependencies. CR is probably released relatively soon

**Comment by sbueringer** [comment]
@Fedosin When you've got some time, can you please pick up controller-runtime v0.13 as well? Thank yoU!

**Comment by sbueringer** [comment]
> @Fedosin When you've got some time, can you please pick up controller-runtime v0.13 as well? Thank you!

@Fedosin Do you have time to address this?

**Pull request closed without merging**
