### PR TITLE
🌱 Randomly generated namespace in util pkg tests

### PR DESCRIPTION
**Pull request by GrigoriyMikhalkin**
Partly solves #4629.

Updates namespace generation in util pkg tests.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/ok-to-test
please ensure namespace cleanup and whenever possible replace "default" with a random namespace

**Comment by fabriziopandini** [comment]
Please squash commits before merge

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
