### PR TITLE
📖 Update required configurations for Metal³ provider

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Adds required environment variables for Metal3 provider in quick-start page.
These required vars can be found in cluster-api-provider-metal3 getting-started [page](https://github.com/metal3-io/cluster-api-provider-metal3/blob/master/docs/getting-started.md#environment-variables) and also mentioned in the [release note](https://github.com/metal3-io/cluster-api-provider-metal3/releases).

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/approve
/milestone v0.4.0

Do you want to backport this to v1alpha3 (release-0.3) branch as well?

**Comment by fmuyassarov** [comment]
/retest
@vincepri Sure, I'll do it in a follow up PR.

**Pull request merged**
