### PR TITLE
🌱 Bump kpromo to v3.5.1

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
We probably need this to properly generate our promotion PR for the new registry folder

xref: https://github.com/kubernetes/k8s.io/pull/4954#issuecomment-1472996956

cc @kubernetes-sigs/cluster-api-release-team 
cc @fabriziopandini @killianmuldoon 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by killianmuldoon — APPROVED** [review]
/approve

**Comment by sbueringer** [comment]
@killianmuldoon do you maybe have some time to open a cherry-pick for 1.2?

**Comment by sbueringer** [comment]
Opened the 1.2 PR: https://github.com/kubernetes-sigs/cluster-api/pull/8305

**Pull request merged**
