### PR TITLE
[release-1.2] :seedling: Bump shellcheck version (0.7.0 -> 0.9.0) 

### PR DESCRIPTION
**Pull request by killianmuldoon**
This is a manual cherry-pick of #7737 
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by oscr** [comment]
There is a diff between 1.2 and main. But it's strange this would cause it to fail: `git diff origin/release-1.2 main -- hack/ensure-golangci-lint.sh`

**Comment by oscr** [comment]
@killianmuldoon @fabriziopandini @ykakarap I think I've found the issue by enabling tracing in main:

```
+ '[' 1 -ne 1 ']'
+ VERSION=v0.9.0
+ OS=unknown
+ [[ linux-gnu == \l\i\n\u\x* ]]
+ OS=linux
++ dirname ./hack/verify-shellcheck.sh
+ source ./hack/utils.sh
++ get_root_path
++ git rev-parse --show-toplevel
+ ROOT_PATH=/home/oscaru/go/src/k8s.io/kubernetes-sig/cluster-api
++ mktemp -d
+ TMP_DIR=/tmp/tmp.b77fDUlRC4
+ OUT=/tmp/tmp.b77fDUlRC4/out.log
+ trap cleanup EXIT
++ dirname ./hack/verify-shellcheck.sh
+ SHELLCHECK=././hack/tools/bin/shellcheck/v0.9.0/shellcheck
+ '[' '!' -f ././hack/tools/bin/shellcheck/v0.9.0/shellcheck ']'
+ echo 'Running shellcheck...'
Running shellcheck...
+ cd /home/oscaru/go/src/k8s.io/kubernetes-sig/cluster-api
++ find . -name '*.sh'
++ grep tilt_modules
+ IGNORE_FILES=
+ cleanup
+ ret=0
+ [[ -s /tmp/tmp.b77fDUlRC4/out.log ]]
+ echo 'Cleaning up...'
Cleaning up...
+ rm -rf /tmp/tmp.b77fDUlRC4
+ exit 0
```

Need to run and do some shopping but will look at it asap.

**Comment by oscr** [comment]
Can recreate now on main. Fix in progress.

**Comment by furkatgofurov7** [comment]
@killianmuldoon `test pull-cluster-api-verify-release-1-2` needs a fix apparently

**Comment by sbueringer** [comment]
@killianmuldoon Should this be unblocked now as #7757 seems to be merged

**Comment by sbueringer** [comment]
Thx!

/approve

**Pull request merged**
