### PR TITLE
🐛 Fix cluster cache tracker healthchecks

### LINKED ISSUE #3610: ClusterCacheTracker fails health checking clusters
**What steps did you take and what happened:**

While investigating memory consumption in CAPI, we discovered that the ClusterCacheTracker is failing health checks at https://github.com/kubernetes-sigs/cluster-api/blob/58f919c5e2de3f3b7a2026ab96a0e06c5b3526ff/controllers/remote/cluster_cache.go#L430

With the following error message

`E0908 18:08:49.534528       1 cluster_cache.go:486] remote/ClusterCacheTracker "msg"="ANDY error health checking cluster" "error"="error making request in healthCheckPath: Object 'Kind' is missing in '{\n  \"paths\": [\n    \"/api\",\n    \"/api/v1\",\n    \"/apis\",\n   ...  ]\n}'"  "cluster"="default/workload-46"`

This error causes the cache to be cleaned up for the cluster, and a new cache recreated (and repeat).

**What did you expect to happen:**

The health check for the ClusterCacheTracker to properly report status, so the cache is cleaned up only when necessary.

/kind bug
/priority critical-urgent
/milestone v0.3.10

### PR DESCRIPTION
**Pull request by ncdc**
**What this PR does / why we need it**:
Fix a bug in the cluster cache tracker healthcheck code that was failing
to decode the response from the apiserver (it was trying to deserialize
it as a runtime object, and the / repsonse is missing TypeMeta). Switch
to using a pure HTTP client.

Part of a series of fixes for #3609 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3610 

/hold
pending additional verifications

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/approve

**Comment by ncdc** [comment]
/hold

Looks like our 2s isn't enough for Prow (resource starved?), or it's flakey (?)

```
[91m[1m• Failure [2.187 seconds][0m
ClusterCache HealthCheck suite
[90m/home/prow/go/src/sigs.k8s.io/cluster-api/controllers/remote/cluster_cache_healthcheck_test.go:39[0m
  when health checking clusters
  [90m/home/prow/go/src/sigs.k8s.io/cluster-api/controllers/remote/cluster_cache_healthcheck_test.go:40[0m
    [91m[1mwith a healthy cluster [It][0m
    [90m/home/prow/go/src/sigs.k8s.io/cluster-api/controllers/remote/cluster_cache_healthcheck_test.go:111[0m

    [91mExpected
        <bool>: true
    to be false[0m

    /home/prow/go/src/sigs.k8s.io/cluster-api/controllers/remote/cluster_cache_healthcheck_test.go:128
```

**Comment by fabriziopandini** [comment]
@wfernandes FYI this fix might help to solve MHC test failures

**Comment by ncdc** [comment]
Unfortunately this isn't helping with the MHC test flakes.

/retest

**Review by vincepri — APPROVED** [review]
/lgtm
/milestone v0.3.10

**Pull request merged**
