### PR TITLE
Fix SSH issue with in place upgrades.

### LINKED ISSUE #182: GCP Update controlPlane Version Fails
### Overview
Updating `controlPlane` value failes and crashes `clusterapi`

### Repro Steps
1. Create new Kubernetes cluster on GCE via `gcp-deployer create -c cluster.yaml -m machines.yaml -s machine_setup_configs.yaml` using [CONTRIBUTIN.md](https://github.com/kubernetes-sigs/cluster-api/blob/master/gcp-deployer/CONTRIBUTING.md)
```
I0516 15:10:33.474771   10301 deploy_helper.go:58] Starting cluster dependency creation cluster-api-
...
I0516 15:14:49.467724   10301 deploy.go:85] The [cluster-api-test] cluster has been created successfully!
I0516 15:14:49.467740   10301 deploy.go:86] You can now `kubectl get nodes`
```
2. Verify cluster nodes
```
kubectl get nodes
NAME                          STATUS    ROLES     AGE       VERSION
gce-master-cluster-api-test   Ready     master    5m        v1.9.4
gce-node-vhjpt                Ready     <none>    1m        v1.9.4
```
3. Verify clusterapi machines
```
kubectl get machines
NAME                          AGE
gce-master-cluster-api-test   4m
gce-node-vhjpt                4m
```
4. Edit `gce-master-cluster-api-test` machine defintion via 
`kubectl edit machines/gce-master-cluster-api-test --validate=false` and update `controlPlane` from `1.9.4` to `1.9.7`

### Expected results 
Kubernetes cluster control plane is upgraded from `1.9.4` to `1.9.7`

### Actual Result
Kubernetes cluster control plane is not upgraded.
Clusterapi api and controller(s) appears to be in a crashed state.
- cannot retrieve machine resources
```
kubectl get machines
error: the server doesn't have a resource type "machines"
```
- unable to retrieve logs for `clusterapi` pod (exiting tails abruptly terminated)
apiserver:
```
...
ERROR: logging before flag.Parse: I0516 22:19:50.365846       1 logs.go:41] Defaulting fields for Machine gce-master-cluster-api-test
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```
controller-manager
```
...
ERROR: logging before flag.Parse: I0516 22:14:49.310297       1 logs.go:41] Running reconcile Cluster for cluster-api-test
ERROR: logging before flag.Parse: I0516 22:14:49.610299       1 logs.go:41] Running reconcile Cluster for cluster-api-test
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```
gce-machine-controller
```
ERROR: logging before flag.Parse: I0516 22:19:49.342795       1 machineactuator.go:472] Doing an in-place upgrade for master.                                                                                                                                                                                                                     
ERROR: logging before flag.Parse: I0516 22:19:49.342820       1 ssh.go:98] Remote SSH execution 'export KUBEADM_VERSION=$(curl -sSL https://dl.k8s.io/release/stable.txt); curl -sSL https://dl.k8s.io/release/${KUBEADM_VERSION}/bin/linux/amd64/kubeadm | sudo tee /usr/bin/kubeadm > /dev/null; sudo chmod a+rx /usr/bin/kubeadm' on gce-master-cluster-api-test
ERROR: logging before flag.Parse: I0516 22:19:49.464373       1 machineactuator.go:670] remotesshcomand error: error: exit status 255, output:
ERROR: logging before flag.Parse: E0516 22:19:49.465648       1 machineactuator.go:475] master inplace update failed: error: exit status 255, output:
ERROR: logging before flag.Parse: I0516 22:19:49.470835       1 controller.go:83] Running reconcile Machine for gce-master-cluster-api-test
ERROR: logging before flag.Parse: I0516 22:19:49.590860       1 controller.go:117] reconciling machine object gce-master-cluster-api-test triggers idempotent update.
ERROR: logging before flag.Parse: I0516 22:19:49.599154       1 machineactuator.go:472] Doing an in-place upgrade for master.
...
error: http2: server sent GOAWAY and closed the connection; LastStreamID=3, ErrCode=NO_ERROR, debug=""
```

journalctl on master node immediatly after update at 22:19
```
...
May 16 22:17:11 gce-master-cluster-api-test ntpd[1492]: kernel reports TIME_ERROR: 0x41: Clock Unsynchronized
May 16 22:19:49 gce-master-cluster-api-test sshd[7876]: Connection closed by 104.197.87.198 port 49546 [preauth]
May 16 22:19:49 gce-master-cluster-api-test sshd[7880]: Connection closed by 104.197.87.198 port 49548 [preauth]
May 16 22:19:50 gce-master-cluster-api-test sshd[7883]: Connection closed by 104.197.87.198 port 49550 [preauth]
May 16 22:19:50 gce-master-cluster-api-test sshd[7886]: Connection closed by 104.197.87.198 port 49552 [preauth]
May 16 22:19:50 gce-master-cluster-api-test sshguard[1304]: Blocking 104.197.87.198:4 for >630secs: 40 danger in 4 attacks over 0 seconds (all: 40d in 1 abuses over 0s).
May 16 22:20:03 gce-master-cluster-api-test kubelet[5263]: E0516 22:20:03.450557    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test?resourceVersion=0: net/http: request canceled (Client
May 16 22:20:13 gce-master-cluster-api-test kubelet[5263]: E0516 22:20:13.450898    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:20:23 gce-master-cluster-api-test kubelet[5263]: E0516 22:20:23.451240    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:20:33 gce-master-cluster-api-test kubelet[5263]: E0516 22:20:33.452118    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:20:43 gce-master-cluster-api-test kubelet[5263]: E0516 22:20:43.452544    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:20:43 gce-master-cluster-api-test kubelet[5263]: E0516 22:20:43.452579    5263 kubelet_node_status.go:375] Unable to update node status: update node status exceeds retry count
May 16 22:21:03 gce-master-cluster-api-test kubelet[5263]: E0516 22:21:03.453322    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test?resourceVersion=0: net/http: request canceled (Client
May 16 22:21:13 gce-master-cluster-api-test kubelet[5263]: E0516 22:21:13.453775    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:21:23 gce-master-cluster-api-test kubelet[5263]: E0516 22:21:23.454176    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:21:33 gce-master-cluster-api-test kubelet[5263]: E0516 22:21:33.454585    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:21:43 gce-master-cluster-api-test kubelet[5263]: E0516 22:21:43.454888    5263 kubelet_node_status.go:383] Error updating node status, will retry: error getting node "gce-master-cluster-api-test": Get https://104.197.87.198:443/api/v1/nodes/gce-master-cluster-api-test: net/http: request canceled (Client.Timeout exceeded 
May 16 22:21:43 gce-master-cluster-api-test kubelet[5263]: E0516 22:21:43.455267    5263 kubelet_node_status.go:375] Unable to update node status: update node status exceeds retry count
May 16 22:21:57 gce-master-cluster-api-test dockerd[4800]: time="2018-05-16T22:21:57.544560440Z" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/f857ebd8b49e4eae6f9031eede8f16d1a76373abb54a8ab2b6cd9dd65f851be6: exec: \"auplink\": executable file not found in $PATH"
May 16 22:21:57 gce-master-cluster-api-test dockerd[4800]: time="2018-05-16T22:21:57.573475724Z" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/fd3f0cf8c2e7b346922da811a61d6775aee1b930b974cc966b8940cebca3d6df-init: exec: \"auplink\": executable file not found in $PATH"
May 16 22:21:57 gce-master-cluster-api-test dockerd[4800]: time="2018-05-16T22:21:57.603998318Z" level=warning msg="Couldn't run auplink before unmount /var/lib/docker/aufs/mnt/fd3f0cf8c2e7b346922da811a61d6775aee1b930b974cc966b8940cebca3d6df: exec: \"auplink\": executable file not found in $PATH"
May 16 22:21:57 gce-master-cluster-api-test dockerd[4800]: time="2018-05-16T22:21:57.732588705Z" level=warning msg="Unknown healthcheck type 'NONE' (expected 'CMD') in container 344c122adda517044878cff95b559a2720be773f366b5f3365e6897fa94f2d30"
...
```

### PR DESCRIPTION
**Pull request by k4leung4**
**What this PR does / why we need it**:
The master in-place upgrade is currently broken due to an SSH failure
with the error "Host key verification failed."
As the master machine may change, it should be safe to disable the host
key check, which fixes the issue.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #182 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by karan** [comment]
did you try `UserKnownHostsFile=/dev/null` along with what you already have?

**Comment by k4leung4** [comment]
added that option to ssh as well.

**Comment by k4leung4** [comment]
Verified in-place upgrades works.

**Comment by karan** [comment]
Does that mean the control plane works after the upgrade, or only that the image was upgraded?

**Comment by k4leung4** [comment]
Both, was able to upgrade control plane from 1.9.4 to 1.9.7, and the master is responsive after the upgrade, verified by running kubectl get machines

**Comment by karan** [comment]
Sweet. 

/lgtm

**Pull request merged**
