### PR TITLE
:seedling: Fuzzing: Add report

### PR DESCRIPTION
**Pull request by AdamKorcz**
Signed-off-by: AdamKorcz <adam@adalogics.com>

Adds the report for the fuzzing work that was done in collaboration with the CNCF and Ada Logics.

`docs/reports` is merely a suggestion. Feel free to recommend a different location. 

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
I don't think this repo is the best place for keeping a report like this  - pdf, static. Is there some other location to host the report that we could link to?

@PushkarJ wondering if SIG security has any specific repo or recommendations for reports like this?

**Comment by killianmuldoon** [comment]
/hold 
Let's wait to figure out if github.com/kubernetes/sig-security/sig-security-assessments/cluster-api is the right place for this report.

**Comment by aladewberry** [comment]
@DavidKorczynski @killianmuldoon Agreed with @PushkarJ that github.com/kubernetes/sig-security/sig-security-assessments/cluster-api is the appropriate place for this to be stored. Is the next step for me to put it there? Let me know!

**Comment by killianmuldoon** [comment]
I just opened a PR on the sig-security repo at https://github.com/kubernetes/sig-security/pull/52. Once everyone's happy we can close this PR and I'll find a suitable place to put a link to this in the CAPI book. Thanks for all the hard work!

**Comment by killianmuldoon** [comment]
Report is now merged in sig-security 🙂 

/close

**Pull request closed without merging**
