### PR TITLE
✨ docs: fix command-line-tools links in book

### PR DESCRIPTION
**Pull request by damdo**
**What this PR does / why we need it**:
Fixes 3 broken link occurrences in the book.
Found them with:
```
$ grep -r "docs/admin" -l
./docs/book/src/user/concepts.md
```

After the fix no occurrences are found:
```
$ grep -r "docs/admin"
$
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/8160

### CODE REVIEW

**Review by elmiko — COMMENTED** [review]
/lgtm

**Comment by oscr** [comment]
Thank you for the quick fix @damdo! 

/lgtm
/approve

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
