### PR TITLE
🌱 Validating the warnings in tests

### LINKED ISSUE #8732: Validate warnings in webhook unit tests
### What would you like to be added (User Story)?

Note: This is a follow-up to: https://github.com/kubernetes-sigs/cluster-api/pull/8007 (specifically: https://github.com/kubernetes-sigs/cluster-api/pull/8007#discussion_r1202711835)

CR v0.15 extended the validating webhook interfaces to allow returning warnings. In the initial bump PR we just ignored the warning return parameter. Goal of this task is to extend our unit tests to validate that warnings are nil (as of today we never return warnings.

### Detailed Description

The following commits shows all places where we adapted unit tests to ignore the warning return parameter: https://github.com/kubernetes-sigs/cluster-api/commit/ea0dc4da091b13bea47dbb6d41340c1f434bac5d

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind cleanup
/area testing
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by Dhairya-Arora01**
**What this PR does / why we need it**: To validate the warnings in webhook unit tests

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8732

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Comment by sbueringer** [comment]
@Dhairya-Arora01 Looks good so far, that's what I meant!

**Comment by jackfrancis** [comment]
@Dhairya-Arora01 this looks gook, thanks!

Are there any "negative" test cases we can create for these warning responses? The equivalent of `g.Expect(err).To(HaveOccurred())` for errors?

I assume we'll have to author new cases as the existing set of UT that you've backfilled w/ warnings responses are all nil.

**Comment by Dhairya-Arora01** [comment]
@jackfrancis , So we need to write those cases where the warnings are not nil ?

**Comment by sbueringer** [comment]
> @Dhairya-Arora01 this looks gook, thanks!
> 
> Are there any "negative" test cases we can create for these warning responses? The equivalent of `g.Expect(err).To(HaveOccurred())` for errors?
> 
> I assume we'll have to author new cases as the existing set of UT that you've backfilled w/ warnings responses are all nil.

99% of our webhooks do not return any warnings in any case.

**Comment by Dhairya-Arora01** [comment]
@sbueringer , so we need to look for those 1% ?? and write negative test cases for those

**Comment by Dhairya-Arora01** [comment]
@sbueringer so we should wait for that pr to get merged?? or should we move on and after it gets merged open another one

**Comment by sbueringer** [comment]
I think we should move on with this PR. If we want to change unit tests of the code introduced in #8746, this should be discussed and adressed in #8746.

**Pull request merged**
