### PR TITLE
🌱 Add v1alpha3 test templates alongside v1alpha4 ones

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR adds v1alpha3 test templates alongside v1alpha4 ones, so it will be possible to test clusterctl upgrades from v1alpha3 to v1alpha4
(spin-off of #3708)

### CODE REVIEW

**Comment by vincepri** [comment]
I assume we're keeping the v1alpha3 around to test upgrades?

**Comment by fabriziopandini** [comment]
> I assume we're keeping the v1alpha3 around to test upgrades?

Yes, for testing clusterctl upgrades

**Comment by vincepri** [comment]
Sounds good, thanks!

Going forward, let's open issues first for changes of this caliber so we can get the help of new contributors and grow the community.

/approve
/lgtm

**Pull request merged**
