### PR TITLE
 :seedling: Add DiscoverVariables hook implementation for test extension

### PR DESCRIPTION
**Pull request by killianmuldoon**
Add an initial implementation of the DiscoverVariables hook to the test extension.

Part of #7985

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@killianmuldoon ping me when this one is ready for a pass

**Comment by killianmuldoon** [comment]
>@killianmuldoon ping me when this one is ready for a pass
Sure - there's a few PRs that probably need to be merged before this one is really worth looking at as it contains a bunch of those commits.

**Comment by sbueringer** [comment]
/lgtm
/approve

Let's get the basic test merged while we work on a more advanced test.

**Pull request merged**
