### PR TITLE
:warning: Update controller runtime v0.9 (main) and Go 1.16

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

This PR requires https://github.com/kubernetes/test-infra/pull/21114 to be merged first.

/milestone v0.4.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
changes lgtm, waiting for https://github.com/kubernetes/test-infra/pull/21114 before lgtm

**Comment by vincepri** [comment]
@CecileRobertMichon @fabriziopandini ptal, fixed the issue with dependency building

**Pull request merged**
