### PR TITLE
📖  Add AZURE_ENVIRONMENT env var to azure instructions in quick start guide

### PR DESCRIPTION
**Pull request by nader-ziada**
**What this PR does / why we need it**:
-  This `AZURE_ENVIRONMENT` env var specifies the Azure cloud to use. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

will hold for the PR in capz adding this feature to merge https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/649 
/hold

### CODE REVIEW

**Comment by nader-ziada** [comment]
@vincepri yes, comment on PR here: https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/649#discussion_r441178809

**Comment by vincepri** [comment]
Got it, thanks

**Comment by vincepri** [comment]
Seems the linked PR has merged, ok to unhold @CecileRobertMichon @nader-ziada ?

**Comment by nader-ziada** [comment]
yes, PR in capz got merged today

**Pull request merged**
