### PR TITLE
🌱 Makefile: run doctoc only once

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Review by vincepri — APPROVED** [review]

**Comment by fabriziopandini** [comment]
nice catch
/lgtm

**Comment by sbueringer** [comment]
Diff'ing this sort of stuff between CAPI & CAPV has its advantages.. :joy;

**Comment by sbueringer** [comment]
Pushed the same commit again to trigger the CLA bot

**Pull request merged**
