### PR TITLE
:seedling: Remove most of bindata targets in favor of Go 1.16 embed

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/milestone v0.4.0

### CODE REVIEW

**Comment by vincepri** [comment]
@fabriziopandini There is only one file left with `go-bindata`, which is the asset generated through kustomize first for clusterctl

**Comment by CecileRobertMichon** [comment]
> There is only one file left with go-bindata, which is the asset generated through kustomize first for clusterctl

Do we want to track removing that one in an issue?

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

🙌

**Pull request merged**
