### PR TITLE
:seedling: Rename internal/util/ssa util functions for better naming consistency

### LINKED ISSUE #8396: Rename `internal/util/ssa` util functions for better naming consistency
**Detailed Description:**

Rename the following functions in the `ssa` package to have consistent naming scheme:
- IsAllowedPath -> IsPathAllowed ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119200006))
- IsIgnorePath -> IsPathIgnored ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119201340))
- IsNotAllowed -> IsPathNotAllowed ([Ref](https://github.com/kubernetes-sigs/cluster-api/pull/8060#discussion_r1119200893))

All the above functions are in `internal/util/ssa` package. 

The comments on these functions should also be corrected. Example:
For  `IsAllowedPath` the comment should be changed to `// IsAllowedPath returns a functions that returns true when the Path is one of the AllowedPaths.` (similarly for the other functions).

**Additional Information:**
We need to have an explicit `IsPathNotAllowed` and cannot simple use the negation of `IsPathAllowed` and ask used to use `!IsPathAllowed()` as both the functions return a filter function and there is no simple way to get to negation of the returned function. 

/kind cleanup
/help

### PR DESCRIPTION
**Pull request by cahillsf**
**What this PR does / why we need it**:
 Renames `internal/util/ssa` util functions for better naming consistency

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8396

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
Thanks for taking care of this cleanup!
/lgtm
/approve

**Pull request merged**
