### PR TITLE
🌱 Rebase operator changes

### PR DESCRIPTION
**Pull request by alexander-demichev**
**What this PR does / why we need it**:
Rebase operator changes on top of the main branch. No code changes included.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area operator

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/lgtm
/approve
given that it is a simpy rebase of the operator branch, no code changes included.

**Comment by vincepri** [comment]
Could we also pull the last merged PRs?

**Pull request merged**
