### PR TITLE
🌱 Re-enable link checker

### PR DESCRIPTION
**Pull request by benmoss**
**What this PR does / why we need it**:
Reverts the part of #3709 that disables the linkchecker entirely. I think @randomvariable may have been confused in thinking that the linkchecker was blocking Netlify deploys.

It will log 

> The command `mdbook-linkcheck` for backend `linkcheck` was not found, but was marked as optional.

But this is just a warning, not a failure. If you have the linkchecker installed in your `hack/tools/bin` directory it will run the linkchecker, so we specifically don't install it for make targets other than `verify`.

### CODE REVIEW

**Comment by randomvariable** [comment]
Can we add a note in the Makefile to not add it back?

**Comment by benmoss** [comment]
@randomvariable I added a new target to remove `mdbook-linkcheck` from the `hack/tools/bin` dir if you're running `make serve` or `make build`, because I bet that is part of what tripped you up when diagnosing this. I added some flavor text around that target that hopefully makes it clean how the optional plugin magic works.

**Comment by randomvariable** [comment]
Thanks!

/lgtm

**Pull request closed without merging**
