### PR TITLE
Change default image to Ubuntu 1604 for GCP

### LINKED ISSUE #90: GCP support for Ubuntu image
_From @rsdcastro on February 12, 2018 18:15_

This about tracking the current support for Ubuntu to be production ready.

Ideally this should be agnostic so all providers can use it.

_Copied from original issue: kubernetes/kube-deploy#593_

### PR DESCRIPTION
**Pull request by kcoronado**
**What this PR does / why we need it**:
This PR changes the default image from Ubuntu 1710 to Ubuntu 1604-lts in the google machine actuator since that is the image we mostly use for testing. The machine setup configmap is already set up to use Ubuntu 1604.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #90 

**Special notes for your reviewer**:

**Release note**:

```release-note

```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by dims** [comment]
@kcoronado looks like the test case needs to be fixed too

**Comment by kcoronado** [comment]
/retest
I fixed the tests, sorry about that.

**Pull request merged**
