### PR TITLE
:seedling: Enable ClusterResourceSet by default

### LINKED ISSUE #3311: Enable ClusterResourceSet experiment by default
After v0.3.7 is released, we should evaluate to enable the ClusterResourceSet feature gate by default. The change has a few benefits:

- We can have providers to embed CRS resources directly in the infrastructure components.
- Change the quickstart to use CRS based resources without requiring folks to install CNI directly.

/kind feature

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

Graduate CRS in v0.4.0 by enabling the functionality by default.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3311 

/milestone v0.4.0
/assign @CecileRobertMichon @sedefsavas

### CODE REVIEW

**Comment by sedefsavas** [comment]
Kubernetes features are enabled by default when the features become beta.
should we consider upgrading CRS to beta? And even machinepools?

**Comment by CecileRobertMichon** [comment]
We should move CRS out of exp/ before enabling it by default.

For MachinePool we're not quite ready because of #3424 and #4063

**Comment by vincepri** [comment]
> Kubernetes features are enabled by default when the features become beta.

This is true, we can switch it to a beta experiment. I think we've had enough soak time so far.

> We should move CRS out of exp/ before enabling it by default.

Following upstream Kubernetes feature gate model, like Sedef mentioned, there are a bunch of features that are enabled as part of an experiment that are either alpha or beta. Or are we saying that we want only alpha features in exp/?

**Comment by CecileRobertMichon** [comment]
following the k8s model and moving it to beta in exp SGTM

**Comment by fabriziopandini** [comment]
+1 to graduate CRS to beta
For consistency, we should upgrade also manifests, e.g. 
https://github.com/kubernetes-sigs/cluster-api/blob/280db9a796d5e1c2b3b75aa3036fcfe44f669909/config/manager/manager.yaml#L25

And documentation about experimental features
https://master.cluster-api.sigs.k8s.io/tasks/experimental-features/experimental-features.html

Might be there is also some other place like e.g. tests config files...

**Comment by vincepri** [comment]
This is ready to go

**Pull request merged**
