### PR TITLE
🐛 Fix panic in node drain

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
e2e tests are currently broken on main. This PR should fix it.

Found this panic in our test logs: https://storage.googleapis.com/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1496705192203128832/artifacts/clusters/bootstrap/controllers/capi-controller-manager/capi-controller-manager-5ddddd567d-fmdpj/manager.log

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
flake
/test 
pull-cluster-api-e2e-full-main

**Comment by sbueringer** [comment]
flake
/test pull-cluster-api-e2e-full-main

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
