### PR TITLE
🐛 Fix cloudbuild definitions due to invalid syntax

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Wrong syntax was introduced in #6443 (sorry for that)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes broken cloudbuild runs.

### CODE REVIEW

**Comment by ditsuke** [comment]
Thought I was missing some context when I looked at the failing build. Looks good now!

**Review by ditsuke — APPROVED** [review]

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Pull request merged**
