### PR TITLE
🌱 test: retry controller-runtime client instantiation

### PR DESCRIPTION
**Pull request by jackfrancis**
**What this PR does / why we need it**:

This PR adds simple retry tolerance to the controller-runtime client operation during E2E in response to an observed flake.

Reference flake:

https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-provider-azure-capi-e2e-main/1516871720609255424

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by jackfrancis** [comment]
cc @CecileRobertMichon

**Review by CecileRobertMichon — APPROVED** [review]
/lgtm
/approve

Thanks!

**Pull request merged**
