### PR TITLE
🌱 Check for panics during test runs in envtest

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #11272

### CODE REVIEW

**Comment by sbueringer** [comment]
@chrischdi @fabriziopandini Once this is merged, I think it would be a good idea to rebase your current PRs on top of it. Should make it a lot easier to find panics (e2e tests are checking the same, but it's more annoying to find the panics there + our unit test coverage is higher)

**Comment by chrischdi** [comment]
Super awesome addition!

/lgtm
/approve

/hold

To give others some time.

**Comment by fabriziopandini** [comment]
Yes!
/lgtm
/approve

**Pull request merged**
