### PR TITLE
Updated godoc for machine_types.go to align with best practices

### LINKED ISSUE #570: Godoc sometimes does not follow best practice
I noticed a few places that the first word is not the thing being documented:

1. https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L46
2. https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L52
3. https://github.com/kubernetes-sigs/cluster-api/blob/master/pkg/apis/cluster/v1alpha1/machine_types.go#L58

for instance. I expect golint should tell us these things?

### PR DESCRIPTION
**Pull request by phenixblue**
**What this PR does / why we need it**:
This PR cleans up godoc comments for machine_types to align with best practices, specifically to include the name of the thing being documented first.

**Which issue(s) this PR fixes**:
Fixes #570

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by phenixblue** [comment]
> I think you need to run make to update stuff under `config/crds`, as @vincepri did in #693.

Done

**Comment by roberthbailey** [comment]
Also, this now needs a rebase.

**Pull request merged**
