### PR TITLE
🐛 uplift golang and x/net

### PR DESCRIPTION
**Pull request by tuminoid**
Uplift golang to 1.19.6 and x/net to 0.7.0 due https://osv.dev/vulnerability/GO-2023-1571

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks @tuminoid 

/ok-to-test

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

/cherry-pick release-1.3

**Comment by sbueringer** [comment]
@tuminoid Do you have some time to open a manual cherry-pick for release-1.3?

**Comment by tuminoid** [comment]
Sure. I’ll do it later tonight.

**Pull request merged**
