### PR TITLE
:seedling:  Remove v1alpha2 adoption logic from KCP

### PR DESCRIPTION
**Pull request by killianmuldoon**
Remove adoption logic for v1alpha2 from the KCP controller. There is currently no direct support for upgrades from v1alpha2 to v1beta1. This code is designed to support that use case so it should be removed. 

Clusters which are reconciled by 0.3.X / 0.4.X controllers before updating to v1beta1 will already have this ownerReference removed. 

Fixes https://github.com/kubernetes-sigs/cluster-api/pull/8256/files#r1141658906

### CODE REVIEW

**Comment by sbueringer** [comment]
lgtm pending linter fix

**Comment by killianmuldoon** [comment]
>@killianmuldoon do we want to / have to cherry-pick this PR?

No need to cherry-pick IMO. As you said this is a cleanup - nothing to do with any of our current ownerRef tests.

**Review by fabriziopandini — COMMENTED** [review]
nice cleanup
/approve
/lgtm

**Pull request merged**
