### PR TITLE
:running: Pass a stripped down object to controller.Watch

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This is an effort to avoid logging sensitive information when the controller starts watching external resources.

If we pass the whole object, the controller-runtime object will log it out including all fields also within spec. This PR uses an unstructured object with only GVK set to issue the watch instead.

/milestone v0.3.0
/assign @ncdc

### CODE REVIEW

**Comment by vincepri** [comment]
For reference, this is the log line upstream https://github.com/kubernetes-sigs/controller-runtime/blob/e00985b30c688f246e59400ff715e3a2331fa75f/pkg/internal/controller/controller.go#L138

**Comment by detiber** [comment]
Nice find!
LGTM

**Comment by ncdc** [comment]
/lgtm
/hold
would like a manual test to confirm the watch still works

**Comment by ncdc** [comment]
Confirmed with Vince on Slack that it's good.
/unhold

**Pull request merged**
