### PR TITLE
[release-1.4] :seedling: ClusterCacheTracker: ensure Get/List calls are not getting stuck when apiserver is unreachable

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Manual cherry-pick of #9028

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

### CODE REVIEW

**Comment by sbueringer** [comment]
@killianmuldoon why hold? :)

**Comment by killianmuldoon** [comment]
>@killianmuldoon why hold? :)

Just in case anyone else wanted to take a look - feel free to remove

**Comment by sbueringer** [comment]
> [We also have a policy in Contributing.md around this](https://github.com/kubernetes-sigs/cluster-api/blob/main/CONTRIBUTING.md#releases) - but we haven't been following it really.

Good catch. I wasn't aware of it at all to be honest

**Pull request merged**
