### PR TITLE
🌱 Randomly generated namespace in bootstrap pkg tests

### PR DESCRIPTION
**Pull request by GrigoriyMikhalkin**
Partly solves #4629. 

Updates namespace generation in bootstrap pkg tests.

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
I guess that same comments of https://github.com/kubernetes-sigs/cluster-api/pull/4959#pullrequestreview-709256738 apply here as well 😜 
Looking forward to get this merged afterward comments are addressed

**Comment by fabriziopandini** [comment]
/test pull-cluster-api-test-main
Test failures seems unrelated to this PR

/lgtm
please squash commits before merging

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
