### PR TITLE
:seedling: Add Cluster API icons to repo

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Adds icons for Cluster API components to the repo, these icons have been used in various presentations and it makes sense to have them available in the repo rather than having to pass them off to each other via other means.

### CODE REVIEW

**Comment by ncdc** [comment]
I assume these were created in accordance with / fall under the same licensing terms as everything else in this repo (Apache 2)?

**Comment by detiber** [comment]
> I assume these were created in accordance with / fall under the same licensing terms as everything else in this repo (Apache 2)?

They are derived from https://github.com/kubernetes/community/tree/master/icons, which lists Apache-2.0 or CC-BY-4.0, I'll add a similar readme for similar license requirements.

The AI file was created by @jbeda, so tagging him on this as well.

**Comment by detiber** [comment]
/hold
hold until license requirements are agreed upon and this PR is updated accordingly.

**Comment by fabriziopandini** [comment]
+1 to get shared images in the repo (if possible)!

**Comment by jbeda** [comment]
Go for it! Would love to see these be included.  Let me know if you need any tweaks.  Happy to see these be included with the rest of these icons with the same license.

**Comment by detiber** [comment]
/hold cancel

Updated with a README linking to the Kubernetes Icon Set along with updated license information.

**Pull request merged**
