### PR TITLE
:bug: log in restore cmd causing crashes

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What this PR does / why we need it**:
Allows the use of the restore function, as it is right now broken.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/lgtm
@jpmcb PTAL

**Comment by vincepri** [comment]
We need a linter for these 😄

**Pull request merged**
