### PR TITLE
🌱 Update jobs.md and make it version-independent

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Updated the jobs.md and got rid of some toil. Not very useful to try to keep this doc 100% up-to-date with links etc. if we can just link to the source of truth instead.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #10062

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/approve

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
nice cleanup!
/lgtm
/approve

**Pull request merged**
