### PR TITLE
🐛 re-add patch for events

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

Fixup changes from:

* #10552

By grepping through job logs

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area api

### CODE REVIEW

**Comment by chrischdi** [comment]
This should be good now. grepped over the `e2e-main` logs/artifacts

/assign @sbueringer 
/assign @fabriziopandini

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/approve

**Pull request merged**
