### PR TITLE
[release-1.5] :seedling: Add log level for kube components patch to ClusterClass

### PR DESCRIPTION
**Pull request by killianmuldoon**
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/9493

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/hold

I want to do a run with the dualstack logging to be sure

/area e2e-testing

**Comment by killianmuldoon** [comment]
/retitle [release-1.5] :seedling: Add debug logging patch to ClusterClass

**Comment by killianmuldoon** [comment]
Clusters for this run can be compared here: https://gcsweb.k8s.io/gcs/kubernetes-jenkins/pr-logs/pull/kubernetes-sigs_cluster-api/9501/pull-cluster-api-e2e-release-1-5/1706695106448330752/artifacts/clusters/

I'll revert the change in the e2e tests now.

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/approve

**Pull request merged**
