### PR TITLE
📖 Add issue template for Kubernetes bumps, fix links to fork

### LINKED ISSUE #7389: Setup initial release docs, dates and team
This is an umbrella issue which captures tasks we want to do **before** the v1.4.0 release cycle starts to have a starting point from which we can iterate.

## Preparation tasks

* [x] Assemble the release team for v1.4 (@CecileRobertMichon)
  * [x] PR to add the release team to the doc: #7470
* [x] Finalize v1.3 + v1.4 release dates + initial release cycle definition (@sbueringer #7391)
* [x] #7476 (@ykakarap)
  * Initial setup done, adding Joe now
* [x] #7499 (@sbueringer)
* [ ] Write doc for Kubernetes bump: #7561 (@sbueringer)

/kind feature

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
This PR documents the Kubernetes bump via an issue template and also fixes the links to my fork introduced in #7499.

Examples:
* Create issue: https://github.com/sbueringer/cluster-api/issues/new/choose
  image
* Example issue: https://github.com/sbueringer/cluster-api/issues/83

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7389

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @stmcginnis

**Comment by sbueringer** [comment]
/assign @fabriziopandini 
(should be the last sub-task to close #7389)

cc @killianmuldoon @ykakarap

**Review by fabriziopandini — COMMENTED** [review]
last two nits, otherwise lgtm for me

**Comment by sbueringer** [comment]
Updated.

I also dropped the patch version numbers for the monthly patch releases in the release timelines. I think it's only relevant that there are patch releases for certain release series, doesn't matter which one exactly.

Otherwise it's hard to keep the exact versions up-to-date if we do additional patch releases from time to time.

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by CecileRobertMichon — COMMENTED** [review]
/cc @kubernetes-sigs/cluster-api-release-team

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

this is great, thanks @sbueringer

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Review by cpanato — APPROVED** [review]
/lgtm

**Pull request merged**
