### PR TITLE
🌱 bump go-github dependency to version v53

### PR DESCRIPTION
**Pull request by cpanato**
**What this PR does / why we need it**:
- 🌱 bump go-github dependency to version v53

/assign @sbueringer @fabriziopandini 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

I guess dependabot isn't able to pick up version bumps where there's a new path - not great, but I don't think we have many dependencies of that form.

**Comment by sbueringer** [comment]
Maybe we should open a feature request (in case it doesn't exist yet)

**Comment by killianmuldoon** [comment]
Closed: https://github.com/dependabot/dependabot-core/issues/3623

:disappointed:

**Pull request merged**
