### PR TITLE
:seedling: Bump etcd to v3.5.0

### LINKED ISSUE #4745: Update etcd client dependency
**User Story**

The etcd client dependency is very outdated, and we're missing grpc fixes as a result. Need to refactor the cluster etcd client to make use of v3.4.16.

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:
Bumps etcd client to v3.5.0, the main thing is that  this takes us off a special commit of etcd client that was made specifically for Kubernetes, and gets us at least a year of go-grpc updates.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4745

### CODE REVIEW

**Comment by randomvariable** [comment]
worked once, will it work again? one way to find out...

/test pull-cluster-api-e2e-workload-upgrade-1-21-latest-main

**Comment by randomvariable** [comment]
I think this is ok actually, and the errors we were seeing were flakes from k/k's main branch.

**Review by vincepri — APPROVED** [review]
/lgtm
/assign @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

this time for real :)

**Pull request merged**
