### PR TITLE
⚠️ Remove deprecated Bootstrap Data

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Machine.Spec.Bootstrap.Data and KubeadmConfigStatus.BootstrapData were deprecated in v1alpha3 in favor of Bootstrap.DataSecretName. This PR removes the deprecated types and all references to them in the codebase and docs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
@CecileRobertMichon thanks for this PR!
/lgtm

**Comment by ncdc** [comment]
@CecileRobertMichon do you need to run `make diagrams` from the `docs` dir to regenerate from the plantuml file you changed?

**Pull request merged**
