### PR TITLE
🌱 Make ClusterClass generated object names consistent

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #9135

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @fabriziopandini

**Comment by chaunceyjiang** [comment]
Just a question, if we directly modify the name, will there be any compatibility issues?

Not long ago, I also wanted to pick up this issue. However, I made the same modification but did not submit a pull request in the end because I was unsure if this modification would cause any compatibility issues.

**Review by killianmuldoon — COMMENTED** [review]
/area clusterclass

**Comment by sbueringer** [comment]
> Just a question, if we directly modify the name, will there be any compatibility issues?
> 
> Not long ago, I also wanted to pick up this issue. However, I made the same modification but did not submit a pull request in the end because I was unsure if this modification would cause any compatibility issues.

There should be no compatibility issue. Do you mean during upgrades? 

We only use those functions when we create the name of new objects. So existing objects are not affected in any way by this change.

**Comment by sbueringer** [comment]
clusterctl upgrade is green and checked the test artifacts. Everything looks as expected

**Comment by sbueringer** [comment]
clusterctl upgrade is green and checked the test artifacts. Everything looks as expected

**Comment by killianmuldoon** [comment]
/approve

/hold

(Feel free to unhold whenever you'd like)

**Pull request merged**
