### PR TITLE
:seedling:  Add killianmuldoon to bootstrap + docs reviewers

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

PR to add myself as a reviewer on PRs in the /docs and /bootstrap owners aliases :smile:

### CODE REVIEW

**Comment by sbueringer** [comment]
Thanks for stepping up and for all your past and ongoing contributions!!!

+1 from my side

**Comment by fabriziopandini** [comment]
Yay! thanks for stepping up @killianmuldoon 
+1

**Comment by vincepri** [comment]
+1
/lgtm

/hold
for community meeting

**Comment by CecileRobertMichon** [comment]
+1 👏

**Comment by elmiko** [comment]
+1 :rocket:

**Comment by stmcginnis** [comment]
+1
/lgtm

**Pull request merged**
