### PR TITLE
:sparkles: Dynamic CRS templating

### PR DESCRIPTION
**Pull request by bigkevmcd**
**What this PR does / why we need it**:

This adds templating to CRS objects as they are being inserted into the remote cluster.

Standard Go templating is used, and cluster is made available as the context, along with a couple of helper functions to help with getting annotations and labels from the cluster.

This can be useful if you want to create objects in the remote cluster that are dynamic, based on the cluster that has been created.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by mdbooth — CHANGES_REQUESTED** [review]
The values which can be templated and their paths become part of the API. In this PR we're passing in the whole cluster object. Some thoughts:

Do we need to pin the version of the cluster object to the version of the ClusterResourceSet? If the CRS is v1beta1 but the cluster is v1, do we downgrade the cluster to v1beta1 before templating?

Are all parts of the cluster object safe for templating? For example, if a user can manipulate a cloud to produce a particular error message in Status.FailureMessage, can they use that to alter the structure of the rendered object in a manner which isn't safe?

If we went this route it's probably worth reducing the surface of issues like these by creating a new struct which contains values intended for templating.
* Changes to permitted templated values are isolated, easier to document, and easier to reason about across upgrades.
* Permitted templated values can be restricted to values which are known to be safe.

**Comment by bigkevmcd** [comment]
> The values which can be templated and their paths become part of the API. In this PR we're passing in the whole cluster object. Some thoughts:
> 
> Do we need to pin the version of the cluster object to the version of the ClusterResourceSet? If the CRS is v1beta1 but the cluster is v1, do we downgrade the cluster to v1beta1 before templating?

Do we gain anything here?

> 
> Are all parts of the cluster object safe for templating? For example, if a user can manipulate a cloud to produce a particular error message in Status.FailureMessage, can they use that to alter the structure of the rendered object in a manner which isn't safe?

I'd propose to simplify it to just the `ObjectMeta` and `Spec` fields.

The [data](https://pkg.go.dev/text/template#Template.Execute) parameter could be altered to...
```go
map[string]interface{}{
    "cluster": map[string]interface{}{
        "meta": cl.ObjectMeta,
        "spec": cl.Spec,
        }
    }
```
Honestly tho', my primary use-case is extracting data that was placed as annotations/labels on the `Cluster` specifically to configure the CRS that is placed into the remote cluster, so I could do without the Spec.

> If we went this route it's probably worth reducing the surface of issues like these by creating a new struct which contains values intended for templating.

Does the simplified data above work for you?

While I could "simplify" the `ObjectMeta` and `Spec` further, it feels like the cost of maintaining the mapping from fields in the `Cluster` to fields in the provided data map, would be significant (both technically, and from a UX perspective).
 
> * Changes to permitted templated values are isolated, easier to document, and easier to reason about across upgrades.
> * Permitted templated values can be restricted to values which are known to be safe.

I _think_ this addresses this issue?

**Comment by mdbooth** [comment]
> > The values which can be templated and their paths become part of the API. In this PR we're passing in the whole cluster object. Some thoughts:
> > Do we need to pin the version of the cluster object to the version of the ClusterResourceSet? If the CRS is v1beta1 but the cluster is v1, do we downgrade the cluster to v1beta1 before templating?
> 
> Do we gain anything here?

I was thinking more about if we lose something. For example, if we remove a field in v1 our template which is expecting fields from v1beta1 may explode. If we handle templated data separately we have an opportunity to manage things like this explicitly.

> > Are all parts of the cluster object safe for templating? For example, if a user can manipulate a cloud to produce a particular error message in Status.FailureMessage, can they use that to alter the structure of the rendered object in a manner which isn't safe?
> 
> I'd propose to simplify it to just the `ObjectMeta` and `Spec` fields.
> 
> The [data](https://pkg.go.dev/text/template#Template.Execute) parameter could be altered to...
> 
> ```go
> map[string]interface{}{
>     "cluster": map[string]interface{}{
>         "meta": cl.ObjectMeta,
>         "spec": cl.Spec,
>         }
>     }
> ```
> 
> Honestly tho', my primary use-case is extracting data that was placed as annotations/labels on the `Cluster` specifically to configure the CRS that is placed into the remote cluster, so I could do without the Spec.
> 
> The above data would result in templating that was more explicit, `{{ cluster.meta.Name }}` for example to grab the cluster name, but could also use the `label` and `annotation` functions that are provided e.g. `{{ annotation "example.com/testing" }}`.
> 
> > If we went this route it's probably worth reducing the surface of issues like these by creating a new struct which contains values intended for templating.
> 
> Does the simplified data above work for you?
> 
> While I could "simplify" the `ObjectMeta` and `Spec` further, it feels like the cost of maintaining the mapping from fields in the `Cluster` to fields in the provided data map, would be significant (both technically, and from a UX perspective).

I would still worry about 'accidental API', and about some potential brain twisters during API upgrades. I was thinking something more like:

```go
struct {
    ClusterName string
    ClusterAnnotations map[string]string
    ClusterLabels map[string]string
}
```

New values can be added explicitly as required, and we're not accidentally adding anything we haven't thought about carefully in advance.

**Comment by fabriziopandini** [comment]
/lifecycle frozen
/hold

let's keep this around until the corresponding proposal get's merged https://github.com/kubernetes-sigs/cluster-api/pull/6555

**Pull request closed without merging**
