### PR TITLE
📖 Update CAPI support and guarantees for v1.9

### PR DESCRIPTION
**Pull request by chandankumar4**
**What this PR does / why we need it**:
- This PR updates the supported versions for the release cycle (1.9).

@kubernetes-sigs/cluster-api-release-team

/area documentation

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
only note from my side:

There are two half on this PR
- Drop 1.5 column, mark 1.6 version as EOL
- Add 1.9 column

The first half has to be back ported to the release-1.8 branch, the second no.
I'm not sure how this has been done in the past, but please keep it in mind for the backport

**Comment by fabriziopandini** [comment]
/hold

This seems a duplicate of https://github.com/kubernetes-sigs/cluster-api/pull/11151
cc @Sunnatillo

**Comment by fabriziopandini** [comment]
@chandankumar4 could you kindly open the manual cherry pick as per https://github.com/kubernetes-sigs/cluster-api/pull/11163#pullrequestreview-2292057539?

**Comment by sbueringer** [comment]
Usually we don't add information about v1.9 to the v1.8 book. Or do you mean only cherry-pick a subset of this PR?

**Comment by fabriziopandini** [comment]
I have raised the same question in https://github.com/kubernetes-sigs/cluster-api/pull/11163#pullrequestreview-2292057539, proposing a manual cherry pick that we need as soon as possible (1.6 is EOS from ~1m now, and the book still reports it as supported).
cc @Sunnatillo

**Comment by sbueringer** [comment]
Ah my bad, missed that comment. Makes sense!

**Comment by chandankumar4** [comment]
Have raised the manual cherry-pick PR https://github.com/kubernetes-sigs/cluster-api/pull/11177
@fabriziopandini

**Comment by Sunnatillo** [comment]
Part of https://github.com/kubernetes-sigs/cluster-api/issues/11092

**Pull request merged**
