### PR TITLE
🌱 Update references following Flatcar GitHub org rename

### PR DESCRIPTION
**Pull request by johananl**
**What this PR does / why we need it**: The flatcar-linux GitHub organization is being renamed to "flatcar". This PR updates all references accordingly.

Upstream issue: https://github.com/flatcar-linux/Flatcar/issues/836

I'm opening this PR in advance to allow quick merging once the rename occurs. I'll mark it as on hold in the meantime.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
None

## TODO (after the rename)

- [x] Run `go mod tidy` and ensure correct update of all `go.sum` files.
- [x] Run `make generate-modules`.
- [x] Verify everything compiles and runs.
- [x] Verify tests are passing.
- [x] Verify CI is green.

### CODE REVIEW

**Comment by johananl** [comment]
/hold

(see description for explanation)

**Comment by chrischdi** [comment]
I think it requires a `make generate-modules` :-)

**Comment by johananl** [comment]
> 

Cool, I'll add it to the TODO for after the rename (can't do it now).

**Comment by t-lo** [comment]
> Does GitHub have any kind of redirect from old to new org name? IIRC there was one at least in the browser when cert-manager changed orgs.

Yes, redirects should be in place automatically after the rename and URLs using `flatcar-linux/...` should continue to work. We've been working with GitHub support (which has been awesome tbh) to ensure this does not break 3rd parties.

> Considering all that, do we have to make the same change on all branches of CAPI that should still compile after the org rename?

I'd argue this depends on the CAPI release cycle and support lifetime of older releases. Given that we take care of redirects and old URLs continuing to work it might well be an option to just "age" the old references out instead of back-porting.

**Comment by sbueringer** [comment]
Sounds good. Thx!

Then we'll merge this PR on main and maybe do one backport to release-1.2 but that should be good enough.

**Review by invidian — COMMENTED** [review]
/lgtm

**Comment by johananl** [comment]
PR is ready for merging.

/unhold

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-main

/lgtm

approval after the ignition test which is run as part of e2e-full is green

**Comment by sbueringer** [comment]
Thx!!

/approve

/cherry-pick release-1.2

**Comment by sbueringer** [comment]
@johananl Can you please create a manual cherry-pick PR for this change for release-1.2? Thank you!

**Comment by johananl** [comment]
Maybe I should do something like `git cherry-pick -m 1 a86df7130` 🤔

**Comment by johananl** [comment]
@sbueringer I've opened https://github.com/kubernetes-sigs/cluster-api/pull/7217. Hope it's good.

**Comment by sbueringer** [comment]
Thx! Essentially I just meant, open a PR with the same changes onto release-1.2. Not really important how :)

I'll review on the other PR

**Pull request merged**
