### PR TITLE
🌱 Use rest config from ClusterCacheTracker consistently

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Had to fix a unit test

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve
/hold

**Comment by killianmuldoon** [comment]
Feel free to remove /hold when you're happy this is ready.

**Comment by fabriziopandini** [comment]
/lgtm
feel free to unhold

@sbueringer one question:
should we deprecate NewClusterClient and RESTConfig (and make them private in a follow-up release), so we prevent issues like this to pop back in the future?

**Comment by sbueringer** [comment]
> /lgtm feel free to unhold
> 
> @sbueringer one question: should we deprecate NewClusterClient and RESTConfig (and make them private in a follow-up release), so we prevent issues like this to pop back in the future?

Sounds reasonable to me at a first glance. I would prefer not having to maintain them anymore. But I don't know who is using them and maybe they don't want to use the CCT. For example in a CLI folks might just want to get a rest config for a cluster and then don't want to run an entire CCT for that

**Pull request merged**
