### PR TITLE
:bug: readme: fix typo s/NPT/NTP/

### PR DESCRIPTION
**Pull request by jdef**
**What this PR does / why we need it**:

fix typo

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by detiber** [comment]
@jdef thanks for catching this. Once the CLA issue is resolved we can get this merged.
/ok-to-test
/approve

**Comment by detiber** [comment]
@jdef the cla shouldn't expire...  but it might be failing to match on email address or similar.

The github UI doesn't give me much insight, but it does appear that your previous commits such as https://github.com/kubernetes/kubernetes/pull/24916/commits/a74573277f81565b3aeff8c5d4bfe2a3110c1ccd have slightly different authorship than https://github.com/kubernetes-sigs/cluster-api/pull/1568/commits/d4c260e1e53963f5b69612ca09107dc16e27d9b1

**Comment by ncdc** [comment]
@jdef have you been able to double check your CLA status with the email address you used on this commit?

**Comment by jdef** [comment]
AFAICT I've signed it: https://github.com/cncf/gitdm/blob/e242a451fff02a436b6d0a078b9f31a7121e8a01/developers_affiliations1.txt#L15721

I no longer work for Mesosphere, and I made this contribution as an Individual. Do I need to send a PR to gitdm to be reclassified as Individual?

**Comment by detiber** [comment]
> AFAICT I've signed it: https://github.com/cncf/gitdm/blob/e242a451fff02a436b6d0a078b9f31a7121e8a01/developers_affiliations1.txt#L15721

> I no longer work for Mesosphere, and I made this contribution as an Individual. Do I need to send a PR to gitdm to be reclassified as Individual?

I definitely would suggest updating gitdm for the correct information, however gitdm is used for attribution of contributions rather than CLA adherence. You will likely need to re-sign the CLA as an individual

**Comment by ncdc** [comment]
@jdef hi, just checking in! Any luck getting your CLA updated?

**Comment by jdef** [comment]
I signed it

**Comment by ncdc** [comment]
Make sure the email address for your git commit (your g-mail account) is the same email configured for your account at https://identity.linuxfoundation.org/user/me/edit

**Comment by jdef** [comment]
fixed by another PR that landed while I was fighting with the CLA bot

**Pull request closed without merging**
