### PR TITLE
🌱 e2e: Resolve flake: Wait for controlplane to be available on management cluster

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This PR fixes a flake on kcp-adoption e2e test due to the code querying for object aggressively after apply

### CODE REVIEW

**Comment by vincepri** [comment]
@fabriziopandini Can we adjust the title to include what the fix is?

**Comment by randomvariable** [comment]
/retitle 🌱 e2e: Resolve flake: Wait for controlplane to be available on management cluster

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
