### PR TITLE
:warning: Set InfrastructureReady before APIEndpoint

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by detiber** [comment]
/lgtm
/hold
holding for review from @akutz

**Comment by akutz** [comment]
/lgtm

Thanks for this @vincepri.

**Pull request merged**
