### PR TITLE
🌱 Bump versions to v1.3

### LINKED ISSUE #6833: Prepare main branch for v1.3 development
Let's prepare the main branch for v1.3 development.

This issue is mostly about changing all occurrences of the CAPI v1.2.x version to v1.3.x

As far as I'm aware we have to do the following:

* Add new release to top-level metadata.yaml and test/e2e/data/shared/v1beta1/metadata.yaml
* Update providers in docker.yaml. Roughly:
   * create a new entry for each provider for v1.2.0
    * rename v1.2.99 to v1.3.99
* Update create-local-repository.py: v1.2.99 => v1.3.99
* Update tools/tilt-prepare/main.go: v1.2.99 => v1.3.99
* Make sure CI is green (on the PR: `/test pull-cluster-api-e2e-full-main` and `/test pull-cluster-api-e2e-workload-upgrade-1-23-latest-main`)

Part of #6615

/kind feature

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

This PR bumps the versions in the main branch for v1.3 developemt.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6833

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm
/approve

Agree with the hold. Although we only need it for the clusterctl upgrade job. If we're willing to let clusterctl v1.2=>main fail until the release we could merge this PR and the one in test-infra. But I'm fine with holding both until the release

**Comment by sbueringer** [comment]
@ykakarap WDYT about using our own beta.2 for now and bumping later after the release?
This way we could already verify our own beta release.

We would have to:
* on this PR:
    * change the URLs for v1.2.0 to ~ `https://github.com/kubernetes-sigs/cluster-api/releases/download/v1.2.0-beta.2/core-components.yaml` (the name *has* to stay the same)
* on the test infra PR
   * Also use the beta.2 in `INIT_WITH_BINARY`

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-main
/test pull-cluster-api-e2e-workload-upgrade-1-21-1-22-main
(using 1.21=>1.22 as 1.24=>latest is broken)

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
Merged the test-infra job as well, so we should have some results in testgrid soon

**Comment by sbueringer** [comment]
@ykakarap clusterctl upgrade to beta2 looks good: https://testgrid.k8s.io/sig-cluster-lifecycle-cluster-api#capi-e2e-upgrade-v1-2-to-main

**Pull request merged**
