### PR TITLE
[release-1.2] ⚠️ KCP: block upgrade to versions with old registry, improve registry handling

### PR DESCRIPTION
**Pull request by sbueringer**
handling

Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Manual cherry-pick of #7856

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @fabriziopandini

**Comment by sbueringer** [comment]
/retest

I'll try to reproduce locally in parallel

**Comment by sbueringer** [comment]
I think it's a flake. Looks like a kube-apiserver Pod didn't come up for some reason. On my machine the same test was green

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
