### PR TITLE
[rbac] There are roles missing in the clusterapiservertemplate file.

### PR DESCRIPTION
**Pull request by alejandroEsc**
**What this PR does / why we need it**: Some cluster role bindings were missing as suggested in https://github.com/kubernetes-incubator/apiserver-builder/blob/master/docs/concepts/auth.md. 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```
missing rbac resources added to apiserverclusterapiservertemplate file.
```

### CODE REVIEW

**Comment by davidewatson** [comment]
Should common code make assumptions about cluster-scoped resources (e.g. `ClusterRole`s, `Namespaces`s, etc.)? Maybe not.

Even still, I tend to favor merging this, or some other common code which providers can share. Each provider shouldn't have to create this `ClusterRolBinding`...

**Comment by roberthbailey** [comment]
@davidewatson - embedding this yaml inside the code probably isn't a great idea long term, but for now I think it makes sense to make the role bindings correct. Any objections to merging this?

**Comment by davidewatson** [comment]
@roberthbailey: lgtm, thanks!

**Pull request merged**
