### PR TITLE
📖 book: add download links for all clusterctl architectures to quick start

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

Adds all architectures ([listed in Makefile](https://github.com/kubernetes-sigs/cluster-api/blob/97573c15810fc2ae279d7d44e788139307dc9432/Makefile#L911-L917)) to the Quick Start docs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by ykakarap — APPROVED** [review]
/lgtm

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm 
/approve

**Comment by sbueringer** [comment]
@oscr looks like the automatic cherry-picks failed. What do you think about opening a manual cherry-pick for v1.3? (not sure if v1.2 is important, v1.3 is the one currently hosted on https://cluster-api.sigs.k8s.io/)

**Comment by oscr** [comment]
@sbueringer No problem! Will fix it when I get home.

**Comment by sbueringer** [comment]
Sure, no rush! Thx!

**Pull request merged**
