### PR TITLE
 🌱 include deamonsets in list images in clusterctl - 0.3.x

### LINKED ISSUE #4858: Backport list images daemon set fix to 0.3.x
**User Story**

Backport #4455 to 0.3.x

**Detailed Description**

[A clear and concise description of what you want to happen.]

**Anything else you would like to add:**

[Miscellaneous information that will assist in solving the issue.]

/kind feature

### PR DESCRIPTION
**Pull request by shysank**
**What this PR does / why we need it**:
Backports #4455 
**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4858

### CODE REVIEW

**Comment by shysank** [comment]
cc: @fabriziopandini @randomvariable

**Comment by randomvariable** [comment]
My understanding is this is required for multi-tenancy support on CAPZ on v1alpha3 which is why it's a backport candidate.

Is that correct @nader-ziada @CecileRobertMichon ?

**Comment by randomvariable** [comment]
otherwise
/lgtm

**Comment by nader-ziada** [comment]
> My understanding is this is required for multi-tenancy support on CAPZ on v1alpha3 which is why it's a backport candidate.
> 
> Is that correct @nader-ziada @CecileRobertMichon ?

yes, its need to support the image of `nmi` which is used by capz multi-tenancy and is a deamonset

**Comment by CecileRobertMichon** [comment]
> My understanding is this is required for multi-tenancy support on CAPZ on v1alpha3 which is why it's a backport candidate.

We didn't add support for multi-tenancy until v1alpha4, I don't think we need it in alpha3?

Also, since v0.4.0 is out, we shouldn't be backporting to release-0.3 anymore unless absolutely necessary

**Comment by nader-ziada** [comment]
> > My understanding is this is required for multi-tenancy support on CAPZ on v1alpha3 which is why it's a backport candidate.
> 
> We didn't add support for multi-tenancy until v1alpha4, I don't think we need it in alpha3?
> 
> Also, since v0.4.0 is out, we shouldn't be backporting to release-0.3 anymore unless absolutely necessary

the nmi image in capz was included at v1alpha3

**Comment by CecileRobertMichon** [comment]
> the nmi image in capz was included at v1alpha3

My bad, you are correct. In that case, +1 to backporting.

/assign @fabriziopandini @vincepri

**Comment by shysank** [comment]
> We didn't add support for multi-tenancy until v1alpha4, I don't think we need it in alpha3?
>

I think we support multi tenancy in v1alpha3, the only change in v1alpha4 was the change in `namespacesAllowed` logic. Correct me if I'm wrong @nader-ziada

**Comment by nader-ziada** [comment]
> > We didn't add support for multi-tenancy until v1alpha4, I don't think we need it in alpha3?
> 
> I think we support multi tenancy in v1alpha3, the only change in v1alpha4 was the change in `namespacesAllowed` logic. Correct me if I'm wrong @nader-ziada

correct

**Comment by nader-ziada** [comment]
lgtm

**Comment by shysank** [comment]
@CecileRobertMichon Since Vince and Fabrizio are ooo this week, can I assign this to you?

**Pull request merged**
