### PR TITLE
🌱 Release v1.5.4

### PR DESCRIPTION
**Pull request by g-gaston**
/area release

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/approve
/hold

**Review by furkatgofurov7 — APPROVED** [review]
/approve

Unless there is no diff between now and the time we merge this PR

**Comment by furkatgofurov7** [comment]
> /approve
> 
> Unless there is no diff between now and the time we merge this PR

This is up-to-date, can be merged

**Pull request merged**
