### PR TITLE
:bug: unmarshal data to a pointer when parsing kubetest config

### PR DESCRIPTION
**Pull request by randomvariable**
Cherry pick of #4774 on release-0.3.

For details on the cherry pick process, see the [cherry pick requests](https://git.k8s.io/community/contributors/devel/sig-release/cherry-picks.md) page.

### CODE REVIEW

**Comment by randomvariable** [comment]
Not sure what happened with the title here...

**Review by vincepri — APPROVED** [review]
/lgtm

**Review by benmoss — APPROVED** [review]

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
