### PR TITLE
🌱 Bump controller-tools to v0.11.3

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
I only bumped it in the Makefile the last time and forgot hack/tools/go.mod.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
@killianmuldoon feel free to merge :D

**Comment by killianmuldoon** [comment]
😄 
/approve

**Comment by sbueringer** [comment]
/hold

Sorry. Maybe I'll bump directly to v0.11.3 which might be released soon

**Comment by sbueringer** [comment]
@killianmuldoon Should be good now

And after this PR we can use example markers :rocket:

**Review by killianmuldoon — APPROVED** [review]
/lgtm
/approve

**Pull request merged**
