### PR TITLE
📖 Remove Alibaba and Baidu Cloud from providers list

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

Removes two seemingly abandoned providers as discussed in issue #6714

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold
Let's ping maintainer for those projects and give them 1 or two weeks to reply
Also before dropping some providers it will be great to formalize criteria we are applying/get community agreement

**Comment by oscr** [comment]
https://github.com/oam-oss/cluster-api-provider-alicloud/issues/1

**Pull request merged**
