### PR TITLE
[release-1.2] 🌱 test/e2e: Cleanup test files

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Manual cherry-pick of https://github.com/kubernetes-sigs/cluster-api/pull/7825

Might need a few tries to get the tests green. I re-implemented the PR as 1.2 is just too different

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
It seems everything worked well. Let's make another round

/test pull-cluster-api-e2e-full-release-1-2
/test pull-cluster-api-e2e-workload-upgrade-1-26-latest-release-1-2

**Comment by sbueringer** [comment]
Looks like an unrelated flake
/retest

**Comment by sbueringer** [comment]
@fabriziopandini should be good to go

**Pull request merged**
