### PR TITLE
:seedling:  Use quiet mode on markdown link checker

### PR DESCRIPTION
**Pull request by killianmuldoon**
This updates the markdown lint checker config to only produce errors.

Fixes #

### CODE REVIEW

**Comment by killianmuldoon** [comment]
The quiet mode still spits out each file its checking, but it no longer produces the full list of links which is an improvement, but not ideal: https://github.com/kubernetes-sigs/cluster-api/runs/5234540056?check_suite_focus=true

**Comment by sbueringer** [comment]
Not sure how it looked before, but that looks easily grepp'able
```yaml
ERROR: 1 dead links found!
[✖] https://-0-3.cluster-api.sigs.k8s.io/user/quick-start.html → Status: 0
```

**Comment by sbueringer** [comment]
> I think this is the best we'll get without updating the JS code and picking up a new linter. WDYT about merging this for now as it makes the output more readable?

Easily a big improvement. So +1 from my side
/lgtm

**Comment by sbueringer** [comment]
cc @CecileRobertMichon

**Comment by CecileRobertMichon** [comment]
/lgtm
/approve

Definitely better

**Pull request merged**
