### PR TITLE
📖  Docs/remove self links

### PR DESCRIPTION
**Pull request by killianmuldoon**
Remove the remaining links to the web version of the book from the book text. This ensure that older versions of the book should continue to work by linking to their own versions of pages even when those pages are removed from the book in later versions.

Relates to  #6028

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!
Looks good +/- whatever the linkchecker is complaining about

**Comment by killianmuldoon** [comment]
testgrid is being a little flaky itself today - a least for our link checker 😄

**Comment by sbueringer** [comment]
/lgtm
by just reviewing the code (I don't want to wait for the linkchecker to finish)

**Comment by killianmuldoon** [comment]
My force push (in case there's another) is just a 'retry' btw

**Pull request merged**
