### PR TITLE
✨ Add k0smotron provider

### PR DESCRIPTION
**Pull request by makhov**
**What this PR does / why we need it**:

Adds k0smotron provider.

[K0smotron](https://github.com/k0sproject/k0smotron/) is an infrastructure, bootstrap, and control plane provider. Uses `k0s` as Kubernetes distro.

### CODE REVIEW

**Comment by chrischdi** [comment]
Maybe blocked by #9975 which changes the naming rules.

**Comment by sbueringer** [comment]
> Maybe blocked by #9975 which changes the naming rules.

Yup, it's very likely #9975 will be merged (and soon). So we should already hold merging PRs that don't comply to the new naming rules

**Comment by makhov** [comment]
Thanks! I renamed `k0smotron` to `k0sproject-k0smotron`.

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

We should be able to merge this once #9975 is merged

**Pull request merged**
