### PR TITLE
🌱Upgrade corefile migration to v1.0.11

### LINKED ISSUE #3851: Update corefile-migration dependency to v1.0.11
**User Story**

As a user I would like to have support for future kubernetes upgrades which include newer versions of coredns

**Detailed Description**

v1.0.11 of corefile-migration was recently released, we should update to it to proactively support future k8s releases which will require newer versions of coredns

/kind feature

### PR DESCRIPTION
**Pull request by arghya88**
**What this PR does / why we need it**:

Upgrade corefile migration to v1.0.11 from v1.0.10

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3851

### CODE REVIEW

**Comment by vincepri** [comment]
@arghya88 Run `make modules` to update the go module files

**Comment by vincepri** [comment]
@arghya88 After this merges, are you able to open a PR to do the same change against the `release-0.3` branch?

**Comment by arghya88** [comment]
> @arghya88 After this merges, are you able to open a PR to do the same change against the `release-0.3` branch?

Yes sure

**Comment by detiber** [comment]
/lgtm
+1 to a backport PR for `release-0.3` branch

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
