### PR TITLE
:sparkles: Add Makefile targets for clusterctl unit test

### PR DESCRIPTION
**Pull request by Jaakko-Os**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by vincepri** [comment]
`make test` should cover all tests in the whole project, unless I'm missing something

**Comment by Jaakko-Os** [comment]
Yes I agree.
My goal was to run tests in clusterctl scope only and avoid running all. These options were not available earlier. Also I find the test coverage option quite informative for unit testing.
Ofcourse the coverage could be run during 'make test' instead clusterctl only. It would mean increased test execution time.
Please instruct how to move forward.

**Comment by vincepri** [comment]
Thanks for the explaination @Jaakko-Os I'd say to run specific tests usually we either rely on an editor or leave it to the user to run `go test` manually. 

Instead of having new make targets, we could potentially expand `make test` to accept some parameters and keep the default the same as they are today. For example we could have `TEST_PATH` to default to `./...`, and `TEST_FOCUS` that conditionally addds `-run <TEST_FOCUS>`, etc.

Regarding coverage, we had it in the past but found it misleading at times so we removed it

**Comment by wfernandes** [comment]
I tend to lean towards using `go test` when I need to test a specific part of the codebase.

- I think it works because if I'm at the top level then I can just run `go test -v TEST_PATH`. I don't see it being that different from `make test TEST_PATH`. 
Also, the former style works if you are inside the directory as well whereas `make` only works from the top level (unless you use `make -C`).

- I can also use flags like `-race` and `-count` with `go test` directly.

Regarding coverage, I think it can be helpful for developers to perform against specific parts of the codebase during their development but I don't think it should be used as a flag or condition for PRs being accepted.

**Comment by Jaakko-Os** [comment]
Thank you all for explanations. I'll close this PR.

**Pull request closed without merging**
