### PR TITLE
🌱 hack/observability: add metrics-server chart

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Is this just an add-on or is it useful on top of prometheus / node-exporter in some way? Should we just deploy node-exporter?

**Comment by sbueringer** [comment]
> Is this just an add-on or is it useful on top of prometheus / node-exporter in some way? Should we just deploy node-exporter?

This is useful because it allows to get a quick overview over the resource usage in a cluster with kubectl top node/pod.

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
