### PR TITLE
[release-1.5] ✨ ClusterClass: Introduce NamingStrategy and allow generating names using go templates

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

This is a manual cherry-pick of:

- #9340
- #9425

The changes are only part of the experimental topology feature.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area topology

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

/hold

For CI

**Comment by sbueringer** [comment]
I'll do a quick review after lunch

**Comment by sbueringer** [comment]
/hold cancel

🎉

**Pull request merged**
