### PR TITLE
Added ibm cloud to architecture diagram.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

/cc @detiber @vincepri

### CODE REVIEW

**Comment by davidewatson** [comment]
I have a mild concern about adding icons to this list since eventually, we will not be able to list them all... That said, can we move the IBM icon after Google so that the cloud providers remain in alphabetical order?

**Comment by gyliu513** [comment]
@davidewatson seems we are already out of order, `Bare Metal` is at last.

I have an issue opened at https://github.com/kubernetes-sigs/cluster-api/issues/935 and want to enable us can commit the RAW file for all of the images so that people can update it at ease.

**Comment by gyliu513** [comment]
@davidewatson seems we are already out of order, `Bare Metal` is at last.

I have an issue opened at https://github.com/kubernetes-sigs/cluster-api/issues/935 and want to enable us can commit the RAW file for all of the images so that people can update it at ease.

**Comment by davidewatson** [comment]
Bare metal is not a concrete provider; it is a catch-all for many different possible implementations. Are you saying it is difficult for you to make the change until #935 is addressed?

**Comment by russellb** [comment]
> Bare metal is not a concrete provider; it is a catch-all for many different possible implementations. Are you saying it is difficult for you to make the change until #935 is addressed?

just fyi, there is a provider implementing automated bare metal host provisioning called cluster-api-provider-baremetal (https://github.com/metal3-io/cluster-api-provider-baremetal).  For a generic catch all, maybe something like "custom infrastructure" or something?

**Comment by gyliu513** [comment]
@davidewatson I can move it after Google Cloud, will update the PR later.

Still not clear for why baremetal is not a concrete provider, as we already have a provider at  https://github.com/metal3-io/cluster-api-provider-baremetal @russellb @davidewatson

**Comment by davidewatson** [comment]
Thanks @gyliu513.

I think there is a difference between specific company names and the general phrase "bare metal". While I am aware of the implementation referenced, it is relatively new, and as far as I am aware, is not a source of confusion.

**Comment by davidewatson** [comment]
Also, @russellb unless you are concerned there will be confusion, I think the phrase "bare metal" is fine. I am excited about the https://github.com/metal3-io/cluster-api-provider-baremetal provider but it is not the first provider for "custom infrastructure"...

**Comment by gyliu513** [comment]
@davidewatson Done, moved IBM icon after Google.

**Pull request merged**
