### PR TITLE
⚠️ Remove all v1alpha1 code

### LINKED ISSUE #1503: Remove all v1alpha1 code
Remove v1alpha1 types, conversion functions, and anything else referencing v1alpha1
/kind feature
/milestone v0.3.0
/priority important-soon
/help

### PR DESCRIPTION
**Pull request by tahsinrahman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1503

### CODE REVIEW

**Comment by ncdc** [comment]
We may want to keep conversion-gen around because we're going to need conversion webhooks to go between v1alpha2 and v1alpha3 (I assume conversion-gen helps with that).

**Comment by tahsinrahman** [comment]
> We may want to keep conversion-gen around because we're going to need conversion webhooks to go between v1alpha2 and v1alpha3 (I assume conversion-gen helps with that).

@ncdc updated, does it look ok now?

**Comment by detiber** [comment]
> We may want to keep conversion-gen around because we're going to need conversion webhooks to go between v1alpha2 and v1alpha3 (I assume conversion-gen helps with that).

I do not believe that kubebuilder uses conversion-gen, at least according to the scaffolded [makefile](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/v2/makefile.go) or [go.mod](https://github.com/kubernetes-sigs/kubebuilder/blob/master/pkg/scaffold/v2/gomod.go).

I believe they implement their own generator, similar to the other generators.

**Comment by ncdc** [comment]
It doesn't look like kubebuilder does it by default, but if we can take advantage of generated conversions, it's probably worthwhile.

**Comment by vincepri** [comment]
@tahsinrahman Can you rebase to resolve the conflict

otherwise LGTM, @ncdc ?

**Comment by tahsinrahman** [comment]
rebased :)

**Comment by vincepri** [comment]
Can you squash commits in a single one? They seem all related

**Comment by tahsinrahman** [comment]
> Can you squash commits in a single one? They seem all related

@vincepri done!

**Pull request merged**
