### PR TITLE
🐛 fix: markdown broken links

### PR DESCRIPTION
**Pull request by adityabhatia**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area documentation

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks!

/lgtm
/appove

**Review by stmcginnis — COMMENTED** [review]
Is there a different doc that can be linked to. I get that the current one no longer worked, but if there is another copy out there, that would be good historical information to have.

**Comment by adityabhatia** [comment]
> Is there a different doc that can be linked to. I get that the current one no longer worked, but if there is another copy out there, that would be good historical information to have.

I tagged the original contributor in this [slack thread](https://kubernetes.slack.com/archives/C8TSNPY4T/p1707298171904929) . It's unfortunately an old proposal so not sure if that exists. 
cc: @pydctw

**Pull request merged**
