### PR TITLE
Apply k8s 1.18.5 

### PR DESCRIPTION
**Pull request by tomahawk28**
**What this PR does / why we need it**:

Apply the latest k8s 1.18 clientgo changes. (1.18.5) and update cluster-runtime as well to sync with that.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
I'm not sure this is something we want to do now in the v0.3.x series or wait for the upcoming v0.4.x (and wait for v1.19), but I leave this call to @vincepri 
/ok-to-test

**Comment by ncdc** [comment]
/hold

I don't think we should change Kubernetes, controller-runtime, client-go, etc. dependency versions until we change to a new minor version (0.4.x). We can discuss the timeline for moving the main branch to 0.4 and creating a release-0.3 branch for any future bug fixes during today's community meeting.

/milestone v0.4.0

**Comment by vincepri** [comment]
Thanks for bringing this up, we've actually discussed a similar change in #2961 and ultimately decided to wait during a community meeting to only upgrade dependencies like these when working on the next minor release.

**Comment by puja108** [comment]
Thanks for the quick feedback. We just discussed this internally and as the decision to only work on such upgrades in the next minor for this group makes sense, we'll be evaluating if we can in the mean-time just run our own fork with v1.18 to solve our dependency issues until we again align with the next minor upstream and then might just be v1.19.

**Comment by vincepri** [comment]
Thanks for understanding @puja108 and @tomahawk28, I'll close down this PR for now, given that usually these dependencies get updated with controller-runtime.

/close

**Pull request closed without merging**
