### PR TITLE
🌱 Bump kustomize version to 3.9.1

### PR DESCRIPTION
**Pull request by fmuyassarov**
**What this PR does / why we need it**:
Bump kustomize version to [3.9.1](https://github.com/kubernetes-sigs/kustomize/releases/tag/kustomize%2Fv3.9.1).

### CODE REVIEW

**Comment by detiber** [comment]
@fmuyassarov can you elaborate on the purpose of the version bump?

Is it to fix a bug?
Is it to enable a feature?
Is it just syncing with latest?

**Comment by fmuyassarov** [comment]
> @fmuyassarov can you elaborate on the purpose of the version bump?
> 
> Is it to fix a bug?
> Is it to enable a feature?
> Is it just syncing with latest?

Hi @detiber ,
It is just to sync up with the latest. I just realized that in CAPI it is a bit old version of kustomize after running into an issue where there was the kustomize version mismatches between CAPI and CAPM3. Because, in CAPM3 we were using 3.8.4. And below is an example of the logs from Tilt environment.

```
Traceback (most recent call last):
  /home/fmuyassarov/est/cluster-api/Tiltfile:241:17: in <toplevel>
  /home/fmuyassarov/est/cluster-api/Tiltfile:224:24: in enable_providers
  /home/fmuyassarov/est/cluster-api/Tiltfile:209:17: in enable_provider
  <builtin>: in k8s_yaml
Error: Empty YAML passed to k8s_yaml
```
But as said, it just to have the latest version. Feel free to close if you think it is not needed.

**Comment by detiber** [comment]
> But as said, it's just to have the latest version. Feel free to close if you think it is not needed.

Thanks for the info, was mainly trying to understand the rationale.

/ok-to-test

**Comment by fmuyassarov** [comment]
@detiber Shall I re-tigger the CI? I'm not if the failure is somehow related to the change.

```
 I0108 15:10:23.638092   10284 controller.go:129] controller-runtime/manager/controller/machinehealthcheck "msg"="Starting EventSource" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineHealthCheck" "source"={}
=== RUN   TestMachineHealthCheck_Reconcile/it_should_ensure_the_correct_cluster-name_label_when_the_label_has_the_wrong_value
E0108 15:10:23.654034   10284 controller.go:267] controller-runtime/manager/controller/cluster "msg"="Reconciler error" "error"="clusters.cluster.x-k8s.io \"test-cluster-rc2wb\" not found" "name"="test-cluster-rc2wb" "namespace"="test-mhc-sxkfp" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="Cluster" 
E0108 15:10:23.739843   10284 cluster_cache.go:350]  "msg"="Error health checking cluster" "error"="timed out waiting for the condition"  "cluster"="test-mhc-sxkfp/test-cluster-rc2wb"
E0108 15:10:23.743555   10284 controller.go:267] controller-runtime/manager/controller/machinehealthcheck "msg"="Reconciler error" "error"="[MachineHealthCheck.cluster.x-k8s.io \"test-mhc-bkpq8\" not found, machinehealthchecks.cluster.x-k8s.io \"test-mhc-bkpq8\" not found]" "name"="test-mhc-bkpq8" "namespace"="test-mhc-sxkfp" "reconciler group"="cluster.x-k8s.io" "reconciler kind"="MachineHealthCheck" 
```

**Comment by vincepri** [comment]
The verify job should be fixed (that's not a flake), it seems the bindata files need to be regenerated

**Comment by fmuyassarov** [comment]
> The verify job should be fixed (that's not a flake), it seems the bindata files need to be regenerated

@vincepri Do you mean I should run generate-bindata Makefile [target](https://github.com/kubernetes-sigs/cluster-api/blob/953ad253ee2bc169ddda765efe5851c30ffb1def/Makefile#L270) ?

**Comment by fmuyassarov** [comment]
I don't the `make test` failing when running locally :/, or is it a wrong target that I am running locally...

**Comment by fmuyassarov** [comment]
@vincepri I regenerated bindata. Thanks!

**Comment by vincepri** [comment]
@fmuyassarov That seems a flake, we're trying to fix those in separate PRs

**Comment by fmuyassarov** [comment]
@vincepri  Do you think it is good to go now?

**Review by vincepri — APPROVED** [review]
/lgtm
/assign @CecileRobertMichon

**Pull request merged**
