### PR TITLE
🌱 capd: add support for btrfs and zfs

### PR DESCRIPTION
**Pull request by schrej**
**What this PR does / why we need it**:
When using the Btrfs or ZFS storage drivers for docker it is necessary to mount `/dev/mapper` into the container when trying to run kubelet. Otherwise cAdvisor will fail to fetch partition information when the host system is using Btrfs or ZFS, which is a fatal error in kubelet.

Kind ran into the same issue, this PR ports the fix to CAPD: https://github.com/kubernetes-sigs/kind/pull/1464
Issue with more info: https://github.com/kubernetes-sigs/kind/issues/1416#issuecomment-606514724

It probably makes sense to hold off on merging this until #4413 is done, as this currently calls the docker cli.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
I'm generally +1 to the idea; it would be great to add some more colour to the PR description (or to a issue) by describing some use cases where this could be useful

**Comment by sbueringer** [comment]
@schrej I agree with @fabriziopandini. Apart from that I don't think we have to wait for #4413 as it will be split up in individual PRs and will take a bit (/cc @stmcginnis please correct me if you see it differently)

**Comment by stmcginnis** [comment]
I agree, let's not wait on #4413. It needs some work yet. I plan on focusing on it next week after I get back from PTO, but it will still take some time to get everything in order.

**Comment by schrej** [comment]
I've extended the PR description a bit. The use use case for this is running CAPD on a system with Btrfs or ZFS.
Should I just change this to be the first thing using the docker client then?

**Comment by sbueringer** [comment]
@schrej I would advise against that for now :). We're having a discussion about go modules right now in https://github.com/kubernetes-sigs/cluster-api/pull/4499#discussion_r630359066 .

/lgtm

**Pull request merged**
