### PR TITLE
🌱 Upgrade to controller-runtime v0.11.2

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This PR upgrades to the recently released controller-runtime v0.11.2: https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.11.2

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by JoelSpeed — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Had to run generate-modules twice somehow..

**Comment by sbueringer** [comment]
/cherry-pick release-1.1

I didn't find anything critical in the controller-runtime and Kubernetes changelog, but I think it doesn't hurt to use the newer version in the next v1.1 release

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by JoelSpeed** [comment]
> I didn't find anything critical in the controller-runtime and Kubernetes changelog, but I think it doesn't hurt to use the newer version in the next v1.1 release

FWIW, I also had a scan over the changelogs and agree with this assessment

**Pull request merged**
