### PR TITLE
 🐛 Update MachineDeployment controller image in docs

### LINKED ISSUE #2867: Book's MachineDeployment page shows MachineSet controller flow
This page https://cluster-api.sigs.k8s.io/developer/architecture/controllers/machine-deployment.html shows the incorrect flow (MachineSet), instead of the MachineDeployment one.

/kind documentation
/help
/milestone v0.3.x

### PR DESCRIPTION
**Pull request by prankul88**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #2867

### CODE REVIEW

**Comment by prankul88** [comment]
@JoelSpeed Should I update it here?

**Comment by JoelSpeed** [comment]
Up to you, if you wouldn't mind doing so then that's great, otherwise we can follow up another time

**Comment by prankul88** [comment]
@JoelSpeed Have updated. PTAL

**Comment by prankul88** [comment]
@JoelSpeed Sorry forgot about that. Updating..

**Comment by prankul88** [comment]
@JoelSpeed Done. Please see if anything needs to be updated

**Pull request merged**
