### PR TITLE
🌱 Fix typo in clusterctl client test

### PR DESCRIPTION
**Pull request by windayski**
**What this PR does / why we need it**:
Fix a typo in clusterctl client test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by arghya88 — COMMENTED** [review]
/lgtm

**Comment by arghya88** [comment]
@windayski Just retitle the PR to have 🌱instead of 🐛

**Comment by vincepri** [comment]
/retitle 🌱 Fix typo in clusterctl client test

**Review by vincepri — APPROVED** [review]

**Pull request merged**
