### PR TITLE
Fix e2e link

### PR DESCRIPTION
**Pull request by jichenjc**
**What this PR does / why we need it**:
external link test reported error about it ...

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sedefsavas** [comment]
There is one more place we will need this change that points to `docker-dev.yaml`:
 https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/testing.md

**Review by fabriziopandini — COMMENTED** [review]
/approve

**Pull request merged**
