### PR TITLE
🐛 CAPD: Implement watch filter

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
CAPD had the command line flag but wasn't actually using it

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by alexander-demicev — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Comment by killianmuldoon** [comment]
Fine for me if we don't include the manual cherry-pick in release 1.3

**Pull request merged**
