### PR TITLE
🐛 [WIP][DNR] test presubmits on main for kubekins v1.29

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@chrischdi Should we close this PR or do you want to use it to test after https://github.com/kubernetes/test-infra/pull/31441 is merged?

**Comment by chrischdi** [comment]
I close it for now. I can reopen if I need that PR for it

/close

**Comment by sbueringer** [comment]
> I close it for now. I can reopen if I need that PR for it
> 
> /close

Sounds good. In general it found be fine to merge the 1.29 PRs and then the test-infra PR and potentially test it on some random PR

**Pull request closed without merging**
