### PR TITLE
✨ Topology Mutation: Add types for Topology Mutation Hook

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #6545

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold
 until #6349 is merged

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
/hold cancel

Proposal is merged

/assign @fabriziopandini

**Comment by sbueringer** [comment]
Fixed importas finding and generated openapi definitions

**Comment by fabriziopandini** [comment]
Types are consistent with what was discussed in the proposal, let's keep moving and eventually improve documentation as soon as we can audit the first set of generated OpenAPI specifications
/lgtm
/approve

**Pull request merged**
