### PR TITLE
🌱 Add support for 'ipam' and 'other' providers to tilt

### PR DESCRIPTION
**Pull request by schrej**
**What this PR does / why we need it**:
This adds support for 'ipam-' and 'other-' providers to `tilt-prepare` to allow using ipam or any other new providers with our tilt setup.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/lgtm
/assign @fabriziopandini

**Comment by sbueringer** [comment]
Q: Is this the PR where we introduce `ipam-` and `other-` prefixes in addition to the ones we already have for bootstrap/infra/control-plane?

Mostly asking because I'm not aware of that clusterctl or any other part of the code base supports it.

**Comment by schrej** [comment]
They are not supported by clusterctl. There is an issue regarding clusterctl support here: #6154
The idea here is to just enable those two kinds of providers to work with tilt for now. We can adapt the tilt config once we've decided how to handle it in clusterctl.

**Comment by fabriziopandini** [comment]
/hold
Provider and ProviderType are clusterctl constructs, and until there is a proper analysis on what are the impacts of having additional provider types this can potentially prevent us from running clusterctl commands r or from debugging E2E tests (which are using clusterctl internally) on a cluster created with tilt.

As an alternative, we can merge this PR to simplify IPAM provider development, but we should clearly document in the comment/book that this is a temporary solution and it could lead to errors in the scenario described above

**Comment by schrej** [comment]
I have no idea what changed, and I didn't even notice because I was working with this branch checked out locally for a while, but it seems like this change is no longer necessary. It used to cause errors to have a provider that's not recognised by tilt-prepare, but that error vanished. We probably don't need this anymore.
The following config works fine with this tilt-provider.yaml config: https://github.com/telekom/cluster-api-ipam-provider-in-cluster/blob/main/tilt-provider.yaml
```yaml
default_registry: localhost:5000
allowed_contexts: ["kind-capi"]
kind_cluster_name: "capi"
provider_repos:
- ../cluster-api-ipam-provider-in-cluster
enable_providers:
# - docker
- ipam-in-cluster
extra_args: 
  core: ["--feature-gates=ClusterTopology=true"]
  kubeadm-bootstrap: ["--feature-gates=ClusterTopology=true"]
  kubeadm-control-plane: ["--feature-gates=ClusterTopology=true"]
  docker: ["--feature-gates=ClusterTopology=true"]
debug:
  ipam-in-cluster:
    port: 30001
```

**Pull request closed without merging**
