### PR TITLE
:seedling: Remove files and markers for Kubebuilder

### PR DESCRIPTION
**Pull request by killianmuldoon**
Remove files and markers required for generating Cluster API with kubebuilder.

CAPI doesn't use kubebuilder to scaffold projects anymore.

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/area api

**Review by g-gaston — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

/hold
Let's make sure the v1alpha3 removal merges first and maybe give folks until Monday to review.

Would be great if you can do the same cleanup in CAPV.

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Pull request merged**
