### PR TITLE
🌱 Remove pull-cluster-api-make-main job related script 

### LINKED ISSUE #6001: Remove pull-cluster-api-make-main job
We currently have a job called `pull-cluster-api-make-main` which is optional for PRs and not run per default, i.e. it can be triggered manually on PRs (`/test pull-cluster-api-make-main`). Given that we didn't use the job for a long time and that the verifications in the job are also covered by other jobs / GitHub actions we want to remove the job now (Slack xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1643213661202300).

To remove the job we have to do the following:
* kubernetes/test-infra:
    * Remove the Job configuration in https://github.com/kubernetes/test-infra/blob/802fa645f173c637230d5e947246832279d55466/config/jobs/kubernetes-sigs/cluster-api/cluster-api-presubmits-main.yaml#L21-L46
* kubernetes-sigs/cluster-api:
    * Remove the ./scripts/ci-make.sh shell script

Feel free to ask if there are any questions :)

/kind cleanup
/good-first-issue
/help-wanted

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Removes `ci-make.sh` script under scripts/ folder. 

Related to https://github.com/kubernetes/test-infra/pull/25022

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6001

### CODE REVIEW

**Comment by furkatgofurov7** [comment]
/assign @fabriziopandini @sbueringer 
/hold 
needs https://github.com/kubernetes/test-infra/pull/25022 to be merged before this can go in.

**Comment by sbueringer** [comment]
@furkatgofurov7 
Yup, perfect. 
Thank you!

/lgtm
/assign @fabriziopandini

**Pull request merged**
