### PR TITLE
🌱 Update visualizer chart to v1.1.0

### PR DESCRIPTION
**Pull request by Jont828**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Jont828** [comment]
@sbueringer Just to clarify, do we want to pin the chart versions in the repo?

**Comment by sbueringer** [comment]
> @sbueringer Just to clarify, do we want to pin the chart versions in the repo?

Given our experience with the Loki chart - yes. We spent quite a lot of time there debugging "latest" which randomly broke after a new release and we still can't bump because the chart is still not fixed.

**Comment by Jont828** [comment]
@sbueringer Are we good to merge this?

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
