### PR TITLE
✨  Remove clusterclass-changes test customization

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Changes added in #7081 were introduced to ensure we could test both applying a time.Duration value to the ControlPlane and MachineDeployment in the e2e test and that those values could be changed. As we only had one field it was required to add a new flavor for our clusterclass_changes e2e test.

With the introduction of #7098 this limitation is gone and we can test one time.Duration in the quickstart test and a second in the clusterclass_changes test without losing coverage.

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!
/lgtm
/approve

/hold
for e2e-full

**Review by ykakarap — APPROVED** [review]
/lgtm

**Comment by fabriziopandini** [comment]
Thanks for the cleanup!
/hold cancel
/lgtm
/approve

**Pull request merged**
