### PR TITLE
🌱 Use url.JoinPath instead of fmt to concat endpoint

### PR DESCRIPTION
**Pull request by sivchari**
**What this PR does / why we need it**:

Currently, kubeadmconfg's endpoint is liked using fmt.Sprintf. But if the endpoint is `/host:port`, the result is `https:///host:port`. So I use url.JoinPath to concat safely.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by chrischdi** [comment]
Change looks okay so far, but I have a question:

> Currently, kubeadmconfg's endpoint is liked using fmt.Sprintf. But if the endpoint is /host:port, the result is https:///host:port. So I use url.JoinPath to concat safely.

Why should the endpoint be in format `/host:port`? We pass in the output of `clusterv1.APIEndpoint`'s `String()` method which if I see it right should not have a leading `/`. So I'm curious if you have been able to hit this as an issue or this is just a cleanup/improvement.

**Comment by sivchari** [comment]
@chrischdi 

> Why should the endpoint be in format /host:port? We pass in the output of clusterv1.APIEndpoint's String() method which if I see it right should not have a leading /. So I'm curious if you have been able to hit this as an issue or this is just a cleanup/improvement.

https://go.dev/play/p/pNz485g0Igc

This CL is for improvement to make the endpoint safely. Since APIEndpoint is the field of CRD, the value that has prefix of `/` might be set. And if so, the endpoint url is invalid value because the output is `https:///host`. So to prevent it, I want to use the url.JoinPath to concat server endpoint.

**Comment by sbueringer** [comment]
Especially as this is an exported util, fine to make it more robust

**Review by chrischdi — COMMENTED** [review]
/retest

**Pull request merged**
