### PR TITLE
🌱 add EOS Notice for the v1.0 branch

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
According to our contributor's guide, 1.0 branch is now EOL.
I will raise the point to the next office hours as well.

/cc @vincepri @CecileRobertMichon @enxebre

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm 

Good to see the matrix getting a little bit smaller 😄

**Comment by sbueringer** [comment]
@fabriziopandini 
Are there consequences like:
* no further releases and cherry-picks onto release-1.0
* dropping the test jobs for release-1.0

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

**Pull request merged**
