### PR TITLE
🐛 Defaulting webhook should check class is set in ClusterClass-based clusters

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Sort of amazed we didn't already have this check 

/lgtm
/approve

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
> Sort of amazed we didn't already have this check
> 
> /lgtm /approve

We had it in validateTopology for ValidateCreate/Update. There it was run before we were validating variables, but yeah we never had it in Default and we also never added it when we moved over the variable validation.

**Pull request merged**
