### PR TITLE
📖 fix TOC of CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

This PR fixes the TOC of CONTRIBUTING.MD

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
