### PR TITLE
:sparkles: Bump to golangci-lint v1.44.2

### LINKED ISSUE #6163: Bump to golangci-lint v1.44.1
golangci-lint v1.44.1 was just released, let's use it :)

Tasks:
* [ ] bump golangci-lint in .github/workflows/golangci-lint.yml
* [ ] run make lint and potentially fix findings
* [ ] the new release contains thelper v0.5.1 which fixes a panic. For that panic we had to introduce a workaround in https://github.com/kubernetes-sigs/cluster-api/pull/6014/files that we now should be able to revert.
  * (just grep for `// TODO(sbueringer) We are storing the func in testFunc temporarily to work around`)

/kind feature
/good-first-issue

### PR DESCRIPTION
**Pull request by Prajyot-Parab**
Signed-off-by: Prajyot-Parab <prajyot.parab2@ibm.com>

**What this PR does / why we need it**:
- Bump to golangci-lint v1.44.2
- Fix lint findings
- Revert panic workaround

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6163

### CODE REVIEW

**Comment by sbueringer** [comment]
We have already a WIP PR for this: https://github.com/kubernetes-sigs/cluster-api/pull/6240

**Comment by Prajyot-Parab** [comment]
> We have already a WIP PR for this: #6240

@sbueringer what is your suggestion as next step for this PR ?

**Comment by killianmuldoon** [comment]
I don't think there's a big rush to change this version so If it's alright I'd like to give #6240 a few more days to see if we can get it in shape. If we can't resolve the issues by the end of the week I'm happy to merge this PR.

**Comment by Prajyot-Parab** [comment]
New version `1.45.0` of `golangci-lint` available, updated PR - #6335 

cc - @sbueringer @killianmuldoon

**Pull request closed without merging**
