### PR TITLE
⚠️ Graduate MachinePools feature from experimental to stable API

### LINKED ISSUE #9005: Graduate MachinePools from experimental to stable API
### What would you like to be added (User Story)?

As a production user of CAPZ, I'm not comfortable working with "experimental" parts of the product, but I would like to take advantage of the native VM-grouping construct at my cloud provider.

### Detailed Description

MachinePools have been part of the experimental API for years, but their API has been overall stable (recent backward-compatible changes for MachinePool Machines notwithstanding). Moving them out of `exp/` will declare that MachinePools are stable, supported, and safe to use.

### Anything else you would like to add?

The graduation criteria in the [MachinePools proposal](https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/20190919-machinepool-api.md) remains `TBD`. Informally, when the question "when can MPs graduate?" has been asked, the answer has generally been "after MachinePool Machines land."

MachinePool Machines have begun to land and should soon be largely complete. This seems like the time to consider graduating MachinePools, although there may be more context or specific `// TODO` items I'm not aware of. I'm hoping to identify those in this issue.

### Label(s) to be applied

/kind feature

/cc @dtzar @Jont828

### PR DESCRIPTION
**Pull request by mboersma**
**What this PR does / why we need it**:

Moves MachinePools out of `exp` into `api`, and updates the numerous things that affects.

**Which issue(s) this PR fixes**:
Fixes #9005

/area api
/area machinepool

### CODE REVIEW

**Comment by mboersma** [comment]
/retitle ⚠️ [WIP] Graduate MachinePools feature from experimental to stable API

This is still failing a unit test and possibly the e2e ClusterClass / MPs test. I'm working on it but thought it could benefit from the community's wisdom at this point.

Questions:
- Should we leave empty packages around in `exp` with just a `doc.go` file for future experimental features, or clean them up?
- Should we remove the `EXP_MACHINEPOOL` var and feature flag entirely now?
- Are we ready for this? (Are there other changes we may want before MachinePools are stable?)

**Comment by mboersma** [comment]
/retitle ⚠️ Graduate MachinePools feature from experimental to stable API

**Comment by enxebre** [comment]
Thanks for this! I might have missed it but I don't see any docs updated on the PR which I assume we need.
Also it'd be good to share some insight on where we are on unit/test coverage for this feature https://github.com/kubernetes-sigs/cluster-api/issues/9005#issuecomment-2178657628

**Comment by serngawy** [comment]
Can we break this PR to several PRs like first one with the stable API only , second with changing test and controllers.
Another thing is moving the API from exp to stable this will break any running environment "It will be tough for any environment to upgrade CAPI". I believe best approach to keep exp API with stable API, announce deprecation for at least 2 releases then remove it.

**Comment by mboersma** [comment]
> Can we break this PR to several PRs 

Of course we can, but I confess I'm not sure what changing the tests and controllers later would accomplish. Maybe I'm missing something.

When we discussed this at office hours, consensus seemed to be that this would be a breaking change, but only in terms of providers who import CAPI MachinePools code who need to change their imports. Specifically, `expv1.MachinePool` becomes `clusterv1.MachinePool`. Is there more to it than that?

I think you're suggesting maintaining both import paths for a couple releases, so there's a slower deprecation path. That seems reasonable, although I'd like to hear from other maintainers if they agree. Sorry if I'm misunderstanding something!

**Comment by serngawy** [comment]
> > Can we break this PR to several PRs
> 
> Of course we can, but I confess I'm not sure what changing the tests and controllers later would accomplish. Maybe I'm missing something.
> 
> When we discussed this at office hours, consensus seemed to be that this would be a breaking change, but only in terms of providers who import CAPI MachinePools code who need to change their imports. Specifically, `expv1.MachinePool` becomes `clusterv1.MachinePool`. Is there more to it than that?
> 
> I think you're suggesting maintaining both import paths for a couple releases, so there's a slower deprecation path. That seems reasonable, although I'd like to hear from other maintainers if they agree. Sorry if I'm misunderstanding something!

Thanks Matt for replying, As we discussed in the office hour the idea was be sure we are not breaking running env. So as we said changing the go path for the API package not changing the CRD definition. I guess we are safe to move the API, its more breaking the imports in the providers source code only.

**Comment by fabriziopandini** [comment]
/close
As per discussion in recent office hours, we should regroup and step up maintaners in this area before re-considering this step (see https://github.com/kubernetes-sigs/cluster-api/issues/9005#issuecomment-2263289591)

**Pull request closed without merging**
