### PR TITLE
🌱 bump controller-runtime v0.12.2

### LINKED ISSUE #6650: Upgrade to controller-runtime v0.12.2
We should upgrade to the upcoming CR release to pick up this fix: https://github.com/kubernetes-sigs/controller-runtime/issues/1908

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by ykakarap**
**What this PR does / why we need it**:

Bump controller-runtime to v0.12.2.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6650

### CODE REVIEW

**Comment by sbueringer** [comment]
I re-generated modules. We often have to run make generate-modules twice because of our relative dependencies between go modules

/lgtm
/assign @fabriziopandini

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
