### PR TITLE
🌱 Bump cert-manager to v1.13.0

### LINKED ISSUE #9405: Bump to cert-manager v1.13.0
Hey folks,
a new cert-manager release was published. Let's use it :)

([cert-manager/cert-manager/releases](https://github.com/cert-manager/cert-manager/releases))

Prior bump PR: https://github.com/kubernetes-sigs/cluster-api/pull/9197

/kind feature

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:
Updates cert-manager to v1.13.0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9405 

/area clusterctl

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

Thanks!

**Comment by furkatgofurov7** [comment]
@killianmuldoon @chrischdi do we need to cherry-pick this?

**Comment by sbueringer** [comment]
I assume there is nothing breaking the release notes?

**Comment by furkatgofurov7** [comment]
> I assume there is nothing breaking in the release notes? (also relevant for main)

@sbueringer from the release notes:

-  ⚠️ ⚠️ BREAKING ⚠️ ⚠️ : If you deploy cert-manager using helm and have .featureGates value set, the features defined there will no longer be passed to cert-manager webhook, only to cert-manager controller. Use webhook.featureGates field instead to define features to be enabled on webhook.
- Potentially breaking: If you were, for some reason, passing cert-manager controller's features to webhook's --feature-gates flag, this will now break (unless the webhook actually has a feature by that name).
- ⚠️ possibly breaking: Webhook validation of CertificateRequest resources is stricter now: all KeyUsages and ExtendedKeyUsages must be defined directly in the CertificateRequest resource, the encoded CSR can never contain more usages that defined there.

**Comment by sbueringer** [comment]
Thx for looking it up.

I'm fine with backporting. The alternative is that sooner or later we're using an unsupported version which is also not great.

**Comment by furkatgofurov7** [comment]
> Thx for looking it up.
> 
> I would prefer backporting. The alternative is that sooner or later we're using an unsupported version which is not great.

Assuming you meant only release-1.5:

/cherry-pick release-1.5

**Comment by killianmuldoon** [comment]
I think we should also backport this to 1.4

/cherry-pick release-1.4

**Pull request merged**
