### PR TITLE
Sync up go.mod.

### PR DESCRIPTION
**Pull request by gyliu513**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/cc @detiber @vincepri

### CODE REVIEW

**Comment by gyliu513** [comment]
Thanks @vincepri , 1.12 does works.

**Comment by detiber** [comment]
@vincepri do we need to update `hack/ensure-go.sh` to error if go v1.13+ is detected?

**Comment by vincepri** [comment]
We could, but that script isn't run locally afaik

**Comment by vincepri** [comment]
@gyliu513 Is it ok to close this PR?

**Comment by gyliu513** [comment]
> @vincepri do we need to update hack/ensure-go.sh to error if go v1.13+ is detected?

@vincepri @detiber I think we still need to update hack/ensure-go.sh to error if go v1.13+ is detected, this can help some local dev environment, comments?

**Pull request closed without merging**
