### PR TITLE
📖 docs: link Kubernetes contributor guide in CONTRIBUTING.md

### LINKED ISSUE #8061: Consider linking the Kubernetes New Contributor Course in our book
Kubernetes recently added a New Contributor Course to their book: https://www.kubernetes.dev/docs/onboarding/

While it is targeted at k/k development I think ~80% of it is relevant for new CAPI contributors as well.

I wonder if we should link it (and probably a few more other pages from kuberntes.dev as well) in our CAPI book

/kind documentation

### PR DESCRIPTION
**Pull request by Sajiyah-Salat**
**What this PR does / why we need it**:
Add kubernetes contributor course in contributing. md

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8061

### CODE REVIEW

**Comment by sbueringer** [comment]
/retitle 📖 docs: link Kubernetes contributor guide in CONTRIBUTING.md

**Comment by oscr** [comment]
Great work!

/lgtm
/approve

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test
/lgtm
/approve

**Pull request merged**
