### PR TITLE
🌱 Update typo in cert_manager.go

### PR DESCRIPTION
**Pull request by mgrote**
Fix typo. (Test for Stefan Bührigner :-))

**What this PR does / why we need it**:
There are some test from @sbueringer supported by this PR.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

<sub>Michael Grote <michael.grote@mercedes-benz.com>, Mercedes-Benz Tech Innovation GmbH, [Provider Information](https://github.com/mercedes-benz/foss/blob/master/PROVIDER_INFORMATION.md)</sub>

### CODE REVIEW

**Comment by oscr** [comment]
Reference: https://kubernetes.slack.com/archives/C8TSNPY4T/p1663798471762659

/assign @sbueringer

**Comment by sbueringer** [comment]
Okay this is going to be a bit tricky.
First we need an /ok-to-test so our Prow jobs will run, this will also enable the linter to run (but only once)

So plan is:
* /ok-to-test
* Prow Jobs => green & linter => green
* We need ~ git commit --amend + git push --force (no changes needed)
* Prow Jobs will still run, linter won't
* Then I try to merge the PR and it shouldn't work (somehow)

Let's go :)

/ok-to-test

**Comment by sbueringer** [comment]
Looks like this time /ok-to-test didn't allow the golangci-lint GitHub actions (it did yesterday)

So we can probably skip step 3.

**Pull request merged**
