### PR TITLE
:book: Add 1.4 -> 1.5 migrations doc. Move migrations docs to single folder.

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

- Adds migration doc for 1.5 since 1.4 is branched and "almost" released. 
- Moves all migration docs to a single folder since we will have ~3 more per year and it's getting messy.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

Looks like there's a rebase needed now though.

**Comment by killianmuldoon** [comment]
/retitle :book: Add 1.4 -> 1.5 migrations doc. Move migrations docs to single folder.

(to shorten for release notes)

**Comment by hackeramitkumar** [comment]
Part of #8429

**Pull request merged**
