### PR TITLE
🏃 ClusterReconciler: make Client a proper field

### LINKED ISSUE #1381: ClusterReconciler: make Client a proper field
We are trying to be explicit when we invoke methods on the embedded Client field (Get/Patch/Delete/etc). Let's make `client.Client` a proper field.

/kind cleanup
/good-first-issue
/help
/milestone Next
/priority important-longterm

### LINKED ISSUE #1384: MachineSetReconciler: make Client a proper field
We are trying to be explicit when we invoke methods on the embedded Client field (Get/Patch/Delete/etc). Let's make client.Client a proper field.

/kind cleanup
/good-first-issue
/help
/milestone Next
/priority important-longterm

### PR DESCRIPTION
**Pull request by tahsinrahman**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1381

### CODE REVIEW

**Comment by ncdc** [comment]
@tahsinrahman could you please update the PR title to include the appropriate emoji text (warning/bug/running/etc)?

**Comment by tahsinrahman** [comment]
I'm not sure what emoji it should be? should it be running?

**Comment by ncdc** [comment]
Running is fine, thanks

**Pull request merged**
