### PR TITLE
🌱 Fix redundant judgment for reterr==nil

### PR DESCRIPTION
**Pull request by chymy**
**What this PR does / why we need it**:
Condition is always 'true' because 'reterr' is always 'nil'

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by JoelSpeed** [comment]
/lgtm

I don't like named returns, perhaps we should just get rid from this function altogether to reduce the confusion 😅 A follow up cleanup maybe

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Pull request merged**
