### PR TITLE
:bug: Checking cert's keypair for nil before accessing to avoid panics

### PR DESCRIPTION
**Pull request by makhov**
**What this PR does / why we need it**:

In some circumstances `AsFiles()` can panic. The PR adds additional nil check for `c.KeyPair` to avoid it.
```
2024-02-02T09:15:35Z	INFO	Observed a panic in reconciler: runtime error: invalid memory address or nil pointer dereference	{"controller": "k0scontrollerconfig", "controllerGroup": "bootstrap.cluster.x-k8s.io", "controllerKind": "K0sControllerConfig", "K0sControllerConfig": {"name":"bar-2-1","namespace":"default"}, "namespace": "default", "name": "bar-2-1", "reconcileID": "8a558d44-7dcf-406e-a7e0-e47c895189f6"}
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
	panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x16ca8fd]

goroutine 270 [running]:
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile.func1()
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:116 +0x1e5
panic({0x1a37520?, 0x2e3bb30?})
	/usr/local/go/src/runtime/panic.go:914 +0x21f
sigs.k8s.io/cluster-api/util/secret.(*Certificate).AsFiles(...)
	/go/pkg/mod/sigs.k8s.io/cluster-api@v1.5.3/util/secret/certificates.go:374
sigs.k8s.io/cluster-api/util/secret.Certificates.AsFiles({0xc00035ffb0, 0x4, 0xc0002839b0?})
	/go/pkg/mod/sigs.k8s.io/cluster-api@v1.5.3/util/secret/certificates.go:419 +0xbd
github.com/k0sproject/k0smotron/internal/controller/bootstrap.(*ControlPlaneController).getCerts(0xc000144300, {0x1f94308, 0xc00043cb40}, 0xc000775be0)
	/workspace/internal/controller/bootstrap/controlplane_bootstrap_controller.go:415 +0x1d0
github.com/k0sproject/k0smotron/internal/controller/bootstrap.(*ControlPlaneController).genControlPlaneJoinFiles(0xc000144300, {0x1f94308, 0xc00043cb40}, 0xc000775be0, 0x192b7c0?, {0xc000801fb0, 0x1, 0x1})
	/workspace/internal/controller/bootstrap/controlplane_bootstrap_controller.go:279 +0x19f
github.com/k0sproject/k0smotron/internal/controller/bootstrap.(*ControlPlaneController).Reconcile(0xc000144300, {0x1f94308, 0xc00043cb40}, {{{0xc0006097d0, 0x7}, {0xc0006097c6, 0x7}}})
	/workspace/internal/controller/bootstrap/controlplane_bootstrap_controller.go:180 +0xf7f
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).Reconcile(0x1f97e00?, {0x1f94308?, 0xc00043cb40?}, {{{0xc0006097d0?, 0xb?}, {0xc0006097c6?, 0x0?}}})
	/go/pkg/mod/sigs.k8s.io/controller-runtime@v0.16.3/pkg/internal/controller/controller.go:119 +0xb7
sigs.k8s.io/controller-runtime/pkg/internal/controller.(*Controller).reconcileHandler(0xc0002bedc0, {0x1f94340, 0xc0004afa40}, {0x1afb900?, 0xc0003a25c0?})
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

Fixes https://github.com/k0sproject/k0smotron/issues/438

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/ok-to-test

For sake of documentation, could you clarify when c.KeyPair could be nil?

**Comment by makhov** [comment]
We do
```
certificates := secret.NewCertificatesForInitialControlPlane(config)
err := certificates.Lookup(ctx, client, util.ObjectKey(cluster))
if err != nil {
	return err
}
for _, cert := range certificates.AsFiles() {
   ....
}
```

If the secret doesn't exist (eg, was removed manually), `certificates.Lookup` doesn't return an error, but `cert.KeyPair` is nil.

**Comment by fabriziopandini** [comment]
Thanks for the explanation, let's add a test case for this scenario, then ok for me

**Review by chrischdi — COMMENTED** [review]
/approve

**Pull request merged**
