### PR TITLE
Bumped calico version to 3.15

### PR DESCRIPTION
**Pull request by kubealex**
📖 
Bumped calico version to 3.15

### CODE REVIEW

**Comment by kubealex** [comment]
Added signed CLA

**Comment by fabriziopandini** [comment]
@vincepri @detiber I don't see problems on using latest Calico in the quick-start.
I'm going to approve unless you have other preferences

**Comment by vincepri** [comment]
FYI, we should post the minimum supported version as reported in https://docs.projectcalico.org/getting-started/kubernetes/requirements

**Comment by detiber** [comment]
@vincepri agree, but we should do that in general, since it also matches our support policy :)

**Comment by vincepri** [comment]
You mean for management clusters? I was thinking about workload clusters, technically for those we support whatever kubeadm v1beta1 covers

**Comment by detiber** [comment]
> You mean for management clusters? I was thinking about workload clusters, technically for those we support whatever kubeadm v1beta1 covers

That is the technical limitation, yes, but we've also said that "official" support for versions of workload clusters is the same upstream k8s supported versions

**Pull request merged**
