### PR TITLE
🏃add e2e test config for vsphere

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
This PR adds a config file that can be used for running e2e test on Vsphere.

/area testing
/assign @fabriziopandini

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/hold 
for https://github.com/kubernetes-sigs/cluster-api/pull/2943 to merge (with the calico manifest)

**Comment by yastij** [comment]
@sedefsavas @fabriziopandini - is there a reason for this to be located in the cluster-api repo ?

**Comment by sedefsavas** [comment]
We added aws and vsphere for running CAPI tests on CAPV and CAPA locally besides CAPD. 
Although providers may have different e2e tests, they may be missing CAPI functionality tests, so it makes sense to run CAPI-related tests on different providers locally. Wdyt @yastij?

**Comment by ncdc** [comment]
+1 to closing here and moving to CAPV

**Pull request closed without merging**
