### PR TITLE
⚠️ Stop supporting CRDs with invalid names

### LINKED ISSUE #5686: Stop using full CRD list as a fallback to get ObjectMetadata for UpdateReferenceAPIContract
**Detailed Description**

Context: We automatically update references in CAPI to newer versions if there is a newer version with the same contract for a CRD.
Example: The MachineSet controller automatically updates references to a InfrastructureMachineTemplate if there is a newer apiVersion for the InfrastructureMachineTemplate which complies to the same CAPI contract.

This functionality is implemented via the `UpdateReferenceAPIContract` func. It uses the labels on a CRD to calculate if there is a newer version of a CRD complying to the same CAPI contract.

To avoid retrieving/caching whole CRDs, the func uses `GetGVKMetadata` to retrieve the PartialObjectMetadata of a CRD. `GetGVKMetadata` depends on that the CRD is correctly named, i.e. the name is :
```go
fmt.Sprintf("%s.%s", flect.Pluralize(strings.ToLower(gvk.Kind)), gvk.Group)
```
(e.g. `infrastructure.cluster.x-k8s.io/DockerMachineTemplate` => `dockermachinetemplates.infrastructure.cluster.x-k8s.io`)

In cases where the name is different we do a full CRD list and identify the correct CRD by checking the GK inside the CRD. The problem is that in this case the controller is listing/watching/caching all CRDs in the cluster which leads to high memory usage of the controller. This affects the CAPI core and the KCP controller. It looks like the func is not used outside of the core repo: https://cs.k8s.io/?q=UpdateReferenceAPIContract&i=nope&files=&excludeFiles=&repos=

To avoid running into this issue we would propose to drop the fallback mechanism. This is also a forcing function to name CRDs correctly.

WDYT?

Tasks are roughly:
* Drop the fallback mechanism in `UpdateReferenceAPIContract` (probably create a copy of the func, deprecate the old one (?))
* Use only the new func in our controllers
* Document the change in the migration guide (maybe also in the contract docs (?))

/kind cleanup

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #5686

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
yay! nice cleanup!
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
Nice!

/lgtm

Happy to approve when you think it's ready / has enough eyes on it.

**Comment by sbueringer** [comment]
Yup I think we can merge, I think we won't get more reviews.

**Review by killianmuldoon — APPROVED** [review]
/approve

**Comment by sbueringer** [comment]
@killianmuldoon Had to change a call to `UpdateReferenceAPIContract`which was introduced in the MachinePool controller in another PR

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
