### PR TITLE
🌱 Add template metadata to CABPK and KCP types

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This PR adds metadata in the following places:
* KubeadmConfigTemplate.spec.template.metadata
* KubeadmControlPlaneTemplate.spec.template.metadata
* KubeadmControlPlaneTemplate.spec.template.spec.machineTemplate.metadata

This is a prepartion for the upcoming PR to test propagation.

Based on the proposal these fields should be propagated but they don't exist today: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/proposals/images/in-place-propagation/proposed-changes.png

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Could you also add the ObjectMeta back to the implementers guide in the book? i.e. on this page: https://cluster-api.sigs.k8s.io/developer/providers/bootstrap.html

ref: https://github.com/kubernetes-sigs/cluster-api/pull/6935/files#r923255539

**Comment by sbueringer** [comment]
Done

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
