### PR TITLE
README: Add implementer office hours

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:
Add times for the implementer office hours and link to meeting notes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # N/A

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by errordeveloper** [comment]
Are both of these in the shared calendar now?

**Comment by roberthbailey** [comment]
I added the Tuesday one to the shared calendar during the meeting last week and I just put the Monday one onto the calendar now. Let me know if you don't see it.

**Comment by errordeveloper** [comment]
I can see both now, thanks! Not sure why the one yesterday didn't show up.

**Pull request merged**
