### PR TITLE
🐛  Avoid masking possible errors in flaky CRS test

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

This PR makes sure that the flaky CRS test we're seeing in lots of PRs spits out the proper error message rather than masking it.

/milestone v0.4
/assign @CecileRobertMichon @sedefsavas @fabriziopandini

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by yastij — COMMENTED** [review]
/lgtm

**Pull request merged**
