### PR TITLE
[WIP] :seedling: Move webhooks to internal

### LINKED ISSUE #7176: Make the v1beta1 api package easier to consume
**User Story**

As a user I would like to easily consume the CAPI v1beta1 API package without introducing unwanted transitive dependencies.

**Detailed Description**

Currently if one imports the CAPI v1beta1 API package, which in turn imports `sigs.k8s.io/controller-runtime`, the user transitively imports `sigs.k8s.io/controller-runtime/pkg/client/config`, which sets the string var `kubeconfig` to the default command line FlagSet. See:
* https://github.com/kubernetes-sigs/controller-runtime/blob/15b6689c55745514d6bade4c55efb3333c0da4d9/alias.go#L23
* https://github.com/kubernetes-sigs/controller-runtime/blob/15b6689c55745514d6bade4c55efb3333c0da4d9/pkg/client/config/config.go#L38
* PR that addresses the issue directly in controller-runtime: https://github.com/kubernetes-sigs/controller-runtime/pull/1999

In the past this lead to redefined flag panics in our internal code base. A [slack discussion](https://kubernetes.slack.com/archives/C8TSNPY4T/p1662119727596599) revealed two possible solutions in CAPI:

* [Use manager and builder pkgs of controller-runtime explicitly](https://github.com/kubernetes-sigs/cluster-api/pull/7175): 
  * Less intrusive but skips using `alias.go` and directly depends on the packages itself.
* [Move webhooks to internal](https://github.com/kubernetes-sigs/cluster-api/pull/7157):
  * This fixes the issue implicitly by moving the code parts that import controller-runtime away from the API package to the webhooks package. More intrusive but might align with the idea to move [webhook code to internal](https://github.com/kubernetes-sigs/cluster-api/issues/5599). Though, there is no consensus if this should be done for existing code in the first place.

**Anything else you would like to add:**

It's probably most desirable to fix this directly in controller-runtime instead of CAPI and potential providers. Nevertheless, for both mentioned "CAPI solutions" there are corresponding WIP PRs in place. If one is more desirable the other one could be closed.

/kind feature

<sub>Johannes Frey <[johannes.frey@mercedes-benz.com](mailto:johannes.frey@mercedes-benz.com)>, Mercedes-Benz Tech Innovation GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

### PR DESCRIPTION
**Pull request by johannesfrey**
**What this PR does / why we need it**:

Follow up of https://github.com/kubernetes-sigs/cluster-api/issues/5599.

Move webhooks to internal and create alias.go for exposing Machine, MachineSet, MachineDeployment, MachineHealthCheck, KubeadmConfig and KubeadmConfigTemplate for now. I also added a deprecation comment to the types in the betav1 package and to the book, as seen in e.g. `cluster_webhook.go` before they were removed.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #7176

<sub>Johannes Frey <[johannes.frey@mercedes-benz.com](mailto:johannes.frey@mercedes-benz.com)>, Mercedes-Benz Tech Innovation GmbH ([Provider Information](https://github.com/mercedes-benz/daimler-foss/blob/master/PROVIDER_INFORMATION.md))</sub>

### CODE REVIEW

**Comment by sbueringer** [comment]
To be honest. I don't know if we have consensus to move all webhooks to this pattern. We got consensus for the ones which are currently in a separate folder only because they require a CR Client and thus would introduce a lot more dependencies into the API package.

**Comment by johannesfrey** [comment]
> To be honest. I don't know if we have consensus to move all webhooks to this pattern. We got consensus for the ones which are currently in a separate folder only because they require a CR Client and thus would introduce a lot more dependencies into the API package.

Thanks for the info. As discussed in Slack, I will make create an issue explaining why there might be issues when importing `sigs.k8s.io/controller-runtime` in the API packages and a move to another package helps in this case.

**Comment by johannesfrey** [comment]
Closing because of https://github.com/kubernetes-sigs/cluster-api/issues/7176#issuecomment-1293101354

**Pull request closed without merging**
