### PR TITLE
🌱 Update operator to use certmanager v1 resources

### PR DESCRIPTION
**Pull request by MarcelMue**
**What this PR does / why we need it**:

Aligning the cert-manager config with master. 

towards https://github.com/kubernetes-sigs/cluster-api/issues/4246

### CODE REVIEW

**Comment by MarcelMue** [comment]
/area operator

cc @alexander-demichev

**Comment by vincepri** [comment]
Hm, could we rebase the `operator-0.4` PR based on the main branch instead?

**Comment by MarcelMue** [comment]
> Hm, could we rebase the `operator-0.4` PR based on the main branch instead?

I don't follow - the `exp/operator` folder does exist on the main branch. So rebasing would not solve this, right? Maybe I am missing something obvious.

**Comment by vincepri** [comment]
I see, does the operator-0.4 branch already include the certmanager v1.1 bits that @fabriziopandini pushed a week or so ago? If so, let's proceed, I was only wondering if we were rebasing off the main branch

**Comment by alexander-demichev** [comment]
@vincepri Yes, operator-0.4 branch includes v1.1 certmanager https://github.com/kubernetes-sigs/cluster-api/blob/operator-0.4/config/certmanager/certificate.yaml
I will open a PR that rebases all operator changes on top of main.

**Comment by vincepri** [comment]
/retitle 🌱 Update operator to use certmanager v1 resources
/lgtm

**Pull request merged**
