### PR TITLE
Update project maintainers

### PR DESCRIPTION
**Pull request by roberthbailey**
**What this PR does / why we need it**:

- Graduates @vincepri  to approver :tada: 
- Removes @jessicaochen, @karan, @kris-nova, & @mkjelland :wave: 

from the OWNERS file.

Welcome and congrats new reviewers and approvers! Thanks for all of the contributions from the emeritus approvers, and hopefully we'll see you around again!

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by jessicaochen** [comment]
lgtm. Thanks for taking care of this. :)

**Comment by vincepri** [comment]
+1 to verbal check tomorrow.

I just realized that we actually said 2 weeks (and not 1 week) as timeout for approvers refresh. We should probably stick to that and aim to merge this on the 25th. Wdyt?

**Pull request merged**
