### PR TITLE
:book: Redirect on curl k8s stable version and kustomize install

### PR DESCRIPTION
**Pull request by knabben**
**What this PR does / why we need it**:
Fix Kustomize bash installation documentation and redirect stable.txt download

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!
/lgtm

**Comment by fabriziopandini** [comment]
Wondering if we should remove this and instead refer to `hack/ensure-kustomize.sh` that installs the exact version of kustomize we rely on under the `/hack/tools/bin` folder 🤔

**Comment by sbueringer** [comment]
> Wondering if we should remove this and instead refer to `hack/ensure-kustomize.sh` that installs the exact version of kustomize we rely on under the `/hack/tools/bin` folder 🤔

Is an alternative, but might be good if users don't have to clone the repo (I guess we also execute it via curl)

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
