### PR TITLE
:seedling: Improve gomega fail handling in clusterClass rollout

### PR DESCRIPTION
**Pull request by killianmuldoon**
Improve the `without` function in the ClusterClass rollout test to take a gomega handler and fail when the key doesn't exist in the map. 

This improves on the change made in https://github.com/kubernetes-sigs/cluster-api/pull/8761

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/cherry-pick release-1.4

(not sure this will work, if not I'll do it manually.)

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
