### PR TITLE
:seedling: add talos providers to defaults in clusterctl

### PR DESCRIPTION
**Pull request by rsmitty**
**What this PR does / why we need it**:

This PR will add the talos bootstrap and controlplane providers to the
list of default providers to enable with `clusterctl init`. Also just cleans up the constants a bit for readability.

Signed-off-by: Spencer Smith <robertspencersmith@gmail.com>

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by vincepri** [comment]
+1 🎉

**Comment by fabriziopandini** [comment]
FYI former PR showing where changes are required for a new provider 
https://github.com/kubernetes-sigs/cluster-api/pull/3121
https://github.com/kubernetes-sigs/cluster-api/pull/3123

**Comment by rsmitty** [comment]
@fabriziopandini good call. I missed the metadata stuff at first.

**Pull request merged**
