### PR TITLE
:seedling: Add dependabot configuration

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:
Adds dependabot configuration for automated dependency updates. 
You can see what's happening in CAPA here https://github.com/kubernetes-sigs/cluster-api-provider-aws/pulls?q=is%3Apr+label%3Adependencies 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by randomvariable** [comment]
I think a maintainer will need to switch it on in the settings. A github action should have checked the configuration being valid.

**Comment by randomvariable** [comment]
/hold 
as per above.

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
