### PR TITLE
🏃Drop capd-e2e test

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
Drops capd-e2e test, now replaced by test/e2e

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/assign @vincepri 
/assign @sedefsavas 
/area testing

/hold 
until https://github.com/kubernetes/test-infra/pull/17547 merge

**Comment by fabriziopandini** [comment]
> pull-cluster-api-capd-e2e — Job failed.

this is legit for this PR

**Comment by fabriziopandini** [comment]
@vincepri this pr seems stuck because somehow it is expecting pull-cluster-api-capd-e2e to complete 🤔

**Comment by randomvariable** [comment]
We need to remove it from test-infra first?

**Comment by benmoss** [comment]
Can you make it just empty for now?

**Comment by fabriziopandini** [comment]
@randomvariable  done by https://github.com/kubernetes/test-infra/pull/17547 one week ago

**Comment by randomvariable** [comment]
Ah, the list of tests is set in stone at PR creation time. You'll need to resubmit it I think.

**Comment by fabriziopandini** [comment]
Force pushing to get the list of jobs without pull-cluster-api-capd-e2e

**Comment by randomvariable** [comment]
cool

/lgtm

**Pull request merged**
