### PR TITLE
[release-1.4] :bug: Use known kindest/node image versions by sha for e2e upgrade tests

### PR DESCRIPTION
**Pull request by killianmuldoon**
Pin the kind image used in the clusterctl upgrade tests to a known good version which works with CAPD and KIND v0.19.0. These images are the ones suggested in the KIND v0.19.0 release at https://github.com/kubernetes-sigs/kind/releases/tag/v0.19.0

This should fix test failures related to https://github.com/kubernetes-sigs/cluster-api/issues/8815

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/area e2e-testing

**Comment by sbueringer** [comment]
Changes look good to me

/lgtm
/approve

/hold
given you wanted to take a look at CI / the test is failed

**Comment by killianmuldoon** [comment]
/close

This approach isn't going to work. Will look to also revert this on main.

**Comment by sbueringer** [comment]
Thank you very much!

/lgtm
/approve

**Pull request merged**
