### PR TITLE
📖 Set linkchecker base branch to main

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Looks like https://github.com/kubernetes-sigs/cluster-api/pull/6853 broke the check: https://github.com/kubernetes-sigs/cluster-api/runs/7245805212?check_suite_focus=true

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
/approve

Let's see if that's enough

**Pull request merged**
