### PR TITLE
:book: update Azure quick start for CAPZ v1.16

### PR DESCRIPTION
**Pull request by nojnhuh**
**What this PR does / why we need it**:

This change updates the Azure parts of the quick start guide to account for the default auth mechanism in templates [changing to Workload Identity](https://github.com/kubernetes-sigs/cluster-api-provider-azure/pull/4765) in CAPZ v1.16 (coming next week). These changes add steps to change back to Service Principal auth to avoid turning this doc into yet-another-Workload-Identity-setup doc and to continue to support CAPZ v1.15.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api-provider-azure/issues/4921

/area documentation
/area provider/azure

### CODE REVIEW

**Comment by nojnhuh** [comment]
We'd also like to have this in the latest release branch so it's live when we release CAPZ v1.16 next week. No need to wait until before then to merge though.

/cherry-pick release-1.7

**Review by jackfrancis — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
Nice, thx!

/lgtm
/approve

**Pull request merged**
