### PR TITLE
⚠️ Remove old metrics from v1a3

### PR DESCRIPTION
**Pull request by wfernandes**
**What this PR does / why we need it**:
In preparation of revamped metrics and remove burden of memory consumption on tsdbs.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/3327

### CODE REVIEW

**Comment by vincepri** [comment]
⚠️ ?

**Comment by vincepri** [comment]
@wfernandes Seems make modules needs to be run

**Comment by wfernandes** [comment]
Apologies. I thought I did that but guess I didn't commit it.

**Comment by fabriziopandini** [comment]
Given this can avoid memory problems in production
/lgtm

**Comment by fabriziopandini** [comment]
apidiff output
```
sigs.k8s.io/cluster-api/controllers/metrics
  Incompatible changes:
  - ClusterControlPlaneReady: removed
  - ClusterFailureSet: removed
  - ClusterInfrastructureReady: removed
  - ClusterKubeconfigReady: removed
  - MachineBootstrapReady: removed
  - MachineInfrastructureReady: removed
  - MachineNodeReady: removed
```

**Pull request merged**
