### PR TITLE
Add "all" target to Makefile

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

from the main Makefile
- Add target to build the 4 binaries
- Add target to build the 4 images
- build the various *-gen binaries and then use them
- use the vendored versions of the packages for the *-gen binaries
- add a scripts/ci-make.sh for use in CI

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by dims** [comment]
Here's a new job to go with this - https://github.com/kubernetes/test-infra/pull/8419

**Comment by k4leung4** [comment]
lgtm

**Comment by dims** [comment]
@spew i added the `scripts/ci-make.sh` as you requested in the test-infra PR. let's get this in and i'll fix up the test-infra PR

**Comment by dims** [comment]
@mkjelland @spew can you please re-apply lgtm?

**Pull request merged**
