### PR TITLE
🏃 Fix capd build

### PR DESCRIPTION
**Pull request by ashish-amarnath**
Signed-off-by: Ashish Amarnath <ashish.amarnath@gmail.com>

**What this PR does / why we need it**:
To get CAPD to build again

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/assign @chuckha

### CODE REVIEW

**Comment by detiber** [comment]
This fix is also included in #1652

**Comment by chuckha** [comment]
I'm working on that PR right now 😄 totally cool if y'all wanna merge this quickly tho and fix the build

**Pull request merged**
