### PR TITLE
WIP: 🌱 Change unexpected rollouts timeout in clusterctl upgrade tests

### PR DESCRIPTION
**Pull request by furkatgofurov7**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@furkatgofurov7 This issue should be resolved now. Just merged the second fix PR (https://github.com/kubernetes-sigs/cluster-api/pull/8139)

I think we can close this PR

**Comment by furkatgofurov7** [comment]
> @furkatgofurov7 This issue should be resolved now. Just merged the second fix PR (#8139)
> 
> I think we can close this PR

Thanks @sbueringer, closing it

/close

**Pull request closed without merging**
