### PR TITLE
Fix Netlify redirects

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Fix the Netlify redirects for the `release-0.1` branch

**Release note**:
```release-note
NONE
```

### CODE REVIEW

**Comment by detiber** [comment]
/hold
holding until we can determine why the CNAME entries result in a `Not Found` error w/ Netlify.

**Comment by ncdc** [comment]
I don't know anything about Netlify... LGTM but should someone else tag it?

**Pull request merged**
