### PR TITLE
Remove terraform provider

### PR DESCRIPTION
**Pull request by dims**
**What this PR does / why we need it**:

Thanks for keeping this around based on my request. We will be starting from another direction directly using gophercloud based on the code in https://github.com/kubernetes-sigs/cluster-api/pull/176. So we no longer need this for OpenStack.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

**Release note**:

```release-note
NONE
```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by roberthbailey** [comment]
lgtm

**Comment by kfox1111** [comment]
has the other directory diverged? If not, would it be better to delete the other one and git mv this back over so history is maintained?

**Comment by dims** [comment]
@kfox1111 yes it has

**Pull request merged**
