### PR TITLE
🌱 Set gci linter prefix value

### PR DESCRIPTION
**Pull request by stmcginnis**
**What this PR does / why we need it**:

This sets the correct prefix value for the gci linter's namespace.

Good practice is to have imports separated into three distinct groups:
standard library imports, third party package imports, and local
imports. The gci linter is used to enforce this convention, making it
easy to see what is local, what is standard with go, and what is being
pulled in externally.

The gci linter configuration has a "prefix" setting that is used to tell
it what to match as the starting string to identify local imports. This
was set to "false", effectively disabling the ability to differentiate
local imports from third party ones.

This change sets the "prefix" value to our "sigs.k8s.io/cluster-api"
path so that our local imports are identified and grouped separately.

### CODE REVIEW

**Comment by sbueringer** [comment]
Some context. I had previously set it to the correct prefix. It was a compromise to enable gci, but without local prefix: https://github.com/kubernetes-sigs/cluster-api/pull/5592#discussion_r744889986

**Comment by stmcginnis** [comment]
> I personally prefer using local prefix too...

Thanks for that background. I figured something of the sort must have happened. ;)

I would like to see this added. It's consistent with conventions used with other go projects. The good part was it reduced the amount of churn in your original PR, so at least this should be a little easier to review.

@vincepri could you share your opinion since you gave the original feedback?

**Comment by vincepri** [comment]
Actually before I go look back what I said in the other PR: does `make lint-fix` fix the imports with the local paths?

**Comment by stmcginnis** [comment]
> does make lint-fix fix the imports with the local paths

Yes it does, thankfully! I actually started making manual updates at first, before I realized how many files it flagged. Then just ran `make lint-fix` and it took care of everything quickly.

**Comment by vincepri** [comment]
Perfect, that sounds good I originally thought it was going to be painful to change local configurations for everyone.

/approve
/lgtm

**Comment by vincepri** [comment]
/lgtm cancel

One second, looking around a bit in k8s repos

**Comment by vincepri** [comment]
Looking a bit in `kubernetes/kubernetes` I don't see this pattern being applied consistently. 

What's the advantage of having local imports separate from all the other ones? Looking at https://github.com/golang/go/issues/40660 it sounds like a decision wasn't even made in `gopls` which is widely used today. We're forcing in our configuration for the local import to be the main cluster repository, but we do carry multiple modules locally

**Comment by vincepri** [comment]
It sounds like more of a Intellij problem though than something that needs to be enforced in Cluster API, isn't `gci` without the local directive be enough to guarantee there is always a single group of imports?

**Comment by stmcginnis** [comment]
I guess it's a per-project or per-org preference. Obviously by having the local-prefix setting, gci itself has the preference for the three groups. But others like Uber go with two groups: https://github.com/uber-go/guide/blob/master/style.md#import-group-ordering

So it probably comes down to what this team would prefer to do. Personally, I prefer the three separate groups, especially since we are using gci. But there is nothing set in stone saying that is the correct way.

**Comment by stmcginnis** [comment]
This needs a rebase now, but before I do that I was hoping we could get some feedback. Is there any consensus on the two import groupings versus three import groupings discussed above?

**Comment by fabriziopandini** [comment]
I don't have a strong opinion but given that make lint-fix can help the users and votes seems positive (Vince 0-, me 0, Cecile +1, Stefan +1), let's go for it

**Pull request merged**
