### PR TITLE
✨ Introduce possibility to create clusterctl plugins

### PR DESCRIPTION
**Pull request by alexander-demicev**
**What this PR does / why we need it**:

We would like `clusterctl` to support bootstrapping a management cluster using the CAPI Operator, but at the same time, we'd like to avoid introducing new code to `clusterctl` for maintenance reasons (dependencies, etc.). One possible option for us is to enable the creation of `clusterctl` plugins in a similar way to [kubectl](https://kubernetes.io/docs/tasks/extend-kubectl/kubectl-plugins/#writing-kubectl-plugins).

This PR introduces a change that enables the creation of such plugins. The code relies on the `kubectl` package and borrows some code from it, specifically https://github.com/kubernetes/kubectl/blob/master/pkg/cmd/cmd.go#L115. In the current implementation, it will only be possible to create plugins for the `clusterctl` commands and not for subcommands.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
I need some time to look at additional transitive dependencies + test; in the meantime, it will be great if you can document plugins in https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html (might be there is a better place)

**Comment by fabriziopandini** [comment]
@ykakarap @Jont828 PTAL

**Comment by sbueringer** [comment]
> I need some time to look at additional transitive dependencies + test; in the meantime, it will be great if you can document plugins in https://cluster-api.sigs.k8s.io/clusterctl/provider-contract.html (might be there is a better place)

`sigs.k8s.io/kustomize/kustomize/v5 v5.0.1` seems to be a big one

**Comment by Fedosin** [comment]
Tested this PR locally and it seems working right. 
@alexander-demicev let me know if you need any help with documentation or tests for this patch.

**Comment by fabriziopandini** [comment]
Dependency seems ok (they are all already k8s deps)

The only tricky one is sigs.k8s.io/kustomize/kustomize/v5 v5.0.1, which is big one, so I will ask other maintainers for an opinion on it (I'm +1)

Also, the PR is lacking the necessary doc + test, so we should consider if to get this merged before code-freeze if @alexander-demicev can follow up in the next two weeks at least for docs (I'm +1)

cc @CecileRobertMichon @sbueringer @killianmuldoon @enxebre @vincepri

**Comment by vincepri** [comment]
I'm +1 as well

**Review by CecileRobertMichon — COMMENTED** [review]
no objections on dependencies from my end

cc @dtzar @mboersma

**Comment by alexander-demicev** [comment]
I added some documentation, most of what is described in `kubectl` docs also applies here.

**Review by dtzar — APPROVED** [review]

**Review by Fedosin — APPROVED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
Thank you for doing this!

**Pull request merged**
