### PR TITLE
✨ Allow for easier UX when using MS/MD template refs

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR allows templated references to have an empty APIVersion and Kind field by copying the values present in the object reference. The Kind value is a special case: the word `Template` is stripped when it's a suffix of the object reference's Kind.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by detiber** [comment]
/cc @akutz 
What are your thoughts here? Having this would allow us to remove the embedded objectmeta from here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/api/v1alpha2/types.go#L42

I know it's late in the release cycle, but if we don't make the adjustment now we are stuck with having to define objectmeta for every template object instead of being able to infer it.

**Comment by akutz** [comment]
> /cc @akutz
> What are your thoughts here? Having this would allow us to remove the embedded objectmeta from here: https://github.com/kubernetes-sigs/cluster-api-provider-vsphere/blob/master/api/v1alpha2/types.go#L42
> 
> I know it's late in the release cycle, but if we don't make the adjustment now we are stuck with having to define objectmeta for every template object instead of being able to infer it.

Hi @detiber,

First, thanks for asking! As for my thoughts? Hmmm... 

It *appears* this is related to just inferring the GVK for the template, correct? If that's the case, then...

From a practical standpoint it makes complete sense, I agree. 

From a release cycle standpoint, it doesn't look like this is a breaking change, so I've not issues with it there.

From a k/k standpoint, what's the accepted behavior here? It seems odd to me to go from this:

```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: VSphereMachineTemplate
metadata:
  name: example-md-0
spec:
  datacenter: my-dc
  network:
    devices:
    - networkName: vm-network-1
      dhcp4: true
      dhcp6: false
  numCPUs: 2
  memoryMiB: 2048
  diskGiB: 20
  template: ubuntu-1804-kube-v1.15.3
---
```

to this

```yaml
---
metadata:
  name: example-md-0
spec:
  datacenter: my-dc
  network:
    devices:
    - networkName: vm-network-1
      dhcp4: true
      dhcp6: false
  numCPUs: 2
  memoryMiB: 2048
  diskGiB: 20
  template: ubuntu-1804-kube-v1.15.3
---
```

Without the infrastructure ref from the MD to the template, doesn't it become impossible to know what the above object is?

I understand the desire to make things simpler, but a lot of work around CAPI seems to be based on trying to reduce the work necessary to produce/manage manifests. From the manifest generation to this PR -- I just haven't seen other k/k solutions that make the manifest UX part of the core k/k application.

I personally think it's the domain of whatever product is built *on top* of CAPI to simplify the production of CAPI manifests.

That said, as I noted above, this doesn't appear to be a breaking change, so I can't argue against it in good faith from that perspective. I'd just stress that we should probably stop trying to simplify manifest UX as part of CAPI and provider code and focus on the creation of an external tool to assist with that.

**Comment by akutz** [comment]
Hi @detiber,

Looking at the code again, I realized that `Template` is being stripped. I saw that the first time, but I suppose I was confused by the phrase:

> every template object

If it's not the template resources for which the GVK is being inferred, then which resource type is it?

**Comment by detiber** [comment]
@akutz It is actually going from this:
```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: VSphereMachineTemplate
metadata:
  name: example-md-0
spec:
  template:
    apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
    kind: VSphereMachine
    spec:
      datacenter: my-dc
      network:
        devices:
        - networkName: vm-network-1
          dhcp4: true
          dhcp6: false
      numCPUs: 2
      memoryMiB: 2048
      diskGiB: 20
      template: ubuntu-1804-kube-v1.15.3
```
to
```yaml
---
apiVersion: infrastructure.cluster.x-k8s.io/v1alpha2
kind: VSphereMachineTemplate
metadata:
  name: example-md-0
spec:
  template:
    spec:
      datacenter: my-dc
      network:
        devices:
        - networkName: vm-network-1
          dhcp4: true
          dhcp6: false
      numCPUs: 2
      memoryMiB: 2048
      diskGiB: 20
      template: ubuntu-1804-kube-v1.15.3
```

**Comment by detiber** [comment]
> If it's not the template resources for which the GVK is being inferred, then which resource type is it?

It is the Machine Infrastructure type being inferred by the Machine Infrastructure Template type, so an AWSMachineTemplate -> AWSMachine when creating the Machine for a MachineSet

**Comment by akutz** [comment]
> > If it's not the template resources for which the GVK is being inferred, then which resource type is it?
> 
> It is the Machine Infrastructure type being inferred by the Machine Infrastructure Template type, so an AWSMachineTemplate -> AWSMachine when creating the Machine for a MachineSet

That was what I thought until I saw "template objects." I'm just easily confused.

And since CAPV has an incorrect version of the template example anyway, we have to update things, so we'll just updated them based on this patch. Thanks!

**Comment by akutz** [comment]
/lgtm cancel

Sorry, assigned to Andy.

**Comment by akutz** [comment]
/assign @ncdc 

Assigning back to Andy.

**Pull request merged**
