### PR TITLE
✨ Merge operator branch into main

### PR DESCRIPTION
**Pull request by alexander-demichev**
**What this PR does / why we need it**:

This PR does not contain any code changes and only applies operator related commits on top of the main. Having a separate branch for developing operator becomes hard to rebase and maintain - 1. If there are fixed conflicts in previous commits, someone needs to force push the rebase. 2. Part of logic relies on clusterctl code and it would be nice to always work on top of fresh changes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by alexander-demichev** [comment]
Update: Some minor changes in the last 3 commits to make it work on top main. 

1. Update unit tests to last CAPI changes, use new env test helper package.
2. Properly setup envtest in operator, refactor makefile so it doesn't use not existing scripts.
3. Fix golang-ci in operator, fix all linter warnings and errors.

**Review by vincepri — COMMENTED** [review]
/hold

Could we discuss about merging it into the main branch at the community meeting?

**Comment by asalkeld** [comment]
This is awesome :-) It will make it much easier to keep up todate with the latest clusterctl code. :+1:

**Comment by fabriziopandini** [comment]
As per July 21th 2021 office hours, the main problem to be addressed is how to preserve a fully functional main branch while implementing the part of this proposal that requires changes to clusterctl init/move/upgrade for using the operator.
Either we can propose a solution for ensuring isolation/explicit op-in in this feature, or we can explore other solutions that can help in working on the separated branch (eg. @vincepri was suggesting to temporarily add a new go.mod file..)

**Comment by asalkeld** [comment]
> As per July 21th 2021 office hours, the main problem to be addressed is how to preserve a fully functional main branch while implementing the part of this proposal that requires changes to clusterctl init/move/upgrade for using the operator.
> Either we can propose a solution for ensuring isolation/explicit op-in in this feature, or we can explore other solutions that can help in working on the separated branch (eg. @vincepri was suggesting to temporarily add a new go.mod file..)

I am not sure that will help, let's imagine..
1. I make a go.mod and use clusterctl from main
2. I find an issue in clusterctl and now have to fix it in main (as I don't see how to mostly include master using go.mod and also use a local cmd/clusterctl/client/repository/components.go
3. we are back to master changing to support the operator code...

**Comment by vincepri** [comment]
@asalkeld You can use specific commits (or latest) in go.mod, wouldn't that be enough to adopt the latest code?

**Comment by alexander-demichev** [comment]
closing this for now

**Pull request closed without merging**
