### PR TITLE
📖 Fix CAPZ redirection links in quick-start page

### PR DESCRIPTION
**Pull request by NareshKoduru**
This PR fixes the broken links that redirect pages in the CAPZ book.

/area documentation

### CODE REVIEW

**Comment by sbueringer** [comment]
Change seems fine

@NareshKoduru please check the bot comments above regarding CLA

**Comment by sbueringer** [comment]
/assign @mboersma 
(to review the Azure link changes)

**Comment by jackfrancis** [comment]
@willie-yao could you take a look at this?

**Comment by willie-yao** [comment]
Yup!

/assign

**Review by willie-yao — APPROVED** [review]
/lgtm

**Comment by NareshKoduru** [comment]
/hold

@willie-yao , @sbueringer , @jackfrancis , Can you please consider https://github.com/kubernetes-sigs/cluster-api/pull/11109 instead of this PR please. Thanks 
Apologies I messed up my local branch and pushed the commits into this.

**Comment by chrischdi** [comment]
/close
in favor of #11109

**Pull request closed without merging**
