### PR TITLE
🌱 bump `golangci-lint` to v1.56.1

### LINKED ISSUE #10114: Bump golangci-lint to v1.56.1
Bump [golangci-lint](https://github.com/golangci/golangci-lint) to the latest minor release ~~v1.56.0~~ v1.56.1

The release notes are here: https://github.com/golangci/golangci-lint/releases/tag/v1.56.1

/kind feature

### PR DESCRIPTION
**Pull request by adityabhatia**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10114

/area dependency

### CODE REVIEW

**Comment by sbueringer** [comment]
@adityabhatia There was a .1 release a few minutes ago

**Comment by adityabhatia** [comment]
> @adityabhatia There was a .1 release a few minutes ago

thanks for the heads up. The `revive` linter bump alone in the `1.56.1` patch resulted in a lot more changes.

**Review by sbueringer — COMMENTED** [review]
Thx!

/lgtm
/approve

**Pull request merged**
