### PR TITLE
:bug: Add back tolerations to cert-manager Deployments

### LINKED ISSUE #4276: cert-manager Tolerations removed
**What steps did you take and what happened:**
`clusterctl init` against a bootstrap cluster whose Nodes all have the `node-role.kubernetes.io/master:NoSchedule` Taint. The cert-manager Pods never got scheduled, because they are missing the Tolerations for that Taint.

**What did you expect to happen:**
I expected `init` to complete.

**Anything else you would like to add:**
#3034 added these Tolerations, and #3511 removed them, probably by accident.

Do we want to prevent this from happening again? One idea might be to add the Taint to the one-node kind clusters used by the e2e tests. Kind removes the Taint on such clusters by default. (Update: @fabriziopandini pointed to the right place to add a regression unit test, which is a more scoped way to verify this.)

**Environment:**

- Cluster-api version: master
- Minikube/KIND version: v0.10
- Kubernetes version: (use `kubectl version`): v1.20.4

/kind bug
/area clusterctl

### PR DESCRIPTION
**Pull request by dlipovetsky**
**What this PR does / why we need it**:
Adds back Tolerations to the `node-role.kubernetes.io/master:NoSchedule` Taint, so that cert-manager Pods can be scheduled. Also adds a test to verify that every Deployment has the Toleration, to prevent future regressions.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4276

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
@dlipovetsky thanks for this PR!
Do you mind to add a unit test to

https://github.com/kubernetes-sigs/cluster-api/blob/24926f65a835ba0c3b70cb44e92651d752efcf94/cmd/clusterctl/client/cluster/cert_manager_test.go#L61

So we ensure that the toleration should be there every time the manifest gets updated?

**Comment by dlipovetsky** [comment]
> So we ensure that the toleration should be there every time the manifest gets updated?

> Do you mind to add a unit test to
> 
> https://github.com/kubernetes-sigs/cluster-api/blob/24926f65a835ba0c3b70cb44e92651d752efcf94/cmd/clusterctl/client/cluster/cert_manager_test.go#L61

:100: Thanks for pointing me to the right place to add the test!

**Comment by vincepri** [comment]
need to regen go-bindata 🙃

**Comment by dlipovetsky** [comment]
> need to regen go-bindata upside_down_face

Thank you, I missed that.

**Comment by dlipovetsky** [comment]
Ran `make generate-bindata`, amended and force-pushed.

**Comment by dlipovetsky** [comment]
Added unit test to commit and force-pushed.

**Comment by vincepri** [comment]
Thank you!

**Comment by dlipovetsky** [comment]
> Do we need to backport?

Yes, per @fabriziopandini's [comment](https://github.com/kubernetes-sigs/cluster-api/issues/4276#issuecomment-793578473) on the issue.

**Pull request merged**
