### PR TITLE
📖 Update instructions to generate release notes

### PR DESCRIPTION
**Pull request by g-gaston**
**What this PR does / why we need it**:

After the last refactor the required CLI args and build steps are different.

In addition, fixing the build and test commands to work with go 1.21.

/area release

### CODE REVIEW

**Comment by g-gaston** [comment]
cc @kubernetes-sigs/cluster-api-release-team

**Comment by sbueringer** [comment]
Thx!

/lgtm

**Review by willie-yao — APPROVED** [review]
/lgtm

**Pull request merged**
