### PR TITLE
[release-1.9] 🌱 Reconcile topology only when necessary

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Cherry-pick of #11605

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold
to merge the PR against main first

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Comment by chrischdi** [comment]
/lgtm

With the last change :-)

**Pull request merged**
