### PR TITLE
🌱 Add test for listDescendents fetch MachinePools

### LINKED ISSUE #3294: Add tests for listDecendents fetching MachinePools
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
This is a follow up to PR #3196 

**What did you expect to happen:**
Add test for the functionality added.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version:
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by wangzewang**
**What this PR does / why we need it**:
Test case for MachinePools

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3294

### CODE REVIEW

**Review by CecileRobertMichon — COMMENTED** [review]
/ok-to-test

**Comment by CecileRobertMichon** [comment]
@wangzewang `TestFilterOwnedDescendants` is failing

**Review by vincepri — COMMENTED** [review]
/lgtm
/assign @CecileRobertMichon

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
