### PR TITLE
🐛 Fix conversion-gen outside of GOPATH

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/assign @chrischdi 

Tested locally and it seems to be fine. Let's see what Prow is saying

**Comment by sbueringer** [comment]
Looks like Prow is happy too

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by chrischdi** [comment]
/retitle 🐛 Fix conversion-gen outside of GOPATH

**Pull request merged**
