### PR TITLE
🐛 Fix RuntimeClient nil check in ClusterClass controller

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
RuntimeClient is only mandatory if RuntimeSDK feature gate is enabled

xref: https://kubernetes.slack.com/archives/C8TSNPY4T/p1730227198605269

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by Jont828** [comment]
Fixed my issue, thanks!

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
