### PR TITLE
🌱 e2e: Display path of the kubeconfig file for the bootstrap cluster

### PR DESCRIPTION
**Pull request by superbrothers**
**What this PR does / why we need it**:

This PR displays the path of the kubeconfig file for the bootstrap cluster for E2e tests. It makes it easier to debug provider controllers if it fails to initialize the bootstrap cluster.

```
STEP: Setting up the bootstrap cluster
INFO: Creating a kind cluster with name "test-6lnn2w"
INFO: The kubeconfig file for the kind cluster is /var/folders/d3/lsp0h4wx7wsd4_yrymm9nnm80000gn/T/e2e-kind675530722
STEP: Initializing the bootstrap cluster
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by fabriziopandini** [comment]
BTW, while running test locally, I find simpler and faster to use an existing kind cluster instead of creating one for each test run...

**Comment by superbrothers** [comment]
I know I can use an existing kind cluster, but sometimes I want to reference a cluster for various uses, such as an Infrastructure Machine creation failure. Also, I know that all objects are dumped on exit, but not all new Infrastructure Providers have fully implemented Phases and Events.

**Review by vincepri — APPROVED** [review]
/lgtm
/milestone v0.3.10

**Pull request merged**
