### PR TITLE
🌱 add possibility to specify webhook cert dir

### PR DESCRIPTION
**Pull request by lobziik**
**What this PR does / why we need it**:
Allows to specify webhook cert dir for being able to use anything else then default controller-runtime one.

Useful for debugging purposes and potentially in environments with different certificate management flow.

#4165

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
It would be nice to have an issue documenting the use case behind this change.

However, for my better understanding of the proposed solution:

With the new flag, it will be possible to change the folder where the capi controller reads certificates, but in order to provide alternative certificates, I assume you still have to edit the capi deployment and add a new volume mount.

If this is the case, why not to replace 
```
      volumes:
      - name: cert
        secret:
          defaultMode: 420
          secretName: $(SERVICE_NAME)-cert
```
with your alternative volume mount?

Also, for consistency, we should implement the same change for KCP/CABPK,CAPD; TBD if this should became a contract for the providers as well, but this really depends by the use case we are trying to address here

**Comment by vincepri** [comment]
If we go down the path of adding this flag, we should probably also make sure it's in the v1alpha3 -> v1alpha4 guide, and in all the other `main.go` files as well

**Comment by lobziik** [comment]
> If this is the case, why not to replace
> 
> ```
>       volumes:
>       - name: cert
>         secret:
>           defaultMode: 420
>           secretName: $(SERVICE_NAME)-cert
> ```
> 
> with your alternative volume mount?

@fabriziopandini

**Comment by lobziik** [comment]
> It would be nice to have an issue documenting the use case behind this change.
[#4165](https://github.com/kubernetes-sigs/cluster-api/issues/4165)

> If this is the case, why not to replace
> 
> ```
>       volumes:
>       - name: cert
>         secret:
>           defaultMode: 420
>           secretName: $(SERVICE_NAME)-cert
> ```
> 
> with your alternative volume mount?

@fabriziopandini,  in order to provide alternate certificates this have to be done for sure. I also want to tune volume mountPath.
``` 
       volumeMounts:
        - mountPath: /tmp/k8s-webhook-server/serving-certs
          name: cert
          readOnly: true
```
It might be done with kustomize during installation/release build process, but manager doesn't support this. This new flag provides such possibility.

**Comment by CecileRobertMichon** [comment]
If infra providers are expected to support this as well please add to https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md as well

**Comment by lobziik** [comment]
> If infra providers are expected to support this as well please add to https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md as well

Added. @CecileRobertMichon hope I got right purpose of this document.

**Comment by fabriziopandini** [comment]
change sgtm to me, please squash commits

**Comment by fabriziopandini** [comment]
/lgtm
given the change in the contract, let's wait for the provider maintainers to loop in
@CecileRobertMichon @detiber @randomvariable @nader-ziada @gab-satchi @srm09 @yastij @sedefsavas

**Review by yastij — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
