### PR TITLE
⚠️ Deprecate MD.Spec.ProgressDeadlineSeconds

### LINKED ISSUE #11470: Remove spec.ProgressDeadlineSeconds in MachineDeployments
ProgressDeadlineSeconds field on MD is not used anywhere, so we probably should deprecate and remove it at the first chance

/kind cleanup

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:

Fixes #11470

/area machinedeployment
/hold for consensus on the issue

### CODE REVIEW

**Comment by troy0820** [comment]
/lgtm 

Holding for consensus

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Pull request merged**
