### PR TITLE
📖 docs: add link to release 1.4 in capi book

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

Adds link to the 1.4 release in CAPI book.

**Should be merged after production branch is updated to 1.4 in Netlfiy**
/hold

cc @kubernetes-sigs/cluster-api-release-team

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
/lgtm
/approve

@oscr Why not merge now? Merging this PR only affects the main/release-1.5 book

**Review by furkatgofurov7 — COMMENTED** [review]
LGTM

**Comment by oscr** [comment]
> @oscr Why not merge now? Merging this PR only affects the main/release-1.5 book

Sounds good to me! 

/hold cancel

**Pull request merged**
