### PR TITLE
✨Add support for CoxEdge provider

### PR DESCRIPTION
**Pull request by jayesh-srivastava**
**What this PR does / why we need it**:
The PR adds Cluster API Provider CoxEdge to clusterctl and infra providers list.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/retest

flake

**Comment by fabriziopandini** [comment]
Nice to see new providers to show up!
/lgtm

**Review by ykakarap — APPROVED** [review]
/lgtm

**Pull request merged**
