### PR TITLE
📖 Drop personas from the book

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
This page is almost unmaintained since a couple of years now, and this might be confusing for users.

### CODE REVIEW

**Comment by elmiko** [comment]
seems like a reasonable removal to me, especially if we aren't maintaining it and it is starting to bit rot.

/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

**Comment by sbueringer** [comment]
/approve

(re-triggered all actions, no idea why they all failed)

**Pull request merged**
