### PR TITLE
📖 Rename diagrams ending with .puml to .plantuml

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

I noticed a diagram wasn't regenerated. Found it was due to file ending .puml instead of .plantuml. So I renamed the diagrams I found and regenerated them.

### CODE REVIEW

**Comment by stmcginnis** [comment]
/lgtm

Good to be consistent.

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
thx!

/approve

**Pull request merged**
