### PR TITLE
📖 Drop docs not maintained

### PR DESCRIPTION
**Pull request by fabriziopandini**
**What this PR does / why we need it**:
Dropping pages not maintained since a long time

**Which issue(s) this PR fixes**:
Fixes https://github.com/kubernetes-sigs/cluster-api/issues/5705

/area documentation

### CODE REVIEW

**Comment by chrischdi** [comment]
/hold

For your convinience

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

Definitely a good idea to remove these IMO

**Pull request merged**
