### PR TITLE
📖 migration-doc: clarify instructions to use new registry in published components yaml

### PR DESCRIPTION
**Pull request by sbueringer**
manifests

Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @oscr 
(just reframed it slightly to make a bit more clear that the images are already in the new registry and only the published manifests have to be changed)

/assign @fabriziopandini

**Comment by oscr** [comment]
Thanks! Looks like a great improvement to me.  

/lgtm

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Review by ykakarap — APPROVED** [review]
/lgtm

**Pull request merged**
