### PR TITLE
Return the reconcile result if the machine exists

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuck@heptio.com>

**What this PR does / why we need it**:
This PR will return the machine reconcile result and the error if the machine already existed. if this doesn't return the code will continue into the create call.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by davidewatson** [comment]
If create fails midway through, do we expect update to finish the job? I think that makes sense. Either way I have the same comment as for #536: we need to document this better. :)

**Comment by davidewatson** [comment]
This document is probably reviewing in light of this PR: https://docs.google.com/document/d/1PTAWB8jC1PTx6K2-emvi7Mmo7ZVtLIE11rNEJJm2TJw/edit#

**Comment by roberthbailey** [comment]
@chuckha - needs rebase

**Comment by chuckha** [comment]
looks like this got fixed in some other PR!

**Pull request closed without merging**
