### PR TITLE
🌱 Enable kubeadm ControlPlaneKubeletLocalMode feature gate in e2e tests

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This PR is a test to figure out if setting the feature flag would solve an issue that we found in CI. We will eventually revert this PR but for now we want to now if the feature gate would fix this issue.

The issue:
* Since we bumped our tests to Kubernetes 1.31 the "When testing Cluster API working on self-hosted clusters using ClusterClass with a HA control plane" test has been failing pretty frequently 
* The root cause is that in some case a 1.31 kubelet tries to list services from a 1.30 apiserver
* This fails because the 1.30 apiserver does not support field selectors for spec.clusterIP: https://github.com/kubernetes/kubernetes/pull/123905
* The problem is that kubeadm join configures the kubelet to use the apiserver loadbalancer instead of the local apiserver.
* With the feature gate enabled kubeadm should use the local apiserver endpoint instead

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by chrischdi** [comment]
Let's have a

/hold

This is related to this failures / flakes: https://prow.k8s.io/view/gs/kubernetes-jenkins/logs/periodic-cluster-api-e2e-main/1816296183270739968

Which comes down to CNI not coming up on the v1.31 control plane nodes

**Comment by chrischdi** [comment]
/lgtm

Not sure if we want to merge it to see coverage via periodics

/test help

**Comment by sbueringer** [comment]
cc @kubernetes-sigs/cluster-api-release-team  (Just fyi)

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-main 

(some other failure)

**Review by neolit123 — COMMENTED** [review]
/lgtm
/hold (pls drop hold if see fit)

+1 to exercise this in CAPI e2e tests. 
the original failure domain around the unsupported skew of immutable upgrades was discovered in CAPI.

**Comment by sbueringer** [comment]
@neolit123 This one is just the first round of confirming that the feature gate would avoid the issue / test failure. We'll follow-up in any case to discuss how we want to address this

/hold cancel
(need the data we can gather over night from periodics)

**Comment by sbueringer** [comment]
/hold

Seems like the gate might break even more, let's not merge for now

**Comment by sbueringer** [comment]
Now only setting the feature gate for 1.31 (otherwise kubeadm says the feature name is not valid)

/test pull-cluster-api-e2e-main

**Comment by neolit123** [comment]
> Now only setting the feature gate for 1.31 (otherwise kubeadm says the feature name is not valid)
> 
> /test pull-cluster-api-e2e-main

@chrischdi added a kubeadm e2e test and it works:
https://github.com/kubernetes/kubeadm/blob/main/kinder/ci/workflows/control-plane-local-kubelet-mode-tasks.yaml#L63

https://testgrid.k8s.io/sig-cluster-lifecycle-kubeadm#kubeadm-kinder-control-plane-kubelet-local-mode-latest
https://storage.googleapis.com/kubernetes-jenkins/logs/ci-kubernetes-e2e-kubeadm-kinder-control-plane-kubelet-local-mode-latest/1816545578880864256/build-log.txt

```
time="18:53:28" level=debug msg="generating config..."
apiServer:
  certSANs:
  - localhost
  - 172.17.0.2
apiVersion: kubeadm.k8s.io/v1beta4
clusterName: kinder-control-plane-local-kubelet-mode
controlPlaneEndpoint: 172.17.0.7:6443
controllerManager:
  extraArgs: null
featureGates:
  ControlPlaneKubeletLocalMode: true
kind: ClusterConfiguration
kubernetesVersion: v1.31.0-beta.0.395+9edabd617945cd
networking:
  podSubnet: 192.168.0.0/16
  serviceSubnet: ""
scheduler:
  extraArgs: null
```

**Comment by sbueringer** [comment]
Okay test now locally green :) 

If someone is still around, I think we can merge now to get more data from CI :)

/hold cancel

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
