### PR TITLE
add release-1.6 branch to the github workflows

### PR DESCRIPTION
**Pull request by nawazkh**
**What this PR does / why we need it**:
This PR updates github workflows to include release-1.6 branch and drops release-1.4 branch

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes # N/A

### CODE REVIEW

**Comment by nawazkh** [comment]
Hold until release-1.6 branch exists.
/hold

**Comment by nawazkh** [comment]
For continuity of context, if a reviewer is approving this PR, please also take a look at https://github.com/kubernetes/test-infra/pull/31290

**Comment by sbueringer** [comment]
/lgtm
/approve

(+/- pr tiltle / area)

**Comment by nawazkh** [comment]
> (+/- pr tiltle / area)

I can update this, not sure which area this PR belongs to?
And by "title", shall I be updating the title to something else?

**Comment by nawazkh** [comment]
Looks like https://github.com/kubernetes-sigs/cluster-api/pull/9708 has already been merged achieving the same.
/close

**Comment by sbueringer** [comment]
Please try to avoid duplicate PRs in the future, I think we had a similar duplicate one in test-infra :)

**Comment by sbueringer** [comment]
> I can update this, not sure which area this PR belongs to? And by "title", shall I be updating the title to something else?

I guess area/release or something :), Without an icon as a prefix the GitHub check won't succeed in general

**Pull request closed without merging**
