### PR TITLE
🐛 Fix Community meeting area formatting in release notes

### PR DESCRIPTION
**Pull request by g-gaston**
**What this PR does / why we need it**:
Tons of stupid mistakes from my side lately. Hopefully we can get https://github.com/kubernetes-sigs/cluster-api/pull/9617 merged soon to avoid these :) 

/area release

### CODE REVIEW

**Comment by g-gaston** [comment]
cc @kubernetes-sigs/cluster-api-release-team

**Review by furkatgofurov7 — APPROVED** [review]
Thanks!

/approve
/lgtm

**Pull request merged**
