### PR TITLE
 📑 update termination handler 🖋

### PR DESCRIPTION
**Pull request by sbarikdev**
What this PR does / why we need it:
This PR updates the spot instances proposal with termination handler design & It's security level.

### CODE REVIEW

**Comment by JoelSpeed** [comment]
I think this change is already being covered by some existing work that's been ongoing for a little while, see #5432

**Comment by killianmuldoon** [comment]
>I think this change is already being covered by some existing work that's been ongoing for a little while, see #5432

This appears to be a direct copy of the text from that PR. I think we should close this unless @sbarikdev has some reason not to.

**Review by killianmuldoon — COMMENTED** [review]
I think this change is already being covered by some existing work that's been ongoing for a little while, see #5432

This appears to be a direct copy of the text from that PR. I think we should close this unless @sbarikdev has some reason not to.

**Pull request closed without merging**
