### PR TITLE
clusterctl test framework: Restore CNIManifestPath to struct for API compat

### LINKED ISSUE #3607: Breaking API change in clusterctl for 0.3.9
**What steps did you take and what happened:**
[A clear and concise description on how to REPRODUCE the bug.]
https://github.com/kubernetes-sigs/cluster-api/pull/3332 deleted the `CNIManifestPath` field from the `clusterctl.ApplyClusterTemplateAndWaitInput` struct

This effectively broke CAPA's e2e tests.

**What did you expect to happen:**
No breaking changes to e2e.

**Anything else you would like to add:**
[Miscellaneous information that will assist in solving the issue.]

**Environment:**

- Cluster-api version: 0.3.9
- Minikube/KIND version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

/kind bug
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by randomvariable**
Parity with Cluster API 0.3.8

Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3607

### CODE REVIEW

**Comment by sedefsavas** [comment]
cc @fabriziopandini

**Comment by fabriziopandini** [comment]
/approve 
to restoring the possibility to specify a CMI manifest path without using CRS.

@sedefsavas, should https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1816 switch CAPA to use CRS (so this field won't be used anymore)?

**Comment by sedefsavas** [comment]
@fabriziopandini Yes after that PR is in, it will be the case for CAPA but this PR is fine too to revert an undocumented breaking change, in the next release we can document and do this change.

> @sedefsavas, should [kubernetes-sigs/cluster-api-provider-aws#1816](https://github.com/kubernetes-sigs/cluster-api-provider-aws/pull/1816) switch CAPA to use CRS (so this field won't be used anymore)?

**Pull request merged**
