### PR TITLE
🌱 Bump to ginkgo v2.5 and gomega 1.24.1

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
/hold
for office hours

**Comment by fabriziopandini** [comment]
/lgtm
/approve

As per the office hours discussion, hold till Friday, but it is good to get the latest minors (and it seems they do not require any change in provider neither from reading the release notes, neither from actually doing the bump in CAPI)

**Pull request merged**
