### PR TITLE
🏃  Move cloudinit module into internal

### PR DESCRIPTION
**Pull request by chuckha**
Signed-off-by: Chuck Ha <chuckh@vmware.com>

**What this PR does / why we need it**:
CABPK is not willing to support cloudinit as an importable library.

### CODE REVIEW

**Comment by ncdc** [comment]
/hold

Holding to make sure we get the changelog details before we merge. @chuckha I can write it today if you'd like, or I'm happy to wait too.

**Comment by chuckha** [comment]
Added the breaking changes

**Comment by ncdc** [comment]
@akutz you all aren't importing CABPK's `cloudinit` package, are you?

**Comment by akutz** [comment]
Hi @ncdc,

Thank you for asking. It doesn't appear so.

image

**Comment by chuckha** [comment]
@ncdc if master is able to break and the documentation was in place, what was the hold for? Is someone consuming master of cluster-api?

regardless, it's rebased. Let me know if anything else needs addressing.

**Comment by ncdc** [comment]
/lgtm

Thanks Chuck!

**Pull request merged**
