### PR TITLE
:book: update quickstart doc

### PR DESCRIPTION
**Pull request by CecileRobertMichon**
**What this PR does / why we need it**: Update quickstart documentation based on some feedback I got from a first time user:

- bump k8s version to latest patch
- show clusterctl describe command
- add note on choosing an Azure location / vm size 
- update kcp output to latest

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
