### PR TITLE
📖 Fix 'clustrctl' typo

### PR DESCRIPTION
**Pull request by nojnhuh**
**What this PR does / why we need it**: Fixed typo

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks for the contribution! I think you might need to add an extra line to the PR message to pass our PR verify check 🙂

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
I found one more if you have time to change it in this PR:

https://github.com/kubernetes-sigs/cluster-api/blob/af33e43d891e3af3787e86bceabce6b8e052c984/cmd/clusterctl/config/embedded_manifest.go#L22

**Comment by killianmuldoon** [comment]
Thanks! lgtm pending squashing the commits

**Review by ykakarap — APPROVED** [review]
/lgtm

**Pull request merged**
