### PR TITLE
🌱 Swap in new 1.8 RT members in OWNERS

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #10472

/area release

### CODE REVIEW

**Comment by sbueringer** [comment]
/approve

(So you don't have to wait for an approval once the PR is finalized & someone else verified it)

**Comment by adilGhaffarDev** [comment]
@Sunnatillo @chandankumar4 please check your teams. @chrischdi @fabriziopandini please give lgtm.

**Comment by chrischdi** [comment]
/lgtm

/hold

To give @Sunnatillo @chandankumar4 a chance to check.

**Review by chandankumar4 — APPROVED** [review]
lgtm

**Comment by sbueringer** [comment]
Tide weirdly stuck. Trying to fix it by addding an empty line to the PR descriptoin

**Pull request merged**
