### PR TITLE
Add event recording package

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vince@vincepri.com>

**What this PR does / why we need it**:

This PR adds the `record` package to be used as a global event recorder. This is a port from the [aws provider](https://github.com/kubernetes-sigs/cluster-api-provider-aws/tree/master/pkg/record). 

The goal of this package is to offer a generic and global solution to event recording to reduce boilerplate and friction.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by davidewatson** [comment]
/lgtm

There are out of tree users here: https://github.com/kubernetes-sigs/cluster-api-provider-aws/search?q=Eventf&unscoped_q=Eventf

**Comment by vincepri** [comment]
@roberthbailey This came out a discussion with @timothysc and @detiber a while ago. The goal is to offer an easy way to globally record events on runtime objects. In the other (maybe more common) approach each control loop has to init its own recorder. The name of the recorder seems to me it's almost like a "User-Agent" in the browser world, therefore seemed fine to me to have a global recorder and include more context in the messages.

**Comment by roberthbailey** [comment]
My gut reaction to init functions is that we should avoid them. In my experience they tend to make code more brittle, less testable, harder to refactor, and they tend to introduce global variables.

**Comment by roberthbailey** [comment]
I guess I'm not sure why using the event recorder that we inject into each controller isn't sufficient. What code needs to produce events outside of the control loops?

**Comment by vincepri** [comment]
In the AWS provider, we're providing user info/error events on machines and network components for example, this package is currently used there. I was hoping to get this in so others providers can also use a global event recorder by having a `klog`-style package. Happy to close this PR if the pacakge isn't useful though.

**Comment by roberthbailey** [comment]
If it isn't too hard, can you drop a link to where you are using this sort of event recorder?

**Comment by vincepri** [comment]
@roberthbailey https://github.com/kubernetes-sigs/cluster-api-provider-aws/search?q=%22record.Eventf%22&unscoped_q=%22record.Eventf%22 This should do it I think

**Comment by roberthbailey** [comment]
I looked briefly, and it seems like the aws provider [creates a cluster actuator](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/587119942eb737e728be38be2d252849c7f5c468/cmd/manager/main.go#L67) which reconciles the cluster by [creating a "service"](https://github.com/kubernetes-sigs/cluster-api-provider-aws/blob/55671b3a1f3cf6429f735e84c116775af9b79cd4/pkg/cloud/aws/actuators/cluster/actuator.go#L63) inside of which the record.Eventf calls are made.

I guess I don't understand why an event recorder isn't just passed down as a parameter into the actuator / service constructors. In the gcp machine actuator, we create a new event recorder when we create the actuator (by calling `mgr.GetRecorder("recorder-name-goes-here")` which can then be used to create events. 

My feeling is that, like golang's [context](https://golang.org/pkg/context/) which you often see passed down call stacks, it's better to have variables locally scoped rather than rely on global variables or global Init functions.

**Comment by vincepri** [comment]
I agree for the most part with the global variables / init function. We were trying to optimize for simplicity in the aws provider, given that we have a bunch of layer of abstraction and passing a recorder in each layer is a much bigger change than having the package ready for all the pieces to consume.

**Comment by vincepri** [comment]
I'm gonna go ahead and close this one, we can reopen later if it's useful to other providers.

/close

**Pull request closed without merging**
