### PR TITLE
🌱 machinedeployment: set revision on machinedeployment and patch via defer

### PR DESCRIPTION
**Pull request by chrischdi**
**What this PR does / why we need it**:

This is a follow-up from: https://github.com/kubernetes-sigs/cluster-api/pull/10124/files#r1484483425

This code recently got changed in this PR: https://github.com/kubernetes-sigs/cluster-api/pull/10124/files#diff-d9a80cabbd6ae2ad7412b4e57a7f3d474b4816a021e4b84987c0895c6b1189c6R117

Before that, when calling `r.updateMachineDeployment` did never make any sense, because inside the anonymous function we never passed through the variable from the function, but our global machinedeployment instead.

So technically we already always used patching using `defer` instead of immediately patching the object.

There also seems to be no race when patching in defer, because the annotation gets never read **from the machinedeployment**. (We read it from machinesets).

cc @sbueringer 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/area machinedeployment

### CODE REVIEW

**Comment by sbueringer** [comment]
Thank you!

/lgtm

/assign @fabriziopandini @vincepri

**Comment by chrischdi** [comment]
/assign @fabriziopandini 

:-)

**Comment by fabriziopandini** [comment]
nice cleanup!
/lgtm
/approve

**Pull request merged**
