### PR TITLE
:seedling: Backport of conformance updates for Kubernetes 1.22

### PR DESCRIPTION
**Pull request by randomvariable**
**What this PR does / why we need it**:
Backport of #4761 and #4662

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by CecileRobertMichon** [comment]
/lgtm cancel

`kubetest/run.go:182:15: undefined: os.ReadFile`

**Comment by randomvariable** [comment]
Yeah, I forgot to convert for the older go version

**Review by vincepri — APPROVED** [review]
/lgtm

**Pull request merged**
