### PR TITLE
🌱 Bump envtest binaries to 1.28

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #8708

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold

Will fail until https://github.com/kubernetes-sigs/kubebuilder/pull/3545 is merged

**Review by killianmuldoon — COMMENTED** [review]
/area dependency

/lgtm
/approve

**Comment by furkatgofurov7** [comment]
Thx!

/lgtm

**Comment by sbueringer** [comment]
Independent known flake

/retest

**Pull request merged**
