### PR TITLE
🌱 test/e2e/in-memory: sync in-memory provider ClusterClass with test

### PR DESCRIPTION
**Pull request by sbueringer**
ClusterClass

Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@fabriziopandini @killianmuldoon What do we think about adding an `area/provider/infrastructure-in-memory` label to our repo?

Would be good if someone can create the PR for it in test-infra (I would add it manually in parallel until that PR is merged)

**Comment by killianmuldoon** [comment]
>@fabriziopandini @killianmuldoon What do we think about adding an area/provider/infrastructure-in-memory label to our repo?

I'll do this now - good idea

**Comment by killianmuldoon** [comment]
https://github.com/kubernetes/test-infra/pull/29872 

@sbueringer PR for adding the label.

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
