### PR TITLE
🌱 Normalizing flags from _ to -

### LINKED ISSUE #4309: Normalize capi's flags
**Detailed Description**
When Klog is used, the flags of capi components should be normalized. So the underline `_` of Klog flags should be replaced by `-`, same as k/k.

use `component-base` `WordSepNormalizeFunc` function
```go
InitFlags(pflag.CommandLine)
// flags normalize
pflag.CommandLine.SetNormalizeFunc(cliflag.WordSepNormalizeFunc)
pflag.CommandLine.AddGoFlagSet(flag.CommandLine)
```

/kind feature

### PR DESCRIPTION
**Pull request by davideimola**
**What this PR does / why we need it**:
This PR will normalize the flags from `_` to `-`.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #4309

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
@davideimola changes lgtm to me
Please make CI make to pass:
```
controlplane/kubeadm/main.go:31: File is not `gofmt`-ed with `-s` (gofmt)
107
	clientgoscheme "k8s.io/client-go/kubernetes/scheme"
```

**Comment by davideimola** [comment]
Yes, I have already fixed it @fabriziopandini !

**Comment by JoelSpeed** [comment]
Makes sense to me based on context in the attached issue
/lgtm

**Comment by JoelSpeed** [comment]
Out of interest though, what happens to users who are already using these flags? Will they no longer work? Do we need to update any deployment manifests etc before this can be merged?

**Comment by vincepri** [comment]
Should we mark this change as ⚠️ ? It seems it's breaking

**Comment by sbueringer** [comment]
Is this something we want to standardize between controllers? (i.e. should we add it to the migration doc?)

**Comment by fabriziopandini** [comment]
+1 to add a note on https://github.com/kubernetes-sigs/cluster-api/blob/master/docs/book/src/developer/providers/v1alpha3-to-v1alpha4.md#align-manager-flag-names-with-upstream-kubernetes-components and try to standardise this across providers

**Comment by sbueringer** [comment]
> Should we mark this change as  ? It seems it's breaking

I tested it locally. If I got it correctly it doesn't break anything. With this change you parse e.g. both those variants:
* `--webhook_cert_dir=/tmp/abc`
* `--webhook-cert-dir=/tmp/abc`

**Comment by vincepri** [comment]
Thanks folks!

**Pull request merged**
