### PR TITLE
🐛 KCP: fix rollout after upgrade

### LINKED ISSUE #8124: KCP triggers rollout after upgrade
As described in https://github.com/kubernetes-sigs/cluster-api/issues/8101 our e2e-main test is currently flaky. The test case which is responsible for that is the clusterctl upgrade test (v0.3 => main). The problem is that once we upgrade Cluster API to the version from main, Machines are rolled out. After a bit of investigation we found out that the KCP controller triggers the rollout.

[Spoiler alert] The test is failing roughly since 2 weeks ago when we merged #7772

Some Context:
* We introduced a new ImagePullPolicy field in `KubeadmConfigSpec.InitConfiguration.NodeRegistration` and `KubeadmConfigSpec.JoinConfiguration.NodeRegistration`
* The ImagePullPolicy field has a default value (`IfNotPresent`) which is applied via OpenAPI
* The defaulting happens automatically as soon as there is any kind of update on KCP and KubeadmConfig objects
* When KCP checks if it needs to rollout a machine it also compares the KubeadmConfigSpec in KCP with the KubeadmConfig of existing Machines

Example error case:
* We install Cluster API v0.3
* We create the cluster including the KCP object
* Cluster API is upgraded (to the "main" version)
* ImagePullPolicy is defaulted in the KubeadmConfig of the Machine. It is not defaulted on the KCP object.
  * Because there was an update on the Machine which triggered defaulting, but not on the KCP object.
* KCP controller reconcile detects a diff and triggers a rollout
  * Diff is: `InitConfiguration.NodeRegistration.ImagePullPolicy: IfNotPresent != ""`

The solution is to implement defaulting in a way that it doesn't make a difference when we calculate if we need a rollout or not:
* Move the defaulting from OpenAPI to the default func: https://github.com/kubernetes-sigs/cluster-api/pull/8120/commits/998f5f3b509400bdcd4cbe3d8efcb16b51b33d2f
  * Context: the default func is called on both KCP and KubeadmConfig before diffing

P.S. This bug doesn't affect any released version of Cluster API as #7772 was just merged on main.

/kind bug
/area control-plane
[One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels]

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
For more details see the linked issue

Additional verification that the bug is fixed via: https://github.com/kubernetes-sigs/cluster-api/pull/8120 (I'm running the e2e test 10x in the e2e-main job there)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8124

### CODE REVIEW

**Comment by sbueringer** [comment]
/hold
until a few more runs on https://github.com/kubernetes-sigs/cluster-api/pull/8120 proof that the issue is fixed

**Review by ykakarap — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
/hold
Looks like we have another issue with clusterclass and MDs

**Comment by sbueringer** [comment]
/hold cancel

/lgtm
/approve

To get CI back to green

**Pull request merged**
