### PR TITLE
📖 Add latest stable release status badge

### PR DESCRIPTION
**Pull request by R3DRUN3**
**Safe to merge PR**:
Added latest stable release status badge to readme, as per documentation best practices:

GitHub release (latest SemVer)

### CODE REVIEW

**Comment by sbueringer** [comment]
Stupid question, but where are thoes best practices defined?

**Comment by killianmuldoon** [comment]
Thanks for this @R3DRUN3 - I think this could be useful. One question though -  when you say "documentation best practices" what are you referring to exactly? 

/ok-to-test

**Comment by R3DRUN3** [comment]
> Thanks for this @R3DRUN3 - I think this could be useful. One question though - when you say "documentation best practices" what are you referring to exactly?
> 

@killianmuldoon  When I talk about best practices I don't mean something universally recognized but rather best practices dictated by common sense: when you visit a project page it is very useful to have a glance on the latest stable release.
I have read many blog posts where they talked about the various status badges that are useful to include in the docs of an OSS project.

**Comment by killianmuldoon** [comment]
>when you visit a project page it is very useful to have a rapid glance on the latest stable release.

100 percent agreed - we currently have that under `Releases` in the sidebar, but I'm not really sure how people see and consume badges compared to that.

Thanks for the contribution @R3DRUN3!

/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
