### PR TITLE
🐛 fix gocyclo lint errors and remove nolint suppression

### LINKED ISSUE #1946: gocyclo lint errors in main.go
**What steps did you take and what happened:**
[MachinePool types PR](https://github.com/kubernetes-sigs/cluster-api/pull/1929) introduced gocyclo lint errors, suppressed with `// nolint:gocyclo`.

Consider replacing controller and webhook code with the following:
``` golang
err = doSomething()
logAndExitIfError(err, "unable to create webhook", "webhook", "Cluster")

func logAndExitIfError(err error, msg string, keysAndValues ...interface{}) {
  if err == nil {
    return
  }

  setupLog.Error(msg, keysAndValues...)
  os.Exit(1)
}
```

**What did you expect to happen:**
No lint errors or suppressions in main.go.

/kind bug

### PR DESCRIPTION
**Pull request by juan-lee**
**What this PR does / why we need it**:
[MachinePool types PR](https://github.com/kubernetes-sigs/cluster-api/pull/1929) introduced gocyclo lint errors, suppressed with `// nolint:gocyclo`. Fixing gocyclo lint errors and removing suppression.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #1946

### CODE REVIEW

**Comment by vincepri** [comment]
Do we actually need this? It's code generate by kubebuilder, which will need manual changes if we use this pattern.

**Comment by ncdc** [comment]
While the code is generated by kubebuilder, I don't believe it still generates correctly if you add new webhooks because of our `if` check for disabling the webhook server (you have to move what it generates to inside the `if` block).

We don't have to do this, but at some point we may need to break `main.go` from being "maintained" by kubebuiler (as long as it doesn't break our ability to use kubebuilder to generate the rest of the stuff like new API types, controllers, and webhook code).

**Comment by vincepri** [comment]
Ok that makes more sense, I wanted to avoid changing things around only because of the linter, but your explanation makes sense!

**Comment by vincepri** [comment]
Is this still relevant now that the managers have been split and code reduced?

**Comment by ncdc** [comment]
Because we've split into 3 managers recently, this is no longer needed. @juan-lee thanks for working on this, though!

/close

**Pull request closed without merging**
