### PR TITLE
Fix fmt strings

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Without this patch, `make`  fails on go 1.11 with a 
```
# sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer/clusterclient
cmd/clusterctl/clusterdeployer/clusterclient/clusterclient.go:592: Warningf format %v reads arg #2, but call has 1 arg
# sigs.k8s.io/cluster-api/cmd/clusterctl/clusterdeployer
cmd/clusterctl/clusterdeployer/clusterdeployer_test.go:814: T.Fatalf format %q has arg tc.inputMachines of wrong type []*sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1.Machine
cmd/clusterctl/clusterdeployer/clusterdeployer_test.go:818: T.Fatalf format %q has arg tc.inputMachines of wrong type []*sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1.Machine
cmd/clusterctl/clusterdeployer/clusterdeployer_test.go:823: T.Fatalf format %q has arg tc.inputMachines of wrong type []*sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1.Machine
cmd/clusterctl/clusterdeployer/clusterdeployer_test.go:827: T.Fatalf format %q has arg tc.inputMachines of wrong type []*sigs.k8s.io/cluster-api/pkg/apis/cluster/v1alpha1.Machine
```

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

### CODE REVIEW

**Comment by alvaroaleman** [comment]
cc @xmudrii

**Comment by alvaroaleman** [comment]
/retest

All the failed tests have a `timeout waiting for process kube-apiserver to start` on top of them, maybe that timeout is too low?

**Comment by roberthbailey** [comment]
@pwittrock ^^

**Pull request merged**
