### PR TITLE
🌱 MHC: Drop Reconciling log, CAPD: log image name during preload

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/lgtm

I'm not sure how much value the imageTarPath adds here as it's more of an internal implementation (I get `/tmp/image-tar2302139686/image-6.tar`) , but I don't think there's any harm in including it.

Thanks for following up on this!

**Comment by sbueringer** [comment]
> /lgtm
> 
> I'm not sure how much value the imageTarPath adds here as it's more of an internal implementation (I get `/tmp/image-tar2302139686/image-6.tar`) , but I don't think there's any harm in including it.
> 
> Thanks for following up on this!

Agree, given it's a dev provider more information probably doesn't hurt.

**Review by fabriziopandini — COMMENTED** [review]
thanks for this cleanup
/lgtm
/approve

**Pull request merged**
