### PR TITLE
WIP: Add a reference to the cluster in the machine spec

### LINKED ISSUE #145: Link MachineSets/MachineDeployments to their Cluster via both Labels and OwnerReferences
Owner references were added to Machines created via a MachineSet in https://github.com/kubernetes-sigs/cluster-api/pull/108

However as it stands today there is no established link required between MachineSet and it's Cluster. Similar for MachineDeployment.

Would it be reasonable to implement two links:

1. Require (via validation) a label linking MachineSet / MachineDeployment to a Cluster, and Machine to it's MachineSet as well as it's Cluster. This would be useful for querying in a multi-tenant environment where there are multiple Clusters even in a single namespace. During validation the Cluster does not have to exist, the label must simply be set.
1. Controllers set OwnerReference on MachineSet + Deployment as soon as the Cluster linked in the now manadatory label exists. This would allow for the same cascading deletion we implemented for MachineSet -> Machine.

All of this is possible to add-on but we were wondering if this makes sense for the core of cluster-api?

### PR DESCRIPTION
**Pull request by staebler**
**What this PR does / why we need it**:

Adds a reference to the cluster in the machine spec. This is needed to be able to support multiple clusters in a single namespace. Currently, a machine is implicitly associated with the only cluster in a namespace. The reference makes the association between a machine and a cluster explicit.
A machine is required to have the cluster reference set.
A machineset or machinedeployment is required to have the cluster reference set in the machine template.
Adds field selectors for the cluster name to machine, machineset, and machinedeployment.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #145.

**Special notes for your reviewer**:

**Release note**:

```release-note
MachineSpec has an additional field called ClusterRef. This is a reference to the Cluster of which a Machine is a part. Every MachineSpec is required to have a non-empty Name in its ClusterRef. This applies to the MachineSpec in Machine, MachineSet, and MachineDeployment.
[action required] Users must fill out the Name field in the ClusterRef of the MachineSpec in any existing Machine, MachineSet, and MachineDeployment objects.
```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by mvladev** [comment]
Every object can have multiple `OwnerReferences`. Isn't this sufficient for the use case?

**Comment by staebler** [comment]
@mvladev An owner reference would not work. That would require that the Cluster object exist prior to the Machine, MachineSet, or MachineDeployment. The user would then need to provide the UID of the Cluster when creating the Mahine*** object, which would be difficult to script.

The crux either way, though, is that the machine controller needs to have some way of determining which cluster to fetch to pass along to the actuator. Whether it is done through a local object reference or an owner reference, it would still need to exist for the machine controller to use. The alternative is that the machine controller could assume that there is only a single cluster in the namespace if the reference is empty. Even then though the machine controller would still expect there to be **some** cluster object.

**Comment by mvladev** [comment]
Following on last week's meeting:

- Let's keep the `ClusterRef` field optional for now and we can make it required later if it looks like everyone is always using it. That leaves the door open, at least for now, to see if any controllers wouldn't want a strong link between them.
- Change the type to `corev1.ObjectReference` as it'll allow cross namespace consumption.

**Comment by staebler** [comment]
> Let's keep the ClusterRef field optional for now

@mvladev What is the expected behavior in the machine controller when the ClusterRef field is empty? Should the machine controller default back to expecting that there is only a single cluster in the namespace in that case?

**Comment by mvladev** [comment]
@staebler Yes, I think that this should be okay. To keep the behavior consistent, if there is more than 1 `Cluster` in a namespace and the `Machine` doesn't have a `ClusterReference`, then an error should be thrown.

**Comment by staebler** [comment]
I am closing this PR. Red Hat no longer has a pressing need for this, and there did not seem to be any strong desire for this from other participants.

**Pull request closed without merging**
