### PR TITLE
Add Cluster API logos from CNCF

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:

Adds CNCF-provided Cluster API logos

@alexcontini can you confirm that the provided licensing information and trademark statement here is correct?

### CODE REVIEW

**Comment by detiber** [comment]
Removing hold since there hasn't been a response.
/hold cancel

**Comment by alexcontini** [comment]
@detiber sorry about that! I read it wrong and thought you were waiting for other response from CNCF. It all looks good to me!

**Comment by detiber** [comment]
@alexcontini thanks!

**Pull request merged**
