### PR TITLE
:bug: remove --enable-hostpath-provisioner flag

### PR DESCRIPTION
**Pull request by carlory**
**What this PR does / why we need it**:

See https://github.com/kubernetes/kubernetes/issues/123804

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
See https://github.com/kubernetes/kubernetes/issues/123804#issuecomment-1985360589

### CODE REVIEW

**Comment by carlory** [comment]
kindly ping @sbueringer all jobs are successful

**Review by fabriziopandini — COMMENTED** [review]
just one nit from my side

**Pull request merged**
