### PR TITLE
Add make gendeepcopy to generate the deepcopy methods just with one command

### PR DESCRIPTION
**Pull request by ingvagabund**
**What this PR does / why we need it**: Adding make gendeepcopy to generate the deepcopy methods

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:
Building the deepcopy-gen from the vendored `k8s.io/code-generator/cmd/deepcopy-gen` since the latest deepcopy-gen binary can produce differently generated code.

**Release note**:

```release-note
None
```

@kubernetes/kube-deploy-reviewers

### CODE REVIEW

**Comment by ingvagabund** [comment]
@roberthbailey @dims PTAL

**Comment by dims** [comment]
/assign @mkjelland

LGTM 👍

**Comment by roberthbailey** [comment]
lgtm
/approve

**Pull request merged**
