### PR TITLE
:seedling: Rename md parameters for consistency

### PR DESCRIPTION
**Pull request by killianmuldoon**
Update MachineDeployment parameter names (`d` -> `md`) to make them more consistent across the codebase.

/kind cleanup
/area code-organization

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Note: this is a follow  up for https://github.com/kubernetes-sigs/cluster-api/pull/7509/files#r1016472426

**Comment by sbueringer** [comment]
> Note: this is a follow up for https://github.com/kubernetes-sigs/cluster-api/pull/7509/files#r1016472426

I already forgot this 😃

**Comment by killianmuldoon** [comment]
>I already forgot this

Probably no the highest priority change, but I'm closing that PR so I wanted to make sure this was covered over somewhere.

**Pull request merged**
