### PR TITLE
:running: Update Go 1.13

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by ncdc** [comment]
Is there a need to update to go 1.13? I'm not opposed to it, but the reason I ask is that Kubernetes only moved to 1.13.x yesterday, so this change hasn't made its way out to client-go, controller-runtime, etc.

**Comment by vincepri** [comment]
CI images have moved to 1.13 because of Kuberentes as you mentioned. I'd expect other tools to follow as well soon.

Without this change we need roll back our images in test-infra

**Comment by detiber** [comment]
I'm a bit hesitant for this change as well for the same reasons as @ncdc. I'm wondering if instead we should update our prow configs to use the latest 1.16 image instead (gcr.io/k8s-testimages/kubekins-e2e:v20191106-09649c7-1.16, based on the output of the latest build and the configured variants for the image: https://github.com/kubernetes/test-infra/blob/master/images/kubekins-e2e/variants.yaml#L18-L22), at least until we update our dependencies to a newer version of k8s?

The main reason we switched to the experimental tag in the past was for a newer version of bazel, which we are no longer using.

*Note* we may need to exclude the conformance jobs that are testing k8s master from this change, since they are testing.

**Comment by ncdc** [comment]
Yes, let's switch to the 1.16 images

**Pull request closed without merging**
