### PR TITLE
Use bazel for ci-build.sh

### LINKED ISSUE #660: scripts/ci-build.sh should fail if bazel fails
/kind feature

**Describe the solution you'd like**
If you use a really old version of bazel, `./scripts/ci-build.sh` will output errors about bazel failing but the makefile will continue running and finish with a successful exit code (luckily, `./scripts/ci-test.sh` actually fails, so we won't merge a PR that breaks bazel). 

I don't know which version of bazel is required for the build to work, but 0.15 failed and 0.21 passed, so it's somewhere in between those two. 

We should also fix the developer documentation (in the gitbook or CONTRIBUTING.md) to mention that installing bazel is required and note a minimum version. 

**Anything else you would like to add:**
It's also broken for `./scripts/ci-make.sh` and we should fix that as well. 

**Environment:**

- Cluster-api version:
- Kubernetes version: (use `kubectl version`):
- OS (e.g. from `/etc/os-release`):

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #660 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by roberthbailey** [comment]
What about changing the makefile to use bazel instead of `go build`? Otherwise the targets in the makefile are basically going to be orphaned, but building these binaries via bazel isn't documented.

**Comment by vincepri** [comment]
That also sounds good, I went for the most conservative change here given that it might affect dev experience.

**Pull request closed without merging**
