### PR TITLE
Switch yaml package from ghodss repo to sigs.k8s.io fork

### PR DESCRIPTION
**Pull request by detiber**
Now that the yaml package has been officially forked to sigs.k8s.io, switch our usage over to the sigs.k8s.io fork.

### CODE REVIEW

**Comment by detiber** [comment]
/hold
to update after kubernetes-sigs/yaml#1 merges

**Comment by roberthbailey** [comment]
Gopkg.lock still has an entry for ghodss/yaml. Does dep not automatically remove that if it is no longer referenced in the project?

And is this one file really the only place we import the yaml parser?

**Comment by detiber** [comment]
> Gopkg.lock still has an entry for ghodss/yaml. Does dep not automatically remove that if it is no longer referenced in the project?

It's still pulled in by other dependencies currently, it should be fully removed after kubebuilder updates to v1.13+

> And is this one file really the only place we import the yaml parser?

Yes

**Comment by roberthbailey** [comment]
https://github.com/kubernetes-sigs/yaml/pull/1 has merged, so removing the hold.

/hold cancel

**Comment by detiber** [comment]
Re-adding the hold, need to wait on sigs.k8s.io/yaml to cut a release before dep picks up the update.
/hold

**Comment by dims** [comment]
Ack @roberthbailey

**Comment by dims** [comment]
@detiber Done - https://github.com/kubernetes-sigs/yaml/releases/tag/v1.1.0

**Comment by detiber** [comment]
It looks like the gcloud-in-go image in use is golang-1.9, working up an associated test-infra PR to patch up :)

**Comment by roberthbailey** [comment]
ping @dims

**Comment by dims** [comment]
/lgtm

(sorry, did not realized this was stuck on my account)

**Pull request merged**
