### PR TITLE
📖 fix link to RuntimeSDK CAEP

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

/cherry-pick release-1.2

### CODE REVIEW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

Good catch! 

Is there a way we could render proposals in html in the book? Is it worthwhile to do so?

**Comment by sbueringer** [comment]
> Is there a way we could render proposals in html in the book? Is it worthwhile to do so?

I think it's not necessary. I talked to Fabrizio a bit about documentation and we would move a lot of stuff from the proposal to the book and then just link it from the proposal (~the dev guides). I'll open a PR with the proposed documentation (structure) soon.

**Pull request merged**
