### PR TITLE
🏃KCP: Migrate from flags to pflags

### PR DESCRIPTION
**Pull request by sedefsavas**
**What this PR does / why we need it**:
This PR move KCP flags to pflags for consistency with the rest of the code base.

### CODE REVIEW

**Comment by vincepri** [comment]
@sedefsavas can you rebase on master?

**Comment by sedefsavas** [comment]
@vincepri 
Rebased but still getting the same error: 

```
docs/book/src/developer/providers/implementers-guide/building_running_and_testing.md
	ERROR	https://cluster-api.sigs.k8s.io/tasks/installation.html#install-cluster-api
		Not Found (HTTP error 404)
```

That link is actually missing.

**Comment by vincepri** [comment]
@sedefsavas do you mind checking if the link is actually going 404 locally?

**Comment by detiber** [comment]
@vincepri I think the error is related to the removal of the separate Installation doc with it being incorporated into the quick start

**Comment by vincepri** [comment]
Yeah, but it should have been caught in the other PR, I'm trying to understand if this is a false positive or if the verification job needs to be changed somehow

**Comment by sedefsavas** [comment]
> Yeah, but it should have been caught in the other PR, I'm trying to understand if this is a false positive or if the verification job needs to be changed somehow

Yes, tasks/installation.html is missing locally too.

**Pull request merged**
