### PR TITLE
🌱 Add envtest unit tests for node label sync

### LINKED ISSUE #8053: Add envtest unit tests for node label sync
Now that we migrated the other machine controller tests to envtest (#7964). Let's implement a few envtest-based unit tests for the node label sync.

/kind cleanup
/area testing
/assign

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8053

### CODE REVIEW

**Review by fabriziopandini — COMMENTED** [review]
That's a great test to have!
/lgtm

**Comment by sbueringer** [comment]
/lgtm
/approve

Given lgtm above. Let's start merging to reduce the amount of open PRs.

**Pull request merged**
