### PR TITLE
:seedling: Add pod metadata to capbk manager

### LINKED ISSUE #10165: CABPK manifest is missing metadata
### What steps did you take and what happened?

I updated from 1.4.9 to 1.5.5

In `capi-kubeadm-bootstrap-controller-manager-59984b8784-q78pk`, there is only this Info/warn/error:
```
I0216 09:59:20.071707       1 cluster_cache_tracker.go:161] "remote/ClusterCacheTracker: Couldn't find controller pod metadata, the ClusterCacheTracker will always access clusters using the regular apiserver endpoint"
```

In other controller, I don't see errors.

But on `capi-controller-manager-58fbc78955-g4njq`, there is this error:
```
E0216 10:00:13.382563       1 machineset_controller.go:883] "Unable to retrieve Node status" err="failed to create cluster accessor: failed to get lock for cluster: cluster is locked already" controller="machineset" controllerGroup="cluster.x-k8s.io" controllerKind="MachineSet" MachineSet="prod/prod-md-0-sm6mt" namespace="prod" name="prod-md-0-sm6mt" reconcileID=xxx MachineDeployment="prod/prod-md-0" Cluster="prod/prod" Machine="prod/prod-md-0-sm6mt-2mz62" node=""
```

I see this error 2 times for each worker, and I have 3 workers.

If I downgrade to 1.4.9, it goes away. I have the same error in 1.5.5 nad on 1.6.1.

### What did you expect to happen?

no errors in the logs

### Cluster API version

1.5.5

### Kubernetes version

1.27.9

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by nikParasyr**
**What this PR does / why we need it**:

Add pod metadata to capbk manager manifests. This
will allow the ClusterCacheTracker to access the
cluster directly when possible

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #10165 

/area provider/bootstrap-kubeadm

### CODE REVIEW

**Review by chrischdi — COMMENTED** [review]
/ok-to-test

**Comment by g-gaston** [comment]
I think we should cherry-pick this to 1.6 and 1.5

**Pull request merged**
