### PR TITLE
Update generated files, add workaround for controller-tools

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
This PR updates the generated files which are out-of-date after the update to the latest `controller-tools`. It also adds a workaround for RBAC files until https://github.com/kubernetes-sigs/controller-tools/pull/230 is merged.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note

```

### CODE REVIEW

**Comment by detiber** [comment]
@vincepri The integration test looks to be failing due to something still referencing an old path name.

**Comment by vincepri** [comment]
@detiber updated

**Pull request merged**
