### PR TITLE
🌱 KCP: drop redundant get machines

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
This check is redundant as we already check this before:
* Reconcile calls initControlPlaneScope which stores the owned machines in control plane
* initializeControlPlane is then only called if the number of (owned) machines is 0

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/test pull-cluster-api-e2e-full-main 

/hold
for full test results

**Comment by sbueringer** [comment]
/hold cancel
e2e is green

**Comment by fabriziopandini** [comment]
nice catch
/lgtm
/approve

**Pull request merged**
