### PR TITLE
Remove CAPD's machine deletion

### LINKED ISSUE #3581: Remove CAPD's aggressive deletion of machines
CAPD deletes and replaces machines if they fail to bootstrap. This was previously done to handle flakes, but it can mask errors, and make things difficult to debug.

Additionally, this behaviour is unlike most of the other providers, which explicitly fail a Machine for user intervention or for cleanup by MHC.

### PR DESCRIPTION
**Pull request by Boutheina-Dab**
**What this PR does / why we need it**:
This PR is to remove machine deletion feature enabled for CAPD.
This was previously added to handle flakes, but it can mask errors.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #3581

### CODE REVIEW

**Comment by vincepri** [comment]
@Boutheina-Dab Are you still working on this?

**Comment by fabriziopandini** [comment]
/approve
@Boutheina-Dab please remove WIP

**Pull request merged**
