### PR TITLE
[release-1.2] 🐛 ClusterClass: fix reconciliation of MD delete

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Manual cherry-pick of #7403

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Diffed current_state.go against main and the diff looks clean.

**Comment by sbueringer** [comment]
(rebased onto latest release-1.2)

/test pull-cluster-api-e2e-full-release-1-2

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
Github API flake

/retest

**Comment by sbueringer** [comment]
unrelated self-hosted test flake

/retest

**Pull request merged**
