### PR TITLE
🌱 Replacing gomega.Equal with gomega.BeComparableTo

### LINKED ISSUE #8095: Consider using ginkgo.BeComparableTo instead of ginkgo.Equal
> A few days ago I found myself very frustrated (again) with the fact that the widely used Go test assertion library, gomega, has an Equal() matcher that, when the equality assertion fails, emits the entire contents of both structs being compared. This makes finding which specific field was different a chore, especially when working with very large structs. I started looking at a way to improve this, and I found that there is a better option! Gomega added a BeComparableTo() [matcher](https://onsi.github.io/gomega/#becomparabletoexpected-interface-options-cmpoption) earlier this year that uses the gocmp package and it outputs a diff of exactly which fields are different instead of the entire object! This is a huge time saver, so I thought I would share in case anyone else runs into something similar.
> https://kubernetes.slack.com/archives/C8TSNPY4T/p1670011256246809

Sounds like a great improvement to me. Would be good if something can try it out and potentially open a PR if it works as expected in our case

Kudos @dthorsen for bringing this up

/kind cleanup
/area testing

### PR DESCRIPTION
**Pull request by Dhairya-Arora01**
**What this PR does / why we need it**:
Replacing gomega.Equal with BeComparableTo as Equal dumps both the values when comparing for equality in case the assertion fails. BeComparableTo tries to show the diff output which is more relevant while working with large structs. In this PR BeComparableTo is used only while comparing structs as gomega.Equal is fine while comparing small values as discussed in #8095  

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #8095

### CODE REVIEW

**Comment by vincepri** [comment]
squash commits?

**Comment by Dhairya-Arora01** [comment]
> squash commits?

oh! sorry about that

**Review by vincepri — APPROVED** [review]
/lgtm

**Comment by sbueringer** [comment]
@Dhairya-Arora01 Sorry for the delayed response. Can you please rebase? I'll try to review soon after

**Comment by sbueringer** [comment]
Thx!

/lgtm

Waiting with approve until https://github.com/kubernetes-sigs/cluster-api/pull/8939 is merged to avoid further rebases on #8939

**Comment by sbueringer** [comment]
/approve

CI found a few issues in https://github.com/kubernetes-sigs/cluster-api/pull/8939 so let's go ahead

**Pull request merged**
