### PR TITLE
🌱 Adds a test for ensureNamespaces (plural)

### LINKED ISSUE #2252: [clusterctl] add unit tests for ensureNamespaces
As per https://github.com/kubernetes-sigs/cluster-api/pull/2245#issuecomment-581563431 we should add unit tests for the `ensureNamespaces` function introduced by https://github.com/kubernetes-sigs/cluster-api/pull/2245

/area clusterctl
/help
/priority backlog

### PR DESCRIPTION
**Pull request by hazbo**
Following my recent work on fixing a small bug and writing tests for
`ensureNamespace` in #3217 in order to close #2252 

**What this PR does / why we need it**:
A few test cases have been added to ensure namespaces are created on a target before other objects are moved across.

**Which issue(s) this PR fixes**:
Fixes #2252
This was closed I think in some confusion with my previous test which was `ensureNamespace` (no S).

### CODE REVIEW

**Comment by fabriziopandini** [comment]
/close
Closed by #3217

**Comment by hazbo** [comment]
@fabriziopandini I'm unsure why this was closed. Does this code not require test coverage?

**Comment by fabriziopandini** [comment]
Ohh, you are right, I missed the plural part (note for self: drink more coffee on Monday 😉 )
/reopen

**Pull request merged**
