### PR TITLE
📖 Improve comment on MachineDeploymentStrategyType

### LINKED ISSUE #9376: Improve description for machine deployment.spec.strategy.type
### What steps did you take and what happened?

For folks doing things w/ i.e. GPU where theres resource constraints its important to know the alterantvies  RolloutStrategies.... 
```
kubo@PmilRMT2e4lE2:~$ kubectl explain md.spec.strategy
KIND:     MachineDeployment
VERSION:  cluster.x-k8s.io/v1beta1

RESOURCE: strategy <Object>

DESCRIPTION:
     The deployment strategy to use to replace existing machines with new ones.

FIELDS:
   rollingUpdate        <Object>
     Rolling update config params. Present only if MachineDeploymentStrategyType
     = RollingUpdate.


*** WHAT ELSE :) ***

   type <string>
     Type of deployment. Default is RollingUpdate.

kubo@PmilRMT2e4lE2:~$ kubectl explain md.spec.strategy.type
KIND:     MachineDeployment
VERSION:  cluster.x-k8s.io/v1beta1

FIELD:    type <string>

DESCRIPTION:
     Type of deployment. Default is RollingUpdate.
```

### What did you expect to happen?

The description would have valid rollout values since they are strongly typed

### Cluster API version

cluster-api/cluster-api-controller:v1.4.5

### Kubernetes version

_No response_

### Anything else you would like to add?

_No response_

### Label(s) to be applied

/kind bug
One or more /area label. See https://github.com/kubernetes-sigs/cluster-api/labels?q=area for the list of labels.

### PR DESCRIPTION
**Pull request by rvanderp3**
**What this PR does / why we need it**:
This PR improves the description for the field deployment.spec.strategy.type.

**Which issue(s) this PR fixes**:
Fixes #9376

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
Thanks! 

/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/ok-to-test
/retitle 📖 Improve comment on MachineDeploymentStrategyType
/area documentation

**Comment by sbueringer** [comment]
Thx. Look like you also have to re-gen the openapi stuff (or just modify it manually according to the diff in the verify job, that's probably quicker)

**Comment by rvanderp3** [comment]
> Thx. Look like you also have to re-gen the openapi stuff (or just modify it manually according to the diff in the verify job, that's probably quicker)

thanks @sbueringer! that update has been made and this is ready for review.

**Comment by sbueringer** [comment]
Thank you!

/lgtm
/approve

**Pull request merged**
