### PR TITLE
:bug:  Validate variables in defaulting webhook

### PR DESCRIPTION
**Pull request by killianmuldoon**
Move variable validation from the Cluster validation webhook to the Cluster defaulting webhook

This fixes a race condition caused by moving variable definitions from ClusterClass spec to status. That change means there is a chance that the defaulting and validating webhook are working off of different versions of the ClusterClass as each independently retrieves it from the cache.

Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/lgtm
/approve

/test pull-cluster-api-e2e-full-main 

/hold
for e2e & in case you want additional reviews from other folks befoer merging

**Comment by sbueringer** [comment]
/cherry-pick release-1.4

Sorry, typo with v1.3

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
