### PR TITLE
🌱 Bump to Go 1.22.7

### PR DESCRIPTION
**Pull request by adilGhaffarDev**
**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by adilGhaffarDev** [comment]
cc @chrischdi @sbueringer

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Pull request merged**
