### PR TITLE
🌱 Upgrade to controller-tools v0.8.0

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Have to retry the verify job a bit more to make sure the regen was done completely. Could take a bit until the job runs on a working node

/test pull-cluster-api-verify-main

**Review by vincepri — APPROVED** [review]
/approve
/lgtm

**Pull request merged**
