### PR TITLE
🌱 Add oscr to cluster-api-docs-reviewers

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

PR to add myself as reviewer for docs. Just to help out with some of the simpler, more straight forward doc prs.

### CODE REVIEW

**Comment by fabriziopandini** [comment]
You're doing a great job on Cluster API, this is well deserved!
/lgtm

I will broadcast this during the next office hours and propose a deadline for feedback EOW

**Review by killianmuldoon — APPROVED** [review]
/lgtm

Very very welcome addition!

**Review by ykakarap — APPROVED** [review]
/lgtm

Very well deserved. A welcome addition 🙂

**Comment by fabriziopandini** [comment]
as per office hours, lazy consensus by EOW (16th of September)

**Comment by vincepri** [comment]
Welcome!

**Comment by oscr** [comment]
Thank you @sbueringer @fabriziopandini @killianmuldoon @ykakarap and @vincepri for your support and help :pray:

**Pull request merged**
