### PR TITLE
 🐛 Fix clusterproxy interface in e2e: regression

### PR DESCRIPTION
**Pull request by shysank**
**What this PR does / why we need it**:
Fixes regression introduced by #4354 

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by shysank** [comment]
cc @fabriziopandini @vincepri sorry about the regression :(

**Review by vincepri — APPROVED** [review]
/lgtm

**Review by fabriziopandini — COMMENTED** [review]
/approve

**Pull request merged**
