### PR TITLE
:book: Fix broken links in book

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Fix two of broken links in the book.

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
/cherry-pick release-1.3

**Comment by fabriziopandini** [comment]
@killianmuldoon @oscr should we backport this fix? if yes, up to which version?

**Comment by killianmuldoon** [comment]
I've got a cherry-pick open for 1.3 - I think for book nits updating the mainline version is probably sufficient unless it's something major - do you think we should also cherry pick to 1.2?

**Pull request merged**
