### PR TITLE
🌱 Bump corefile-migration library to v1.0.21

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
Let's get this merged before the releases next week

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
