### PR TITLE
🌱 test/e2e: increase concurrency

### LINKED ISSUE #9579: Speed up e2e tests by increasing concurrency / # of ginkgo nodes
This issue is about running our e2e tests with more ginkgo nodes / concurrency instead of 3.

I think this would improve our dev efficiency because we end up with a quicker feedback loop for e2e-full. It also allows us to add more e2e tests without being too worried about test durations.

For context: Slack: https://kubernetes.slack.com/archives/C8TSNPY4T/p1697730320651299

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #9579

### CODE REVIEW

**Review by vincepri — APPROVED** [review]

**Review by chrischdi — COMMENTED** [review]
/lgtm
/approve

**Comment by sbueringer** [comment]
Let's try a few more times. Otherwise I'll go down a bit 

/test pull-cluster-api-e2e-main
/test pull-cluster-api-e2e-mink8s-main

**Comment by sbueringer** [comment]
Known flake

/test pull-cluster-api-e2e-main

**Comment by sbueringer** [comment]
We're going to try GINKGO_NODES 8 in periodicis, if tests are becoming more flaky we'll reduce it a bit

**Comment by sbueringer** [comment]
/cherry-pick release-1.8

To speed up tests on release-1.8

**Pull request merged**
