### PR TITLE
⚠️ Updates controller-runtime version to v0.8.1

### LINKED ISSUE #4096: Upgrade the controller-runtime version to v0.8.x
**User Story**
**controller-runtime** is a dependency that is vendored in the CAPI codebase. Recently, a [newer version](https://github.com/kubernetes-sigs/controller-runtime/releases/tag/v0.8.0) of controller-runtime has been released. 

**Detailed Description**
n/a

**Anything else you would like to add:**
The k8s bits in the controller-runtime packages have been updated to v1.20.1 . But the minimum supported version for the management cluster should still remain at v1.19.0 in the test cases.

/kind feature

### PR DESCRIPTION
**Pull request by srm09**
**What this PR does / why we need it**:
This patch updates the controller-runtime version to `v0.8.1`. The k8s dependencies in the codebase have been updated to v0.20.2 since this version of controller-runtime has those dependencies.

**Which issue(s) this PR fixes**:
Fixes #4096

### CODE REVIEW

**Comment by vincepri** [comment]
This is a ⚠️ because of the changes needed in the types

**Comment by srm09** [comment]
/retitle ⚠️ Updates controller-runtime version to v0.8.1

**Comment by srm09** [comment]
@vincepri Any suggestions?

**Review by vincepri — APPROVED** [review]
/lgtm
/hold

@CecileRobertMichon @detiber FYI please review, there are required changes to the slice types to use non-pointer structs

**Comment by sedefsavas** [comment]
Shall we add this requirement to `Cluster API v1alpha3 compared to v1alpha4` doc as well?

**Comment by srm09** [comment]
@CecileRobertMichon @detiber Did y'all get a chance to take a look at this one?

**Review by CecileRobertMichon — COMMENTED** [review]
/lgtm

note to self: we'll have to change the Subnets type in CAPZ https://github.com/kubernetes-sigs/cluster-api-provider-azure/blob/master/api/v1alpha3/types.go#L96

**Comment by detiber** [comment]
> @CecileRobertMichon @detiber FYI please review, there are required changes to the slice types to use non-pointer structs

The changes to the slice types seem like they are a concerning issue since it seems to effect not just the v1alpha4 types but also the v1alpha3 types. It seems like this is a bug that we need to get addressed in the code generator.

**Comment by vincepri** [comment]
@detiber Are you thinking about folks importing and using v1alpha3 type while using a v0.4.x version?

**Comment by detiber** [comment]
> @detiber Are you thinking about folks importing and using v1alpha3 type while using a v0.4.x version?

No, my concern was around how it would potentially affect existing resources that are already defined, would this break us being able to deserialize previously stored resources in etcd? I don't see any changes to the CRD openapi definition, so maybe that is the case.

If I'm reading the apiextensions-apiserver registry code right, it looks like the resource is stored in etcd as Unstructured, so I suppose as long as there isn't any impact on serialization between yaml/json and golang structs or between unstructured.Unstructured and the golang structs then it's likely a non-issue.

After digging through things, it looks like it's a non-issue, the type change to the v1alpha3 resource caught me a bit off guard :)

**Pull request merged**
