### PR TITLE
:seedling: Update dependencies: controller-runtime v0.5.7 and json-patch

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
/assign @detiber @JoelSpeed

### CODE REVIEW

**Comment by detiber** [comment]
lgtm, will give @JoelSpeed the ability to review and tag for lgtm

**Comment by JoelSpeed** [comment]
/lgtm

Thanks @vincepri

**Comment by detiber** [comment]
/approve

Will downstream consumers need to also override json-patch? If so, should be something we highlight in the release notes and in the weekly meetiing.

**Comment by vincepri** [comment]
@detiber Possibly, I am hoping that in a few releases the version is fixed in the upstream dependencies and we don't need the replace. CAPI is probably where we're using json-patch the most today.

Jordan mentioned they'd backport the fix, we'll have to wait for the dependencies to be updated as well.

**Pull request merged**
