### PR TITLE
[WIP] Revert ":bug: Cluster should be provisoned when cpRef and endpoint is set

### PR DESCRIPTION
**Pull request by sbueringer**
This reverts commit a6e73adacf52b08ed7874f4710ce4c35fafbfdc5.

**What this PR does / why we need it**:
Want to check if reverting this PR fixes the e2e test

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
@chrischdi Tests green, I think this confirms that it was definitely this change that introduced it

**Comment by Sunnatillo** [comment]
```
if (cluster.Spec.InfrastructureRef == nil || cluster.Status.InfrastructureReady) &&
		(cluster.Spec.ControlPlaneRef == nil || cluster.Status.ControlPlaneReady) &&
		cluster.Spec.ControlPlaneEndpoint.IsValid()
```
(cluster.Spec.ControlPlaneRef == nil || cluster.Status.ControlPlaneReady) is problematic because in kcp remediation test controlplane never becomes ready  and it should start remediation. With that line cluster never becomes provisioned and remediation will not start.

**Review by Sunnatillo — COMMENTED** [review]
LGTM

**Comment by fabriziopandini** [comment]
/close 
in favour of https://github.com/kubernetes-sigs/cluster-api/pull/10903

**Pull request closed without merging**
