### PR TITLE
📖  Fix formatting for book plantuml image

### PR DESCRIPTION
**Pull request by killianmuldoon**
Signed-off-by: killianmuldoon <kmuldoon@vmware.com>

Fix a formatting issue resulting from a recent update of the plantuml version used to generate images.

Related to #7017, https://github.com/kubernetes-sigs/cluster-api/pull/7033

### CODE REVIEW

**Review by killianmuldoon — COMMENTED** [review]
@oscr Do you think this is close enough to the original version? It's an easy enough fix for the other PR if so.

**Comment by oscr** [comment]
> @oscr Do you think this is close enough to the original version? It's an easy enough fix for the other PR if so.

I think this looks great. Great catch and fix. Looks closer to the old image: 
https://github.com/kubernetes-sigs/cluster-api/pull/7017/files#diff-c5d7dddf5137951a5a2973770b166e01bc529d2cb498598752893a8addb901ca

**Review by ykakarap — APPROVED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Comment by sbueringer** [comment]
@killianmuldoon do we need a manual cherry-pick for thix?

**Comment by killianmuldoon** [comment]
We could, but I don't believe it's necessary as [the verison in the current book is fine](https://cluster-api.sigs.k8s.io/tasks/experimental-features/runtime-sdk/implement-topology-mutation-hook.html#introduction), and I didn't want to add too many items to the merge queue for the 1.2 release.

**Pull request merged**
