### PR TITLE
📖 Add CAPDO quickstart in CAPI book

### PR DESCRIPTION
**Pull request by prksu**
**What this PR does / why we need it**:
This PR adds Cluster API Provider DigitalOcean Quick Start in CAPI book

/cc @kubernetes-sigs/cluster-api-provider-digitalocean-maintainers

### CODE REVIEW

**Review by xmudrii — APPROVED** [review]
/lgtm

Thank you for taking care of this!

**Review by cpanato — APPROVED** [review]
/lgtm

**Review by vincepri — APPROVED** [review]
/approve

**Pull request merged**
