### PR TITLE
:seedling: Bump dependencies, August 2021

### PR DESCRIPTION
**Pull request by randomvariable**
Signed-off-by: Naadir Jeewa <jeewan@vmware.com>

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
lgtm more or less. @randomvariable I think you have to rollback the changes to cluster-api.yaml

**Comment by randomvariable** [comment]
> I think you have to rollback the changes to clusterctl-api.yaml

Not sure why it changed on my branch?

**Comment by sbueringer** [comment]
> > I think you have to rollback the changes to clusterctl-api.yaml
> 
> Not sure why it changed on my branch?

Maybe an older version of controller-tools? (not sure how strict that's enforced by our makefile)

**Comment by randomvariable** [comment]
> Maybe an older version of controller-tools? (not sure how strictly that's enforced by our makefile, EDIT: tested it locally and in my case controller-gen was automatically overwritten)

Yeah, it's weird. If it happens again, I'll open an issue.

**Comment by fabriziopandini** [comment]
my only concern Is for k8s.io dependencies because usually we are keeping them in sync with what controller runtime is using, otherwise lgtm
@vincepri ^^

**Comment by vincepri** [comment]
@randomvariable Let's update most of these in Controller Runtime first (noticing also in the PR title that we're updating k8s to 1.21.4) and then pull controller runtime in here

**Comment by randomvariable** [comment]
I've removed the Controller Runtime linked updates. Particularly interested in getting signal on the grpc bump for etcd.

Separately, Controller Runtime's been updated on both main and v0.9 release branches.

**Comment by randomvariable** [comment]
Also had some misaligned versions with both 1.21.2 and 1.21.3 which are cleaned up.

**Comment by vincepri** [comment]
@randomvariable Can you rebase?

**Comment by vincepri** [comment]
Closing for now, tackling these updates separately

/close

**Pull request closed without merging**
