### PR TITLE
🌱  Markdown nit in release-1.8.md

### PR DESCRIPTION
**Pull request by meatballhat**
**What this PR does / why we need it**:

Fixes markdown hyperlink syntax to match others nearby.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:

N/A

/area documentation

### CODE REVIEW

**Comment by sbueringer** [comment]
Thx!

/lgtm
/approve

**Review by hackeramitkumar — APPROVED** [review]

**Pull request merged**
