### PR TITLE
Fix machineDeployment CRD for kube 1.12

### PR DESCRIPTION
**Pull request by alvaroaleman**
**What this PR does / why we need it**:

Current `MachineDeployment` crd fails validation on Kube 1.12: `error validating data: [unknown object type "nil" in CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxSurge, unknown object type "nil" in CustomResourceDefinition.spec.validation.openAPIV3Schema.properties.spec.properties.strategy.properties.rollingUpdate.properties.maxUnavailable]; if you choose to ignore these errors, turn validation off with --validate=false`

This fixes that.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**Release note**:

```release-note
NONE
```

CC @chaosaffe 

/assign @roberthbailey

### CODE REVIEW

**Comment by roberthbailey** [comment]
Did you verify that this still works on 1.11 as well?

**Comment by alvaroaleman** [comment]
@roberthbailey Just did that, works fine

**Comment by alvaroaleman** [comment]
@roberthbailey To be precise, the current version in master doesn't work on 1.11 either. I assume the integration tests spawn a 1.10 control plane which is why it doesn't happen there.

**Comment by roberthbailey** [comment]
Thanks. 

/approve

**Pull request merged**
