### PR TITLE
[release-1.2] 🌱 Use new registry in published manifests

### PR DESCRIPTION
**Pull request by sbueringer**
**What this PR does / why we need it**:
Manual cherry-pick of the most important part of #7410 (using the new registry in our published manifests)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
/cc @oscr @ameukam 

/assign @fabriziopandini 

/hold
until after the v1.3 beta release today with which we verify that the published manifests with the new registry works

**Comment by sbueringer** [comment]
/hold cancel

Verified. v1.3.0-beta.0 works with manifests referencing the new registry

**Review by fabriziopandini — COMMENTED** [review]
/lgtm
/approve

**Pull request merged**
