### PR TITLE
📖 Add PlantUML diagram transparency for book and proposals

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

After upgrading PlantUML @killianmuldoon noticed some differences between how the diagrams where rendered before and after the upgrade. While working on how to recreate the old look we noticed that you could add partial transparency to the diagrams which IMO looks better than solid white or fully transparent. Therefore I would like to suggested adding it. We can of course add more or less transparency if wanted.

### CODE REVIEW

**Review by vincepri — APPROVED** [review]
Looks great!

/approve

**Comment by killianmuldoon** [comment]
Can't backport because we're changing - @oscr could you open a PR against release 1.2? We'll also need to do the same for https://github.com/kubernetes-sigs/cluster-api/pull/7033

**Comment by oscr** [comment]
No problem! I'll open a pr for each in the correct order.

**Pull request merged**
