### PR TITLE
:running: Remove TemplateCloner, MachineGenerator, and KubeadmConfigGenerator interfaces

### PR DESCRIPTION
**Pull request by detiber**
**What this PR does / why we need it**:
Removes the TemplateCloner, MachineGenerator, and KubeadmConfigGenerator interfaces

### CODE REVIEW

**Comment by detiber** [comment]
/assign @vincepri @ncdc 

If this looks good, I can rebase the Status and Scale Up PRs on top of this one.

**Comment by ncdc** [comment]
👏 this is great. I can review in full detail after lunch, unless @vincepri wants to own it

**Comment by chuckha** [comment]
just out of curiosity, why do want to remove these interfaces? I don't see anything about why this change is made in the description or a link to an issue. I have no problem with the change, just interested in why

**Comment by ncdc** [comment]
I can't quickly find my comment from yesterday, but the logic differences between the real and fake generators were minimal, and our test code was testing that the fake generators were working as desired, which is suboptimal. The only real sticking point was the fact that controller-runtime's fake client doesn't handle foo.metadata.generateName at all, and our fake generators existed pretty much solely to work around that issue.

**Comment by chuckha** [comment]
> I can't quickly find my comment from yesterday, but the logic differences between the real and fake generators were minimal, and our test code was testing that the fake generators were working as desired, which is suboptimal. The only real sticking point was the fact that controller-runtime's fake client doesn't handle foo.metadata.generateName at all, and our fake generators existed pretty much solely to work around that issue.

got it, thx

**Pull request merged**
