### PR TITLE
:running: Remove private APIs from Kubeadm v1beta1 types

### PR DESCRIPTION
**Pull request by vincepri**
Signed-off-by: Vince Prignano <vincepri@vmware.com>

**What this PR does / why we need it**:
Context: https://kubernetes.slack.com/archives/C8TSNPY4T/p1583780405249500
/milestone v0.3.0
/assign @ncdc @fabriziopandini

### CODE REVIEW

**Comment by vincepri** [comment]
wondering why this is failing now ^

**Comment by chuckha** [comment]
this looks good to me

Was there a particular reason for changing the generated code?

**Comment by vincepri** [comment]
Without it, it'd fail compilation because we removed the field, I only added the paths to the Makefile, because we use controller-gen the generated files are slightly different but with same functionality

**Comment by ncdc** [comment]
LGTM. Ready to merge?

**Comment by vincepri** [comment]
Ready for me!

**Pull request merged**
