### PR TITLE
📖 Kubernetes bump issue template: fix prior art link

### PR DESCRIPTION
**Pull request by sbueringer**
Signed-off-by: Stefan Büringer buringerst@vmware.com

**What this PR does / why we need it**:
Should be no need to backport as the issue template is only used from the default branch (main)

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

### CODE REVIEW

**Comment by sbueringer** [comment]
cc @aniruddha2000

**Comment by fabriziopandini** [comment]
cherry-pick is not required, my bad (the change is on issue templates, not on doc). 
I will close the PR as soon as created

**Comment by sbueringer** [comment]
> cherry-pick is not required, my bad (the change is on issue templates, not on doc). I will close the PR as soon as created

No problem. I wrote that in the PR description, but who is reading PR descriptions :D (I'm also guilty of that)

**Pull request merged**
