### PR TITLE
🐛 ClusterResourceSet: apply objects in sorted order

### LINKED ISSUE #6500: Cluster Resource Set doesn't apply priority follow
https://github.com/kubernetes-sigs/cluster-api/blob/dd89b090ec478481738de723f94c38c81916da3e/exp/addons/internal/controllers/clusterresourceset_helpers.go#L84-L91

Problem in line 86, `objs` need be replace `sortedObjs`

### PR DESCRIPTION
**Pull request by tranthang2404**
**What this PR does / why we need it**:
Change variable in code to make object created by Cluster Resource Set will follow priority

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #6500

### CODE REVIEW

**Comment by sbueringer** [comment]
/retitle 🐛 ClusterResource Set: apply objects in sorted order

/lgtm

**Comment by chrischdi** [comment]
/lgtm

Thank you for the finding :+1:

**Review by killianmuldoon — APPROVED** [review]
/lgtm

**Pull request merged**
