### PR TITLE
🌱 Upgrade golang version (1.18.3 -> 1.19.0)

### PR DESCRIPTION
**Pull request by oscr**
**What this PR does / why we need it**:

Upgrade golang version 1.18.3 -> 1.19.0 as required by v1.25.0.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Part of #6661

### CODE REVIEW

**Comment by sbueringer** [comment]
@oscr Can you please also update the go version in v.12-to-v1.3.md?

**Comment by oscr** [comment]
@sbueringer Done. I didn't bump `go.mod` since it's still on `1.17`. Do want it upgraded?

**Comment by sbueringer** [comment]
> @sbueringer Done. I didn't bump `go.mod` since it's still on `1.17`. Do want it upgraded?

I think it's fine when we bump it when we actually bump our Go dependencies in #7123 (or as a follow-up to that one)

**Comment by sbueringer** [comment]
/lgtm

Looks like the jobs are working onw

**Comment by fabriziopandini** [comment]
Great Job!
/lgtm
/test pull-cluster-api-e2e-full-main

for a last check

**Pull request merged**
