### PR TITLE
📖 update coredns + contributing for v1.7.0

### PR DESCRIPTION
**Pull request by cahillsf**
**What this PR does / why we need it**:
update docs for v1.7 based off of release cutting doc steps: https://github.com/kubernetes-sigs/cluster-api/blob/main/docs/release/release-tasks.md#repeatedly-cut-a-release

/area documentation

### CODE REVIEW

**Review by Sunnatillo — COMMENTED** [review]
LGTM

**Review by chrischdi — COMMENTED** [review]
/lgtm

**Review by killianmuldoon — COMMENTED** [review]
/lgtm
/approve

/cherry-pick release-1.7

**Pull request merged**
